import type { BehaviourKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const SCHOOL_BEHAVIOURS: BehaviourKnowledgeNode[] = [
  // ── Classroom learning behaviours (25) ────────────────────────────────────────
  { id: "behaviour:school:hand-raised-answering-question", kind: "behaviour", description: "Student raising a hand with intent, leaning slightly forward from their seat — the confidence signal of a student who knows the answer and wants to be seen", emotionalSignal: "confident participation", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["school"], tags: ["hand-raised", "classroom", "answering", "participation"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:school:teacher-writing-on-whiteboard", kind: "behaviour", description: "Teacher writing key terms or working on a maths problem on the whiteboard, one hand writing while the other taps the board to emphasise a point", emotionalSignal: "expert clarity", compatibleHeroes: ["person", "environment", "moment"], industryIds: ["school"], tags: ["whiteboard", "teacher", "writing", "emphasis"], priority: 1, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:school:student-lightbulb-moment-expression", kind: "behaviour", description: "Student's face changing as they understand something difficult — eyes widening, slight open mouth, leaning forward, the physical expression of comprehension arriving", emotionalSignal: "the lightbulb moment", compatibleHeroes: ["person", "moment"], industryIds: ["school"], tags: ["lightbulb", "understanding", "expression", "comprehension"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "behaviour:school:pair-work-leaning-together", kind: "behaviour", description: "Two students leaning toward each other over a shared worksheet — one explaining, one listening, the collaborative proximity of pair work", emotionalSignal: "collaborative focus", compatibleHeroes: ["person", "lifestyle", "environment"], industryIds: ["school"], tags: ["pair-work", "collaboration", "leaning-in", "shared"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:school:group-project-around-table", kind: "behaviour", description: "Four students gathered around a table with papers, pens and a shared task — different contributions visible, one writing, one gesturing, one reading", emotionalSignal: "productive group energy", compatibleHeroes: ["person", "lifestyle", "environment"], industryIds: ["school"], tags: ["group-project", "table", "collaboration", "roles"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:school:student-reading-aloud", kind: "behaviour", description: "Student reading aloud from a text, the class listening, the reader's posture upright, voice steady — the public performance of literacy", emotionalSignal: "quiet courage", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["school"], tags: ["reading-aloud", "class", "public", "literacy"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:school:student-at-computer-coding", kind: "behaviour", description: "Student at a computer screen typing code — focus complete, one hand on keyboard and one occasionally on mouse, testing a function and watching the output appear", emotionalSignal: "technical focus", compatibleHeroes: ["person", "environment", "product"], industryIds: ["school"], tags: ["coding", "computer", "focus", "output"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:school:teacher-kneeling-to-child-level", kind: "behaviour", description: "Teacher kneeling beside a child's desk to explain something one-to-one — the physical lowering that makes the teacher accessible and the child the focus", emotionalSignal: "individualised care", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["school"], tags: ["teacher", "kneeling", "one-to-one", "child"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:school:class-listening-in-focus", kind: "behaviour", description: "Whole class listening to a teacher — all eyes on the board or the speaker, the room quiet and attentive, a moment of genuine collective absorption", emotionalSignal: "collective engaged attention", compatibleHeroes: ["environment", "person", "moment"], industryIds: ["school"], tags: ["class", "listening", "attention", "collective"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:school:student-note-taking-with-colour", kind: "behaviour", description: "Student making notes with different coloured pens — underlining key points, drawing boxes around definitions, the personal revision system visible in the organisation of colour", emotionalSignal: "methodical self-organisation", compatibleHeroes: ["person", "lifestyle", "product"], industryIds: ["school"], tags: ["note-taking", "colours", "revision", "organised"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:school:science-experiment-pouring-carefully", kind: "behaviour", description: "Student carefully pouring a liquid into a beaker, tongue slightly out in concentration, goggles on, the measured precision of a science experiment underway", emotionalSignal: "concentrated precision", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["school"], tags: ["science", "experiment", "pouring", "goggles"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:school:art-student-painting-at-easel", kind: "behaviour", description: "Student standing at an easel with a brush, stepping back periodically to look at the whole canvas — the painter's posture of creation and assessment alternating", emotionalSignal: "creative expression", compatibleHeroes: ["person", "lifestyle", "environment"], industryIds: ["school"], tags: ["art", "painting", "easel", "creative"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:school:student-presenting-to-class", kind: "behaviour", description: "Student presenting to the class from the front — notes in one hand, other hand gesturing toward the board behind them, classmates facing them", emotionalSignal: "performed confidence", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["school"], tags: ["presenting", "front-of-class", "public-speaking", "gesture"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:school:music-student-practising-instrument", kind: "behaviour", description: "Student practising an instrument in the music room — the same phrase played three times, adjusted, played again, the private iteration of learning a difficult passage", emotionalSignal: "persistent practice", compatibleHeroes: ["person", "lifestyle", "environment"], industryIds: ["school"], tags: ["music", "instrument", "practice", "iteration"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:school:student-helping-struggling-peer", kind: "behaviour", description: "Student leaning across to help a classmate who is stuck — pointing at the page, explaining quietly, the teacher unaware, the peer support happening naturally", emotionalSignal: "spontaneous kindness", compatibleHeroes: ["person", "moment", "lifestyle"], industryIds: ["school"], tags: ["helping", "peer", "kindness", "spontaneous"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Teacher & staff behaviours (20) ───────────────────────────────────────────
  { id: "behaviour:school:teacher-marking-at-desk", kind: "behaviour", description: "Teacher at a desk after hours marking books — pen moving, pausing at an answer, adding a comment, the quiet professional commitment of marking work no student sees done", emotionalSignal: "unseen professional care", compatibleHeroes: ["person", "lifestyle", "environment"], industryIds: ["school"], tags: ["teacher", "marking", "desk", "commitment"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:school:teacher-pride-at-student-success", kind: "behaviour", description: "Teacher's face as a student gets an answer right or achieves something — the involuntary smile, the slight nod, the pride that belongs to the teacher as much as the student", emotionalSignal: "vicarious pride", compatibleHeroes: ["person", "moment"], industryIds: ["school"], tags: ["teacher", "pride", "student-success", "involuntary"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:school:teacher-greeting-students-at-door", kind: "behaviour", description: "Teacher standing at the classroom door as students arrive — greeting each one by name, the micro-relationship of the doorway welcome that sets the lesson's tone", emotionalSignal: "warm professional connection", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["school"], tags: ["greeting", "door", "by-name", "welcome"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:school:teacher-explaining-with-model", kind: "behaviour", description: "Teacher holding a physical model — a globe, a molecule, an anatomical model — turning it to show students from different angles as they explain", emotionalSignal: "embodied explanation", compatibleHeroes: ["person", "moment", "product"], industryIds: ["school"], tags: ["model", "teacher", "3d", "explaining"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:school:headteacher-on-assembly-stage", kind: "behaviour", description: "Headteacher at the front of a school assembly, addressing the gathered students — the posture of authority, the voice carrying across the hall, everyone facing forward", emotionalSignal: "institutional authority", compatibleHeroes: ["person", "environment", "moment"], industryIds: ["school"], tags: ["headteacher", "assembly", "hall", "authority"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:school:teacher-feedback-one-to-one", kind: "behaviour", description: "Teacher giving verbal feedback to a student at their desk — leaning slightly toward the student, pointing at the work, voice low, the private exchange within the public class", emotionalSignal: "personalised guidance", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["school"], tags: ["feedback", "one-to-one", "desk", "guidance"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:school:pe-teacher-demonstrating-technique", kind: "behaviour", description: "PE teacher demonstrating a sporting technique — the physical execution slowed down for students to see, body positioned correctly, arms or legs moved into the right form", emotionalSignal: "physical authority", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["school"], tags: ["PE", "demonstration", "technique", "physical"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Achievement & celebration behaviours (20) ─────────────────────────────────
  { id: "behaviour:school:student-receiving-award-on-stage", kind: "behaviour", description: "Student walking across the stage to receive a certificate or trophy — the handshake with the headteacher, the moment held for the photograph, the return to their seat", emotionalSignal: "earned recognition", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["school"], tags: ["award", "stage", "certificate", "recognition"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "behaviour:school:graduation-cap-throw", kind: "behaviour", description: "Graduates throwing their caps into the air simultaneously — the collective upward motion, the caps briefly airborne against the sky, the moment of release after years of work", emotionalSignal: "collective liberation and joy", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["school"], tags: ["graduation", "cap-throw", "collective", "liberation"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "behaviour:school:reading-exam-result-letter", kind: "behaviour", description: "Student opening an exam result envelope — the pause before looking, the eyes scanning the paper, the immediate physical response before they have processed what it means", emotionalSignal: "high-stakes emotional revelation", compatibleHeroes: ["person", "moment"], industryIds: ["school"], tags: ["exam-result", "envelope", "reading", "response"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "behaviour:school:class-applauding-a-peer", kind: "behaviour", description: "A class spontaneously applauding a fellow student after a presentation or performance — the sound of genuine peer recognition, everyone facing the one being applauded", emotionalSignal: "peer recognition", compatibleHeroes: ["moment", "person", "environment"], industryIds: ["school"], tags: ["applause", "peer-recognition", "class", "genuine"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:school:sports-day-finishing-line-celebration", kind: "behaviour", description: "Student crossing the sports day finishing line, hands raised, face in the expression of a winner who did not expect to win quite so decisively", emotionalSignal: "surprised victory", compatibleHeroes: ["person", "moment", "lifestyle"], industryIds: ["school"], tags: ["sports-day", "finishing-line", "victory", "surprised"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:school:drama-curtain-call-bow", kind: "behaviour", description: "School play cast taking their curtain call — the cast holding hands and bowing together, parents in the audience visible, the applause at its peak", emotionalSignal: "earned theatrical triumph", compatibleHeroes: ["moment", "person", "environment"], industryIds: ["school"], tags: ["drama", "curtain-call", "bow", "applause"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:school:science-fair-winning-project", kind: "behaviour", description: "Student standing beside their science fair project with a first-place ribbon attached — explaining it to a judge, the pride of the project being chosen as the best", emotionalSignal: "academic achievement pride", compatibleHeroes: ["person", "moment", "product"], industryIds: ["school"], tags: ["science-fair", "winning", "project", "ribbon"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:school:debate-win-team-celebration", kind: "behaviour", description: "School debate team celebrating a debate competition win — the cluster of students, someone's hand on the winner's shoulder, the coach at the edge of the group", emotionalSignal: "team intellectual victory", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["school"], tags: ["debate", "team", "winning", "celebration"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Transition & social behaviours (20) ───────────────────────────────────────
  { id: "behaviour:school:first-day-child-with-parent", kind: "behaviour", description: "Small child on their first day of school, school bag oversized on their back, holding a parent's hand at the gate — the threshold moment before the new world begins", emotionalSignal: "vulnerable courage", compatibleHeroes: ["person", "moment", "lifestyle"], industryIds: ["school"], tags: ["first-day", "child", "parent", "gate"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "behaviour:school:running-in-playground", kind: "behaviour", description: "Children running freely in the playground — multiple directions, no pattern, the pure kinetic energy of unstructured time between structured lessons", emotionalSignal: "pure childhood freedom", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["school"], tags: ["playground", "running", "children", "freedom"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:school:friends-meeting-at-school-gate", kind: "behaviour", description: "Friends meeting at the school gate in the morning — the greeting hug, the immediate resumption of a conversation from yesterday, the ease of established friendship", emotionalSignal: "social belonging", compatibleHeroes: ["person", "lifestyle", "moment"], industryIds: ["school"], tags: ["friends", "gate", "morning", "belonging"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:school:carrying-textbooks-in-corridor", kind: "behaviour", description: "Students moving through a school corridor between lessons — textbooks under arms, bags on backs, conversations mid-sentence, the social flow of the school day", emotionalSignal: "school-day rhythm", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["school"], tags: ["corridor", "textbooks", "moving", "social"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:school:school-leaving-day-year-book-signing", kind: "behaviour", description: "School leavers signing each other's yearbooks — the earnest writing of messages that feel important now, people gathering signatures they will not read for twenty years", emotionalSignal: "bittersweet transition", compatibleHeroes: ["person", "moment", "lifestyle"], industryIds: ["school"], tags: ["leaving-day", "yearbook", "signing", "transition"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:school:parent-teacher-evening-handshake", kind: "behaviour", description: "Parent and teacher greeting at parent-teacher evening — the formal handshake across a small desk, both professional and personal, the meeting of the two adults who care most about the child", emotionalSignal: "mutual investment in a child", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["school"], tags: ["parent-teacher", "evening", "handshake", "meeting"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:school:child-running-to-greet-teacher", kind: "behaviour", description: "A young child running toward their teacher at the start of the day — arms slightly wide, speed above what is technically permitted, the relationship expressed entirely in momentum", emotionalSignal: "unconstrained affection", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["school"], tags: ["child", "running", "greeting", "teacher"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:school:student-in-library-absorbed", kind: "behaviour", description: "Student alone in the school library reading — legs tucked under on a beanbag or hunched over a desk, the book held close, the world of the library replacing the world of the school", emotionalSignal: "solitary absorption", compatibleHeroes: ["person", "lifestyle", "environment"], industryIds: ["school"], tags: ["library", "reading", "absorbed", "alone"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:school:prospective-parent-on-open-day", kind: "behaviour", description: "A parent on a school open day — looking carefully at displays on walls, peering into classrooms, asking a student guide a prepared question, assessing with parental precision", emotionalSignal: "parental evaluation", compatibleHeroes: ["person", "lifestyle", "environment"], industryIds: ["school"], tags: ["open-day", "parent", "prospective", "evaluating"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:school:international-student-arriving", kind: "behaviour", description: "International student arriving at a new school — navigating an unfamiliar space with a map, finding their first classroom, the determined self-sufficiency of a student far from home", emotionalSignal: "brave independence", compatibleHeroes: ["person", "moment", "lifestyle"], industryIds: ["school"], tags: ["international", "arriving", "navigating", "independence"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:school:tutor-and-student-one-to-one", kind: "behaviour", description: "Private tutor and student at a kitchen table or small desk — the problem worked through slowly, the tutor noticing the exact moment of misunderstanding and stopping there to address it", emotionalSignal: "precision support", compatibleHeroes: ["person", "moment", "lifestyle"], industryIds: ["school"], tags: ["tutor", "one-to-one", "kitchen-table", "precision"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:school:reading-university-offer-letter", kind: "behaviour", description: "Student reading a university offer letter — the paper held still while the eyes move fast, then the re-reading slowly, then the reaction that is too big to contain", emotionalSignal: "life-changing news received", compatibleHeroes: ["person", "moment"], industryIds: ["school"], tags: ["university", "offer-letter", "reading", "reaction"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "behaviour:school:nqt-nervously-starting-first-class", kind: "behaviour", description: "A newly qualified teacher standing at the front of their first class — the slight over-preparation visible, the notes they will not need, the class assessing them before they have spoken", emotionalSignal: "professional beginning", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["school"], tags: ["NQT", "first-class", "nervous", "beginning"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
];
