import type { CommercialSituationKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const SCHOOL_COMMERCIAL_SITUATIONS: CommercialSituationKnowledgeNode[] = [
  // ── Enrolment & admissions (12) ───────────────────────────────────────────────
  { id: "commercial_situation:school:open-day-visit-to-enrolment", kind: "commercial_situation", situation: "A family visiting a school open day — watching lessons, speaking to students, being shown the facilities — and leaving to submit an enrolment application within 48 hours", conversionMoment: "Application submitted after the open-day visit — the physical experience converting interest into commitment", visualRepresentation: "Family on open-day tour, child visibly engaged, parent asking staff questions, family discussing in the car on the way home, application form completed that evening", industryIds: ["school"], tags: ["open-day", "visit", "enrolment", "application"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "commercial_situation:school:private-school-admissions-interview", kind: "commercial_situation", situation: "A child attending a private school admissions interview accompanied by parents — the process the family has prepared for, the school and family assessing each other simultaneously", conversionMoment: "Interview completed, offer letter sent — the formal selection process resulting in a place offer", visualRepresentation: "Child and parents in reception, child taken to interview room, parents waiting, the return of the child, the awaited letter that follows", industryIds: ["school"], tags: ["private-school", "admissions", "interview", "selection"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "commercial_situation:school:first-day-new-academic-year", kind: "commercial_situation", situation: "The new academic year beginning — families who have already enrolled returning, but also any mid-year or late enrolments that were triggered by the institutional reset of September", conversionMoment: "New term enrolments completed — the academic calendar's natural conversion window", visualRepresentation: "School gate on the first day, new uniforms, parents with phones out, children meeting friends, the buzz of the renewed institution", industryIds: ["school"], tags: ["new-year", "first-day", "enrolment", "september"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "commercial_situation:school:online-enquiry-form-submitted", kind: "commercial_situation", situation: "A parent submitting an online school enquiry form after researching options — the digital conversion that starts the admissions journey without a visit yet", conversionMoment: "Enquiry submitted and follow-up call scheduled — digital lead converted to admissions conversation", visualRepresentation: "Parent on school website late at night, reading prospectus content, submitting enquiry form, confirmation email received", industryIds: ["school"], tags: ["online-enquiry", "digital", "prospectus", "late-night"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:school:scholarship-application-high-achiever", kind: "commercial_situation", situation: "A high-achieving student applying for a scholarship — the application that simultaneously selects the student and converts them to the school's highest-profile admission", conversionMoment: "Scholarship awarded and place accepted — the school's most valuable admission, full fee or partial covering confirmed", visualRepresentation: "Student completing scholarship application, test papers completed, award ceremony, student accepting at prize event", industryIds: ["school"], tags: ["scholarship", "high-achiever", "application", "awarded"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Ongoing tuition & fees (10) ────────────────────────────────────────────────
  { id: "commercial_situation:school:tuition-fee-direct-debit-setup", kind: "commercial_situation", situation: "A family setting up a direct debit for termly or monthly school tuition fees — the commitment to recurring payment that underlies the academic relationship", conversionMoment: "Direct debit mandate signed — the financial foundation of the school's relationship with the family established", visualRepresentation: "Finance meeting with bursar, fee schedule reviewed, direct debit form completed, the payment plan beginning the term", industryIds: ["school"], tags: ["tuition-fee", "direct-debit", "termly", "financial-commitment"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "commercial_situation:school:after-school-club-sign-up", kind: "commercial_situation", situation: "Parent signing a child up for an after-school club or activity — the co-curricular addition that extends school engagement and adds revenue", conversionMoment: "Club places confirmed and payment taken — additional activity generating additional revenue per pupil", visualRepresentation: "Club options form being completed by parent, child's preference requested, place confirmed, payment made, child attending first session", industryIds: ["school"], tags: ["after-school", "club", "sign-up", "co-curricular"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:school:school-trip-payment-permission", kind: "commercial_situation", situation: "Parent signing a school trip permission slip and paying the trip fee — the ancillary revenue of educational experiences outside the school building", conversionMoment: "Trip payment completed — ancillary fee collected, pupil attending experience that supports the academic programme", visualRepresentation: "Trip letter home, online payment portal accessed, permission granted, payment confirmed, child prepared and excited", industryIds: ["school"], tags: ["school-trip", "payment", "permission", "experience"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:school:tutoring-service-booking", kind: "commercial_situation", situation: "Parent booking private tutoring for a child who needs extra support — the external service booking driven by parental concern about academic progress", conversionMoment: "Tutoring sessions booked and paid for — private support service conversion driven by academic anxiety", visualRepresentation: "Parent researching tutors online, shortlisting, calling, session structure explained, first session booked and paid", industryIds: ["school"], tags: ["tutoring", "private", "booking", "academic-support"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:school:online-learning-platform-subscription", kind: "commercial_situation", situation: "School purchasing or parent subscribing to an online learning platform — the digital product that extends learning beyond the classroom", conversionMoment: "Platform licence purchased — school-wide or individual subscription converting to active student use", visualRepresentation: "Teacher demonstrating platform, school purchasing, students logging in, parent subscribing separately for home use", industryIds: ["school"], tags: ["online-learning", "platform", "subscription", "digital"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Events & purchases (12) ───────────────────────────────────────────────────
  { id: "commercial_situation:school:school-photography-day-purchase", kind: "commercial_situation", situation: "Parents purchasing school photography day portraits — the annual individual and class photos that generate recurring annual photography revenue", conversionMoment: "Photo package selected and purchased — the reliable annual purchase that most school families make", visualRepresentation: "Photography day in school, portraits taken, proofs sent home digitally, package selection, payment made", industryIds: ["school"], tags: ["photography-day", "portrait", "annual", "proofs"], priority: 2, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:school:school-uniform-purchase", kind: "commercial_situation", situation: "Family purchasing school uniform — the compulsory purchase that provides direct revenue to the school or preferred supplier at the start of each academic year and at transitions", conversionMoment: "Full uniform set purchased — compulsory purchase made at transition or start-of-year, often exceeding £300", visualRepresentation: "Parent and child at uniform shop or school uniform supplier, trying items for fit, full set selected, payment made", industryIds: ["school"], tags: ["uniform", "compulsory", "purchase", "annual"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "commercial_situation:school:pta-fundraiser-donation", kind: "commercial_situation", situation: "A parent donating to a PTA fundraiser or attending a fundraising event — the community finance mechanism that supplements school budgets", conversionMoment: "Donation made or ticket purchased — community fundraising revenue collected from engaged parent body", visualRepresentation: "PTA event advertised, parents attending, raffle tickets sold, auction completed, total raised announced", industryIds: ["school"], tags: ["PTA", "fundraiser", "donation", "community"], priority: 3, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "commercial_situation:school:graduation-ceremony-photography", kind: "commercial_situation", situation: "Parents purchasing graduation ceremony photography or official graduation memorabilia — the milestone purchase at the peak emotional moment of the school relationship", conversionMoment: "Graduation photos and memorabilia purchased — the highest-emotion purchase point of the school's commercial relationship with families", visualRepresentation: "Graduation ceremony, official photographer visible, parents buying packages, student receiving their certificate captured", industryIds: ["school"], tags: ["graduation", "photography", "memorabilia", "milestone"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:school:revision-course-booking", kind: "commercial_situation", situation: "Student or parent booking an intensive revision course before exams — the pre-exam anxiety converted into additional educational spend", conversionMoment: "Revision course booked and paid — the exam-period urgency creating a high-intent short-term purchase", visualRepresentation: "Exam timetable out, parent finding revision course, course booked urgently, student attending sessions", industryIds: ["school"], tags: ["revision-course", "exam", "urgency", "booked"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:school:donation-to-new-building-appeal", kind: "commercial_situation", situation: "A parent or alumnus donating to a school capital appeal — the major gift that funds a new building or facility, the philanthropic relationship between a school and its community", conversionMoment: "Donation pledged to capital campaign — major gift secured from community member with deep school attachment", visualRepresentation: "Capital appeal launched, named giving opportunity explained, meeting with development office, pledge made and acknowledged", industryIds: ["school"], tags: ["capital-appeal", "donation", "building", "philanthropic"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:school:international-student-enrolment", kind: "commercial_situation", situation: "An international student enrolling from overseas — the highest-fee admission category, often involving a boarding place and comprehensive fees well above domestic rates", conversionMoment: "International enrolment confirmed with full fee agreement — the highest-value single admission the school generates", visualRepresentation: "Family from overseas on virtual tour, then physical visit, full boarding and tuition fee package agreed, enrolment confirmed", industryIds: ["school"], tags: ["international", "boarding", "overseas", "highest-fee"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
];
