import type { EmotionalMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const SCHOOL_EMOTIONAL_MOMENTS: EmotionalMomentKnowledgeNode[] = [
  // ── Achievement peaks (18) ────────────────────────────────────────────────────
  { id: "emotional_moment:school:exam-results-reading-relief", kind: "emotional_moment", moment: "A student opening their exam results and reading the grade — the body bracing before the eyes reach the number, then the release of breath as the result is better than feared", emotionType: "relief after sustained anxiety", visualSignals: ["paper held still", "eyes moving fast then stopping", "shoulders dropping on the exhale", "hands beginning to tremble after the moment of relief"], industryIds: ["school"], tags: ["exam-results", "relief", "reading", "release"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:school:graduation-cap-throw-collective", kind: "emotional_moment", moment: "The graduation moment when caps go into the air — the collective release of years of work in a single upward movement, everyone throwing at exactly the same second", emotionType: "collective liberation", visualSignals: ["caps airborne simultaneously", "upturned faces", "arms still extended above heads", "the laughter that follows while caps are still descending"], industryIds: ["school"], tags: ["graduation", "collective", "caps", "liberation"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "emotional_moment:school:university-offer-letter-reaction", kind: "emotional_moment", moment: "A student reading their university offer letter and realising it's from their first choice — the pause while the meaning arrives, then the reaction that fills the room", emotionType: "life-changing news landed", visualSignals: ["letter held in both hands", "re-reading before reacting", "the face changing before the sound comes", "the phone already being reached for to tell someone"], industryIds: ["school"], tags: ["university-offer", "first-choice", "letter", "life-changing"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "emotional_moment:school:award-on-stage-public-recognition", kind: "emotional_moment", moment: "A student crossing the stage to receive an award — the walk that seems longer than the room, the handshake with the headteacher, the applause from people who know what this means", emotionType: "public recognition of private effort", visualSignals: ["walk to the stage", "headteacher's handshake", "face during applause", "returning to seat with the certificate"], industryIds: ["school"], tags: ["award", "stage", "applause", "recognition"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:school:scholarship-announcement-surprise", kind: "emotional_moment", moment: "A student being told they have received a scholarship they applied for without expectation of winning — the announcement arriving when they had already made peace with not getting it", emotionType: "unexpected elevation", visualSignals: ["the look of not understanding at first", "then understanding all at once", "hands to face", "the parent in the room looking at their child"], industryIds: ["school"], tags: ["scholarship", "unexpected", "announcement", "parent-watching"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:school:sports-day-winning-race", kind: "emotional_moment", moment: "A student crossing the sports day finishing line first — the surprise in their face as they look back and see the gap between them and the next runner, larger than they knew", emotionType: "surprised victory", visualSignals: ["crossing the line", "looking back", "the gap visible", "arms beginning to rise before they have fully understood"], industryIds: ["school"], tags: ["sports-day", "winning", "finishing-line", "surprise"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:school:drama-production-standing-ovation", kind: "emotional_moment", moment: "The cast of a school drama production receiving a standing ovation — rows of audience rising, the cast looking at each other in the moment before taking it in", emotionType: "collective triumph", visualSignals: ["audience rising row by row", "cast faces reading the room", "the wave of sound", "cast members reaching for each other's hands on stage"], industryIds: ["school"], tags: ["drama", "standing-ovation", "cast", "collective"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },

  // ── Learning breakthrough peaks (12) ──────────────────────────────────────────
  { id: "emotional_moment:school:lightbulb-moment-understanding", kind: "emotional_moment", moment: "The exact moment a student understands something they have been struggling with — the face changing from a frown of effort to a widening of the eyes, the body relaxing as the answer arrives", emotionType: "intellectual illumination", visualSignals: ["frown dissolving", "eyes widening", "small involuntary nod", "the forward lean of wanting more now"], industryIds: ["school"], tags: ["lightbulb", "understanding", "struggle-resolved", "illumination"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:school:child-reads-first-book-alone", kind: "emotional_moment", moment: "A child reading their first whole book without help — turning the last page, looking up, the realisation that they did that entirely on their own", emotionType: "first literacy independence", visualSignals: ["last page turned", "looking up from the page", "the book still open in the lap", "the expression of someone who has just crossed a threshold"], industryIds: ["school"], tags: ["reading", "first-book", "alone", "independence"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:school:maths-problem-solved-on-board", kind: "emotional_moment", moment: "A student solving a maths problem at the board that the whole class has been stuck on — the class watching, the chalk or marker reaching the answer, the room's collective satisfaction", emotionType: "public intellectual achievement", visualSignals: ["pen reaching the answer", "turning to face the class", "teacher nodding", "class reaction of collective realisation"], industryIds: ["school"], tags: ["maths", "board", "solved", "class-watching"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:school:teacher-sees-student-potential", kind: "emotional_moment", moment: "A teacher reading a student's work and seeing something that was not there before — the pause in the marking, the re-reading, the realisation that this student has turned a corner", emotionType: "recognition of potential arrived", visualSignals: ["pen pausing", "re-reading", "the teacher's expression shifting", "the note written in the margin that says more than the mark"], industryIds: ["school"], tags: ["teacher", "marking", "potential", "turning-corner"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:school:reluctant-reader-absorbed", kind: "emotional_moment", moment: "A child who always says they hate reading, seen absorbed in a book that finally matched them — they have not looked up in twenty minutes, the reading that found the reader", emotionType: "reluctance transformed", visualSignals: ["child unmoving with book", "twenty minutes since they last moved", "teacher watching from a distance", "the book being exactly right"], industryIds: ["school"], tags: ["reluctant-reader", "absorbed", "transformed", "right-book"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Transition & belonging peaks (12) ─────────────────────────────────────────
  { id: "emotional_moment:school:first-day-child-settles-happily", kind: "emotional_moment", moment: "A parent peering back after leaving their child on the first day of school, seeing the child already smiling with another child — the worry released by a glimpse through the window", emotionType: "parental anxiety becoming relief", visualSignals: ["parent looking back through window", "child visible and smiling", "the parent's face changing", "walking away lighter than they arrived"], industryIds: ["school"], tags: ["first-day", "parent", "settled", "window"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:school:school-leaving-day-emotion", kind: "emotional_moment", moment: "The last day of school — the realisation arriving not when expected but in a small ordinary moment: a corridor they have walked a thousand times, suddenly walked for the last time", emotionType: "bittersweet ending", visualSignals: ["ordinary moment recognised as final", "pause in motion", "the corridor empty for a moment", "the weight of leaving felt for the first time"], industryIds: ["school"], tags: ["leaving-day", "ordinary-made-final", "corridor", "bittersweet"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:school:international-student-first-friend", kind: "emotional_moment", moment: "An international student making their first real friend at a new school — the moment of shared laughter that crosses the language difference and makes both of them realise it will be alright", emotionType: "belonging found after isolation", visualSignals: ["shared laughter", "neither trying to bridge the gap anymore", "both relaxing at once", "the relief visible in the posture of the international student"], industryIds: ["school"], tags: ["international-student", "first-friend", "laughter", "belonging"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:school:parent-proud-at-performance", kind: "emotional_moment", moment: "A parent watching their child perform on stage — the child looking for their parent's face in the audience, finding it, the look exchanged that contains everything between them", emotionType: "mutual pride and love", visualSignals: ["child scanning audience", "finding the parent's face", "parent's hands clasped", "the exchange of the look"], industryIds: ["school"], tags: ["parent", "performance", "face-found", "exchange"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:school:teacher-farewell-end-of-year", kind: "emotional_moment", moment: "A class saying goodbye to a beloved teacher at the end of the school year — the small queue of students who want one more moment, the teacher accepting each one", emotionType: "gratitude and farewell", visualSignals: ["queue of students", "teacher kneeling to receive hug from younger child", "older student's handshake", "the last student to leave turning back once"], industryIds: ["school"], tags: ["farewell", "teacher", "queue", "gratitude"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:school:sports-team-losing-gracefully", kind: "emotional_moment", moment: "A school sports team losing a close final and lining up to congratulate the winners — the dignity of the gesture, the emotion contained, the coach's arm around the shoulder of the player who is not containing it", emotionType: "grace in defeat", visualSignals: ["team lining up to shake hands", "faces showing the contained emotion", "coach's arm around one player", "the handshake that takes more courage than winning would have required"], industryIds: ["school"], tags: ["sports-team", "losing", "dignity", "handshake"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:school:student-hearing-teachers-belief-in-them", kind: "emotional_moment", moment: "A teacher telling a student they believe in them at a moment of self-doubt — the student who was about to give up hearing the specific words from the specific person that prevent it", emotionType: "belief received at the right moment", visualSignals: ["teacher leaning forward", "the specific words said quietly", "student's face before and after", "the quality of attention given back in return"], industryIds: ["school"], tags: ["belief", "self-doubt", "teacher-words", "prevention"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
];
