import type { RelationshipKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const SCHOOL_RELATIONSHIPS: RelationshipKnowledgeNode[] = [
  // ── Teacher–student relationships (15) ────────────────────────────────────────
  { id: "relationship:school:teacher-student-breakthrough", kind: "relationship", description: "The teacher-student relationship at the moment of breakthrough — the teacher who found the way to explain what no one else could, the student who finally understood", sceneRoles: ["teacher", "student"], industryIds: ["school"], tags: ["breakthrough", "understanding", "teacher-student", "found-the-way"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "relationship:school:form-tutor-and-tutee", kind: "relationship", description: "Form tutor and tutee — the adult who knows this child across all their subjects and years, the consistent relationship in an otherwise compartmentalised school day", sceneRoles: ["form tutor", "student"], industryIds: ["school"], tags: ["form-tutor", "consistent", "known-across-subjects", "years"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:school:sen-teacher-and-student", kind: "relationship", description: "A Special Educational Needs teacher and a student with learning differences — the specialised understanding that sees past the label to the specific person and their specific potential", sceneRoles: ["SEN teacher", "student with learning differences"], industryIds: ["school"], tags: ["SEN", "specialist", "learning-differences", "specific-potential"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:school:newly-qualified-teacher-first-class", kind: "relationship", description: "An NQT and their first class — the relationship forming in both directions simultaneously, both teacher and class figuring out who the other will be", sceneRoles: ["NQT teacher", "first class"], industryIds: ["school"], tags: ["NQT", "first-class", "forming", "both-directions"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:school:private-tutor-and-student", kind: "relationship", description: "A private tutor and a student — the more individual attention and the resulting progress that happens when the relationship is one-to-one and persistent", sceneRoles: ["private tutor", "student"], industryIds: ["school"], tags: ["private-tutor", "one-to-one", "progress", "individual"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:school:school-counsellor-and-student", kind: "relationship", description: "School counsellor and a student — the safe, confidential space within the school structure where the emotional life of the student can be addressed separately from academic performance", sceneRoles: ["school counsellor", "student"], industryIds: ["school"], tags: ["counsellor", "safe-space", "emotional", "confidential"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:school:subject-specialist-inspiring-student", kind: "relationship", description: "The subject specialist whose passion for their discipline transfers to a student — the teacher who makes physics or history or literature suddenly matter personally", sceneRoles: ["subject specialist", "inspired student"], industryIds: ["school"], tags: ["specialist", "passion", "inspiring", "subject-love"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Student peer relationships (15) ───────────────────────────────────────────
  { id: "relationship:school:best-friends-in-same-class", kind: "relationship", description: "Best friends who are in the same class — the partnership that makes the school day more manageable for both of them, each knowing the other's presence is there", sceneRoles: ["student best friends"], industryIds: ["school"], tags: ["best-friends", "same-class", "partnership", "presence"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:school:sports-team-members", kind: "relationship", description: "School sports team members — the specific relationships that form under pressure of competition and practice, different from classroom friendship", sceneRoles: ["sports team members"], industryIds: ["school"], tags: ["sports-team", "competition", "practice", "specific-bond"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:school:student-and-peer-mentor", kind: "relationship", description: "A student being supported by an older peer mentor — the near-peer relationship that is less hierarchical than teacher-student but more structured than friendship", sceneRoles: ["peer mentor", "supported student"], industryIds: ["school"], tags: ["peer-mentor", "near-peer", "supported", "structured"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:school:competitive-academic-rivals", kind: "relationship", description: "Two students who are academic rivals — the mutual awareness of the other's performance, the competition that motivates both of them more than any other incentive", sceneRoles: ["student rivals"], industryIds: ["school"], tags: ["academic-rivals", "competition", "motivating", "mutual-awareness"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:school:international-student-finding-local-friend", kind: "relationship", description: "An international student forming their first local friendship — the cross-cultural bridge-building that begins with shared laughter at something neither expected to share", sceneRoles: ["international student", "local student"], industryIds: ["school"], tags: ["international", "local-friend", "cross-cultural", "bridge"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:school:student-orchestra-members", kind: "relationship", description: "Students in a school orchestra — the ensemble relationship, the listening to each other required by music, the discipline that creates a kind of intimacy without words", sceneRoles: ["orchestra students", "conductor"], industryIds: ["school"], tags: ["orchestra", "ensemble", "listening", "discipline"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },

  // ── Family–school relationships (10) ──────────────────────────────────────────
  { id: "relationship:school:parent-and-child-school-day", kind: "relationship", description: "Parent and child at the start and end of the school day — the morning goodbye at the gate and the afternoon reunion, the bookends of the school relationship", sceneRoles: ["parent", "child"], industryIds: ["school"], tags: ["parent", "child", "morning-goodbye", "afternoon-reunion"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:school:parent-and-teacher-at-evening", kind: "relationship", description: "A parent and teacher at parents' evening — the formal five-minute slot that contains an entire view of a child from the perspective of their other significant adult", sceneRoles: ["parent", "teacher"], industryIds: ["school"], tags: ["parents-evening", "formal", "five-minutes", "other-view"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:school:grandparent-and-grandchild-school-performance", kind: "relationship", description: "A grandparent in the audience of a school play or concert watching their grandchild perform — the pride that crosses generations, the camera raised to capture what the eye is already recording", sceneRoles: ["grandparent", "grandchild"], industryIds: ["school"], tags: ["grandparent", "performance", "pride", "capturing"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:school:anxious-parent-prospective-school", kind: "relationship", description: "A parent choosing a school on behalf of their child — the responsibility and anxiety of the decision, the visit that may determine a child's next five or seven years", sceneRoles: ["prospective parent", "school"], industryIds: ["school"], tags: ["prospective-parent", "choosing", "responsibility", "deciding"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Institutional relationships (10) ──────────────────────────────────────────
  { id: "relationship:school:headteacher-and-school-community", kind: "relationship", description: "The headteacher and the school community — the institutional relationship, the single person who sets the culture that everyone else lives within", sceneRoles: ["headteacher", "school community"], industryIds: ["school"], tags: ["headteacher", "community", "culture", "institutional"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:school:mentor-teacher-and-nqt", kind: "relationship", description: "An experienced mentor teacher and the NQT they are supporting — the professional guidance that turns qualification into competence, the specific advice passed from one generation of teaching to the next", sceneRoles: ["mentor teacher", "NQT"], industryIds: ["school"], tags: ["mentor", "NQT", "professional-guidance", "competence"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:school:alumni-returning-to-school", kind: "relationship", description: "An alumnus returning to their school — the experience of being in the building as an adult, the particular emotion of seeing it from a different height, the gratitude that comes with perspective", sceneRoles: ["alumnus", "current school"], industryIds: ["school"], tags: ["alumni", "returning", "adult-height", "gratitude"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
];
