import type { BehaviourKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const DENTAL_BEHAVIOURS: BehaviourKnowledgeNode[] = [
  // ── Pre-treatment anxiety reduction (20) ─────────────────────────────────────
  { id: "behaviour:dental:hands-gripping-armrests", kind: "behaviour", description: "Patient gripping dental chair armrests — white knuckles, tension in arms, the physical manifestation of dental anxiety", emotionalSignal: "anxiety", compatibleHeroes: ["person", "moment"], industryIds: ["dental"], tags: ["anxiety", "gripping", "armrests", "tension"], priority: 1, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:dental:breathing-consciously-in-chair", kind: "behaviour", description: "Patient doing conscious breathing in chair — eyes closed, deliberate inhale/exhale before procedure begins", emotionalSignal: "coping / self-regulation", compatibleHeroes: ["person", "moment"], industryIds: ["dental"], tags: ["breathing", "conscious", "coping", "chair"], priority: 2, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:dental:hands-unclenching-after-kind-word", kind: "behaviour", description: "Hands unclenching in chair after dentist says something reassuring — the physical release of anxiety", emotionalSignal: "relief from reassurance", compatibleHeroes: ["person", "authority"], industryIds: ["dental"], tags: ["unclenching", "hands", "relief", "reassurance"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:dental:feet-pushing-into-footrest", kind: "behaviour", description: "Feet pushing down into chair footrest — whole body braced, anxiety visible from toe to shoulder", emotionalSignal: "braced anxiety", compatibleHeroes: ["person", "moment"], industryIds: ["dental"], tags: ["feet", "pushing", "anxiety", "braced"], priority: 4, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:dental:eyes-tracking-every-instrument", kind: "behaviour", description: "Patient's eyes tracking every instrument the dentist picks up — hypervigilant monitoring", emotionalSignal: "hypervigilance", compatibleHeroes: ["person", "moment"], industryIds: ["dental"], tags: ["eyes-tracking", "instrument", "vigilant", "anxiety"], priority: 5, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:dental:nervous-laugh-at-reception", kind: "behaviour", description: "Nervous laugh when checking in at reception — deflecting anxiety through humour, staff recognising and responding gently", emotionalSignal: "deflecting anxiety", compatibleHeroes: ["person", "authority"], industryIds: ["dental"], tags: ["nervous-laugh", "reception", "deflection", "anxiety"], priority: 6, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "behaviour:dental:explaining-fears-to-dentist", kind: "behaviour", description: "Patient explaining specific fear to dentist — the vulnerability of naming it, dentist listening without dismissal", emotionalSignal: "vulnerable honesty", compatibleHeroes: ["person", "authority"], industryIds: ["dental"], tags: ["fear", "explaining", "vulnerable", "listening"], priority: 7, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:dental:raising-hand-stop-signal", kind: "behaviour", description: "Patient using agreed hand raise to signal stop — the control returned to the patient, the agreement honoured", emotionalSignal: "regained control", compatibleHeroes: ["person", "moment"], industryIds: ["dental"], tags: ["hand-raise", "stop-signal", "control", "agreement"], priority: 8, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:dental:child-holding-parent-hand", kind: "behaviour", description: "Child holding parent's hand during examination — connection providing comfort, parent's calm transferred", emotionalSignal: "comfort through connection", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["child", "parent", "hand-holding", "comfort"], priority: 9, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:dental:scrolling-phone-in-waiting-room", kind: "behaviour", description: "Patient scrolling phone in waiting room — visible distraction attempt, passing time before appointment", emotionalSignal: "distraction-seeking", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["phone", "scrolling", "waiting", "distraction"], priority: 10, weight: 0.77, confidence: "high", commercialScore: 76, futureMetadata: fm },
  { id: "behaviour:dental:dentist-explaining-before-doing", kind: "behaviour", description: "Dentist describing exactly what they're about to do — step by step, patient nodding, anticipation managed", emotionalSignal: "informed preparation", compatibleHeroes: ["authority", "person"], industryIds: ["dental"], tags: ["explaining", "before-procedure", "preparation", "transparency"], priority: 11, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:dental:eyes-closed-during-procedure", kind: "behaviour", description: "Patient with eyes closed during procedure — choosing not to see, managing experience through not-looking", emotionalSignal: "managed coping", compatibleHeroes: ["person", "moment"], industryIds: ["dental"], tags: ["eyes-closed", "procedure", "coping", "managed"], priority: 12, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:dental:headphones-music-procedure", kind: "behaviour", description: "Patient wearing headphones during procedure — music blocking drill sound, self-directed comfort", emotionalSignal: "active coping", compatibleHeroes: ["person", "moment"], industryIds: ["dental"], tags: ["headphones", "music", "drill", "coping"], priority: 13, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:dental:shoulders-dropping-after-anesthetic", kind: "behaviour", description: "Patient's shoulders visibly dropping after anaesthetic takes effect — the body releasing tension as pain pathway blocked", emotionalSignal: "relief at numbness", compatibleHeroes: ["person", "moment"], industryIds: ["dental"], tags: ["shoulders", "dropping", "anaesthetic", "relief"], priority: 14, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:dental:laughing-gas-relaxing", kind: "behaviour", description: "Patient with nitrous oxide mask — visible relaxation spreading through body, eyes softening, hands unclenching", emotionalSignal: "sedation relaxation", compatibleHeroes: ["person", "moment"], industryIds: ["dental"], tags: ["nitrous", "laughing-gas", "relaxation", "sedation"], priority: 15, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── Treatment / professional (25) ────────────────────────────────────────────
  { id: "behaviour:dental:dentist-mirror-examination", kind: "behaviour", description: "Dentist examining with mirror and explorer — systematic, unhurried, calling findings to assistant", emotionalSignal: "systematic expertise", compatibleHeroes: ["authority", "moment"], industryIds: ["dental"], tags: ["examination", "mirror", "systematic", "expertise"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:dental:gloves-snapping-on", kind: "behaviour", description: "Dentist snapping on gloves before procedure — the small ritual that signals readiness and professionalism", emotionalSignal: "professional preparation", compatibleHeroes: ["authority", "moment"], industryIds: ["dental"], tags: ["gloves", "snapping", "preparation", "professional"], priority: 2, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:dental:leaning-over-with-attention", kind: "behaviour", description: "Dentist leaning over patient with focused attention — the posture of care, examination light reflecting", emotionalSignal: "focussed care", compatibleHeroes: ["authority", "person"], industryIds: ["dental"], tags: ["leaning", "attention", "care", "focus"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:dental:shade-matching-teeth", kind: "behaviour", description: "Shade guide held to teeth — comparison, selection, the scientific measurement of colour", emotionalSignal: "precision and care", compatibleHeroes: ["authority", "product"], industryIds: ["dental"], tags: ["shade", "matching", "precision", "care"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:dental:tapping-outside-jaw-diagnostic", kind: "behaviour", description: "Dentist tapping outside of jaw to locate pain — diagnostic process, patient giving feedback", emotionalSignal: "diagnostic collaboration", compatibleHeroes: ["authority", "person"], industryIds: ["dental"], tags: ["tapping", "jaw", "diagnostic", "collaboration"], priority: 5, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:dental:photographing-teeth-for-records", kind: "behaviour", description: "Clinical photographs of teeth being taken — mouth mirror placed, camera positioned, professional documentation", emotionalSignal: "meticulous documentation", compatibleHeroes: ["authority", "product"], industryIds: ["dental"], tags: ["photography", "clinical", "documentation", "records"], priority: 6, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:dental:polishing-teeth-hygiene", kind: "behaviour", description: "Hygienist polishing teeth — prophy cup spinning, paste visible, the cleaning ritual in progress", emotionalSignal: "active care and cleaning", compatibleHeroes: ["authority", "moment"], industryIds: ["dental"], tags: ["polishing", "hygiene", "prophy", "cleaning"], priority: 7, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:dental:flossing-instruction-demonstration", kind: "behaviour", description: "Hygienist demonstrating correct flossing technique — patient watching closely, hands at mouth following along", emotionalSignal: "education and care", compatibleHeroes: ["authority", "person"], industryIds: ["dental"], tags: ["flossing", "instruction", "demonstration", "education"], priority: 8, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:dental:impression-taken-old-vs-digital", kind: "behaviour", description: "Digital vs traditional impression — wand scanning versus putty — the modernity of the experience", emotionalSignal: "modern care", compatibleHeroes: ["authority", "product"], industryIds: ["dental"], tags: ["impression", "digital", "wand", "modern"], priority: 9, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:dental:suction-positioned-assistant", kind: "behaviour", description: "Dental assistant positioning suction — the teamwork of a procedure, assistant anticipating dentist's needs", emotionalSignal: "team coordination", compatibleHeroes: ["authority", "environment"], industryIds: ["dental"], tags: ["suction", "assistant", "teamwork", "anticipation"], priority: 10, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "behaviour:dental:bonding-light-cure", kind: "behaviour", description: "Curing light applied to bonding material — blue LED light, patient with protective glasses, the setting process", emotionalSignal: "precision completion", compatibleHeroes: ["authority", "product"], industryIds: ["dental"], tags: ["curing-light", "bonding", "LED", "precision"], priority: 11, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:dental:patient-checking-bite-paper", kind: "behaviour", description: "Patient biting on articulating paper — the bite check, tapping, the dentist asking 'high or even?'", emotionalSignal: "precision refinement", compatibleHeroes: ["authority", "person"], industryIds: ["dental"], tags: ["bite-check", "articulating-paper", "precision", "refinement"], priority: 12, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:dental:implant-torque-wrench-placed", kind: "behaviour", description: "Implant torque wrench being used — precise rotational force, the engineering precision of implant placement", emotionalSignal: "surgical precision", compatibleHeroes: ["authority", "product"], industryIds: ["dental"], tags: ["implant", "torque", "precision", "surgical"], priority: 13, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:dental:veneer-trial-placed-in-chair", kind: "behaviour", description: "Temporary veneers placed — patient's eyes going wide in the chair, mirror raised, the trial run", emotionalSignal: "transformative reveal", compatibleHeroes: ["person", "transformation"], industryIds: ["dental"], tags: ["veneers", "trial", "mirror", "reveal"], priority: 14, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:dental:gum-recession-measurement", kind: "behaviour", description: "Periodontal probing — numbers being called as depths measured, patient holding still, the health data being gathered", emotionalSignal: "health monitoring", compatibleHeroes: ["authority", "person"], industryIds: ["dental"], tags: ["probing", "measurement", "periodontal", "health"], priority: 15, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },

  // ── Post-treatment delight (20) ───────────────────────────────────────────────
  { id: "behaviour:dental:tongue-over-new-crown", kind: "behaviour", description: "Patient running tongue over new crown in chair — sensing the smoothness, the fit, the difference", emotionalSignal: "tactile discovery", compatibleHeroes: ["person", "product"], industryIds: ["dental"], tags: ["tongue", "crown", "smooth", "discovery"], priority: 1, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:dental:first-smile-after-treatment", kind: "behaviour", description: "First deliberate smile after treatment — tentative, then wider, the permission given by what they see", emotionalSignal: "cautious delight becoming open", compatibleHeroes: ["person", "transformation"], industryIds: ["dental"], tags: ["first-smile", "post-treatment", "cautious", "delight"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:dental:patient-taking-mirror-selfie", kind: "behaviour", description: "Patient taking selfie in dental chair immediately after treatment — phone raised, big smile, can't wait to share", emotionalSignal: "immediate sharing desire", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["selfie", "chair", "immediate", "sharing"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:dental:hugging-dentist-thank-you", kind: "behaviour", description: "Patient hugging dentist after major treatment — the gratitude that exceeds a handshake, the transformation earned", emotionalSignal: "profound gratitude", compatibleHeroes: ["person", "authority"], industryIds: ["dental"], tags: ["hug", "dentist", "gratitude", "major-treatment"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:dental:teeth-brushing-lovingly", kind: "behaviour", description: "Post-treatment morning brushing — careful, attentive, protecting the investment, the relationship with dental hygiene changed", emotionalSignal: "protective care", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["brushing", "morning", "protective", "investment"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:dental:showing-friend-new-smile", kind: "behaviour", description: "Showing new smile to friend — the demonstrating gesture, lifting lip slightly, eyes watching for reaction", emotionalSignal: "shared pride", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["showing-friend", "smile", "reaction", "pride"], priority: 6, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:dental:not-hiding-at-photos", kind: "behaviour", description: "At a photo — not moving to the back, not raising hand to mouth, standing with confidence, smile ready", emotionalSignal: "reclaimed confidence", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["photo", "not-hiding", "confidence", "reclaimed"], priority: 7, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:dental:laughing-fully-without-covering", kind: "behaviour", description: "Laughing fully at a joke — no hand raised to mouth, no pulled back cheeks — completely uninhibited laugh", emotionalSignal: "social freedom", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["laughing", "uninhibited", "freedom", "no-covering"], priority: 8, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:dental:eating-foods-avoided-for-years", kind: "behaviour", description: "Patient eating food they had avoided for years due to sensitivity or missing teeth — the functional restoration joy", emotionalSignal: "functional restoration delight", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["eating", "avoided-food", "restored", "functional-joy"], priority: 9, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:dental:straight-posture-in-conversation", kind: "behaviour", description: "Person holding eye contact and smiling in conversation — no physical shrinking, the smile an asset not a liability", emotionalSignal: "confidence in interaction", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["posture", "eye-contact", "conversation", "confidence"], priority: 10, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Social / lifestyle (20) ───────────────────────────────────────────────────
  { id: "behaviour:dental:deliberate-smile-at-stranger", kind: "behaviour", description: "Deliberate smile at stranger — the person who now deploys their smile as a social tool, not hiding it", emotionalSignal: "social confidence", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["smile-at-stranger", "deliberate", "social", "confidence"], priority: 1, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:dental:making-video-content-no-hesitation", kind: "behaviour", description: "Making social media video — speaking to camera without covering mouth, smile visible throughout", emotionalSignal: "digital confidence", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["video", "camera", "social-media", "digital"], priority: 2, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:dental:ordering-at-restaurant-smiling-server", kind: "behaviour", description: "Smiling at waiter while ordering — the social use of the smile made easy and natural", emotionalSignal: "effortless social warmth", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["restaurant", "ordering", "server", "natural"], priority: 3, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:dental:no-longer-covering-mouth-speaking", kind: "behaviour", description: "Person speaking without hand near mouth — the old habit of concealment dropped, speech fully open", emotionalSignal: "barrier removed", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["speaking", "no-covering", "barrier-removed", "open"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:dental:photo-without-closed-mouth", kind: "behaviour", description: "Person allowing open-mouth photo to be taken — the photographer no longer has to ask them to smile", emotionalSignal: "photo confidence", compatibleHeroes: ["person", "lifestyle"], industryIds: ["dental"], tags: ["photo", "open-mouth", "photographer", "confidence"], priority: 5, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
];
