import type { CommercialSituationKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const DENTAL_COMMERCIAL_SITUATIONS: CommercialSituationKnowledgeNode[] = [
  // ── New patient acquisition (12) ─────────────────────────────────────────────
  { id: "commercial_situation:dental:calling-to-book-first-appointment", kind: "commercial_situation", situation: "Potential new patient calling to book their first appointment after seeing an ad or review", conversionMoment: "Appointment booked and confirmed — new patient record created, first step in relationship taken", visualRepresentation: "Phone to ear, speaking to receptionist, calendar visible on screen, patient name being entered", industryIds: ["dental"], tags: ["new-patient", "booking", "first-call", "conversion"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "commercial_situation:dental:online-booking-first-appointment", kind: "commercial_situation", situation: "Patient booking first appointment through online portal — selecting appointment type, date, and time", conversionMoment: "Confirmation email received — the commitment made digitally, reminder set", visualRepresentation: "Booking portal on phone or desktop, selecting 'New Patient' appointment type, calendar date being chosen", industryIds: ["dental"], tags: ["online-booking", "new-patient", "portal", "digital"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "commercial_situation:dental:instagram-ad-leads-to-enquiry", kind: "commercial_situation", situation: "Instagram smile transformation ad stopping a scroll — DM inquiry sent asking about treatment options", conversionMoment: "Inquiry message sent — lead captured, practice responding to convert to consultation", visualRepresentation: "Instagram feed with before-after smile post, 'Learn More' being tapped, message window opening", industryIds: ["dental"], tags: ["instagram", "before-after", "scroll-stop", "inquiry"], priority: 3, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "commercial_situation:dental:friend-recommendation-call", kind: "commercial_situation", situation: "Patient calling practice because a friend recommended them specifically — highest trust lead", conversionMoment: "Appointment booked with friend's name mentioned — referral recorded, relationship-based acquisition", visualRepresentation: "Person on phone saying 'my friend Sarah recommended you', receptionist noting the referral, appointment confirmed", industryIds: ["dental"], tags: ["referral", "friend-recommendation", "trust", "highest-lead"], priority: 4, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "commercial_situation:dental:google-review-drives-click", kind: "commercial_situation", situation: "Google Maps search for local dentist — five-star rating and recent reviews driving the click and enquiry", conversionMoment: "Click from Google to website, then booking — digital first impression converting", visualRepresentation: "Google Maps result showing 4.9 stars, scrolling reviews, clicking website link, booking page loading", industryIds: ["dental"], tags: ["google-review", "local-search", "stars", "click"], priority: 5, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:dental:emergency-toothache-search", kind: "commercial_situation", situation: "Emergency search 'dentist near me open now' — pain driving immediate conversion with zero price sensitivity", conversionMoment: "First available appointment accepted — the urgency of pain removing all normal friction", visualRepresentation: "Emergency search on phone, 'Emergency Dental' in results, number being called, 'can you see me today?' spoken", industryIds: ["dental"], tags: ["emergency", "pain", "urgency", "same-day"], priority: 6, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "commercial_situation:dental:moving-to-area-need-dentist", kind: "commercial_situation", situation: "New resident searching for dentist — the routine registration need that begins a long relationship", conversionMoment: "Registration form completed and submitted — the practice relationship beginning", visualRepresentation: "New patient registration form on screen, address field showing new area, submitting and receiving welcome email", industryIds: ["dental"], tags: ["new-resident", "registration", "routine", "beginning-of-relationship"], priority: 7, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:dental:insurance-accepted-confirmation", kind: "commercial_situation", situation: "Patient confirming insurance accepted before booking — the financial barrier removed enabling the conversion", conversionMoment: "'Yes, we accept your plan' — barrier removed, booking immediately follows", visualRepresentation: "Patient on call confirming insurance, receptionist checking, confirmation given, appointment being offered", industryIds: ["dental"], tags: ["insurance", "barrier-removal", "acceptance", "booking"], priority: 8, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:dental:practice-website-consultation-request", kind: "commercial_situation", situation: "Visitor exploring cosmetic dentistry page, requesting free consultation — the considered cosmetic lead", conversionMoment: "Consultation request submitted — high-intent lead captured, follow-up call scheduled", visualRepresentation: "Cosmetic dentistry page with before-after gallery, 'Book Free Consultation' button clicked, form being completed", industryIds: ["dental"], tags: ["website", "consultation-request", "cosmetic", "high-intent"], priority: 9, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:dental:community-event-dental-check", kind: "commercial_situation", situation: "Community health event where dental checks are offered — the unexpected touchpoint that converts into a patient", conversionMoment: "Card taken, appointment booked at event — the community touchpoint working as conversion", visualRepresentation: "Community event with dental check booth, participant taking leaflet, booking card being exchanged", industryIds: ["dental"], tags: ["community", "event", "check", "touchpoint"], priority: 10, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "commercial_situation:dental:smile-makeover-competition-enquiry", kind: "commercial_situation", situation: "Entering or seeing a smile makeover giveaway campaign — the aspirational route to treatment beginning", conversionMoment: "Entry form submitted, or inquiry after seeing winner — aspiration becoming enquiry", visualRepresentation: "Competition post on social media, 'Win Your Smile Makeover' visible, entry form being completed", industryIds: ["dental"], tags: ["competition", "smile-makeover", "giveaway", "aspiration"], priority: 11, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "commercial_situation:dental:special-offer-impulse-booking", kind: "commercial_situation", situation: "Limited time whitening or check-up offer driving impulse booking — price creates timing urgency", conversionMoment: "Offer redeemed and appointment confirmed before expiry — urgency working as intended", visualRepresentation: "Promotional offer on email or social with expiry countdown, booking immediately, offer code entered", industryIds: ["dental"], tags: ["offer", "limited-time", "whitening", "impulse"], priority: 12, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },

  // ── Treatment decision / upsell (20) ─────────────────────────────────────────
  { id: "commercial_situation:dental:cosmetic-consultation-case-presented", kind: "commercial_situation", situation: "Cosmetic treatment plan presented at consultation — photos, digital smile design, treatment options, costs", conversionMoment: "Patient agreeing to proceed and signing consent — the considered yes after seeing digital preview", visualRepresentation: "Screen showing digital smile design, treatment plan document, patient nodding, signing the form", industryIds: ["dental"], tags: ["cosmetic-consultation", "case-presented", "digital-smile", "consent"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "commercial_situation:dental:implant-consultation-first-decision", kind: "commercial_situation", situation: "Implant consultation decision — treatment coordinator explaining investment, patient weighing cost vs quality of life", conversionMoment: "Deposit paid for implant treatment — long-considered, high-value decision made", visualRepresentation: "Treatment coordinator at desk, implant model in hand, cost breakdown visible, patient considering then accepting", industryIds: ["dental"], tags: ["implant-consultation", "deposit", "quality-of-life", "high-value"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "commercial_situation:dental:aligner-scan-to-start", kind: "commercial_situation", situation: "Aligner digital scan to initiation — the scan that begins the treatment, the commitment visible in the impression", conversionMoment: "Scan completed and treatment confirmed — the 3D model beginning the transformation journey", visualRepresentation: "Digital scan wand in mouth, 3D model building on screen, patient watching, treatment plan generating", industryIds: ["dental"], tags: ["aligner-scan", "start", "3D-model", "treatment-begin"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:dental:payment-plan-enables-treatment", kind: "commercial_situation", situation: "Patient learning treatment is available on payment plan — the 'I can actually afford this' moment", conversionMoment: "Finance application approved — the barrier to treatment removed, booking made immediately after", visualRepresentation: "Treatment coordinator showing payment plan options, patient's relief visible, calculator showing monthly amount", industryIds: ["dental"], tags: ["payment-plan", "finance", "barrier-removal", "approved"], priority: 4, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:dental:hygiene-recall-compliance", kind: "commercial_situation", situation: "Patient booking recall hygiene appointment — the routine care that keeps the practice relationship alive", conversionMoment: "Appointment booked at reception on exit — next visit secured before leaving the building", visualRepresentation: "Patient at reception desk, next appointment being offered, card being handed, appointment confirmed", industryIds: ["dental"], tags: ["hygiene", "recall", "routine", "retention"], priority: 5, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:dental:whitening-home-kit-purchase", kind: "commercial_situation", situation: "Patient purchasing home whitening kit after in-chair whitening — the at-home maintenance purchase", conversionMoment: "Kit purchased at checkout — product sale extending the clinical relationship into home care", visualRepresentation: "Whitening kit being packaged at reception, patient paying, instructions being explained", industryIds: ["dental"], tags: ["whitening-kit", "home", "maintenance", "product-sale"], priority: 6, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "commercial_situation:dental:electric-toothbrush-recommended", kind: "commercial_situation", situation: "Hygienist recommending electric toothbrush — specific model, clinical reason, product sale in clinical context", conversionMoment: "Patient purchasing recommended brush — clinical authority driving product conversion", visualRepresentation: "Hygienist holding up electric brush model, explaining, patient taking it to reception counter", industryIds: ["dental"], tags: ["electric-toothbrush", "recommendation", "clinical", "product"], priority: 7, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "commercial_situation:dental:check-up-discovers-treatment-need", kind: "commercial_situation", situation: "Routine check-up discovering necessary treatment — the appointment that generates further revenue through proper examination", conversionMoment: "Treatment booked at same appointment or recalled — the routine check as diagnostic revenue generator", visualRepresentation: "Dentist showing X-ray finding to patient, explaining treatment need, receptionist booking the treatment", industryIds: ["dental"], tags: ["check-up", "discovery", "treatment-need", "diagnostic"], priority: 8, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:dental:membership-plan-sign-up", kind: "commercial_situation", situation: "Patient signing up for practice membership plan — routine care included, monthly fee establishing relationship", conversionMoment: "Direct debit mandate signed — recurring revenue secured, patient retention improved", industryIds: ["dental"], visualRepresentation: "Membership plan brochure, direct debit form, patient signing, annual savings being explained", tags: ["membership", "plan", "direct-debit", "recurring"], priority: 9, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:dental:second-opinion-converts", kind: "commercial_situation", situation: "Patient seeking second opinion from practice — unhappy with previous quote or diagnosis, trust built at second opinion", conversionMoment: "Patient agreeing to proceed with this practice after second opinion consultation — transferred loyalty", visualRepresentation: "Patient at consultation with previous dental records, dentist reviewing, building confidence, treatment agreed", industryIds: ["dental"], tags: ["second-opinion", "transfer", "trust", "converts"], priority: 10, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Loyalty / retention (18) ──────────────────────────────────────────────────
  { id: "commercial_situation:dental:recall-letter-prompts-booking", kind: "commercial_situation", situation: "Recall letter or text prompting overdue patient to book — the passive lapsed patient reactivated", conversionMoment: "Appointment booked after recall — lapsed patient returned to active status", visualRepresentation: "Recall text message on phone, 'Time for your check-up', link to book tapped, appointment confirmed", industryIds: ["dental"], tags: ["recall", "lapsed", "reactivation", "text"], priority: 1, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "commercial_situation:dental:five-star-review-posted", kind: "commercial_situation", situation: "Patient posting five-star review after exceptional experience — unprompted advocacy creating future patients", conversionMoment: "Review published publicly — future patients converted by this patient's honest experience", visualRepresentation: "Google review being written, five stars selected, specific praise typed, 'Post' being tapped", industryIds: ["dental"], tags: ["review", "five-star", "advocacy", "unprompted"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:dental:family-registration-one-by-one", kind: "commercial_situation", situation: "Patient registering family members one by one — the expanding family account, each member a patient", conversionMoment: "Each family member booked in — the practice becoming the family's dental home", visualRepresentation: "Patient at reception registering child, then partner, then parent — family becoming practice patients", industryIds: ["dental"], tags: ["family", "registration", "expanding", "home"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:dental:annual-check-without-reminder", kind: "commercial_situation", situation: "Patient booking annual check without requiring a reminder — the proactive health behaviour that marks retention", conversionMoment: "Self-initiated booking — the practice embedded in the patient's health routine without prompting", visualRepresentation: "Patient calling or booking online without any recall prompting, 'Just booking my annual check'", industryIds: ["dental"], tags: ["annual", "self-initiated", "proactive", "routine"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "commercial_situation:dental:leaving-with-next-appointment", kind: "commercial_situation", situation: "Patient leaving with next appointment already booked — the standard that prevents lapse before it starts", conversionMoment: "Card in hand with next appointment date — retention architecture working at its most basic", visualRepresentation: "Patient at reception desk, appointment card being handed, date written clearly, patient putting card in wallet", industryIds: ["dental"], tags: ["next-appointment", "leaving", "card", "retention"], priority: 5, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:dental:referring-colleague-to-practice", kind: "commercial_situation", situation: "Existing patient recommending practice to colleague at work — the organic referral network in action", conversionMoment: "New patient calling with existing patient's name — referral chain completing", visualRepresentation: "Two colleagues at coffee, one showing the other their smile, handing over practice's card from wallet", industryIds: ["dental"], tags: ["referral", "colleague", "organic", "network"], priority: 6, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:dental:smile-transformation-ambassador", kind: "commercial_situation", situation: "Transformed patient agreeing to be a case study or ambassador — the highest form of patient advocacy", conversionMoment: "Consent to use before-after photos and testimonial — earned authority converting future patients", visualRepresentation: "Patient being photographed for case study, signing consent, smiling for before-after, proud of contribution", industryIds: ["dental"], tags: ["ambassador", "case-study", "before-after", "consent"], priority: 7, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:dental:annual-membership-renewal", kind: "commercial_situation", situation: "Membership plan renewal — patient choosing to continue their annual care plan without prompting", conversionMoment: "Renewal confirmed — year two of the recurring relationship secured", visualRepresentation: "Renewal notification sent, patient confirming continuation, credit card updated, new year beginning", industryIds: ["dental"], tags: ["renewal", "membership", "recurring", "year-two"], priority: 8, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
];
