import type { EmotionalMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const DENTAL_EMOTIONAL_MOMENTS: EmotionalMomentKnowledgeNode[] = [
  // ── Transformation reveal (15) ────────────────────────────────────────────────
  { id: "emotional_moment:dental:mirror-reveal-tears", kind: "emotional_moment", moment: "Patient sees their transformed smile in mirror for first time — tears forming, dentist standing back, the moment of recognition", emotionType: "overwhelming joy and disbelief", visualSignals: ["eyes glistening", "hand going to mouth", "reflection of new smile visible", "shoulders shaking slightly"], industryIds: ["dental"], tags: ["mirror", "reveal", "tears", "transformation"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "emotional_moment:dental:braces-off-wide-eyes", kind: "emotional_moment", moment: "Braces removed after 18 months — teenager's wide eyes in mirror, running tongue over smooth teeth, then the huge smile", emotionType: "relief and joy", visualSignals: ["wide eyes at reflection", "tongue running over teeth", "then smile breaking wide", "hands pressing cheeks"], industryIds: ["dental"], tags: ["braces-off", "teenager", "relief", "smooth"], priority: 2, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:dental:veneer-reveal-frozen-then-smile", kind: "emotional_moment", moment: "Veneers revealed for first time — patient frozen for three seconds processing what they see, then the smile", emotionType: "processing followed by delight", visualSignals: ["absolute stillness", "then processing blink", "then smile wider than expected", "looking to dentist for confirmation"], industryIds: ["dental"], tags: ["veneers", "frozen", "processing", "delight"], priority: 3, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:dental:whitening-result-shade-check", kind: "emotional_moment", moment: "Shade guide comparison after whitening — patient seeing the improvement in numbers, the quantified delight", emotionType: "measurable satisfaction", visualSignals: ["shade guide held up", "before and after shades side by side", "patient's face comparing", "satisfaction of measurable improvement"], industryIds: ["dental"], tags: ["whitening", "shade", "measurable", "satisfaction"], priority: 4, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "emotional_moment:dental:implant-complete-first-look", kind: "emotional_moment", moment: "Implant crown completed and placed — patient asking for mirror, seeing the gap now filled, years of self-consciousness ending", emotionType: "gap closing joy", visualSignals: ["mirror raised", "mouth opened wide", "gap now filled visible", "closed-mouth smile forming"], industryIds: ["dental"], tags: ["implant", "crown", "gap-filled", "complete"], priority: 5, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:dental:aligner-milestone-progress-photo", kind: "emotional_moment", moment: "Month 4 aligner progress photo — patient holding earlier photo beside current position, visible improvement striking them", emotionType: "progress recognition", visualSignals: ["two photos side by side", "patient comparing carefully", "recognition arriving on face", "growing smile"], industryIds: ["dental"], tags: ["aligner", "progress", "milestone", "comparison"], priority: 6, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:dental:first-open-laugh-after", kind: "emotional_moment", moment: "First fully open laugh after treatment — happening naturally in conversation, the patient realising they didn't cover up", emotionType: "unconscious freedom", visualSignals: ["mouth fully open laughing", "no hand near mouth", "realisation dawning mid-laugh", "then bigger smile"], industryIds: ["dental"], tags: ["laugh", "open", "unconscious", "freedom"], priority: 7, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:dental:dentist-saying-youre-done", kind: "emotional_moment", moment: "Dentist saying 'You're done' after final treatment session — the treatment journey complete, exhale of relief", emotionType: "journey completion", visualSignals: ["patient's deep exhale", "shoulders dropping", "disbelief then relief", "dentist's satisfied expression"], industryIds: ["dental"], tags: ["done", "complete", "exhale", "journey"], priority: 8, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "emotional_moment:dental:before-photo-reaction", kind: "emotional_moment", moment: "Patient shown their before photo months after treatment — 'Was that me?' The distance from their former self visible", emotionType: "distance from former self", visualSignals: ["studying the photo", "disbelief", "looking up at reflection", "the change now visible by contrast"], industryIds: ["dental"], tags: ["before-photo", "disbelief", "distance", "change"], priority: 9, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:dental:sharing-result-on-social-media", kind: "emotional_moment", moment: "Patient posting before-after to social media — the decision to share publicly, to be seen, vulnerability and pride", emotionType: "proud vulnerability", visualSignals: ["posting to screen", "before-after photo visible", "caption being typed", "finger hovering over post"], industryIds: ["dental"], tags: ["social-media", "posting", "before-after", "public"], priority: 10, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Relief from pain / fear (15) ─────────────────────────────────────────────
  { id: "emotional_moment:dental:toothache-relief-chair", kind: "emotional_moment", moment: "Toothache treated — the moment the pain stops, hand leaving jaw, eyes closing in relief, the world returning to normal", emotionType: "relief from pain", visualSignals: ["hand dropping from jaw", "deep exhale", "eyes closing then opening soft", "colour returning to face"], industryIds: ["dental"], tags: ["toothache", "pain-relief", "jaw", "exhale"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:dental:anxious-patient-surviving-appointment", kind: "emotional_moment", moment: "Dental phobic completing appointment — walking out standing tall, the impossibility made possible", emotionType: "pride at overcoming fear", visualSignals: ["standing taller on exit", "slight disbelief in expression", "involuntary smile", "maybe text to someone waiting"], industryIds: ["dental"], tags: ["phobia", "completing", "overcoming", "pride"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:dental:anaesthetic-taking-effect", kind: "emotional_moment", moment: "Anaesthetic taking effect — patient's face physically relaxing, the tension leaving jaw and shoulder", emotionType: "relief at numbness", visualSignals: ["jaw visibly relaxing", "shoulder tension releasing", "slower breathing", "face softening"], industryIds: ["dental"], tags: ["anaesthetic", "relaxing", "jaw", "tension-release"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "emotional_moment:dental:emergency-patient-seen-same-day", kind: "emotional_moment", moment: "Emergency patient told they can be seen today — the relief of not having to wait through the pain", emotionType: "immediate relief", visualSignals: ["visible relief on phone", "tension releasing in face", "gratitude expressed immediately", "coming through the door already better"], industryIds: ["dental"], tags: ["emergency", "same-day", "relief", "pain"], priority: 4, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "emotional_moment:dental:oral-cancer-clear-result", kind: "emotional_moment", moment: "Oral cancer screening result: all clear — the relief from the fear that had been there since the lump was noticed", emotionType: "relief from existential fear", visualSignals: ["exhale of relief", "tears forming", "hands pressed together", "smile of gratitude"], industryIds: ["dental"], tags: ["cancer-screening", "clear", "relief", "existential"], priority: 5, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:dental:child-leaving-with-sticker", kind: "emotional_moment", moment: "Child leaving dental practice with sticker — thumbs up, smile, 'that wasn't so bad' — the fear-free appointment achieved", emotionType: "childlike pride and relief", visualSignals: ["sticker on shirt", "thumbs up gesture", "skipping not walking", "parent's relief visible too"], industryIds: ["dental"], tags: ["child", "sticker", "thumbs-up", "fear-free"], priority: 6, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "emotional_moment:dental:sleeping-no-grinding-mouthguard", kind: "emotional_moment", moment: "Night guard fitted — no more waking with jaw pain, the morning after the fitting the first pain-free morning in months", emotionType: "quiet sustained relief", visualSignals: ["person waking without jaw-hold gesture", "stretching normally", "noticing the absence of pain", "small private smile"], industryIds: ["dental"], tags: ["night-guard", "grinding", "relief", "morning"], priority: 7, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "emotional_moment:dental:dentist-saying-dont-need-filling", kind: "emotional_moment", moment: "Dentist saying 'No fillings needed this time' — the patient who maintained good care rewarded with the best news", emotionType: "validated care and relief", visualSignals: ["visible relief on face", "slight exhale", "smile at self-confirmation", "booking next check ready"], industryIds: ["dental"], tags: ["no-filling", "good-news", "relief", "validated"], priority: 8, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── Confidence / social moments (12) ─────────────────────────────────────────
  { id: "emotional_moment:dental:first-date-smiling-freely", kind: "emotional_moment", moment: "First date after treatment — no filter on the smile, no hesitation, the smile deployed fully and immediately", emotionType: "social confidence deployed", visualSignals: ["open smile immediately", "leaning forward without reserve", "eye contact with smile maintained", "no hand near mouth"], industryIds: ["dental"], tags: ["date", "smile", "deployed", "confident"], priority: 1, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "emotional_moment:dental:job-interview-handshake-smile", kind: "emotional_moment", moment: "Job interview handshake with full smile — confidence projecting through the room, the interviewer responding", emotionType: "professional confidence", visualSignals: ["firm handshake", "full smile", "direct eye contact", "straight posture"], industryIds: ["dental"], tags: ["interview", "handshake", "confidence", "professional"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:dental:wedding-smile-photos", kind: "emotional_moment", moment: "Wedding photographs with open smile — not one closed-mouth photo, the entire album as evidence of the transformation", emotionType: "documented freedom", visualSignals: ["every photo open-smile", "photographer capturing natural joy", "no forced closed mouth", "real expressions throughout"], industryIds: ["dental"], tags: ["wedding", "photos", "open-smile", "documented"], priority: 3, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:dental:stage-moment-smile-open", kind: "emotional_moment", moment: "Speaking on stage, performing, or presenting — the smile natural and open to an audience, confidence visible at room scale", emotionType: "public confidence", visualSignals: ["open smile to audience", "body language open", "no self-consciousness", "room responding warmly"], industryIds: ["dental"], tags: ["stage", "public", "open", "confidence"], priority: 4, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "emotional_moment:dental:old-photo-comparison-emotional", kind: "emotional_moment", moment: "Looking at old photos where mouth is closed — and comparing to current photos where it is not — the contrast emotional", emotionType: "gratitude and distance from former self", visualSignals: ["two photos held side by side", "old: closed mouth", "new: open smile", "emotional processing"], industryIds: ["dental"], tags: ["old-photo", "comparison", "emotional", "gratitude"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
];
