import type { RelationshipKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const DENTAL_RELATIONSHIPS: RelationshipKnowledgeNode[] = [
  // ── Patient–dentist trust (15) ────────────────────────────────────────────────
  { id: "relationship:dental:anxious-patient-reassuring-dentist", kind: "relationship", description: "Anxious patient and reassuring dentist — the dentist earning trust through patience and explanation, anxiety giving way", sceneRoles: ["anxious patient", "reassuring dentist"], industryIds: ["dental"], tags: ["anxiety", "trust-building", "reassurance", "earned-trust"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:dental:regular-patient-familiar-dentist", kind: "relationship", description: "Regular patient with their dentist of many years — familiar ease, first-name basis, the comfort of known care", sceneRoles: ["regular patient", "familiar dentist"], industryIds: ["dental"], tags: ["regular", "familiar", "years", "comfort"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:dental:new-patient-establishing-trust", kind: "relationship", description: "New patient at first appointment — cautious, evaluating, dentist earning confidence through transparency and care", sceneRoles: ["new patient", "dentist"], industryIds: ["dental"], tags: ["new-patient", "evaluating", "earning-trust", "first-appointment"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:dental:phobia-patient-specialist", kind: "relationship", description: "Dental phobia patient with specialist — years of avoidance meeting a dentist trained to handle exactly this", sceneRoles: ["phobia patient", "specialist dentist"], industryIds: ["dental"], tags: ["phobia", "specialist", "avoidance", "breakthrough"], priority: 4, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:dental:cosmetic-consultation-excited-patient", kind: "relationship", description: "Cosmetic patient in consultation — excited, invested, collaborating on their ideal outcome with the dentist", sceneRoles: ["cosmetic patient", "cosmetic dentist"], industryIds: ["dental"], tags: ["cosmetic", "consultation", "excited", "collaboration"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:dental:implant-patient-surgeon", kind: "relationship", description: "Implant patient and oral surgeon — the major treatment relationship, high trust, high stakes, high gratitude", sceneRoles: ["implant patient", "oral surgeon"], industryIds: ["dental"], tags: ["implant", "surgeon", "high-trust", "high-stakes"], priority: 6, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:dental:orthodontic-patient-ongoing", kind: "relationship", description: "Orthodontic patient in ongoing treatment — monthly visits, the relationship building through the transformation", sceneRoles: ["orthodontic patient", "orthodontist"], industryIds: ["dental"], tags: ["orthodontic", "ongoing", "monthly", "relationship-over-time"], priority: 7, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:dental:child-patient-kind-dentist", kind: "relationship", description: "Child patient with kind, fun dental practice — turning fear into fun, the critical relationship for lifelong dental health", sceneRoles: ["child patient", "paediatric dentist"], industryIds: ["dental"], tags: ["child", "fun", "kind", "lifelong-habit"], priority: 8, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:dental:elderly-patient-dignified-care", kind: "relationship", description: "Elderly patient with dentist providing dignified, adapted care — the adjustment of approach to the patient's needs", sceneRoles: ["elderly patient", "dentist"], industryIds: ["dental"], tags: ["elderly", "adapted-care", "dignity", "adjusted"], priority: 9, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:dental:dentist-patient-shared-decision", kind: "relationship", description: "Shared decision making — dentist presenting options, patient choosing their own path, collaborative dentistry", sceneRoles: ["patient", "dentist"], industryIds: ["dental"], tags: ["shared-decision", "options", "collaborative", "autonomy"], priority: 10, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Family / generational (10) ────────────────────────────────────────────────
  { id: "relationship:dental:parent-child-dental-appointment", kind: "relationship", description: "Parent accompanying child to dental appointment — anxiety managed by modelling calm, habit formation watched", sceneRoles: ["parent", "child"], industryIds: ["dental"], tags: ["parent-child", "accompaniment", "modelling", "habit"], priority: 1, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:dental:grandparent-grandchild-dentist", kind: "relationship", description: "Grandparent bringing grandchild to practice they have used for 30 years — the generational continuity of a trusted practice", sceneRoles: ["grandparent", "grandchild"], industryIds: ["dental"], tags: ["generational", "30-years", "continuity", "trust"], priority: 2, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:dental:partner-support-major-treatment", kind: "relationship", description: "Partner accompanying patient for major treatment — waiting, the support presence making the procedure possible", sceneRoles: ["patient", "supporting partner"], industryIds: ["dental"], tags: ["partner", "support", "major-treatment", "accompaniment"], priority: 3, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:dental:siblings-both-at-practice", kind: "relationship", description: "Two siblings both patients at the same practice — family as patient unit, care as family institution", sceneRoles: ["sibling A", "sibling B"], industryIds: ["dental"], tags: ["siblings", "family-practice", "unit", "institution"], priority: 4, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "relationship:dental:mother-daughter-cosmetic", kind: "relationship", description: "Mother and daughter both getting cosmetic work — shared investment in confidence, generational smile commitment", sceneRoles: ["mother", "daughter"], industryIds: ["dental"], tags: ["mother-daughter", "cosmetic", "shared", "confidence"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── Clinical team (10) ────────────────────────────────────────────────────────
  { id: "relationship:dental:dentist-dental-assistant-choreography", kind: "relationship", description: "Dentist and dental assistant working in seamless choreography — anticipation, no verbal instruction needed", sceneRoles: ["dentist", "dental assistant"], industryIds: ["dental"], tags: ["choreography", "team", "anticipation", "seamless"], priority: 1, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:dental:hygienist-patient-education", kind: "relationship", description: "Hygienist educating patient during cleaning — the explaining relationship, not just cleaning but teaching", sceneRoles: ["hygienist", "patient"], industryIds: ["dental"], tags: ["hygienist", "education", "teaching", "cleaning"], priority: 2, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:dental:treatment-coordinator-patient", kind: "relationship", description: "Treatment coordinator walking patient through options and costs — the bridge between clinical and accessible", sceneRoles: ["treatment coordinator", "patient"], industryIds: ["dental"], tags: ["treatment-coordinator", "options", "costs", "accessible"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:dental:reception-nervous-arrival", kind: "relationship", description: "Receptionist managing nervous patient's arrival — the first human contact, warmth reducing the threshold anxiety", sceneRoles: ["receptionist", "nervous patient"], industryIds: ["dental"], tags: ["receptionist", "nervous", "arrival", "first-contact"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:dental:principal-referring-specialist", kind: "relationship", description: "Principal dentist referring patient to specialist colleague — the trust network, referral as continued care", sceneRoles: ["principal dentist", "specialist"], industryIds: ["dental"], tags: ["referral", "specialist", "network", "continued-care"], priority: 5, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },

  // ── Before / after social (10) ────────────────────────────────────────────────
  { id: "relationship:dental:friend-noticing-difference", kind: "relationship", description: "Friend noticing the change before it is mentioned — 'You look different, did something change?' the unprompted compliment", sceneRoles: ["transformed patient", "noticing friend"], industryIds: ["dental"], tags: ["friend", "noticing", "unprompted", "change"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:dental:partner-reaction-to-transformation", kind: "relationship", description: "Partner's reaction to the smile transformation — seeing their person differently, attraction rekindled", sceneRoles: ["transformed patient", "partner"], industryIds: ["dental"], tags: ["partner", "reaction", "attraction", "transformation"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:dental:colleague-complimenting-headshot", kind: "relationship", description: "Colleague complimenting new professional photo — 'Wow, that's your new headshot?' the career impact visible", sceneRoles: ["transformed patient", "colleague"], industryIds: ["dental"], tags: ["colleague", "headshot", "professional", "impact"], priority: 3, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:dental:interviewer-response-to-smile", kind: "relationship", description: "Job interviewer visibly engaging more with confident-smiling candidate — the unmeasured but real advantage", sceneRoles: ["candidate", "interviewer"], industryIds: ["dental"], tags: ["interview", "engagement", "smile-advantage", "confidence"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:dental:patient-recommending-to-friend", kind: "relationship", description: "Transformed patient recommending practice to friend — the authentic advocacy that comes from genuine result", sceneRoles: ["patient advocate", "friend"], industryIds: ["dental"], tags: ["recommendation", "advocate", "friend", "authentic"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
];
