import type { SceneTypeKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const DENTAL_SCENE_TYPES: SceneTypeKnowledgeNode[] = [
  // ── Clinical / surgery environments (30) ────────────────────────────────────
  { id: "scene_type:dental:modern-bright-surgery", kind: "scene_type", environment: "Modern dental surgery — white walls, adjustable chair, overhead light arm, clinical equipment in clean arrangement", lightingCharacter: "Overhead dental light at 5000K, bright white fill, no shadows on work area, face light even and clinical", mood: "Confident competence — every surface clean, every tool accessible, the space says 'you are in good hands'", industryIds: ["dental"], compatibleHeroTypes: ["authority", "person", "product"], tags: ["surgery", "modern", "bright", "clinical"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "scene_type:dental:luxury-boutique-surgery", kind: "scene_type", environment: "Boutique dental surgery — warm wood accents, art on walls, premium chair, calm palette, not institutional", lightingCharacter: "Warm ambient at 3000K, targeted dental light, art lighting at walls, premium feel without cold hospital", mood: "Clinic that feels like a spa — reducing anxiety through beauty and comfort", industryIds: ["dental"], compatibleHeroTypes: ["lifestyle", "person", "environment"], tags: ["boutique", "luxury", "warm", "spa-like"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "scene_type:dental:pediatric-colourful-fun", kind: "scene_type", environment: "Paediatric dental surgery — murals on walls, cartoon characters, TV on ceiling, child-height counter", lightingCharacter: "Bright warm light at 3500K, colours on walls creating ambient tint, overhead screen casting secondary glow", mood: "Adventure not ordeal — the fear of dentistry replaced by something approaching excitement", industryIds: ["dental"], compatibleHeroTypes: ["person", "lifestyle", "environment"], tags: ["pediatric", "colourful", "cartoon", "fun"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "scene_type:dental:digital-technology-surgery", kind: "scene_type", environment: "Technology-forward surgery — multiple screens, digital impression wand, CBCT scanner visible through door", lightingCharacter: "Multiple screen glow, clean overhead, equipment LED indicators contributing to ambient", mood: "Leading-edge capability — this practice invests in technology because they invest in patients", industryIds: ["dental"], compatibleHeroTypes: ["product", "authority", "environment"], tags: ["technology", "digital", "screens", "modern"], priority: 4, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "scene_type:dental:consultation-room-private", kind: "scene_type", environment: "Private consultation room — comfortable chairs, desk, treatment images on wall, no clinical equipment visible", lightingCharacter: "Warm office lighting at 3000K, natural light from window, welcoming rather than clinical", mood: "Safe to ask questions — this room is about decision making, not procedures", industryIds: ["dental"], compatibleHeroTypes: ["authority", "person", "lifestyle"], tags: ["consultation", "private", "comfortable", "welcoming"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:dental:recovery-area-comfortable", kind: "scene_type", environment: "Post-treatment recovery area — recliner chair, blanket, water offered, calm space after procedure", lightingCharacter: "Soft warm light at 2800K, dimmer than surgery, calm and restorative", mood: "Care extends beyond the chair — the practice thinking of the whole person", industryIds: ["dental"], compatibleHeroTypes: ["person", "lifestyle"], tags: ["recovery", "recliner", "calm", "aftercare"], priority: 6, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "scene_type:dental:sterilisation-room-visible", kind: "scene_type", environment: "Sterilisation area visible through glass — autoclave, pouched instruments, the hygiene process transparent", lightingCharacter: "Bright clinical light at 4000K, instruments visible, cleanliness the visual message", mood: "You can see how seriously we take safety — the transparency itself builds trust", industryIds: ["dental"], compatibleHeroTypes: ["authority", "environment", "product"], tags: ["sterilisation", "visible", "transparent", "hygiene"], priority: 7, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "scene_type:dental:panoramic-xray-lightbox", kind: "scene_type", environment: "X-ray viewing — panoramic radiograph on lightbox or screen, dentist and patient examining together", lightingCharacter: "Lightbox glowing, room otherwise dim, the X-ray as primary light source on faces", mood: "Education as care — the patient being shown their own mouth creates ownership of their health", industryIds: ["dental"], compatibleHeroTypes: ["authority", "person", "product"], tags: ["x-ray", "lightbox", "education", "examination"], priority: 8, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:dental:implant-surgery-suite", kind: "scene_type", environment: "Implant surgery suite — surgical drapes, specialist lighting, implant kit, full surgical preparation visible", lightingCharacter: "Surgical light at 6000K, clean and focused, everything else receding into bright white clinical background", mood: "Surgical precision — this is not a standard appointment, this is a surgical procedure done with full care", industryIds: ["dental"], compatibleHeroTypes: ["authority", "product", "environment"], tags: ["implant", "surgical", "drapes", "precision"], priority: 9, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:dental:CAD-CAM-milling-machine", kind: "scene_type", environment: "In-house milling machine room — CAD/CAM unit producing crown, same-day dentistry happening in real time", lightingCharacter: "Machine LED lighting, process visible through viewing window, technical light blue-white", mood: "Same day, no lab wait — technology enabling the convenience that patients value", industryIds: ["dental"], compatibleHeroTypes: ["product", "environment", "authority"], tags: ["CAD-CAM", "milling", "same-day", "technology"], priority: 10, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── Reception / waiting environments (20) ────────────────────────────────────
  { id: "scene_type:dental:warm-welcoming-reception", kind: "scene_type", environment: "Warm reception desk — flowers, branded materials, friendly receptionist, not clinical, entering a welcoming space", lightingCharacter: "Warm reception lighting at 2800K, accent lights behind desk, natural light from windows, inviting", mood: "The anxiety of arrival is met with warmth — the practice communicates care from step one", industryIds: ["dental"], compatibleHeroTypes: ["person", "lifestyle", "environment"], tags: ["reception", "welcoming", "flowers", "warmth"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "scene_type:dental:calm-waiting-area-art", kind: "scene_type", environment: "Calm waiting area — curated art, plants, comfortable seating, coffee station, no old magazines", lightingCharacter: "Ambient at 3000K, natural light supplement, artwork lighting, calm and considered", mood: "Not a waiting room but a pause space — this practice has thought about how waiting feels", industryIds: ["dental"], compatibleHeroTypes: ["lifestyle", "environment", "person"], tags: ["waiting-area", "art", "plants", "calm"], priority: 2, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:dental:before-after-gallery-wall", kind: "scene_type", environment: "Before and after gallery wall in practice — framed cases, real patients, the proof in the space itself", lightingCharacter: "Gallery lighting at 3500K, frames individually lit, professional presentation", mood: "The evidence is on the walls — every visit reinforces the trust through visible results", industryIds: ["dental"], compatibleHeroTypes: ["transformation", "lifestyle", "environment"], tags: ["gallery", "before-after", "cases", "proof"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:dental:child-play-corner-waiting", kind: "scene_type", environment: "Children's play corner in waiting area — books, small toys, low table, designed to make arrival easy", lightingCharacter: "Warm light, slightly brighter in play corner, child-scaled lighting detail", mood: "We thought of your child too — the practice thinking about the whole family experience", industryIds: ["dental"], compatibleHeroTypes: ["lifestyle", "person", "environment"], tags: ["children", "play-corner", "family", "waiting"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "scene_type:dental:awards-credentials-display", kind: "scene_type", environment: "Credentials display wall — degrees, specialist certificates, awards, professional memberships framed", lightingCharacter: "Focused lighting on frame wall, warm ambient surrounds, professional gravitas", mood: "Experience accumulated and displayed — the qualifications doing the persuasion for the practice", industryIds: ["dental"], compatibleHeroTypes: ["authority", "environment", "lifestyle"], tags: ["credentials", "awards", "qualifications", "trust"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── Smile / lifestyle / social environments (30) ─────────────────────────────
  { id: "scene_type:dental:natural-daylight-portrait", kind: "scene_type", environment: "Natural light portrait setting — window beside subject, soft diffused fill from opposite, no studio feel", lightingCharacter: "Natural daylight at 5500K from window, soft reflector fill, clean catchlights in eyes", mood: "Authentic and real — this is a person not a model, the smile is theirs not performed", industryIds: ["dental"], compatibleHeroTypes: ["person", "lifestyle", "transformation"], tags: ["natural-light", "portrait", "window", "authentic"], priority: 1, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "scene_type:dental:bathroom-mirror-morning", kind: "scene_type", environment: "Bathroom mirror scene — person looking at their smile in morning light, personal private moment", lightingCharacter: "Warm bathroom light at 3000K, mirror reflection, slight soft ambient from window", mood: "The private practice of self-regard — the morning ritual with the smile as the subject", industryIds: ["dental"], compatibleHeroTypes: ["person", "lifestyle"], tags: ["bathroom", "mirror", "morning", "private"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:dental:outdoor-bright-daylight-smile", kind: "scene_type", environment: "Outdoors bright day — person in natural setting, full daylight, the confidence to smile in harsh outdoor light", lightingCharacter: "Bright 6000K daylight, slight overhead softening, teeth visible in any light", mood: "Nothing to hide — the confidence to smile in bright light, the ultimate test of the transformation", industryIds: ["dental"], compatibleHeroTypes: ["person", "lifestyle", "transformation"], tags: ["outdoor", "daylight", "confidence", "smile"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "scene_type:dental:corporate-boardroom-smile", kind: "scene_type", environment: "Corporate environment — boardroom, presentation setting, professional confidence, the smile in a work context", lightingCharacter: "Corporate ambient at 3500K, professional overhead, faces well lit and authoritative", mood: "Professional confidence — the career implication of dental confidence made visible and specific", industryIds: ["dental"], compatibleHeroTypes: ["lifestyle", "authority", "person"], tags: ["corporate", "boardroom", "professional", "confidence"], priority: 4, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "scene_type:dental:wedding-venue-smile", kind: "scene_type", environment: "Wedding venue — couple or bridal party, the most photographed day, smile context explicit", lightingCharacter: "Golden hour or venue romantic lighting, backlit for halo, faces warm and luminous", mood: "The most photographed day — the smile that will be frozen in the album for a hundred years", industryIds: ["dental"], compatibleHeroTypes: ["lifestyle", "person", "moment"], tags: ["wedding", "venue", "occasion", "photography"], priority: 5, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "scene_type:dental:social-gathering-open-smile", kind: "scene_type", environment: "Social gathering — dinner party or event, the person who now laughs openly, uninhibited in company", lightingCharacter: "Warm social ambient at 2800K, faces close together, the light of communal warmth", mood: "Social freedom — the gathering where the smile is no longer a liability but an asset", industryIds: ["dental"], compatibleHeroTypes: ["lifestyle", "person", "moment"], tags: ["social", "gathering", "dinner", "uninhibited"], priority: 6, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:dental:family-portrait-outdoors", kind: "scene_type", environment: "Family portrait in park or garden — relaxed, everyone smiling, multi-generational dental investment visible", lightingCharacter: "Bright natural light, slight overcast softening, warm late afternoon colour", mood: "Family document — the family that all smiles, the investment visible in every face", industryIds: ["dental"], compatibleHeroTypes: ["lifestyle", "person"], tags: ["family", "portrait", "garden", "multi-gen"], priority: 7, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:dental:beach-holiday-smile", kind: "scene_type", environment: "Beach setting — summer, the person who is confident enough to be photographed in holiday mode", lightingCharacter: "Bright coastal light, sun from above, reflective white sand fill, high key and summer", mood: "Holiday uninhibited — the smile works in every light, including the unforgiving brightness of the beach", industryIds: ["dental"], compatibleHeroTypes: ["lifestyle", "person", "transformation"], tags: ["beach", "holiday", "confident", "summer"], priority: 8, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "scene_type:dental:close-up-teeth-detail-studio", kind: "scene_type", environment: "Studio close-up — tight frame on smile, controlled light on teeth, the craftsmanship of dentistry at macro level", lightingCharacter: "Studio light at 5500K, specular on teeth surfaces, shadow control precise, teeth as sculpture", mood: "Clinical beauty — the teeth as art object, dentistry as precision craft", industryIds: ["dental"], compatibleHeroTypes: ["product", "transformation", "person"], tags: ["studio", "close-up", "macro", "craftsmanship"], priority: 9, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:dental:video-call-screen-smile", kind: "scene_type", environment: "Video call setting — home office or professional, person smiling through screen, virtual context", lightingCharacter: "Ring light or window facing, screen glow as fill, modern video call light setup", mood: "Modern professional context — the smile that matters in the digital world, confident on camera", industryIds: ["dental"], compatibleHeroTypes: ["lifestyle", "person", "transformation"], tags: ["video-call", "zoom", "digital", "professional"], priority: 10, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── Product / technology close-ups (20) ──────────────────────────────────────
  { id: "scene_type:dental:aligner-on-white-surface", kind: "scene_type", environment: "Clear aligner on white surface — product hero shot, the invisibility visible in macro, precision visible", lightingCharacter: "Studio macro light, clean white background, aligner catching light to show transparency", mood: "Innovation at product level — the technology itself is the story, invisible but transforming", industryIds: ["dental"], compatibleHeroTypes: ["product", "transformation"], tags: ["aligner", "clear", "product-hero", "macro"], priority: 1, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "scene_type:dental:dental-implant-precision-shot", kind: "scene_type", environment: "Dental implant titanium post macro — threads visible, surface texture, the precision of the component", lightingCharacter: "Studio macro, clinical light at 5500K, titanium surface visible, precision communicated", mood: "Engineering at the service of biology — the implant as precision component", industryIds: ["dental"], compatibleHeroTypes: ["product", "authority"], tags: ["implant", "titanium", "macro", "precision"], priority: 2, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "scene_type:dental:porcelain-veneer-natural-light", kind: "scene_type", environment: "Porcelain veneers in natural light — on model or in macro, the translucency of porcelain visible", lightingCharacter: "Natural light at 5500K, translucency of porcelain catching backlight, colour accurate", mood: "Natural beauty engineered — porcelain that looks like enamel, indistinguishable", industryIds: ["dental"], compatibleHeroTypes: ["product", "transformation"], tags: ["porcelain", "veneer", "natural-light", "translucency"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "scene_type:dental:shade-guide-comparison", kind: "scene_type", environment: "Shade guide comparison — tabs held against teeth, before and after visible, measurable improvement", lightingCharacter: "Clinical light, accurate colour rendering, shade tabs clearly distinguishable", mood: "Measurable — the improvement quantified not just felt, the science of whiteness", industryIds: ["dental"], compatibleHeroTypes: ["product", "transformation", "authority"], tags: ["shade-guide", "whitening", "measurement", "comparison"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "scene_type:dental:electric-toothbrush-on-counter", kind: "scene_type", environment: "Premium electric toothbrush on bathroom counter — product lifestyle shot, care routine visible", lightingCharacter: "Warm bathroom ambient, product well lit, clean counter, habit context clear", mood: "The equipment of self-care — the investment in the right tools for daily maintenance", industryIds: ["dental"], compatibleHeroTypes: ["product", "lifestyle"], tags: ["toothbrush", "product", "counter", "routine"], priority: 5, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
];
