import type { BehaviourKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const RETAIL_BEHAVIOURS: BehaviourKnowledgeNode[] = [
  // ── Browsing behaviours (20) ───────────────────────────────────────────────────
  { id: "behaviour:retail:touching-garment-on-rail", kind: "behaviour", description: "Customer walking along a clothing rail dragging fingertips across the fabric of multiple hanging items — the tactile browse that precedes any decision", emotionalSignal: "sensory exploration", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["retail"], tags: ["browsing", "rail", "fingertips", "tactile"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:retail:holding-item-against-body-in-mirror", kind: "behaviour", description: "Customer holding a garment against themselves in front of a mirror — arm extended to hold it at the shoulders, tilting their head to assess, not yet convinced", emotionalSignal: "self-assessment", compatibleHeroes: ["person", "lifestyle", "product"], industryIds: ["retail"], tags: ["holding", "mirror", "garment", "assessment"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:retail:checking-price-tag", kind: "behaviour", description: "Customer turning over a price tag — the decisive motion of reading the number, the half-second of consideration before the item is kept in hand or returned to the rail", emotionalSignal: "price reckoning", compatibleHeroes: ["person", "product", "moment"], industryIds: ["retail"], tags: ["price-tag", "checking", "decision", "kept-or-returned"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:retail:comparing-two-items-side-by-side", kind: "behaviour", description: "Customer with two items held in each hand — looking left, looking right, trying to see the difference that will make the decision, sometimes holding both against themselves alternately", emotionalSignal: "active deliberation", compatibleHeroes: ["person", "product", "moment"], industryIds: ["retail"], tags: ["comparing", "two-items", "left-right", "deciding"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:retail:checking-phone-reviews-in-store", kind: "behaviour", description: "Customer standing in an aisle with their phone reading reviews of the item they are holding — the digital research happening inside the physical store, the two experiences happening simultaneously", emotionalSignal: "information-seeking before commitment", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["phone", "reviews", "in-store", "digital-physical"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:retail:friends-shopping-together-opinion", kind: "behaviour", description: "Friends shopping together — one inside the changing room, the other outside waiting, the curtain opening for the verdict, the friend's expression giving the answer before they speak", emotionalSignal: "trusted social validation", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["friends", "changing-room", "verdict", "validation"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:retail:folding-item-deciding-against", kind: "behaviour", description: "Customer carefully folding an item they have decided not to buy and placing it back on the shelf — the respectful return that contrasts with the hasty drop of indifference", emotionalSignal: "considered decision not to buy", compatibleHeroes: ["lifestyle", "person"], industryIds: ["retail"], tags: ["folding", "returning", "decision", "considered"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:retail:touching-fabric-quality-test", kind: "behaviour", description: "Customer rubbing fabric between thumb and forefinger — testing weight, weave and drape, the quality test that no image can replicate and no description can substitute for", emotionalSignal: "quality assessment through touch", compatibleHeroes: ["person", "product"], industryIds: ["retail"], tags: ["fabric", "quality-test", "rubbing", "weight"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:retail:rush-to-sale-rail", kind: "behaviour", description: "Customers moving quickly toward a sale rail on the opening day — the controlled urgency of people who know the best sizes go first, hands already reaching before they have fully arrived", emotionalSignal: "competitive urgency", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["sale", "rush", "urgency", "competitive"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:retail:window-shopping-stopping-pointing", kind: "behaviour", description: "People pausing at a shop window — one pointing at a specific item to the other, both faces turned toward the glass, the unrequested display working as intended", emotionalSignal: "desire sparked by display", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["retail"], tags: ["window-shopping", "pointing", "display", "stopping"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Changing room behaviours (15) ─────────────────────────────────────────────
  { id: "behaviour:retail:changing-room-transformation-reveal", kind: "behaviour", description: "Customer opening the changing room curtain or door to show a friend or partner the outfit — the reveal that is either immediately right or requires a conversation", emotionalSignal: "seeking validation", compatibleHeroes: ["person", "moment", "lifestyle"], industryIds: ["retail"], tags: ["changing-room", "reveal", "partner", "validation"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "behaviour:retail:selfie-in-changing-room-mirror", kind: "behaviour", description: "Customer photographing themselves in the changing room mirror — the documentation of how it looks before they decide, sometimes sent to someone, sometimes kept for comparison", emotionalSignal: "documentation before decision", compatibleHeroes: ["lifestyle", "person", "product"], industryIds: ["retail"], tags: ["selfie", "changing-room", "mirror", "documentation"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:retail:trying-shoes-first-walk-on-floor", kind: "behaviour", description: "Customer taking the first few steps in a new pair of shoes around the shoe department — the gait-test, the heel-on-hard-floor sound, the assessment of comfort versus aesthetics", emotionalSignal: "physical quality assessment", compatibleHeroes: ["person", "product", "lifestyle"], industryIds: ["retail"], tags: ["shoes", "trying", "walking", "gait-test"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:retail:multiple-sizes-brought-in", kind: "behaviour", description: "Customer with three sizes of the same item in the changing room — working through them systematically, the best fit emerging from the comparison", emotionalSignal: "thorough evaluation", compatibleHeroes: ["person", "product"], industryIds: ["retail"], tags: ["multiple-sizes", "systematic", "fit", "evaluation"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:retail:jeans-fit-finally-found", kind: "behaviour", description: "The moment a customer finds jeans that fit perfectly — the specific combination of waist, length and cut that works, the expression of someone who has been looking for longer than is reasonable", emotionalSignal: "relief and found-it joy", compatibleHeroes: ["person", "moment", "product"], industryIds: ["retail"], tags: ["jeans", "perfect-fit", "relief", "found-it"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },

  // ── Purchase & payment behaviours (20) ────────────────────────────────────────
  { id: "behaviour:retail:carrying-multiple-bags-with-purpose", kind: "behaviour", description: "Person walking through a shopping centre with multiple branded bags — the visible evidence of a successful shopping trip, the bags communicating something about the person carrying them", emotionalSignal: "successful accumulation", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["retail"], tags: ["bags", "carrying", "branded", "successful"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:retail:loyalty-card-scanning-at-checkout", kind: "behaviour", description: "Customer presenting their loyalty card or app at checkout — the habitual gesture of the loyal customer who has made this store theirs, the scan that accumulates the record of a relationship", emotionalSignal: "habitual loyalty", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["retail"], tags: ["loyalty-card", "scanning", "checkout", "habitual"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:retail:gift-wrapping-request", kind: "behaviour", description: "Customer asking for gift wrapping at the counter — the small request that tells the associate this is a gift, the item moving from purchase to present through the wrapping", emotionalSignal: "intentional giving", compatibleHeroes: ["lifestyle", "person", "product"], industryIds: ["retail"], tags: ["gift-wrapping", "request", "counter", "present"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:retail:paying-and-receiving-wrapped-purchase", kind: "behaviour", description: "Customer at the checkout completing their purchase — card or phone payment, the bag being handed across, the receipt offered, the transaction completing the decision-journey", emotionalSignal: "satisfaction of completion", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["payment", "checkout", "bag", "completion"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:retail:returning-item-with-receipt", kind: "behaviour", description: "Customer returning an unwanted item — the slightly awkward explanation of the return reason, the receipt produced, the refund processed, the store demonstrating its service policy", emotionalSignal: "resolved dissatisfaction", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["retail"], tags: ["return", "receipt", "refund", "service"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:retail:associate-upselling-accessory", kind: "behaviour", description: "Store associate suggesting a belt or scarf or bag to complete an outfit the customer is about to purchase — the recommendation that feels like service rather than selling when the fit is right", emotionalSignal: "helpful expertise", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["retail"], tags: ["upselling", "associate", "accessory", "completing"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:retail:personal-shopper-full-outfit-build", kind: "behaviour", description: "A personal shopper moving through a department store pulling pieces — assembling an outfit for a specific occasion for a client who is seated and waiting for the options to arrive", emotionalSignal: "expert service and trust", compatibleHeroes: ["person", "lifestyle", "environment"], industryIds: ["retail"], tags: ["personal-shopper", "pulling-pieces", "occasion", "expert"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:retail:influencer-filming-try-on", kind: "behaviour", description: "Content creator in a store filming a try-on haul — multiple items selected, camera positioned in changing room, each outfit shown and assessed for the audience watching later", emotionalSignal: "aspirational content creation", compatibleHeroes: ["lifestyle", "person", "product"], industryIds: ["retail"], tags: ["influencer", "filming", "try-on", "content"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:retail:online-order-arrival-unboxing", kind: "behaviour", description: "Person opening a retail delivery at home — the box opened, tissue paper folded back, the item lifted out and held up to see it properly before trying it on", emotionalSignal: "anticipation and judgement", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["delivery", "unboxing", "tissue-paper", "held-up"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:retail:click-and-collect-pick-up", kind: "behaviour", description: "Customer collecting a click-and-collect order at the desk — giving the order number, the package appearing from behind the counter, the quick check before leaving", emotionalSignal: "efficient satisfaction", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["retail"], tags: ["click-and-collect", "collection", "order-number", "quick-check"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Discovery & delight behaviours (20) ───────────────────────────────────────
  { id: "behaviour:retail:sale-tag-spotted-stop", kind: "behaviour", description: "A customer walking past a rail and stopping short when they spot a sale tag on something they love — the immediate change of direction, the hand reaching", emotionalSignal: "opportunistic delight", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["sale-tag", "stopping", "spotted", "reaching"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:retail:new-collection-first-in-store", kind: "behaviour", description: "Customer who came for something else discovering the new season collection has arrived — the browsing becoming much more thorough than intended, the basket filling unexpectedly", emotionalSignal: "discovery and extended engagement", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["retail"], tags: ["new-collection", "discovery", "unexpected", "extending"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:retail:mother-daughter-shopping-matching", kind: "behaviour", description: "A mother and teenage daughter shopping together — the generational perspective visible in different choices from the same rail, occasional agreements surprising them both", emotionalSignal: "generational connection through style", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["mother-daughter", "shopping", "different-choices", "occasional-agreement"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:retail:sustainable-brand-reading-label", kind: "behaviour", description: "Customer picking up an item and reading the sustainability label on the inside — the supply chain information, the certifications, the values-aligned purchase being verified before commitment", emotionalSignal: "values alignment verified", compatibleHeroes: ["lifestyle", "person", "product"], industryIds: ["retail"], tags: ["sustainable", "label", "supply-chain", "values"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:retail:first-luxury-purchase-nerves", kind: "behaviour", description: "Customer making their first luxury purchase — the slight hesitation at the till, the internal dialogue happening behind the composed face, the decision to proceed", emotionalSignal: "nervous aspiration becoming action", compatibleHeroes: ["person", "moment", "lifestyle"], industryIds: ["retail"], tags: ["luxury", "first-purchase", "hesitation", "proceeding"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:retail:gift-buying-for-specific-person", kind: "behaviour", description: "Customer shopping for a gift for a specific person — describing the recipient to the store associate, walking the store with that person in mind, every item assessed through the lens of their taste", emotionalSignal: "empathetic gifting", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["gift-buying", "specific-person", "describing", "empathetic"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:retail:loyalty-reward-revealed-at-checkout", kind: "behaviour", description: "Customer being told at checkout that their loyalty points have unlocked a reward — the small unexpected gain that reinforces the decision to keep coming back", emotionalSignal: "loyalty validated by reward", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["loyalty", "reward", "checkout", "surprise"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:retail:brand-store-browsing-first-visit", kind: "behaviour", description: "Customer visiting a brand's flagship store for the first time — the looking-around that is simultaneously orientation and shopping, the space being experienced as much as the product", emotionalSignal: "brand world discovery", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["retail"], tags: ["flagship", "first-visit", "browsing", "brand-world"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:retail:seasonal-wardrobe-refresh-bulk", kind: "behaviour", description: "Customer seasonally refreshing their wardrobe — the deliberate replacements, the items pulled from the rail with intention rather than impulse, the seasonal shopping with a mental list", emotionalSignal: "deliberate seasonal renewal", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["retail"], tags: ["seasonal", "wardrobe-refresh", "deliberate", "mental-list"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:retail:influencer-discount-code-at-checkout", kind: "behaviour", description: "Customer entering an influencer discount code at online checkout — the connection between digital content consumption and purchasing behaviour visible in the typed code", emotionalSignal: "content-to-commerce completion", compatibleHeroes: ["lifestyle", "person", "product"], industryIds: ["retail"], tags: ["influencer", "discount-code", "online", "checkout"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:retail:school-uniform-first-fitting", kind: "behaviour", description: "Parent and child at a school uniform fitting — the child trying on blazer after blazer while the parent watches for fit and judges growing room, the list on a phone being ticked off", emotionalSignal: "practical parental preparation", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["school-uniform", "fitting", "parent-child", "blazer"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:retail:vintage-store-find-excitement", kind: "behaviour", description: "Customer finding something unexpected and perfect in a vintage store — holding it up, looking at the label, the price, the condition, the particular quality of a find that could not have been searched for", emotionalSignal: "serendipitous discovery", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["vintage", "find", "unexpected", "serendipitous"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:retail:associate-finding-size-in-back", kind: "behaviour", description: "Store associate disappearing into the back to check for a size — the customer waiting, the hope and slight doubt, the associate returning with the right size or the honest news that it is not there", emotionalSignal: "suspended hope", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["associate", "back-of-store", "size-check", "hope"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:retail:browsing-online-late-at-night", kind: "behaviour", description: "Person browsing a retail website late at night — the specific low-inhibition browsing of the quiet hours, scrolling and adding to a basket that may or may not complete tomorrow", emotionalSignal: "low-inhibition aspirational browsing", compatibleHeroes: ["lifestyle", "person"], industryIds: ["retail"], tags: ["online", "late-night", "browsing", "basket"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:retail:couple-shopping-for-occasion-outfit", kind: "behaviour", description: "A couple shopping for an occasion outfit together — the specific event in mind, the dress or suit found, the partner's approval carrying the weight of the final decision", emotionalSignal: "shared occasion preparation", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["retail"], tags: ["couple", "occasion-outfit", "event", "approval"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
];
