import type { CommercialSituationKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const RETAIL_COMMERCIAL_SITUATIONS: CommercialSituationKnowledgeNode[] = [
  // ── In-store conversion (12) ──────────────────────────────────────────────────
  { id: "commercial_situation:retail:sale-rail-impulse-purchase", kind: "commercial_situation", situation: "Customer who came for one thing finding something else on sale and leaving with both — the sale incentive expanding the transaction beyond its original intent", conversionMoment: "Additional item purchased on sale — the sale triggering an unplanned purchase that adds to total basket value", visualRepresentation: "Customer heading for specific destination, sale rail catches eye, additional item added, larger transaction at checkout", industryIds: ["retail"], tags: ["sale", "impulse", "additional", "basket-expansion"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "commercial_situation:retail:personal-shopping-appointment", kind: "commercial_situation", situation: "Customer booking a personal shopping appointment and being shown a curated selection — the service conversion that reliably generates higher transaction values than unaided browsing", conversionMoment: "Multiple pieces purchased from curated selection — personal shopping appointment converting to premium transaction", visualRepresentation: "Customer arriving for appointment, pieces pre-selected by stylist, trying each, taking three instead of the intended one", industryIds: ["retail"], tags: ["personal-shopping", "appointment", "curated", "premium"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "commercial_situation:retail:accessory-upsell-with-outfit", kind: "commercial_situation", situation: "Associate suggesting accessories to complete an outfit the customer is already buying — the coordinating shoes, the belt, the bag — each piece serving the look and extending the transaction", conversionMoment: "One or more accessories added to outfit purchase — the completion principle extending the basket", visualRepresentation: "Outfit at till, associate suggesting belt and shoes, customer trying them, both added, transaction larger than arrived for", industryIds: ["retail"], tags: ["accessories", "upsell", "completing", "basket"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "commercial_situation:retail:new-season-launch-store-visit", kind: "commercial_situation", situation: "Loyal customer visiting for the new season launch — coming in specifically because the new collection has arrived, the seasonal calendar driving a reliable return visit", conversionMoment: "New season pieces purchased — the calendar converting loyalty into consistent seasonal revenue", visualRepresentation: "Customer entering on launch day, new displays visible, browsing new collection, purchasing new-season key pieces", industryIds: ["retail"], tags: ["new-season", "launch", "loyal", "calendar"], priority: 1, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "commercial_situation:retail:loyalty-programme-sign-up", kind: "commercial_situation", situation: "First-time customer invited to sign up for a loyalty programme at checkout — the data capture that transforms a transaction into the beginning of a trackable relationship", conversionMoment: "Loyalty account created at checkout — the single transaction becoming the foundation of a loyalty relationship", visualRepresentation: "Checkout completion, associate mentioning loyalty programme, customer signing up with email, loyalty card or app account created", industryIds: ["retail"], tags: ["loyalty-programme", "sign-up", "checkout", "data-capture"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:retail:gift-purchase-with-premium-wrap", kind: "commercial_situation", situation: "Customer purchasing a gift and upgrading to premium gift wrapping — the occasion licensing the additional spend on presentation that enhances the emotional impact of the gift", conversionMoment: "Gift and premium wrapping purchased — the occasion creating both the gift purchase and the presentation upgrade", visualRepresentation: "Gift selected, wrapping options shown, premium option chosen, beautifully wrapped item handed over", industryIds: ["retail"], tags: ["gift", "premium-wrap", "occasion", "presentation"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Online & omnichannel conversion (12) ──────────────────────────────────────
  { id: "commercial_situation:retail:online-browse-to-store-visit", kind: "commercial_situation", situation: "Customer who browsed online coming into the store to see the piece physically — the online research creating the specific intent, the physical experience closing the sale", conversionMoment: "In-store purchase after online research — the omnichannel journey completing in the physical space", visualRepresentation: "Customer arriving with phone notes, asking for specific item, trying it, purchasing without the browsing hesitation of an unaided visitor", industryIds: ["retail"], tags: ["online-to-store", "research", "physical-close", "omnichannel"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "commercial_situation:retail:abandoned-cart-email-return", kind: "commercial_situation", situation: "Customer receiving an abandoned cart reminder email and returning to complete the purchase — often with a small incentive that tips the decision that was already nearly made", conversionMoment: "Abandoned cart completed after email reminder — the re-engagement converting a near-decision into a purchase", visualRepresentation: "Email received showing saved items, click through to cart, item still there, small discount applied, purchase completed", industryIds: ["retail"], tags: ["abandoned-cart", "email", "reminder", "completed"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:retail:influencer-code-purchase", kind: "commercial_situation", situation: "Customer purchasing a product using an influencer's discount code — the content-driven purchase where trust in the influencer's taste substitutes for the physical try-on", conversionMoment: "Purchase completed with influencer code — the content relationship converting to sale, the code tracking the attribution", visualRepresentation: "Influencer content watched or read, link followed, code entered at checkout, purchase completed", industryIds: ["retail"], tags: ["influencer", "discount-code", "purchase", "attribution"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:retail:click-and-collect-order", kind: "commercial_situation", situation: "Customer ordering online for click-and-collect — the online purchase that ends in a physical store visit, often leading to an additional in-store purchase while collecting", conversionMoment: "Click-and-collect order placed, in-store additional purchase made on collection — the service creating a store visit opportunity", visualRepresentation: "Online purchase, collection point selected, arriving at store, collecting order, spotting something else while there", industryIds: ["retail"], tags: ["click-and-collect", "online", "store-visit", "additional"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:retail:free-returns-enabling-online-purchase", kind: "commercial_situation", situation: "Customer completing an online purchase they would otherwise have hesitated on because of the free returns policy — the guarantee removing the risk and enabling the transaction", conversionMoment: "Online purchase completed using free returns policy — the policy removing the barrier and enabling the transaction", visualRepresentation: "Product page with free returns visible, customer adding to cart despite fit uncertainty, purchase completed, product arrives and kept", industryIds: ["retail"], tags: ["free-returns", "policy", "barrier-removal", "online"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:retail:social-media-post-to-purchase", kind: "commercial_situation", situation: "Customer discovering a product through a tagged social media post and purchasing directly — the social commerce path from discovery to transaction with minimal friction", conversionMoment: "Product purchased from social media discovery — the social path complete from post to payment", visualRepresentation: "Social post with tagged product, tapping the tag, product page loading, purchase completing", industryIds: ["retail"], tags: ["social-media", "tagged", "discovery", "purchase"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Loyalty & retention (12) ──────────────────────────────────────────────────
  { id: "commercial_situation:retail:loyalty-points-redeemed", kind: "commercial_situation", situation: "Customer redeeming loyalty points at checkout — the reward for consistent patronage applied as a purchase contribution, the relationship paid back in kind", conversionMoment: "Loyalty points redeemed, purchase completed — the loyalty mechanism delivering its retention benefit", visualRepresentation: "Checkout with loyalty app showing points balance, redemption applied, reduced payment made, balance reset for next accumulation", industryIds: ["retail"], tags: ["loyalty-points", "redeemed", "checkout", "retention"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:retail:five-star-review-with-photo", kind: "commercial_situation", situation: "Customer posting a five-star review with photos of the item they purchased — the organic advocacy that functions as both quality evidence and social proof for future customers", conversionMoment: "Review published with visual evidence — future customer trust built by this purchase's documentation", visualRepresentation: "Review platform with customer-taken photos of item, specific praise for quality and fit, others reading and purchasing", industryIds: ["retail"], tags: ["review", "five-star", "photos", "advocacy"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "commercial_situation:retail:recommendation-to-friend", kind: "commercial_situation", situation: "Customer recommending a specific item or store to a friend — the word-of-mouth that is triggered by a positive experience and generates a new customer from the existing one", conversionMoment: "Friend becomes new customer from recommendation — the referral converting the satisfied customer's advocacy into a sale", visualRepresentation: "Two friends, one showing purchase, other responding positively, store or link shared, friend making purchase", industryIds: ["retail"], tags: ["recommendation", "friend", "word-of-mouth", "referral"], priority: 1, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "commercial_situation:retail:seasonal-preview-for-loyalty-members", kind: "commercial_situation", situation: "Loyal customer invited to a seasonal preview before the public launch — the exclusive access that makes loyalty feel like membership, the early purchase securing the best selection", conversionMoment: "Early purchase from new collection at loyalty preview — the exclusive access driving pre-launch revenue from the most loyal segment", visualRepresentation: "Invitation sent to loyalty members, preview event held, new collection browsed before public, early purchases made", industryIds: ["retail"], tags: ["loyalty-preview", "seasonal", "exclusive", "early-access"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:retail:brand-membership-credit-card-sign-up", kind: "commercial_situation", situation: "Customer signing up for a store credit card or brand membership at checkout — the financial relationship deepening the brand relationship while enabling a larger first transaction", conversionMoment: "Brand credit card or membership signed up — the financial relationship begun, first transaction enabled at higher value", visualRepresentation: "Checkout with associate mentioning card benefit, customer considering and agreeing, application completed, first use applied to same transaction", industryIds: ["retail"], tags: ["brand-card", "membership", "sign-up", "financial"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:retail:sustainable-brand-conversion", kind: "commercial_situation", situation: "Customer switching from a conventional brand to a sustainable alternative — the values-based purchase decision that is simultaneously commercial and ideological", conversionMoment: "Sustainable brand purchase completed — the values-aligned alternative chosen, the conventional purchase displaced", visualRepresentation: "Customer reading sustainability credentials, comparing to usual choice, sustainable brand chosen, the decision both commercial and personal", industryIds: ["retail"], tags: ["sustainable", "switching", "values", "alternative"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:retail:birthday-treat-self-purchase", kind: "commercial_situation", situation: "Customer treating themselves to a purchase for their own birthday — the self-gifting occasion that licenses a spend above the usual level, the birthday providing the internal permission", conversionMoment: "Birthday self-gift purchased — the occasion enabling the spend level that the customer would otherwise resist", visualRepresentation: "Customer in store with birthday as internal justification, choosing something more expensive than usual, purchasing with confidence", industryIds: ["retail"], tags: ["birthday", "self-treat", "licensed-spend", "permission"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:retail:school-uniform-annual-purchase", kind: "commercial_situation", situation: "Annual school uniform purchase at the start of each academic year — the compulsory, reliable seasonal spend that peaks in July-August for September return", conversionMoment: "Full uniform set purchased — the reliable annual transaction at the peak seasonal window", visualRepresentation: "Parent with list at uniform shop, items tried and checked, full set purchased, receipt for school records", industryIds: ["retail"], tags: ["school-uniform", "annual", "compulsory", "seasonal-peak"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
];
