import type { EmotionalMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const RETAIL_EMOTIONAL_MOMENTS: EmotionalMomentKnowledgeNode[] = [
  // ── Finding the perfect item (15) ─────────────────────────────────────────────
  { id: "emotional_moment:retail:jeans-that-finally-fit", kind: "emotional_moment", moment: "A customer pulling on jeans that fit perfectly for the first time — the waist, the length, the cut all working simultaneously, the expression of someone who has found what they had given up hoping to find", emotionType: "relief and triumph", visualSignals: ["stepping out of changing room", "hands on waist checking", "turning to see the back", "the face of someone who cannot quite believe it"], industryIds: ["retail"], tags: ["jeans", "perfect-fit", "relief", "cannot-believe"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:retail:the-outfit-that-is-completely-right", kind: "emotional_moment", moment: "Standing in the changing room and knowing — without needing anyone's opinion — that this outfit is completely right: the colour, the fit, the way it makes you hold yourself", emotionType: "self-certain delight", visualSignals: ["no hedging in the posture", "small smile before anyone has been shown", "checking the reflection from different angles out of pleasure not doubt", "pulling out the phone to photograph it immediately"], industryIds: ["retail"], tags: ["outfit", "completely-right", "self-certain", "knowing"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:retail:sale-find-on-desired-item", kind: "emotional_moment", moment: "Spotting a sale tag on something that was previously out of budget — the moment of registering the price reduction, the hand reaching before the decision has been consciously made", emotionType: "opportunistic elation", visualSignals: ["hand reaching to the tag", "eyes scanning the price", "the quick check of stock for the right size", "the immediate grip of someone who has not let go"], industryIds: ["retail"], tags: ["sale", "tag", "budget", "reaching"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:retail:first-luxury-purchase-completed", kind: "emotional_moment", moment: "Walking out of a luxury store with the bag in hand — the weight of the branded shopping bag distinct from any other, the internal monologue quieted by having finally done it", emotionType: "aspiration fulfilled", visualSignals: ["branded bag held at the side", "slightly different walk than entering", "looking at the bag once outside", "the quiet satisfaction of a decision completed"], industryIds: ["retail"], tags: ["luxury", "purchase-complete", "branded-bag", "aspiration"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:retail:online-order-exceeds-expectation", kind: "emotional_moment", moment: "Opening an online delivery to find the item is far better than the website made it look — the product lifted from tissue paper and held up to the light, the website photo having undersold it", emotionType: "delighted relief", visualSignals: ["item lifted from tissue paper", "held up to light", "turned slowly", "the decision already validated before even trying it on"], industryIds: ["retail"], tags: ["delivery", "exceeds-expectation", "tissue-paper", "undersold"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:retail:vintage-perfect-find", kind: "emotional_moment", moment: "Finding the exact vintage piece that had been searched for — the right era, the right size, the right condition, the improbable specific item that appears when hope of finding it has faded", emotionType: "serendipitous completion", visualSignals: ["stillness on finding it among many others", "lifting it from the rack carefully", "the particular care of handling something that feels already owned", "the certainty before the price is even checked"], industryIds: ["retail"], tags: ["vintage", "exact-find", "improbable", "certainty"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:retail:changing-room-friend-verdict-yes", kind: "emotional_moment", moment: "Opening the changing room curtain and seeing the friend's face — not the careful diplomatic expression but the immediate involuntary one that says yes before the words do", emotionType: "validated by someone whose opinion is trusted", visualSignals: ["curtain opening", "the friend's face before they school it", "the involuntary response readable immediately", "the burst of mutual laughter at the obvious rightness"], industryIds: ["retail"], tags: ["changing-room", "friend", "verdict", "involuntary-yes"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },

  // ── Gifting emotional peaks (12) ──────────────────────────────────────────────
  { id: "emotional_moment:retail:recipient-loves-gift", kind: "emotional_moment", moment: "The recipient opening a gift and their face showing they genuinely love it — the gift buyer watching, the gift landing exactly as hoped, the gamble of choosing for someone else paying off completely", emotionType: "empathetic satisfaction", visualSignals: ["recipient's face", "the buyer watching the face not the gift", "the genuine reaction before composure arrives", "the hug that follows"], industryIds: ["retail"], tags: ["gift", "recipient", "lands-right", "buyer-watching"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:retail:christmas-gift-unwrapping-child", kind: "emotional_moment", moment: "A child unwrapping a specific wanted item on Christmas morning — the wrapping torn before it could be done neatly, the item held up, the immediate move to open the packaging", emotionType: "pure childhood want-fulfilled", visualSignals: ["wrapping torn", "item immediately raised", "packaging immediately attacked", "the absorbed delight of the thing itself"], industryIds: ["retail"], tags: ["christmas", "child", "wanted-item", "absorbed"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:retail:gift-buying-for-known-person", kind: "emotional_moment", moment: "Finding the gift that is exactly right for a specific person — the moment of recognition when browsing becomes purposeful, the knowledge of the person leading to the one object that could only be for them", emotionType: "empathetic certainty", visualSignals: ["browsing stopping", "the item picked up with intention", "the smile of recognition", "no need to compare it to other options"], industryIds: ["retail"], tags: ["gift", "exactly-right", "empathetic", "one-object"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:retail:receiving-a-gift-wrapped-purchase", kind: "emotional_moment", moment: "Being handed a beautifully gift-wrapped parcel from a store — the weight and presentation communicating the quality inside before it opens, the anticipation designed into the packaging", emotionType: "anticipatory pleasure", visualSignals: ["parcel handed across counter", "weight felt immediately", "ribbon noticed", "the careful decision about whether to open now or wait"], industryIds: ["retail"], tags: ["gift-wrap", "parcel", "anticipatory", "weight"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },

  // ── Body confidence & identity moments (12) ────────────────────────────────────
  { id: "emotional_moment:retail:body-confidence-in-the-right-outfit", kind: "emotional_moment", moment: "A customer who struggles with body confidence finding an outfit that makes them feel genuinely good — the posture changing, the walk from changing room different from the walk in", emotionType: "self-acceptance and confidence found", visualSignals: ["posture lifting", "different quality of walking", "the face less concerned", "the purchase decided without hesitation"], industryIds: ["retail"], tags: ["body-confidence", "posture", "right-outfit", "self-acceptance"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:retail:first-independent-fashion-choice", kind: "emotional_moment", moment: "A teenager buying something with their own money for the first time — choosing independently without parental input, the ownership of the choice as important as the item itself", emotionType: "first independent self-expression", visualSignals: ["teenager at till alone", "own payment method used", "no parent to refer to", "the particular pride of having chosen for themselves"], industryIds: ["retail"], tags: ["teenager", "first-independent", "own-money", "pride"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:retail:wearing-purchase-to-event", kind: "emotional_moment", moment: "The moment of getting ready in the new purchase for the occasion it was bought for — the item fulfilling its specific purpose, the decision validated by the rightness of the moment", emotionType: "purchase purpose fulfilled", visualSignals: ["item put on for first real wearing", "checking in mirror", "the satisfaction of the connection between purpose and purchase", "leaving for the event confident"], industryIds: ["retail"], tags: ["wearing", "event", "purpose-fulfilled", "confident"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },

  // ── Loyalty & commercial emotional peaks (11) ─────────────────────────────────
  { id: "emotional_moment:retail:loyalty-reward-surprise-at-checkout", kind: "emotional_moment", moment: "Being told at checkout that a loyalty reward has unlocked — the small unexpected gain that makes the transaction feel like it gave something back, the routine purchase becoming a pleasant surprise", emotionType: "loyalty validated by unexpected gain", visualSignals: ["associate mentioning the reward", "the slight surprise", "the smile at the small win", "the card put back in the wallet with renewed regard"], industryIds: ["retail"], tags: ["loyalty-reward", "checkout", "unexpected", "small-win"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:retail:sale-start-doors-opening", kind: "emotional_moment", moment: "A sale starting — the queue outside moving forward, the doors opening, the collective movement of people entering a store for a limited window of better prices", emotionType: "collective competitive excitement", visualSignals: ["queue moving at once", "doors opening", "people flowing in", "individual focus on specific departments that kicks in immediately"], industryIds: ["retail"], tags: ["sale-start", "queue", "doors-opening", "collective"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:retail:returning-brand-feels-like-home", kind: "emotional_moment", moment: "Walking into a familiar store and being greeted by name — the moment of recognition that makes a retail space feel like a relationship rather than a transaction", emotionType: "belonging in a retail context", visualSignals: ["entering the store", "staff member looking up and greeting by name", "the smile of being known", "the browsing that follows being more relaxed than anywhere else"], industryIds: ["retail"], tags: ["familiar", "greeted-by-name", "belonging", "known"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
];
