import type { HeroMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const RETAIL_HERO_MOMENTS: HeroMomentKnowledgeNode[] = [
  // ── Outfit discovery moments (15) ─────────────────────────────────────────────
  { id: "hero_moment:retail:outfit-discovery-perfect-piece", kind: "hero_moment", subject: "Customer pulling a garment from a crowded rail and holding it out — the colour, cut, and fabric immediately registering as exactly right", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "new_collection"], behaviourIds: [], tags: ["discovery", "rail", "perfect-piece", "instinct"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "hero_moment:retail:jeans-fitting-perfectly", kind: "hero_moment", subject: "Customer fastening the button on a pair of jeans in the changing room and turning to the mirror — the fit landing perfectly without effort", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["changing_room", "outfit_discovery"], behaviourIds: [], tags: ["jeans", "fit", "changing-room", "perfect"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "hero_moment:retail:dress-spotted-across-store", kind: "hero_moment", subject: "Customer stopping mid-stride as a dress on a mannequin across the store floor catches their eye — changing direction immediately toward it", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "new_collection"], behaviourIds: [], tags: ["dress", "spotted", "mannequin", "magnetic"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:retail:jacket-discovery-on-rail", kind: "hero_moment", subject: "Customer lifting a jacket from a rail and holding it against them in the mirror, the colour working immediately, the shape exactly right", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "new_collection"], behaviourIds: [], tags: ["jacket", "rail", "mirror", "discovery"], priority: 2, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "hero_moment:retail:shoes-trying-on-first-walk", kind: "hero_moment", subject: "Customer trying on shoes and taking their first few steps on the shop floor — the heel height, the sole grip, the shape all working together", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "personal_shopping"], behaviourIds: [], tags: ["shoes", "first-walk", "fit", "trying-on"], priority: 2, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "hero_moment:retail:colour-that-works-mirror", kind: "hero_moment", subject: "Customer holding a garment in a colour against their face in a mirror, tilting their head as they realise this shade works for them", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "personal_shopping"], behaviourIds: [], tags: ["colour", "mirror", "works", "discovery"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:retail:sustainable-fashion-discovery", kind: "hero_moment", subject: "Customer turning over a garment tag and reading the sustainable material credentials — a small nod of alignment before adding it to the basket", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["sustainable_fashion", "outfit_discovery"], behaviourIds: [], tags: ["sustainable", "tag", "conscious", "discovery"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:retail:vintage-piece-uncovered", kind: "hero_moment", subject: "Customer pulling a vintage piece from between newer items on a packed rail — something perfectly preserved, from another era, the find of the day", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "sustainable_fashion"], behaviourIds: [], tags: ["vintage", "rail", "discovery", "unique"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:retail:seasonal-wardrobe-refresh", kind: "hero_moment", subject: "Customer pulling an armful of new-season pieces in complementary colours, spreading them across the changing room bench — the full seasonal pivot happening at once", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["new_collection", "outfit_discovery"], behaviourIds: [], tags: ["seasonal", "refresh", "wardrobe", "new-season"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:window-display-stops-passerby", kind: "hero_moment", subject: "Pedestrian stopping outside a shop window, head tilting at the outfit on the mannequin, hand going to their phone to check opening times", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "new_collection"], behaviourIds: [], tags: ["window-display", "passerby", "stopped", "mannequin"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:retail:influencer-seen-item-found", kind: "hero_moment", subject: "Customer recognising an item they saved from an influencer's post on a physical rail in-store, immediately reaching for it", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "digital_commerce"], behaviourIds: [], tags: ["influencer", "recognition", "rail", "discovery"], priority: 3, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:retail:brand-new-season-rails", kind: "hero_moment", subject: "Customer arriving on the first day a new season collection hits the floor — rails still being dressed, the first proper look at what the season holds", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["new_collection", "outfit_discovery"], behaviourIds: [], tags: ["new-season", "rails", "first-day", "arrival"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:end-of-rail-hidden-gem", kind: "hero_moment", subject: "Customer reaching to the far end of a rail and finding the exact piece they had mentally given up on — the last one, in the right size", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "sale_event"], behaviourIds: [], tags: ["hidden-gem", "last-piece", "lucky-find", "rail-end"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:retail:unexpected-discount-found", kind: "hero_moment", subject: "Customer checking a price tag to find the item has already been reduced — a delighted double-take at the number before it goes straight over their arm", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["sale_event", "outfit_discovery"], behaviourIds: [], tags: ["discount", "price-tag", "unexpected", "delight"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:retail:accessories-completing-outfit", kind: "hero_moment", subject: "Customer adding a belt or scarf at the accessories wall and seeing the outfit click into place in the mirror — the finishing piece landing", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["personal_shopping", "outfit_discovery"], behaviourIds: [], tags: ["accessories", "outfit-complete", "finishing-piece", "mirror"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },

  // ── Changing room transformation moments (10) ─────────────────────────────────
  { id: "hero_moment:retail:changing-room-transformation", kind: "hero_moment", subject: "Customer stepping out of a changing room cubicle in a complete outfit — the transformation visible the moment they see themselves in the full-length mirror", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["changing_room", "personal_shopping"], behaviourIds: [], tags: ["transformation", "changing-room", "full-length-mirror", "reveal"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "hero_moment:retail:outfit-completed-changing-room", kind: "hero_moment", subject: "Customer assembling a full outfit in the changing room — garment by garment — then stepping back from the mirror when everything is on", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["changing_room", "outfit_discovery"], behaviourIds: [], tags: ["outfit-assembled", "changing-room", "mirror", "complete"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:retail:selfie-in-changing-room", kind: "hero_moment", subject: "Customer holding their phone up in the changing room mirror to capture an outfit selfie — sharing before deciding, expression already convinced", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["changing_room", "digital_commerce"], behaviourIds: [], tags: ["selfie", "changing-room", "phone", "share"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:friend-reaction-to-try-on", kind: "hero_moment", subject: "Customer stepping out of the changing room to show a friend — the friend's reaction of genuine approval before any words are said", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["changing_room", "outfit_discovery"], behaviourIds: [], tags: ["friend-reaction", "approval", "try-on", "social"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:retail:suit-fitting-in-mirror", kind: "hero_moment", subject: "Customer in a suit jacket angling their shoulders left and right in the changing room mirror — the fit landing across the back exactly right", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["changing_room", "personal_shopping"], behaviourIds: [], tags: ["suit", "fitting", "shoulders", "jacket"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:shoes-matching-outfit-mirror", kind: "hero_moment", subject: "Customer stepping back in the changing room to look at shoes completing an outfit in the full-length mirror — the final piece clicking", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["changing_room", "outfit_discovery"], behaviourIds: [], tags: ["shoes", "outfit", "mirror", "complete"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:retail:size-swap-perfect-fit", kind: "hero_moment", subject: "Customer trying the size the associate suggested after their original choice was wrong — the new size fitting perfectly, the relief visible", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["changing_room", "personal_shopping"], behaviourIds: [], tags: ["size-swap", "associate", "perfect-fit", "service"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:retail:body-confidence-changing-room", kind: "hero_moment", subject: "Customer looking at themselves in the changing room mirror with an expression of pleasant surprise — the cut flattering in a way they had not expected", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["changing_room", "outfit_discovery"], behaviourIds: [], tags: ["body-confidence", "flattering", "surprise", "mirror"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:retail:dress-twirl-approved", kind: "hero_moment", subject: "Customer giving a small twirl in the changing room, the dress lifting slightly, settling back — the movement confirming what the mirror showed", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["changing_room", "outfit_discovery"], behaviourIds: [], tags: ["dress", "twirl", "movement", "approval"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:changing-room-style-reveal", kind: "hero_moment", subject: "Stylist waiting outside the changing room as the customer steps out — both seeing the full look for the first time, a shared moment of assessment", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["personal_shopping", "changing_room"], behaviourIds: [], tags: ["stylist", "reveal", "assessment", "changing-room"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Sale find moments (10) ─────────────────────────────────────────────────────
  { id: "hero_moment:retail:black-friday-queue-and-find", kind: "hero_moment", subject: "Customer queuing from early, then navigating a Black Friday floor and reaching the specific item they came for — held up in triumph", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["sale_event", "outfit_discovery"], behaviourIds: [], tags: ["black-friday", "queue", "find", "triumph"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:retail:sale-price-tag-double-take", kind: "hero_moment", subject: "Customer turning a sale tag over and doing a double-take at the reduced price — holding the item out to a companion to confirm they are reading it right", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["sale_event", "outfit_discovery"], behaviourIds: [], tags: ["sale-tag", "price", "double-take", "disbelief"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:retail:last-item-in-sale-secured", kind: "hero_moment", subject: "Customer reaching for the last item on a sale rail in the right size — another hand approaching the same piece, the first hand getting there first", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["sale_event", "outfit_discovery"], behaviourIds: [], tags: ["last-item", "sale", "competition", "secured"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:retail:designer-sale-find", kind: "hero_moment", subject: "Customer finding a designer piece significantly reduced on a sale rail — reading the brand label twice then the price, expression shifting from disbelief to decision", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["sale_event", "outfit_discovery"], behaviourIds: [], tags: ["designer", "sale", "reduced", "discovery"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:retail:clearance-rail-hidden-gem", kind: "hero_moment", subject: "Customer methodically working through a clearance rail and pulling out a piece that has no reason to be among them at that price", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["sale_event", "outfit_discovery"], behaviourIds: [], tags: ["clearance", "rail", "hidden-gem", "value"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:retail:loyalty-sale-early-access", kind: "hero_moment", subject: "Loyalty member arriving at the store before general opening for member-only sale early access — the floor empty, all the choice theirs", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["loyalty_programme", "sale_event"], behaviourIds: [], tags: ["loyalty", "early-access", "sale", "empty-floor"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:percentage-off-revealed-at-till", kind: "hero_moment", subject: "Customer's expression changing at the till as the sale percentage is applied and the final price appears on the screen — better than expected", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["sale_event", "loyalty_programme"], behaviourIds: [], tags: ["till", "percentage-off", "surprise", "delight"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:retail:january-sale-rush-find", kind: "hero_moment", subject: "Customer navigating the January sale floor on opening morning, arms already full, heading for the changing room with the season's best finds", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["sale_event", "outfit_discovery"], behaviourIds: [], tags: ["january-sale", "rush", "arms-full", "finds"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:boxing-day-sale-win", kind: "hero_moment", subject: "Customer walking out of a Boxing Day sale with a branded bag holding the coat they have wanted since autumn, now at a fraction of the price", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["sale_event", "gifting"], behaviourIds: [], tags: ["boxing-day", "sale", "coat", "win"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:online-sale-code-landing", kind: "hero_moment", subject: "Customer applying a promotional code online and watching the basket total drop significantly — cursor hovering over the confirm payment button", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["digital_commerce", "sale_event"], behaviourIds: [], tags: ["online", "promo-code", "basket-drop", "confirm"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── New season and collection arrivals (10) ────────────────────────────────────
  { id: "hero_moment:retail:new-collection-arrival-rails", kind: "hero_moment", subject: "Customer arriving on the shop floor to find freshly merchandised new-season rails — running a hand along the new colours before stopping at one", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["new_collection", "outfit_discovery"], behaviourIds: [], tags: ["new-collection", "rails", "fresh", "arrival"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:retail:first-autumn-knitwear-in-store", kind: "hero_moment", subject: "Customer lifting the first heavyweight knit of the season from the rail, pressing it to their chest — the shift in the air feeling confirmed by the wool", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["new_collection", "outfit_discovery"], behaviourIds: [], tags: ["knitwear", "autumn", "seasonal", "first"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:retail:limited-edition-launch-day", kind: "hero_moment", subject: "Customer arriving at a store on limited-edition launch day, the display visible before they reach the entrance — pace quickening", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["new_collection", "outfit_discovery"], behaviourIds: [], tags: ["limited-edition", "launch", "display", "pace"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:retail:brand-collaboration-drop", kind: "hero_moment", subject: "Customer finding the in-store installation for a brand collaboration drop — examining each piece in the dedicated display area", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["new_collection", "outfit_discovery"], behaviourIds: [], tags: ["brand-collaboration", "drop", "installation", "display"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:spring-collection-floor-walk", kind: "hero_moment", subject: "Customer walking the spring collection floor for the first time — the new palette hitting them immediately, lighter fabrics, longer shapes, the season real now", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["new_collection", "outfit_discovery"], behaviourIds: [], tags: ["spring", "collection", "palette", "season"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:new-colour-palette-for-season", kind: "hero_moment", subject: "Customer standing at the new-season wall of colour options — scanning the palette, a hand going to the one that speaks directly to them", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["new_collection", "personal_shopping"], behaviourIds: [], tags: ["colour-palette", "seasonal", "wall", "selection"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:retail:first-winter-coat-try-on", kind: "hero_moment", subject: "Customer trying on the first winter coat of the new season in-store — collar turned up, hands in pockets, assessing warmth alongside appearance", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["new_collection", "outfit_discovery"], behaviourIds: [], tags: ["winter-coat", "first-of-season", "collar", "warmth"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:fashion-week-piece-in-store", kind: "hero_moment", subject: "Customer recognising a piece from the brand's fashion-week show now on the shop floor — connecting what they saw online to the physical garment in hand", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["new_collection", "outfit_discovery"], behaviourIds: [], tags: ["fashion-week", "recognition", "physical", "collection"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:retail:summer-holiday-collection-browse", kind: "hero_moment", subject: "Customer browsing a holiday collection display — the colours, fabrications, and silhouettes triggering the specific anticipation of an upcoming trip", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["new_collection", "outfit_discovery"], behaviourIds: [], tags: ["holiday", "collection", "summer", "browse"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:new-season-window-stops-passing", kind: "hero_moment", subject: "Pedestrian pausing at a newly dressed seasonal window display — the styling stopping them mid-walk, the outfit in the window already theirs in imagination", heroType: "environment", industryIds: ["retail"], campaignTypeIds: ["new_collection", "outfit_discovery"], behaviourIds: [], tags: ["window", "seasonal", "pedestrian", "stopped"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },

  // ── Personal shopping and service moments (10) ────────────────────────────────
  { id: "hero_moment:retail:personal-shopper-consultation", kind: "hero_moment", subject: "Customer in the personal shopping suite with a stylist beside them — rails of pre-selected pieces waiting, the consultation beginning with what the customer describes", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["personal_shopping", "outfit_discovery"], behaviourIds: [], tags: ["personal-shopper", "consultation", "suite", "pre-selected"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:retail:stylist-completes-outfit", kind: "hero_moment", subject: "Stylist adding the finishing accessory to a client's assembled outfit, both looking at the mirror at once — the complete look landing", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["personal_shopping", "outfit_discovery"], behaviourIds: [], tags: ["stylist", "finishing-touch", "accessory", "complete"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:retail:associate-correct-size-suggestion", kind: "hero_moment", subject: "Store associate suggesting a size and being exactly right — the customer putting on the item and it fitting perfectly without adjustment", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["personal_shopping", "changing_room"], behaviourIds: [], tags: ["size-suggestion", "associate", "exact-fit", "service"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:retail:gift-wrapped-purchase-presented", kind: "hero_moment", subject: "Gift-wrapped purchase handed across the counter with ribbon tied — the packaging as considered as the item inside, the customer receiving it with both hands", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["gifting", "personal_shopping"], behaviourIds: [], tags: ["gift-wrapped", "ribbon", "counter", "presentation"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:first-luxury-store-experience", kind: "hero_moment", subject: "Customer entering a luxury store for the first time — pausing at the entrance, taking in the marble floor, the associate stepping forward with a quiet welcome", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["personal_shopping", "outfit_discovery"], behaviourIds: [], tags: ["luxury", "first-time", "marble", "welcome"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:retail:personal-styling-final-reveal", kind: "hero_moment", subject: "Personal styling session final reveal — the customer dressed in the complete look, stylist standing back, both looking at the result in a large mirror together", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["personal_shopping", "outfit_discovery"], behaviourIds: [], tags: ["styling", "reveal", "complete-look", "mirror"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:retail:alterations-completed-perfect-fit", kind: "hero_moment", subject: "Customer collecting an altered garment from the in-store tailoring service and trying it on — the hem, the waist, the shoulders all now exact", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["personal_shopping", "changing_room"], behaviourIds: [], tags: ["alterations", "tailoring", "perfect-fit", "collected"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:retail:shoe-fitting-service-result", kind: "hero_moment", subject: "Customer sitting in the shoe department as an associate returns with the correct style and size — fitting them properly, both looking at the result on the floor", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["personal_shopping", "outfit_discovery"], behaviourIds: [], tags: ["shoe-fitting", "associate", "department", "service"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:bespoke-order-collected", kind: "hero_moment", subject: "Customer collecting a made-to-order item, the associate presenting it unwrapped on the counter — the customer's hands reaching for it immediately", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["personal_shopping", "outfit_discovery"], behaviourIds: [], tags: ["bespoke", "order", "collected", "made-to-order"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:style-consultation-unlocks-look", kind: "hero_moment", subject: "Style consultation revealing a combination the customer would never have chosen themselves — the associate holding two pieces together, both visibly working", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["personal_shopping", "outfit_discovery"], behaviourIds: [], tags: ["style-consultation", "new-combination", "unlock", "discovery"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Online and delivery moments (10) ──────────────────────────────────────────
  { id: "hero_moment:retail:online-order-arriving-at-door", kind: "hero_moment", subject: "Customer opening their front door to a parcel delivery — recognising the retailer's packaging immediately, picking it up with both hands", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["digital_commerce", "outfit_discovery"], behaviourIds: [], tags: ["delivery", "parcel", "door", "arrival"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "hero_moment:retail:parcel-opening-moment", kind: "hero_moment", subject: "Customer tearing open the retailer's packaging on the kitchen table, the tissue paper inside, the garment lifted out and immediately held against themselves", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["digital_commerce", "outfit_discovery"], behaviourIds: [], tags: ["parcel-opening", "tissue-paper", "unboxing", "reveal"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:retail:garment-matching-website-photo", kind: "hero_moment", subject: "Customer holding up the received garment and comparing it with the product photo on their phone — the colour and drape matching exactly", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["digital_commerce", "outfit_discovery"], behaviourIds: [], tags: ["garment", "matches-photo", "colour", "online"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:click-and-collect-received", kind: "hero_moment", subject: "Customer at the click-and-collect counter receiving their online order — the associate finding it, handling it over, the customer opening the bag immediately", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["digital_commerce", "outfit_discovery"], behaviourIds: [], tags: ["click-and-collect", "counter", "online-order", "received"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:retail:next-day-delivery-outfit-ready", kind: "hero_moment", subject: "Customer laying out a next-day-delivery outfit on the bed the morning after ordering — everything arrived perfectly for the occasion", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["digital_commerce", "outfit_discovery"], behaviourIds: [], tags: ["next-day", "delivery", "occasion-ready", "complete"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:returns-replaced-right-size", kind: "hero_moment", subject: "Customer receiving the replacement order after a successful return — this time the size is right, the item unfolded and immediately tried on", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["digital_commerce", "changing_room"], behaviourIds: [], tags: ["returns", "replacement", "right-size", "service"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:subscription-box-first-opening", kind: "hero_moment", subject: "Customer opening their first fashion subscription box — layers of tissue giving way to curated pieces, each one lifted out and assessed with curiosity", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["digital_commerce", "outfit_discovery"], behaviourIds: [], tags: ["subscription", "box", "curated", "unboxing"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:app-order-notification-received", kind: "hero_moment", subject: "Customer receiving a push notification that their order has been dispatched — swiping into the app to see the tracking map showing the van nearby", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["digital_commerce", "loyalty_programme"], behaviourIds: [], tags: ["app-notification", "dispatch", "tracking", "anticipation"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "hero_moment:retail:pre-order-item-finally-delivered", kind: "hero_moment", subject: "Customer receiving a long-anticipated pre-order item — a wait of weeks making the unboxing moment more deliberate and savoured", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["digital_commerce", "outfit_discovery"], behaviourIds: [], tags: ["pre-order", "wait", "unboxing", "anticipation"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "hero_moment:retail:online-exclusive-arrives", kind: "hero_moment", subject: "Customer receiving an online-exclusive colourway not available in stores — turning it in the light to see the detail that drew them to it online", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["digital_commerce", "outfit_discovery"], behaviourIds: [], tags: ["online-exclusive", "colourway", "detail", "received"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Brand loyalty and repeat purchase moments (10) ────────────────────────────
  { id: "hero_moment:retail:loyal-customer-recognised-by-name", kind: "hero_moment", subject: "Regular customer entering the store and being greeted by name by an associate — the small acknowledgement carrying a weight of relationship", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["loyalty_programme", "personal_shopping"], behaviourIds: [], tags: ["loyalty", "recognised", "by-name", "relationship"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:retail:loyalty-points-redeemed", kind: "hero_moment", subject: "Customer at the till redeeming accumulated loyalty points — watching the amount they have built up applied to the total, expression of quiet satisfaction", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["loyalty_programme", "sale_event"], behaviourIds: [], tags: ["loyalty-points", "redemption", "till", "satisfaction"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:brand-loyalty-return-purchase", kind: "hero_moment", subject: "Customer returning to a brand with the specific intent of buying the same style in a new season colourway — the trust of a repeat purchase", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["loyalty_programme", "new_collection"], behaviourIds: [], tags: ["loyalty", "repeat-purchase", "trust", "brand"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:VIP-new-card-member-welcome", kind: "hero_moment", subject: "New loyalty card member receiving their card across the counter — the associate explaining the benefits, the customer already planning the next visit", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["loyalty_programme", "personal_shopping"], behaviourIds: [], tags: ["loyalty-card", "new-member", "welcome", "benefits"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:retail:store-credit-redemption", kind: "hero_moment", subject: "Customer using store credit from a previous return to fund a new purchase — the credit clearing the transaction, the exchange feeling seamless", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["loyalty_programme", "sale_event"], behaviourIds: [], tags: ["store-credit", "redemption", "seamless", "exchange"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:returns-handled-seamlessly", kind: "hero_moment", subject: "Customer completing a hassle-free return — in and out in minutes, credit applied, confidence in the brand reinforced rather than damaged", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["loyalty_programme", "digital_commerce"], behaviourIds: [], tags: ["returns", "seamless", "service", "confidence"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:wardrobe-staple-replaced", kind: "hero_moment", subject: "Customer returning to replace a worn-out wardrobe staple from the same brand — the piece so trusted they want no substitutes", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["loyalty_programme", "outfit_discovery"], behaviourIds: [], tags: ["wardrobe-staple", "replacement", "loyalty", "trust"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:regular-customer-VIP-treatment", kind: "hero_moment", subject: "Long-term regular customer receiving preferential service — early access to new stock, a reserved changing room, the relationship made visible", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["loyalty_programme", "personal_shopping"], behaviourIds: [], tags: ["regular", "VIP", "preferential", "relationship"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:brand-anniversary-sale-return", kind: "hero_moment", subject: "Customer returning to the same brand sale they visit every year — the ritual of it making the selection feel earned and familiar", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["loyalty_programme", "sale_event"], behaviourIds: [], tags: ["brand-anniversary", "annual-sale", "ritual", "loyalty"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "hero_moment:retail:influencer-discount-code-used", kind: "hero_moment", subject: "Customer entering an influencer's discount code at checkout, the percentage off applying instantly — the three-party relationship made concrete", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["digital_commerce", "loyalty_programme"], behaviourIds: [], tags: ["influencer-code", "discount", "checkout", "applied"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Gifting and special occasion moments (10) ─────────────────────────────────
  { id: "hero_moment:retail:gift-purchase-for-someone", kind: "hero_moment", subject: "Customer selecting a gift for a specific person — holding pieces and imagining the recipient wearing them, the gift chosen for someone else entirely", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["gifting", "personal_shopping"], behaviourIds: [], tags: ["gift", "recipient", "imagining", "selection"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "hero_moment:retail:prom-dress-final-choice", kind: "hero_moment", subject: "Young person choosing their prom dress — the final two dresses tried, the one chosen stepping out of the changing room to a parent's reaction", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["gifting", "outfit_discovery"], behaviourIds: [], tags: ["prom-dress", "choice", "parent", "reaction"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:retail:wedding-guest-outfit-completed", kind: "hero_moment", subject: "Customer assembling a complete wedding guest outfit in-store — dress, shoes, and bag brought together, the outfit photographed against the wall for the record", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["gifting", "personal_shopping"], behaviourIds: [], tags: ["wedding-guest", "occasion", "assembled", "complete"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:retail:interview-outfit-purchased", kind: "hero_moment", subject: "Customer purchasing the outfit chosen specifically for an important interview — the buy made with clear intention, the bag carried out with purpose", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "personal_shopping"], behaviourIds: [], tags: ["interview", "purpose", "intention", "occasion"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:retail:birthday-outfit-revealed", kind: "hero_moment", subject: "Customer revealing a purchased birthday outfit to the recipient at home — tissue paper parted, the item lifted out, the reaction read immediately", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["gifting", "outfit_discovery"], behaviourIds: [], tags: ["birthday", "reveal", "gift", "reaction"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:retail:christmas-gift-wrapped-instore", kind: "hero_moment", subject: "Customer at the gift-wrapping counter watching their chosen item folded in tissue and boxed — the associate tying the ribbon with expertise", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["gifting", "personal_shopping"], behaviourIds: [], tags: ["christmas", "gift-wrapping", "ribbon", "tissue"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:retail:graduation-outfit-assembled", kind: "hero_moment", subject: "Customer putting together a graduation day outfit in-store — the complete look planned piece by piece, both proud and practical", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["gifting", "outfit_discovery"], behaviourIds: [], tags: ["graduation", "occasion-outfit", "assembled", "proud"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:retail:mothers-day-gift-selected", kind: "hero_moment", subject: "Adult child selecting a Mother's Day gift with care in a boutique — describing their mother to the associate, the gift chosen collaboratively", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["gifting", "personal_shopping"], behaviourIds: [], tags: ["mothers-day", "gift", "collaborative", "thoughtful"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:anniversary-gift-wrapped-purchase", kind: "hero_moment", subject: "Customer purchasing a carefully selected anniversary gift — the item gift-wrapped, a card added to the bag, the purchase made with care", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["gifting", "personal_shopping"], behaviourIds: [], tags: ["anniversary", "gift", "card", "wrapped"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:first-luxury-handbag-purchase", kind: "hero_moment", subject: "Customer completing the purchase of their first luxury handbag — the bag presented in its dustbag inside the branded box, a rite of passage", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "personal_shopping"], behaviourIds: [], tags: ["luxury-handbag", "first-purchase", "dustbag", "milestone"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },

  // ── Children's clothing moments (8) ───────────────────────────────────────────
  { id: "hero_moment:retail:childrens-school-uniform-fitting", kind: "hero_moment", subject: "Child standing still while a parent holds up a new school uniform against them to check the length — the jacket shoulders, the hem of the trousers", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["children_fashion", "outfit_discovery"], behaviourIds: [], tags: ["school-uniform", "fitting", "child", "parent"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:retail:childs-first-pair-shoes", kind: "hero_moment", subject: "Young child having their foot measured in a shoe shop for the first time — sitting still on the chair while the associate slides the measuring gauge along", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["children_fashion", "personal_shopping"], behaviourIds: [], tags: ["first-shoes", "measuring", "child", "fitting"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:retail:child-choosing-own-outfit", kind: "hero_moment", subject: "Child reaching for a garment they want from a children's display — pulling it from the rail and holding it up to their parent with excitement and certainty", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["children_fashion", "outfit_discovery"], behaviourIds: [], tags: ["child", "choosing", "own-selection", "excited"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:retail:back-to-school-uniform-complete", kind: "hero_moment", subject: "Parent ticking off a school uniform checklist at the till — every item accounted for, bags full, child standing beside them ready for September", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["children_fashion", "outfit_discovery"], behaviourIds: [], tags: ["back-to-school", "checklist", "uniform-complete", "September"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "hero_moment:retail:children-school-shoes-tried", kind: "hero_moment", subject: "Child walking up and down the shoe department aisle in new school shoes — stiff and shiny, the child assessing the grip on the floor", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["children_fashion", "personal_shopping"], behaviourIds: [], tags: ["school-shoes", "child", "walking", "trying-on"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:retail:baby-first-outfit-chosen", kind: "hero_moment", subject: "Expectant parent holding a tiny first outfit up in the shop — the miniature proportions immediately emotional, the item added to the basket without hesitation", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["children_fashion", "gifting"], behaviourIds: [], tags: ["baby", "first-outfit", "expectant-parent", "tiny"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:retail:child-party-dress-delight", kind: "hero_moment", subject: "Child trying on a party dress and giving an unsolicited spin — the skirt fanning out, the child's expression making the decision for the parent", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["children_fashion", "outfit_discovery"], behaviourIds: [], tags: ["party-dress", "child", "spin", "delight"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:retail:teen-first-independent-purchase", kind: "hero_moment", subject: "Teenager completing their first independent clothing purchase — their own money, their own choice, their own bag to carry out of the store", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["children_fashion", "outfit_discovery"], behaviourIds: [], tags: ["teenager", "first-independent", "own-money", "milestone"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Sustainable and specialist retail moments (7) ─────────────────────────────
  { id: "hero_moment:retail:sustainable-brand-store-first-visit", kind: "hero_moment", subject: "Customer entering a sustainable fashion brand store for the first time — the material stories on the walls read with genuine interest before anything is touched", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["sustainable_fashion", "outfit_discovery"], behaviourIds: [], tags: ["sustainable", "brand-store", "first-visit", "values"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:retail:designer-sunglasses-found", kind: "hero_moment", subject: "Customer finding the right pair of sunglasses — trying several, the correct pair landing the moment they are on, the decision made before they look in the mirror", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "personal_shopping"], behaviourIds: [], tags: ["sunglasses", "fitting", "instant-decision", "designer"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:retail:sportswear-first-performance-piece", kind: "hero_moment", subject: "Customer trying on technical performance sportswear for the first time — feeling the fabric against skin, the compression, the way movement is supported", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "new_collection"], behaviourIds: [], tags: ["sportswear", "performance", "technical", "first-wear"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:retail:occasion-wear-final-decision", kind: "hero_moment", subject: "Customer making the final decision between two occasion-wear pieces — standing with one over each arm in the changing room, then placing one down without looking back", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "personal_shopping"], behaviourIds: [], tags: ["occasion-wear", "decision", "final-choice", "committed"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:vintage-market-unique-find", kind: "hero_moment", subject: "Shopper at a vintage market pulling a one-of-a-kind piece from a stall rail — reading the label, checking the seams, paying cash with the satisfaction of the unrepeatable", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["sustainable_fashion", "outfit_discovery"], behaviourIds: [], tags: ["vintage", "market", "unique", "one-of-a-kind"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:retail:recycled-materials-garment-discovery", kind: "hero_moment", subject: "Customer reading that a jacket they already liked is made from recycled ocean plastic — the product now holding additional value before it is even tried on", heroType: "moment", industryIds: ["retail"], campaignTypeIds: ["sustainable_fashion", "outfit_discovery"], behaviourIds: [], tags: ["recycled", "ocean-plastic", "sustainable", "values-alignment"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "hero_moment:retail:capsule-wardrobe-completion", kind: "hero_moment", subject: "Customer completing a capsule wardrobe purchase — the final coordinating piece found and bought, the whole system of outfits now in place in one bag", heroType: "lifestyle", industryIds: ["retail"], campaignTypeIds: ["outfit_discovery", "sustainable_fashion"], behaviourIds: [], tags: ["capsule-wardrobe", "completion", "system", "coordinated"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
];
