import type { RelationshipKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const RETAIL_RELATIONSHIPS: RelationshipKnowledgeNode[] = [
  // ── Service relationships (15) ────────────────────────────────────────────────
  { id: "relationship:retail:personal-shopper-and-client", kind: "relationship", description: "A personal shopper and their regular client — the relationship built on knowing the client's size, taste and lifestyle so well that the shopper can select without showing, the trust complete", sceneRoles: ["personal shopper", "client"], industryIds: ["retail"], tags: ["personal-shopper", "trust", "knowing", "selecting"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "relationship:retail:store-associate-and-loyal-customer", kind: "relationship", description: "A store associate and a loyal regular customer — the staff member who recognises them, knows their preferences, holds items they might like, the relationship that makes a store feel like theirs", sceneRoles: ["store associate", "loyal customer"], industryIds: ["retail"], tags: ["associate", "loyal", "recognises", "preference"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:retail:stylist-and-client-occasion", kind: "relationship", description: "A stylist preparing a client for a specific occasion — the wedding guest outfit, the job interview look, the event dress — the brief clear and the collaboration purposeful", sceneRoles: ["stylist", "client"], industryIds: ["retail"], tags: ["stylist", "occasion", "brief", "purposeful"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:retail:brand-ambassador-and-audience", kind: "relationship", description: "A brand ambassador and their online audience — the relationship that turns product experience into content, the audience trusting the ambassador's taste as a reliable proxy for their own", sceneRoles: ["brand ambassador", "online audience"], industryIds: ["retail"], tags: ["brand-ambassador", "audience", "trust", "taste-proxy"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:retail:influencer-and-brand-partnership", kind: "relationship", description: "An influencer and a retail brand in a paid partnership — the content creator whose aesthetic and the brand's product aligning in a way the audience receives as authentic", sceneRoles: ["influencer", "brand partner"], industryIds: ["retail"], tags: ["influencer", "brand", "partnership", "authentic"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:retail:customer-service-agent-resolved", kind: "relationship", description: "A customer service agent and a customer whose problem has been resolved — the journey from frustration to satisfaction, the agent's skill converting a complaint into a retained customer", sceneRoles: ["customer service agent", "resolved customer"], industryIds: ["retail"], tags: ["customer-service", "resolved", "retained", "frustration-to-satisfaction"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Social shopping relationships (15) ────────────────────────────────────────
  { id: "relationship:retail:friends-shopping-together", kind: "relationship", description: "Friends shopping together — the social exercise of the group shopping trip, where the experience is as important as the purchase and the opinions are offered freely", sceneRoles: ["friends group"], industryIds: ["retail"], tags: ["friends", "group", "experience", "opinions"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:retail:mother-daughter-shopping", kind: "relationship", description: "A mother and daughter shopping together — the generational negotiation of taste, the moments of unexpected agreement and the different things they each take from the same rail", sceneRoles: ["mother", "daughter"], industryIds: ["retail"], tags: ["mother-daughter", "generational", "negotiation", "agreement"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:retail:couple-choosing-occasion-wear", kind: "relationship", description: "A couple shopping for occasion wear together — the event shared, the outfits not necessarily matching but co-ordinated, the partner's opinion trusted above the associate's", sceneRoles: ["couple"], industryIds: ["retail"], tags: ["couple", "occasion", "coordinated", "trusted-opinion"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:retail:bridal-party-choosing-outfits", kind: "relationship", description: "A bride and her bridesmaids choosing their outfits together — the democratic or guided selection, the bride's vision and the bridesmaids' comfort being balanced in each choice", sceneRoles: ["bride", "bridesmaids"], industryIds: ["retail"], tags: ["bridal-party", "bridesmaids", "democratic", "vision"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:retail:gift-buyer-and-recipient", kind: "relationship", description: "The gift buyer choosing on behalf of the recipient — the empathetic act of shopping for someone else, translating knowledge of a person into a specific object", sceneRoles: ["gift buyer", "recipient"], industryIds: ["retail"], tags: ["gift-buyer", "recipient", "empathetic", "translating"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:retail:parent-and-child-school-uniform", kind: "relationship", description: "Parent and child at school uniform shopping — the child trying things on while the parent notes fit and judges growing room, the list being worked through systematically", sceneRoles: ["parent", "child"], industryIds: ["retail"], tags: ["parent-child", "school-uniform", "fitting", "systematic"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Brand relationships (10) ──────────────────────────────────────────────────
  { id: "relationship:retail:brand-and-loyal-returning-customer", kind: "relationship", description: "A brand and its loyal repeat customer — the relationship that has been built over years of purchases, the customer who considers themselves a fan of the brand before they are a buyer", sceneRoles: ["loyal customer", "brand"], industryIds: ["retail"], tags: ["brand", "loyal", "fan", "repeat"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:retail:first-time-customer-to-returning", kind: "relationship", description: "The conversion arc from first-time customer to returning customer — the quality of the first experience determining whether the brand has earned the second visit", sceneRoles: ["first-time customer", "brand"], industryIds: ["retail"], tags: ["first-time", "returning", "earned", "second-visit"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:retail:sustainable-brand-and-values-customer", kind: "relationship", description: "A sustainable brand and a values-aligned customer — the relationship where purchase is also an expression of belief, the product chosen as much for what it stands for as what it is", sceneRoles: ["sustainable brand", "values-aligned customer"], industryIds: ["retail"], tags: ["sustainable", "values", "belief", "what-it-stands-for"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:retail:luxury-brand-aspirational-customer", kind: "relationship", description: "A luxury brand and a customer making their first luxury purchase — the aspiration finally acted on, the brand extended into the life of someone who has imagined this purchase for some time", sceneRoles: ["luxury brand", "aspirational customer"], industryIds: ["retail"], tags: ["luxury", "aspirational", "first-purchase", "imagined"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Craft & industry relationships (10) ───────────────────────────────────────
  { id: "relationship:retail:fashion-designer-and-buyer", kind: "relationship", description: "A fashion designer presenting a collection to a retail buyer — the commercial translation of creative work, the designer's vision meeting the buyer's knowledge of what sells", sceneRoles: ["fashion designer", "retail buyer"], industryIds: ["retail"], tags: ["designer", "buyer", "collection", "commercial-translation"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:retail:window-dresser-and-passing-public", kind: "relationship", description: "The window dresser and the passing public — the relationship between the crafted display and the pedestrian who stops, the skilled composition designed to interrupt a journey", sceneRoles: ["window dresser", "passing public"], industryIds: ["retail"], tags: ["window-display", "craft", "pedestrian", "interrupting"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:retail:vintage-dealer-and-collector", kind: "relationship", description: "A vintage dealer and a collector — the relationship built on shared knowledge and mutual respect for the object, the dealer who knows what the collector is looking for and saves it", sceneRoles: ["vintage dealer", "collector"], industryIds: ["retail"], tags: ["vintage", "dealer", "collector", "shared-knowledge"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
];
