import type { CommercialSituationKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const SALON_COMMERCIAL_SITUATIONS: CommercialSituationKnowledgeNode[] = [
  // ── New client acquisition (12) ───────────────────────────────────────────────
  { id: "commercial_situation:salon:instagram-find-and-book", kind: "commercial_situation", situation: "Potential client discovering salon through Instagram transformation post — saving the post then booking", conversionMoment: "Booking made via link in bio after seeing transformation post — the content converting to appointment", visualRepresentation: "Instagram post with before-after hair, heart save, then link in bio being tapped, booking form appearing", industryIds: ["salon"], tags: ["instagram", "discovery", "transformation", "link-in-bio"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "commercial_situation:salon:friend-recommendation-call", kind: "commercial_situation", situation: "Client calling after friend's recommendation — 'Sarah said I should ask for you specifically'", conversionMoment: "Named-stylist booking confirmed — referral captured, highest trust lead converted", visualRepresentation: "Phone call with stylist's name mentioned, receptionist smiling, appointment being made for specific stylist", industryIds: ["salon"], tags: ["friend-recommendation", "named-stylist", "referral", "trust"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "commercial_situation:salon:google-search-local-salon", kind: "commercial_situation", situation: "Google search for 'balayage specialist near me' — practice appearing with reviews and photos driving click", conversionMoment: "Website visit from Google, then online booking completed — search intent converted", visualRepresentation: "Google search result with salon photo and stars, click through to website, booking system opened", industryIds: ["salon"], tags: ["google-search", "local", "balayage", "conversion"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:salon:online-before-after-gallery-drives-enquiry", kind: "commercial_situation", situation: "Website gallery of before-after results driving consultation enquiry — the visual portfolio converting visitors", conversionMoment: "Enquiry form submitted after browsing gallery — work quality compelling the contact", visualRepresentation: "Website gallery page with results, person scrolling, specific image stopping them, contact form being filled", industryIds: ["salon"], tags: ["website-gallery", "before-after", "enquiry", "converting"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:salon:new-area-finding-salon", kind: "commercial_situation", situation: "New to area searching for a new trusted stylist — the discovery that becomes a years-long relationship", conversionMoment: "First appointment booked — beginning of the long-term salon relationship", visualRepresentation: "New resident searching on phone, reading reviews carefully, making first booking with 'New to Area' note", industryIds: ["salon"], tags: ["new-area", "finding", "long-term", "discovery"], priority: 5, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:salon:competition-prize-drives-visit", kind: "commercial_situation", situation: "Salon giveaway competition — free haircut or colour driving entries that convert to paid future visits", conversionMoment: "Winner redeemed, then rebooked at checkout — giveaway converting to long-term client", visualRepresentation: "Competition post with prize description, entries pouring in, winner attending and rebooking at checkout", industryIds: ["salon"], tags: ["competition", "giveaway", "winner", "rebooking"], priority: 6, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "commercial_situation:salon:event-hair-urgent-booking", kind: "commercial_situation", situation: "Event-driven urgent booking — wedding or formal event next weekend, appointment secured with urgency", conversionMoment: "Last-minute booking confirmed — the occasion creating the conversion timeline", visualRepresentation: "Person checking calendar with event visible, calling salon urgently, appointment confirmed in diary", industryIds: ["salon"], tags: ["event", "urgent", "last-minute", "occasion"], priority: 7, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:salon:promotional-offer-first-visit", kind: "commercial_situation", situation: "New client offer — percentage off first visit driving trial that leads to ongoing relationship", conversionMoment: "First visit booked using offer code — trial threshold lowered, relationship beginning", visualRepresentation: "Promotional offer on social media, offer code being saved, first appointment booked using the code", industryIds: ["salon"], tags: ["first-visit-offer", "trial", "code", "relationship-start"], priority: 8, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── In-salon upsell (20) ──────────────────────────────────────────────────────
  { id: "commercial_situation:salon:toner-after-bleach-recommended", kind: "commercial_situation", situation: "Stylist recommending toner addition after bleach — the professional advice that improves result and adds revenue", conversionMoment: "Client agreeing to toner addition — clinical upsell accepted based on stylist's authority", visualRepresentation: "Stylist explaining toner options, showing colour swatches, client nodding and agreeing to add it", industryIds: ["salon"], tags: ["toner", "bleach", "recommended", "authority"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:salon:treatment-added-colour", kind: "commercial_situation", situation: "Treatment offered as colour add-on — 'While we're processing let's add this for the shine'", conversionMoment: "Treatment added to booking on same visit — the natural moment of the appointment enabling the upsell", visualRepresentation: "Treatment product shown to client mid-colour appointment, processing time visible, agreement reached", industryIds: ["salon"], tags: ["treatment", "add-on", "colour-visit", "processing-time"], priority: 2, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:salon:product-recommended-at-basin", kind: "commercial_situation", situation: "Product recommended during wash — 'This is exactly what your hair needs', the experiential sale", conversionMoment: "Product taken to reception for purchase — the experience of the product in the wash driving the purchase", visualRepresentation: "Stylist at basin describing product as they apply it, client responding positively, product packaged at checkout", industryIds: ["salon"], tags: ["product", "basin", "experiential", "purchase"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:salon:gloss-between-colours", kind: "commercial_situation", situation: "Gloss service offered at maintenance appointment — the refresher between colour visits adding revenue", conversionMoment: "Gloss added to routine appointment — the regular touchpoint becoming a service opportunity", visualRepresentation: "Client at maintenance appointment, gloss service described, added to existing visit without new booking needed", industryIds: ["salon"], tags: ["gloss", "maintenance", "add-on", "touchpoint"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:salon:hair-extensions-consultation-to-yes", kind: "commercial_situation", situation: "Extensions consultation converting — showing length samples, matching colour, the visual proof driving decision", conversionMoment: "Deposit paid for extensions appointment — high-value service confirmed after consultation", visualRepresentation: "Sample wefts being held against head, length and colour shown, deposit taken, date set", industryIds: ["salon"], tags: ["extensions", "consultation", "samples", "deposit"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:salon:scalp-treatment-offer", kind: "commercial_situation", situation: "Scalp treatment offered after diagnosis — the hygienist approach to hair health enabling a service sale", conversionMoment: "Scalp treatment booked — health need identified creates service revenue", visualRepresentation: "Stylist showing scalp condition, recommending treatment, client agreeing, treatment being added to same visit", industryIds: ["salon"], tags: ["scalp-treatment", "diagnosis", "health", "care"], priority: 6, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "commercial_situation:salon:membership-plan-regular-client", kind: "commercial_situation", situation: "Loyalty membership presented to regular client — monthly plan securing routine services at locked price", conversionMoment: "Direct debit set up — recurring revenue secured, client retention improved through commitment", visualRepresentation: "Membership plan brochure shown to regular, monthly savings calculated, direct debit form signed", industryIds: ["salon"], tags: ["membership", "loyalty", "regular", "recurring"], priority: 7, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:salon:keratin-consultation-to-booking", kind: "commercial_situation", situation: "Keratin consultation — explaining the transformation and time commitment, client committing to the service", conversionMoment: "Keratin appointment booked with deposit — high-value long-duration service confirmed", visualRepresentation: "Before-after keratin photos shown, process explained on leaflet, appointment date and deposit confirmed", industryIds: ["salon"], tags: ["keratin", "consultation", "booking", "deposit"], priority: 8, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:salon:bridal-package-deposit", kind: "commercial_situation", situation: "Bridal package secured — trial and wedding day booked with deposit protecting the date", conversionMoment: "Bridal deposit paid, both dates in diary — wedding day secured months before", visualRepresentation: "Bridal package brochure, trial date selected, wedding day locked in, deposit receipt given", industryIds: ["salon"], tags: ["bridal", "package", "deposit", "secured"], priority: 9, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "commercial_situation:salon:vivid-colour-consultation-brave", kind: "commercial_situation", situation: "Vivid colour consultation converting the hesitant client — seeing examples building the courage to commit", conversionMoment: "Vivid colour booked — the specific bold decision made after seeing examples", visualRepresentation: "Portfolio of vivid colours shown, client hesitating then pointing at specific colour, appointment booked", industryIds: ["salon"], tags: ["vivid", "consultation", "courage", "committed"], priority: 10, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },

  // ── Loyalty / retention (18) ──────────────────────────────────────────────────
  { id: "commercial_situation:salon:rebooking-at-checkout", kind: "commercial_situation", situation: "Client rebooking at checkout while satisfaction is peak — the appointment secured at the highest motivation point", conversionMoment: "Next appointment confirmed — retention architecture preventing the drop in motivation between visits", visualRepresentation: "Client at reception post-service, next appointment offered, card being exchanged, date confirmed", industryIds: ["salon"], tags: ["rebooking", "checkout", "satisfaction-peak", "prevention"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:salon:five-star-review-transformation", kind: "commercial_situation", situation: "Client posting five-star review with before-after photos — organic content driving future bookings", conversionMoment: "Public review with visual proof published — future clients converted by this client's documentation", visualRepresentation: "Review platform with before-after photos uploaded, five stars selected, praise for specific service", industryIds: ["salon"], tags: ["five-star", "before-after", "organic", "review"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "commercial_situation:salon:product-home-purchase", kind: "commercial_situation", situation: "Client purchasing products to maintain salon result at home — the retail sale extending service value", conversionMoment: "Products purchased at checkout — home care investment protecting the salon service", visualRepresentation: "Client at reception with product bottles, stylist recommendation recalled, payment made", industryIds: ["salon"], tags: ["product", "home", "maintenance", "retail"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:salon:follow-up-message-result-shared", kind: "commercial_situation", situation: "Client sending result photo to salon days later — proactive advocacy maintaining the relationship", conversionMoment: "Photo received and shared — content for salon's social media, referral potential created", visualRepresentation: "Client's message with photo of hair at event, salon sharing it with permission, comments from new potential clients", industryIds: ["salon"], tags: ["follow-up", "photo", "advocacy", "social-content"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:salon:annual-loyalty-review", kind: "commercial_situation", situation: "Annual loyalty review — salon reviewing client's year of visits, offering upgraded loyalty reward", conversionMoment: "Loyalty reward redeemed, another year commenced — retention through recognition", visualRepresentation: "Loyalty tracker showing year of visits, reward explained, client delighted by recognition", industryIds: ["salon"], tags: ["annual", "loyalty", "reward", "recognition"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "commercial_situation:salon:friend-group-booking", kind: "commercial_situation", situation: "Group of friends booking salon day together — the social booking that fills multiple slots at once", conversionMoment: "Group of 4 appointments confirmed simultaneously — bulk slot fill from single conversion", visualRepresentation: "Group chat deciding on salon day, one person calling to book all four, slots confirmed", industryIds: ["salon"], tags: ["group-booking", "friends", "bulk", "slots"], priority: 6, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:salon:old-client-reactivated-offer", kind: "commercial_situation", situation: "Lapsed client returning after 'We miss you' offer — the reactivation campaign working", conversionMoment: "Lapsed client booking after receiving personal offer — relationship reactivated", visualRepresentation: "Personalised text saying 'We miss you — 20% off your next visit', client booking in response", industryIds: ["salon"], tags: ["lapsed", "reactivation", "miss-you", "personal"], priority: 7, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "commercial_situation:salon:ambassador-before-after-content", kind: "commercial_situation", situation: "Client agreeing to be ambassador — their transformation used with permission as organic marketing content", conversionMoment: "Content published driving new enquiries — the client as marketing asset voluntarily", visualRepresentation: "Client agreeing to before-after use, photos published to salon social, enquiries in comments", industryIds: ["salon"], tags: ["ambassador", "before-after", "content", "organic"], priority: 8, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
];
