import type { EmotionalMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const SALON_EMOTIONAL_MOMENTS: EmotionalMomentKnowledgeNode[] = [
  // ── Transformation reveal (15) ────────────────────────────────────────────────
  { id: "emotional_moment:salon:chair-spin-first-look-tears", kind: "emotional_moment", moment: "Stylist spins chair for first look — client seeing themselves and starting to cry, a response no one expected", emotionType: "overwhelming joy", visualSignals: ["hands flying to face", "chair still turning", "stylist touching shoulder gently", "mirror showing both reactions"], industryIds: ["salon"], tags: ["chair-spin", "tears", "overwhelming", "unexpected"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:salon:post-cut-hair-toss-freedom", kind: "emotional_moment", moment: "Client's first hair toss after big cut — the weight gone, the movement so different, pure physical freedom", emotionType: "physical liberation", visualSignals: ["head tossing freely", "eyes surprised by the new movement", "involuntary smile", "doing it again deliberately"], industryIds: ["salon"], tags: ["hair-toss", "freedom", "physical", "liberation"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:salon:bridal-hair-complete-moment", kind: "emotional_moment", moment: "Bridal hair complete on wedding day — stylist placing the last pin, veil being set, bride seeing the whole", emotionType: "peak occasion readiness", visualSignals: ["eyes full", "deep breath", "veil settling", "stylist stepping back in pride"], industryIds: ["salon"], tags: ["bridal", "complete", "veil", "readiness"], priority: 3, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:salon:first-colour-teen-disbelief", kind: "emotional_moment", moment: "Teenager's first colour reveal — looking at themselves and not recognising who they're becoming", emotionType: "identity discovery", visualSignals: ["leaning close to mirror", "touching hair in disbelief", "turning to show parent", "the beginning of a new self-image"], industryIds: ["salon"], tags: ["teen", "first-colour", "identity", "disbelief"], priority: 4, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:salon:natural-hair-embrace-revelation", kind: "emotional_moment", moment: "Client who always straightened her hair seeing her natural curls celebrated for the first time — coming home", emotionType: "self-acceptance revelation", visualSignals: ["touching curls with wonder", "eyes softening", "the smile of recognition", "something settling in the body"], industryIds: ["salon"], tags: ["natural-hair", "curls", "acceptance", "coming-home"], priority: 5, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:salon:colour-correction-complete-relief", kind: "emotional_moment", moment: "Colour correction completed — the bad colour gone, the right colour finally here, the weeks of distress over", emotionType: "relief from aesthetic distress", visualSignals: ["exhale", "touching the even colour", "looking at stylist with gratitude", "the first time they feel like themselves again"], industryIds: ["salon"], tags: ["colour-correction", "relief", "distress-over", "themselves-again"], priority: 6, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:salon:post-blowout-confidence-walk", kind: "emotional_moment", moment: "Client leaving salon with fresh blowout — the walk changes, the posture straightens, the world responds differently", emotionType: "embodied confidence", visualSignals: ["shoulders back", "stride lengthening", "hair moving perfectly", "head slightly higher"], industryIds: ["salon"], tags: ["blowout", "confidence", "walk", "posture"], priority: 7, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "emotional_moment:salon:pre-big-event-hair-done", kind: "emotional_moment", moment: "Hair done before a big event — looking in mirror and feeling ready, the preparation complete", emotionType: "readiness and anticipation", visualSignals: ["checking from multiple angles", "satisfied final look", "gathering bag ready to go", "the event now possible"], industryIds: ["salon"], tags: ["pre-event", "ready", "anticipation", "complete"], priority: 8, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:salon:end-of-treatment-sheen", kind: "emotional_moment", moment: "Conditioning treatment complete — client seeing their damaged hair now gleaming, the repair visible", emotionType: "grateful relief at restoration", visualSignals: ["running fingers through", "the sheen visible to both", "looking at stylist with gratitude", "hair moving differently"], industryIds: ["salon"], tags: ["treatment", "sheen", "repair", "restored"], priority: 9, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:salon:keratin-frizz-gone-morning", kind: "emotional_moment", moment: "First morning after keratin treatment — waking and touching hair, the frizz completely absent, ten minutes back every day", emotionType: "quiet daily transformation", visualSignals: ["touching hair on waking", "the smooth sensation new", "getting ready faster", "life quietly changed"], industryIds: ["salon"], tags: ["keratin", "morning", "frizz-gone", "daily-change"], priority: 10, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Self-care / wellbeing (15) ─────────────────────────────────────────────────
  { id: "emotional_moment:salon:surrendered-scalp-massage-peace", kind: "emotional_moment", moment: "Scalp massage at wash basin — the moment the client completely surrenders, every muscle releasing", emotionType: "complete surrendered peace", visualSignals: ["every muscle going slack", "breath deepening", "the world disappearing", "eyes closed without intention to open"], industryIds: ["salon"], tags: ["scalp-massage", "surrender", "peace", "release"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:salon:self-care-appointment-deserved", kind: "emotional_moment", moment: "Client walking in knowing this appointment is for no one but themselves — a rare selfishness, fully permitted", emotionType: "validated self-permission", visualSignals: ["unhurried arrival", "phone put away deliberately", "deep breath before sitting", "the settling-in of self-care"], industryIds: ["salon"], tags: ["self-care", "selfish", "deserved", "permission"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:salon:appointment-only-quiet-hour", kind: "emotional_moment", moment: "The salon appointment as the only quiet hour in a week — the one place where someone else is in charge", emotionType: "rare peace", visualSignals: ["phone on silent", "not asked to make a decision", "someone doing the doing", "face relaxing through session"], industryIds: ["salon"], tags: ["quiet", "hour", "one-place", "not-deciding"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:salon:post-illness-hair-restored", kind: "emotional_moment", moment: "Client after illness having hair done properly for the first time in months — the return to herself", emotionType: "restorative return to self", visualSignals: ["careful handling", "stylist knowing the context", "client's face becoming more themselves", "the visible restoration"], industryIds: ["salon"], tags: ["post-illness", "restored", "return-to-self", "careful"], priority: 4, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:salon:happy-client-happy-stylist", kind: "emotional_moment", moment: "The mutual satisfaction of a great result — stylist as proud as client, both looking at the mirror together", emotionType: "shared professional pride", visualSignals: ["both looking at mirror", "stylist's smile of pride", "client's joy", "the shared moment of achievement"], industryIds: ["salon"], tags: ["shared-pride", "mutual", "achievement", "mirror"], priority: 5, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Social / connection moments (10) ──────────────────────────────────────────
  { id: "emotional_moment:salon:stylist-remembering-life-event", kind: "emotional_moment", moment: "Stylist asking about the job interview they mentioned last time — the relationship of genuine care and memory", emotionType: "feeling genuinely known", visualSignals: ["client's surprised pleasure", "the relationship deepening visibly", "conversation becoming more real", "the transaction becoming a relationship"], industryIds: ["salon"], tags: ["remembered", "job-interview", "genuine-care", "relationship"], priority: 1, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:salon:friend-salon-day-laughter", kind: "emotional_moment", moment: "Friends in salon together — the laughter that fills the whole salon, the appointment as pure social event", emotionType: "social joy", visualSignals: ["laughter audible", "other clients smiling", "stylist included in the fun", "the appointment as party"], industryIds: ["salon"], tags: ["friends", "laughter", "social", "party"], priority: 2, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "emotional_moment:salon:sharing-difficult-thing-in-chair", kind: "emotional_moment", moment: "Client sharing something difficult in the chair — the safety of the ritual enabling honesty not offered elsewhere", emotionType: "safe vulnerability", visualSignals: ["stylist's hands continuing but attention given", "client's voice quieter", "the intimacy of the revealed difficulty", "tissues quietly placed near"], industryIds: ["salon"], tags: ["sharing-difficult", "safety", "vulnerability", "intimacy"], priority: 3, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "emotional_moment:salon:returning-client-welcomed-back", kind: "emotional_moment", moment: "Returning client welcomed back warmly by their stylist — picked up mid-story from months ago, the relationship real", emotionType: "belonging", visualSignals: ["stylist remembering immediately", "client's posture lifting", "the ease of resumed familiarity", "chair felt like home"], industryIds: ["salon"], tags: ["welcome-back", "belonging", "remembered", "home"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "emotional_moment:salon:post-big-change-nervous-love", kind: "emotional_moment", moment: "Client nervous about their big change but then loving it — the fear and the love arriving in the same look", emotionType: "fear becoming joy", visualSignals: ["initial hesitation on seeing", "then slow smile", "then confidence", "fear-to-love visible as a journey"], industryIds: ["salon"], tags: ["big-change", "nervous-to-love", "fear-becoming-joy", "journey"], priority: 5, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
];
