import type { RelationshipKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const SALON_RELATIONSHIPS: RelationshipKnowledgeNode[] = [
  // ── Stylist–client (15) ───────────────────────────────────────────────────────
  { id: "relationship:salon:regular-client-loyal-stylist", kind: "relationship", description: "Regular client with their stylist of many years — the relationship that follows the stylist from salon to salon", sceneRoles: ["regular client", "loyal stylist"], industryIds: ["salon"], tags: ["regular", "loyal", "years", "follows"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:salon:new-client-stylist-trust-building", kind: "relationship", description: "New client's first appointment — the careful consultation, the trust being established through listening", sceneRoles: ["new client", "stylist"], industryIds: ["salon"], tags: ["new-client", "consultation", "trust", "listening"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:salon:bridal-stylist-bride", kind: "relationship", description: "Bridal stylist and bride — the weeks of consultation, trial runs, and the day itself as the peak of the relationship", sceneRoles: ["bride", "bridal stylist"], industryIds: ["salon"], tags: ["bridal", "trial", "peak", "weeks-of-care"], priority: 3, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:salon:colour-specialist-client", kind: "relationship", description: "Colour specialist and client — the technical expertise relationship, client trusting complex colour to one specialist", sceneRoles: ["colour client", "colour specialist"], industryIds: ["salon"], tags: ["colour-specialist", "technical", "trust", "expert"], priority: 4, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:salon:fearful-client-reassuring-stylist", kind: "relationship", description: "Client nervous about big change — stylist reassuring, showing reference results, the courage being given", sceneRoles: ["nervous client", "reassuring stylist"], industryIds: ["salon"], tags: ["nervous", "reassurance", "big-change", "courage"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:salon:curly-hair-specialist-client", kind: "relationship", description: "Curly hair specialist and client who has struggled with their curl — the specialist who finally understands", sceneRoles: ["curl client", "curl specialist"], industryIds: ["salon"], tags: ["curly-hair", "specialist", "understanding", "struggled"], priority: 6, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:salon:senior-client-known-preferences", kind: "relationship", description: "Senior client whose preferences are known perfectly by their stylist — decades of care accumulated", sceneRoles: ["senior client", "experienced stylist"], industryIds: ["salon"], tags: ["senior", "preferences-known", "decades", "accumulated"], priority: 7, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:salon:celebrity-personal-stylist", kind: "relationship", description: "Public figure and their personal stylist — on-call relationship, style identity maintained", sceneRoles: ["public figure", "personal stylist"], industryIds: ["salon"], tags: ["celebrity", "personal", "on-call", "identity"], priority: 8, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:salon:teen-first-salon-parent-present", kind: "relationship", description: "Teenager's first real salon visit with parent — the rite of passage, the handoff from home cuts to professional", sceneRoles: ["teenager", "parent", "stylist"], industryIds: ["salon"], tags: ["teen", "first-salon", "parent", "rite-of-passage"], priority: 9, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:salon:therapist-like-stylist-client", kind: "relationship", description: "The stylist as listener — clients sharing things in the chair they share nowhere else, the unique trust of the salon", sceneRoles: ["client", "listener-stylist"], industryIds: ["salon"], tags: ["listener", "sharing", "unique-trust", "chair"], priority: 10, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Social / group (15) ──────────────────────────────────────────────────────
  { id: "relationship:salon:friends-salon-day-together", kind: "relationship", description: "Friends booking salon day together — the social event of the appointment, the shared transformation", sceneRoles: ["friend group"], industryIds: ["salon"], tags: ["friends", "social-event", "together", "shared"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:salon:mother-daughter-salon", kind: "relationship", description: "Mother and daughter at salon together — the generational ritual, the shared aesthetic investment", sceneRoles: ["mother", "daughter"], industryIds: ["salon"], tags: ["mother-daughter", "generational", "ritual", "investment"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:salon:bridesmaids-bridal-party", kind: "relationship", description: "Bridal party preparing together — bride and bridesmaids, the collective transformation of the occasion", sceneRoles: ["bride", "bridesmaids", "stylists"], industryIds: ["salon"], tags: ["bridal-party", "collective", "occasion", "transforming"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:salon:salon-team-colleagues", kind: "relationship", description: "Salon team as creative collective — stylists whose work influences each other, healthy creative competition", sceneRoles: ["stylist colleagues"], industryIds: ["salon"], tags: ["team", "creative", "collective", "competition"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:salon:mentor-apprentice-salon", kind: "relationship", description: "Senior stylist mentoring junior — technique passed from hands to hands, craft lineage visible", sceneRoles: ["senior stylist", "junior stylist"], industryIds: ["salon"], tags: ["mentor", "apprentice", "technique", "lineage"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:salon:client-recommending-stylist", kind: "relationship", description: "Client recommending their stylist to a friend — the highest compliment, the personal advocacy", sceneRoles: ["client advocate", "friend"], industryIds: ["salon"], tags: ["recommendation", "advocate", "friend", "personal"], priority: 6, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:salon:new-in-town-finding-salon", kind: "relationship", description: "New resident establishing salon relationship — the search for someone to trust with their hair in a new city", sceneRoles: ["new resident", "new stylist"], industryIds: ["salon"], tags: ["new-in-town", "finding", "trust", "search"], priority: 7, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "relationship:salon:stylist-following-from-old-salon", kind: "relationship", description: "Client following stylist to a new salon — the relationship stronger than the brand, loyalty to the person", sceneRoles: ["client", "moved-stylist"], industryIds: ["salon"], tags: ["following", "loyalty", "moved", "person-not-brand"], priority: 8, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:salon:natural-hair-community", kind: "relationship", description: "Natural hair community client finding specialist salon — the relief of being understood and celebrated", sceneRoles: ["natural hair client", "specialist stylist"], industryIds: ["salon"], tags: ["natural-hair", "community", "specialist", "understood"], priority: 9, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:salon:stylist-owner-team", kind: "relationship", description: "Salon owner-stylist leading their team — the vision-setter whose standard flows through the whole salon", sceneRoles: ["owner-stylist", "salon team"], industryIds: ["salon"], tags: ["owner", "leader", "vision", "standard"], priority: 10, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:salon:client-partner-watching", kind: "relationship", description: "Partner watching client's hair appointment — proud and slightly awed by the transformation they are witnessing", sceneRoles: ["client", "watching partner"], industryIds: ["salon"], tags: ["partner", "watching", "transformation", "proud"], priority: 11, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "relationship:salon:new-grad-first-real-clients", kind: "relationship", description: "Newly qualified stylist working on their first real clients — the vulnerability of new practice, clients supporting", sceneRoles: ["new stylist", "supportive client"], industryIds: ["salon"], tags: ["new-grad", "first-clients", "vulnerability", "support"], priority: 12, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "relationship:salon:before-after-model-stylist", kind: "relationship", description: "Stylist's model relationship for competition or portfolio — the client who becomes a creative collaborator", sceneRoles: ["model client", "competition stylist"], industryIds: ["salon"], tags: ["model", "competition", "portfolio", "collaborator"], priority: 13, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:salon:anxiety-client-safe-space-stylist", kind: "relationship", description: "Client with social anxiety who can relax in their trusted stylist's chair — the safe container", sceneRoles: ["anxious client", "trusted stylist"], industryIds: ["salon"], tags: ["anxiety", "safe-space", "trusted", "container"], priority: 14, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:salon:colour-correction-rescue", kind: "relationship", description: "Client who had bad colour elsewhere, now in capable hands — the rescue relationship, trust rebuilt", sceneRoles: ["colour-damaged client", "colour specialist"], industryIds: ["salon"], tags: ["colour-correction", "rescue", "bad-experience", "trust-rebuilt"], priority: 15, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
];
