import type { SceneTypeKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const SALON_SCENE_TYPES: SceneTypeKnowledgeNode[] = [
  // ── Salon interiors (30) ─────────────────────────────────────────────────────
  { id: "scene_type:salon:modern-luxury-studio", kind: "scene_type", environment: "Modern luxury salon — white walls, marble surfaces, statement mirrors, individual styling stations with privacy", lightingCharacter: "Bright studio light at 5000K, diffused and even, no harsh shadows on hair, backlit mirror warm", mood: "Creative confidence — the space where transformation happens, curated and considered", industryIds: ["salon"], compatibleHeroTypes: ["authority", "lifestyle", "product"], tags: ["luxury", "marble", "studio", "mirrors"], priority: 1, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "scene_type:salon:industrial-edge-salon", kind: "scene_type", environment: "Industrial-edge salon — exposed brick, pendant lights, salvaged wood stations, edgy creative energy", lightingCharacter: "Warm Edison pendants at 2700K, natural light supplement, contrast between warm and cool", mood: "Avant-garde craft — this is where the bold choices are made", industryIds: ["salon"], compatibleHeroTypes: ["authority", "product", "environment"], tags: ["industrial", "brick", "edgy", "creative"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "scene_type:salon:boutique-intimate-salon", kind: "scene_type", environment: "Boutique intimate salon — only 4 chairs, curated music, champagne offered, an experience not a service", lightingCharacter: "Warm intimate at 2800K, stations individually lit, personal and considered", mood: "Exclusive ritual — this appointment is an event not a chore", industryIds: ["salon"], compatibleHeroTypes: ["lifestyle", "person", "authority"], tags: ["boutique", "intimate", "champagne", "exclusive"], priority: 3, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "scene_type:salon:colour-lab-chemistry", kind: "scene_type", environment: "Colour mixing area — formula books, professional bowls, brushes, the laboratory of beauty chemistry", lightingCharacter: "Bright lab light at 4500K, accurate colour rendering for formula assessment, clinical but creative", mood: "Science in service of beauty — the colour lab as the most skilled part of the salon", industryIds: ["salon"], compatibleHeroTypes: ["authority", "product", "environment"], tags: ["colour-lab", "formula", "chemistry", "professional"], priority: 4, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "scene_type:salon:wash-basin-area-spa-like", kind: "scene_type", environment: "Wash basin area — luxury basins with neck support, dim lighting, weighted towels, the relaxation zone", lightingCharacter: "Very warm at 2600K, dimmed for relaxation, candle-equivalent atmosphere, face soft-lit", mood: "Surrender — the only place in a busy schedule where someone cares for you completely", industryIds: ["salon"], compatibleHeroTypes: ["lifestyle", "person"], tags: ["wash-basin", "spa", "relaxation", "surrender"], priority: 5, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "scene_type:salon:nail-studio-dedicated", kind: "scene_type", environment: "Dedicated nail studio — manicure tables with detail lights, organised polish displays, focused nail environment", lightingCharacter: "Bright task light at 5000K above table, display lighting on polish wall, colour-accurate", mood: "Precision and artistry — the nail table is where the smallest details are given full attention", industryIds: ["salon"], compatibleHeroTypes: ["authority", "product", "person"], tags: ["nail-studio", "manicure-table", "polish-wall", "precision"], priority: 6, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:salon:barber-shop-classic", kind: "scene_type", environment: "Classic barbershop — barber's pole, leather chairs, vintage mirrors, masculine grooming space with tradition", lightingCharacter: "Warm traditional at 2800K, barber mirror well lit, vintage bulbs contributing character", mood: "Heritage masculinity — this is the ritual that connects generations of men", industryIds: ["salon"], compatibleHeroTypes: ["authority", "lifestyle", "person"], tags: ["barbershop", "leather-chairs", "vintage", "masculine"], priority: 7, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "scene_type:salon:modern-barber-minimal", kind: "scene_type", environment: "Modern minimal barbershop — concrete surfaces, floating mirror, curated grooming products, contemporary edge", lightingCharacter: "Architectural at 3500K, focused beam on chair, clean and considered", mood: "Contemporary masculine — grooming as self-investment, not vanity", industryIds: ["salon"], compatibleHeroTypes: ["authority", "lifestyle", "product"], tags: ["barbershop", "modern", "minimal", "concrete"], priority: 8, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:salon:bridal-suite-preparation", kind: "scene_type", environment: "Bridal preparation suite — dress hanging, flowers, champagne, team working simultaneously on hair and makeup", lightingCharacter: "Warm bright at 3500K, vanity mirror well lit, a little golden, the occasion in the light temperature", mood: "Peak occasion — the most important morning of the year, everything perfect", industryIds: ["salon"], compatibleHeroTypes: ["lifestyle", "person", "authority"], tags: ["bridal", "suite", "preparation", "occasion"], priority: 9, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "scene_type:salon:training-academy-space", kind: "scene_type", environment: "Salon training academy — multiple mannequins, students learning, educator at front demonstrating technique", lightingCharacter: "Bright educational at 4500K, even coverage, education context clear", mood: "The future of the craft — knowledge being passed through touch and repetition", industryIds: ["salon"], compatibleHeroTypes: ["authority", "education", "environment"], tags: ["training", "academy", "students", "education"], priority: 10, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── Product / styling scenes (20) ─────────────────────────────────────────────
  { id: "scene_type:salon:product-flatlay-hero", kind: "scene_type", environment: "Product flat lay — professional hair care products arranged on marble or textured surface, clean composition", lightingCharacter: "Studio soft box, shadows minimal, product labels readable, hero shot quality", mood: "Product as protagonist — the tools of beauty given full credit", industryIds: ["salon"], compatibleHeroTypes: ["product", "lifestyle"], tags: ["flatlay", "product", "marble", "studio"], priority: 1, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:salon:outdoor-natural-light-hair", kind: "scene_type", environment: "Outdoor lifestyle setting — model in natural environment, hair visible and beautiful in real world light", lightingCharacter: "Natural daylight, directional sun creating shine, lifestyle context real and achievable", mood: "Aspiration meets reality — this is what the hair looks like outside the salon too", industryIds: ["salon"], compatibleHeroTypes: ["lifestyle", "product", "person"], tags: ["outdoor", "natural", "lifestyle", "real-world"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:salon:editorial-studio-shoot", kind: "scene_type", environment: "Editorial studio — seamless backdrop, professional lighting, the salon's work as fashion photography", lightingCharacter: "Editorial quality — controlled, intentional, fashion-context light", mood: "The salon as creative studio — this work is art not just service", industryIds: ["salon"], compatibleHeroTypes: ["product", "authority", "lifestyle"], tags: ["editorial", "studio", "seamless", "fashion"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "scene_type:salon:social-media-mirror-selfie", kind: "scene_type", environment: "Salon mirror selfie context — client photographing their finished look in the styling station mirror", lightingCharacter: "Salon station light, mirror showing both front and back, authentic post-service context", mood: "Real result in real context — the unfiltered authenticity of the salon selfie", industryIds: ["salon"], compatibleHeroTypes: ["person", "transformation", "product"], tags: ["selfie", "mirror", "authentic", "social-media"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:salon:close-up-hair-texture-detail", kind: "scene_type", environment: "Macro hair texture detail — individual strands, colour gradient, shine, the craftsmanship visible at micro level", lightingCharacter: "Macro close-up with controlled light, individual strands illuminated, depth of field shallow", mood: "Craftsmanship at microscale — every strand the result of skill", industryIds: ["salon"], compatibleHeroTypes: ["product", "authority"], tags: ["macro", "texture", "strand", "craftsmanship"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Lifestyle / client experience (30) ───────────────────────────────────────
  { id: "scene_type:salon:client-in-chair-relaxed", kind: "scene_type", environment: "Client in styling chair — relaxed, magazine on lap or phone in hand, the comfortable wait while work happens", lightingCharacter: "Station light warm at 3000K, mirror well lit, client face visible and at ease", mood: "Comfortable surrender — the salon is one of the few places where someone else takes over completely", industryIds: ["salon"], compatibleHeroTypes: ["person", "lifestyle"], tags: ["client", "chair", "relaxed", "comfortable"], priority: 1, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:salon:friends-at-salon-together", kind: "scene_type", environment: "Friends at salon together — adjacent chairs, chatting, the social ritual of the shared salon visit", lightingCharacter: "Warm ambient, conversation light, social rather than solitary, faces lit and animated", mood: "Social ritual — the salon visit as the event, not just the outcome", industryIds: ["salon"], compatibleHeroTypes: ["lifestyle", "person"], tags: ["friends", "together", "social", "ritual"], priority: 2, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "scene_type:salon:client-consultation-reference-images", kind: "scene_type", environment: "Client consultation — scrolling through reference images with stylist, the collaborative planning moment", lightingCharacter: "Station light, phone screen glow, both heads close to the screen, warm and engaged", mood: "Creative partnership — the client and stylist building the vision together", industryIds: ["salon"], compatibleHeroTypes: ["authority", "person", "lifestyle"], tags: ["consultation", "reference", "collaboration", "planning"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "scene_type:salon:morning-opening-ritual", kind: "scene_type", environment: "Salon morning before opening — stylists setting up, mirrors being cleaned, the preparation of the day", lightingCharacter: "Morning natural light supplemented by station lights, fresh and clean, day beginning", mood: "The ritual of readiness — behind every great result is preparation", industryIds: ["salon"], compatibleHeroTypes: ["authority", "environment", "lifestyle"], tags: ["morning", "opening", "preparation", "readiness"], priority: 4, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "scene_type:salon:post-salon-street-confidence", kind: "scene_type", environment: "Client leaving salon — stepping outside, fresh hair, confidence in their step, the world as witness", lightingCharacter: "Natural outdoor light contrasting with salon warmth, the new hair in real light", mood: "The destination is a feeling not a place — this is what the appointment was for", industryIds: ["salon"], compatibleHeroTypes: ["person", "lifestyle", "transformation"], tags: ["leaving", "street", "confidence", "fresh-hair"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
];
