import type { BehaviourKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const FURNITURE_BEHAVIOURS: BehaviourKnowledgeNode[] = [
  // ── First-touch / sensory behaviours (20) ─────────────────────────────────────
  { id: "behaviour:furniture:sinking-into-sofa-first-time", kind: "behaviour", description: "Person lowering themselves slowly into a new sofa, eyes closing as the cushion gives — the full surrender of the first proper sit, shoulders dropping visibly", emotionalSignal: "physical relief and pleasure", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["furniture"], tags: ["sinking", "sofa", "first-sit", "surrender"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "behaviour:furniture:running-hand-across-surface", kind: "behaviour", description: "Person drawing their palm slowly along a table or countertop — feeling grain, temperature, smoothness, the deliberate tactile assessment of a material", emotionalSignal: "sensory delight and evaluation", compatibleHeroes: ["product", "person", "moment"], industryIds: ["furniture"], tags: ["surface", "hand", "grain", "tactile"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:furniture:pressing-cushion-spring-test", kind: "behaviour", description: "Customer pressing a sofa cushion firmly and watching it spring back — the resilience test that predicts years of use, done at every good sofa purchase decision", emotionalSignal: "quality assessment", compatibleHeroes: ["product", "person", "moment"], industryIds: ["furniture"], tags: ["cushion", "pressing", "spring-back", "quality-test"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:furniture:reclining-all-the-way-back", kind: "behaviour", description: "Person reclining fully in an armchair or recliner, feet rising, back dropping, a slow grin as they realise how good this is", emotionalSignal: "discovered comfort", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["furniture"], tags: ["reclining", "feet-up", "grin", "discovered"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:furniture:stretching-across-new-mattress", kind: "behaviour", description: "Person lying spread-eagle on a new mattress — arms and legs extended fully, taking up the whole surface, testing the width and depth of the support", emotionalSignal: "freedom and space", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["furniture"], tags: ["mattress", "spread-eagle", "stretching", "space"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:furniture:looking-under-furniture-for-construction", kind: "behaviour", description: "Serious buyer turning a chair upside down or ducking under a table to examine the joints — the methodical quality check of someone who understands furniture", emotionalSignal: "expert evaluation", compatibleHeroes: ["product", "person", "moment"], industryIds: ["furniture"], tags: ["construction", "joints", "underside", "expert"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:furniture:opening-drawer-testing-slide", kind: "behaviour", description: "Person sliding a drawer fully in and out several times — feeling the glide, listening for smooth silence, the dovetail quality read through the motion", emotionalSignal: "quality detection", compatibleHeroes: ["product", "person", "moment"], industryIds: ["furniture"], tags: ["drawer", "slide", "dovetail", "quality"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:furniture:sitting-and-swivelling-office-chair", kind: "behaviour", description: "Person sitting in an office chair and swivelling left and right — testing range, the slight push from the floor, the chair pivoting smoothly under them", emotionalSignal: "playful evaluation", compatibleHeroes: ["product", "person", "moment"], industryIds: ["furniture"], tags: ["office-chair", "swivelling", "range", "playful"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:furniture:weighing-solid-wood-piece", kind: "behaviour", description: "Customer lifting a corner of a table or the end of a shelf to feel the weight — the solid heaviness of real wood communicating quality before any other test", emotionalSignal: "weight as reassurance", compatibleHeroes: ["product", "person"], industryIds: ["furniture"], tags: ["weight", "solid-wood", "lifting", "quality"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:furniture:touching-fabric-swatch-with-fingertips", kind: "behaviour", description: "Person touching fabric swatches with the pads of their fingertips — the delicate test for texture, the slight scratch of velvet, the coolness of linen, the softness of chenille", emotionalSignal: "texture pleasure and evaluation", compatibleHeroes: ["product", "person"], industryIds: ["furniture"], tags: ["swatch", "fabric", "fingertips", "texture"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Delivery & arrival behaviours (15) ────────────────────────────────────────
  { id: "behaviour:furniture:directing-delivery-team-into-room", kind: "behaviour", description: "Homeowner directing delivery team with hand gestures — pointing at the space, hands showing the angle, the driver's head calculating clearance as they come through the door", emotionalSignal: "anticipation and control", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["furniture"], tags: ["delivery", "directing", "angle", "arrival"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:furniture:removing-wrapping-excited", kind: "behaviour", description: "Person pulling transit wrap off a new piece of furniture — tearing the padding eagerly, the protected surface underneath being revealed in sections", emotionalSignal: "excited unwrapping", compatibleHeroes: ["moment", "person"], industryIds: ["furniture"], tags: ["unwrapping", "delivery", "revealing", "excited"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:furniture:first-sit-family-pile-on-delivery", kind: "behaviour", description: "Family piling onto a new sofa the moment it's set down by the delivery team — children jumping, parents laughing, the piece immediately becoming theirs", emotionalSignal: "joyful collective claiming", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["furniture"], tags: ["family", "pile-on", "delivery", "claiming"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "behaviour:furniture:stepping-back-to-see-first-placement", kind: "behaviour", description: "Person stepping far back to see the new piece in its room for the first time — the full view from across the space, assessing whether it looks right from a distance", emotionalSignal: "first assessment of rightness", compatibleHeroes: ["moment", "person", "environment"], industryIds: ["furniture"], tags: ["stepping-back", "first-view", "distance", "assessment"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:furniture:moving-piece-slightly-to-align", kind: "behaviour", description: "Person adjusting new furniture's exact position by centimetres — hands on the sides, tiny shuffles, checking alignment with walls, rugs, and the other pieces around it", emotionalSignal: "perfectionist placing", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["furniture"], tags: ["aligning", "positioning", "centimetres", "perfectionist"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:furniture:photographing-room-after-delivery", kind: "behaviour", description: "Person photographing the room from multiple angles immediately after the furniture is placed — the documentation of the new order before life disturbs it", emotionalSignal: "pride and documentation", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["furniture"], tags: ["photographing", "room", "documentation", "pride"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Showroom & choosing behaviours (20) ───────────────────────────────────────
  { id: "behaviour:furniture:sitting-on-every-sofa-in-showroom", kind: "behaviour", description: "Customer methodically sitting on each sofa in sequence — the systematic comparison tour, each sit assessed against the last, the body keeping a running ranking", emotionalSignal: "methodical comparison", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["showroom", "systematic", "comparison", "sitting"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:furniture:holding-swatch-in-natural-light", kind: "behaviour", description: "Customer carrying a fabric swatch toward a showroom window to assess the true colour in natural light — the move away from artificial lighting that every serious buyer makes", emotionalSignal: "accuracy seeking", compatibleHeroes: ["product", "person", "environment"], industryIds: ["furniture"], tags: ["swatch", "natural-light", "window", "true-colour"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:furniture:measuring-furniture-with-tape-in-showroom", kind: "behaviour", description: "Customer measuring a piece in the showroom with a tape measure — confirming that the numbers on the label match the space measurements in their phone notes", emotionalSignal: "diligent verification", compatibleHeroes: ["product", "person", "moment"], industryIds: ["furniture"], tags: ["measuring", "tape", "showroom", "verification"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:furniture:returning-to-same-sofa-three-times", kind: "behaviour", description: "Customer who keeps returning to the same piece in a showroom — they've looked at twelve sofas and keep coming back to this one, their body already decided before their mind is", emotionalSignal: "subconscious certainty", compatibleHeroes: ["moment", "person", "environment"], industryIds: ["furniture"], tags: ["returning", "same-piece", "subconscious", "certainty"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:furniture:couple-disagreeing-in-showroom", kind: "behaviour", description: "A couple with different preferences standing between two sofas — one traditional, one contemporary — each trying to convince the other, the negotiation visible as a physical standoff between pieces", emotionalSignal: "productive couple tension", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["furniture"], tags: ["couple", "disagreeing", "negotiation", "preferences"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:furniture:sitting-with-phone-photos-comparing", kind: "behaviour", description: "Person sitting in a showroom sofa while swiping through photos of their living room on their phone — mentally placing the sofa into the real space from memory", emotionalSignal: "mental spatial projection", compatibleHeroes: ["product", "person", "moment"], industryIds: ["furniture"], tags: ["phone-photos", "comparing", "mental-placing", "showroom"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:furniture:child-hiding-inside-wardrobe-in-showroom", kind: "behaviour", description: "A child discovering a large wardrobe in a furniture showroom and stepping inside to see if they fit — the parent calling them out, the child delighted by the secret space", emotionalSignal: "playful discovery", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["furniture"], tags: ["child", "wardrobe", "hiding", "playful"], priority: 6, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:furniture:designer-consulting-on-room-layout", kind: "behaviour", description: "Interior designer or showroom consultant spreading a floor plan on a table and placing scaled furniture cutouts on it — the professional showing the client what their room could become", emotionalSignal: "expert-guided imagination", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["furniture"], tags: ["designer", "floor-plan", "consultation", "layout"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Living with furniture behaviours (25) ─────────────────────────────────────
  { id: "behaviour:furniture:morning-coffee-on-new-sofa", kind: "behaviour", description: "Person with morning coffee on the new sofa — legs tucked under, cup warming both hands, the room quiet, the sofa already fully theirs after the first week", emotionalSignal: "comfortable ownership", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["morning", "coffee", "sofa", "ownership"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:furniture:working-from-home-at-desk", kind: "behaviour", description: "Person working at their home desk in deep focus — screen lit, coffee cooling beside the keyboard, posture supported by an ergonomic chair, the desk holding the day's work", emotionalSignal: "productive focus", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["working", "desk", "focus", "home-office"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:furniture:children-doing-homework-at-table", kind: "behaviour", description: "Children seated at the dining table doing homework — books open, pencils moving, the table serving its educational function as reliably as its mealtime one", emotionalSignal: "purposeful family space", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["children", "homework", "table", "family"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:furniture:sunday-family-dinner-full-table", kind: "behaviour", description: "A full family around the dining table — the table at capacity, every chair filled, the furniture doing exactly what it was chosen to do at the highest occasion", emotionalSignal: "familial completeness", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["sunday-dinner", "family", "full-table", "occasion"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "behaviour:furniture:polishing-wood-with-care", kind: "behaviour", description: "Person applying polish to a wood piece with a soft cloth — the circular motion, the grain direction followed, the patina being maintained and deepened over years", emotionalSignal: "caring stewardship", compatibleHeroes: ["lifestyle", "product", "person"], industryIds: ["furniture"], tags: ["polishing", "care", "grain", "patina"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:furniture:rearranging-room-layout-weekend", kind: "behaviour", description: "Weekend furniture rearranging — moving the sofa to the other wall, trying the chair in the corner, living with it for an hour before deciding it was better before", emotionalSignal: "creative domestic agency", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["rearranging", "weekend", "trying", "domestic"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:furniture:child-climbing-into-bunk-bed", kind: "behaviour", description: "Child climbing the ladder into their new bunk bed for the first time — the upper bunk reached, sitting on the edge looking down with proprietary delight", emotionalSignal: "childhood delight", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["furniture"], tags: ["bunk-bed", "ladder", "child", "upper-bunk"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:furniture:reading-in-well-lit-corner-chair", kind: "behaviour", description: "Person in an armchair in a well-lit corner reading — the chair angled toward the window, feet on an ottoman, entirely absorbed, the room organised around this one person's reading life", emotionalSignal: "satisfied habitual comfort", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["reading", "armchair", "corner", "absorbed"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:furniture:measuring-before-purchase-at-home", kind: "behaviour", description: "Person on the floor with a tape measure, measuring the space the new piece will occupy, the measurements being added to the shopping list", emotionalSignal: "responsible planning", compatibleHeroes: ["lifestyle", "person"], industryIds: ["furniture"], tags: ["measuring", "space", "planning", "home"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:furniture:evening-couple-sofa-together", kind: "behaviour", description: "A couple sharing a sofa in the evening — one at each end, legs tangled in the middle, the television on, comfortable enough to not need to speak", emotionalSignal: "domestic intimacy", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["couple", "evening", "sofa", "intimacy"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:furniture:assembling-flatpack-together", kind: "behaviour", description: "Two people assembling flat-pack furniture from instructions — one reading, one holding, occasional disagreement about which way a piece goes, the finished item a small shared achievement", emotionalSignal: "collaborative completion", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["furniture"], tags: ["flat-pack", "assembling", "together", "instructions"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:furniture:dog-claiming-corner-of-sofa", kind: "behaviour", description: "A dog settled in the corner of a sofa that is officially theirs now — the pet's ownership of the piece accepted and incorporated into the room's logic", emotionalSignal: "charming domestic acceptance", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["dog", "pet", "sofa-corner", "claimed"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:furniture:setting-dining-table-for-guests", kind: "behaviour", description: "Person setting a dining table before guests arrive — the tablecloth, the centrepiece, each place set with care, the table fulfilling its role as the frame for the occasion", emotionalSignal: "hospitable preparation", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["setting", "table", "guests", "hospitable"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:furniture:finding-exact-comfort-position", kind: "behaviour", description: "Person shifting and adjusting in a chair until the exact right position is found — the slight lean, the pillow repositioned, the foot placement changed until complete", emotionalSignal: "pursuit of perfect comfort", compatibleHeroes: ["lifestyle", "person"], industryIds: ["furniture"], tags: ["adjusting", "comfort-position", "perfect", "settling"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:furniture:styling-shelf-with-objects", kind: "behaviour", description: "Person arranging objects on a new shelf — books stacked horizontally and vertically, a plant at one end, a framed photo at the other, stepped back, adjusted, stepped back again", emotionalSignal: "creative arrangement", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["shelf", "styling", "objects", "creative"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:furniture:napping-on-sofa-afternoon", kind: "behaviour", description: "Person asleep on the sofa mid-afternoon — body completely given over to the piece, the cushion cradling the head naturally, the sofa fully equal to the task", emotionalSignal: "deep comfort", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["napping", "sofa", "afternoon", "deep-comfort"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:furniture:teenager-doing-homework-at-desk", kind: "behaviour", description: "Teenager at their own desk in their room doing homework — the desk theirs, the chair adjusted to their height, the space theirs for the first time", emotionalSignal: "ownership and growing up", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["furniture"], tags: ["teenager", "desk", "homework", "ownership"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:furniture:sitting-in-last-old-chair-before-it-goes", kind: "behaviour", description: "Person sitting in the old armchair one last time before the new one arrives — the farewell sit, acknowledging all the years the piece held them", emotionalSignal: "nostalgic farewell", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["furniture"], tags: ["old-chair", "farewell", "nostalgic", "last-time"], priority: 6, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:furniture:running-finger-along-dovetail-joint", kind: "behaviour", description: "Craftsperson or buyer running a fingertip along a dovetail joint — the interlocking geometry felt through touch, the quality of fit communicating decades of stability ahead", emotionalSignal: "craft reverence", compatibleHeroes: ["product", "person"], industryIds: ["furniture"], tags: ["dovetail", "joint", "finger", "craft"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:furniture:moving-into-first-home-furniture-day", kind: "behaviour", description: "Furniture arriving on moving-in day to a first home — the space still largely empty, the pieces making it suddenly real, the new life becoming physical with each piece placed", emotionalSignal: "life milestone made real", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["furniture"], tags: ["first-home", "moving-in", "milestone", "becoming-real"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "behaviour:furniture:toddler-discovering-sensory-drawer", kind: "behaviour", description: "A toddler discovering they can open and close a drawer repeatedly — the delight of cause and effect at the lowest possible volume, the furniture enabling a fundamental discovery", emotionalSignal: "childhood sensory joy", compatibleHeroes: ["lifestyle", "person"], industryIds: ["furniture"], tags: ["toddler", "drawer", "discovery", "cause-effect"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
];
