import type { CommercialSituationKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const FURNITURE_COMMERCIAL_SITUATIONS: CommercialSituationKnowledgeNode[] = [
  // ── New-home purchase trigger (12) ────────────────────────────────────────────
  { id: "commercial_situation:furniture:first-home-full-furnish", kind: "commercial_situation", situation: "First-time homeowners arriving at a showroom to furnish an entirely empty property — the highest-value single-occasion furniture purchase event", conversionMoment: "Multiple rooms furnished in one or a series of purchases — the new home requiring everything simultaneously", visualRepresentation: "Couple in showroom with floor plan measurements, prioritising room by room, consultant guiding selections across multiple categories", industryIds: ["furniture"], tags: ["first-home", "full-furnish", "couple", "multiple-rooms"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "commercial_situation:furniture:moving-to-larger-home-upgrade", kind: "commercial_situation", situation: "Family upsizing and the old furniture no longer fitting the new rooms — the upgrade occasion where quality increases with income and space", conversionMoment: "Existing pieces replaced with higher-spec options — the growth of the family's furniture footprint matching the growth of their home", visualRepresentation: "Family in showroom with photos of new bigger rooms, selecting statement pieces to match the upgrade in home quality", industryIds: ["furniture"], tags: ["upsizing", "upgrade", "family", "larger-home"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "commercial_situation:furniture:post-divorce-new-start-furnish", kind: "commercial_situation", situation: "Person furnishing a new place after separation — the emotionally loaded purchase of new pieces that are entirely their own, no compromises required", conversionMoment: "New pieces selected that express personal taste fully — the post-transition purchase with strong internal motivation", visualRepresentation: "Person alone in showroom, selecting confidently and specifically what they want, pieces representing a fresh start", industryIds: ["furniture"], tags: ["post-divorce", "fresh-start", "solo", "personal-taste"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "commercial_situation:furniture:new-baby-nursery-purchase", kind: "commercial_situation", situation: "First-time parents furnishing a nursery — the cot, the nursing chair, the changing table, the purchase driven by the arrival that changes the home's function entirely", conversionMoment: "Nursery set purchased and assembled before the birth — the preparation purchase with absolute deadline urgency", visualRepresentation: "Expectant couple measuring nursery space, selecting cot and nursing chair, the purchase timed to the due date", industryIds: ["furniture"], tags: ["nursery", "baby", "first-time-parents", "preparation"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "commercial_situation:furniture:student-first-flat-essentials", kind: "commercial_situation", situation: "Student or young person furnishing their first flat — price-sensitive but wanting to express themselves, the entry-level market with lifetime relationship potential", conversionMoment: "Essential pieces purchased on a budget — the first independent furniture purchase beginning the brand relationship", visualRepresentation: "Young person with measuring tape notes, selecting value-led pieces, first independent flat becoming theirs", industryIds: ["furniture"], tags: ["student", "first-flat", "essential", "budget"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:furniture:elderly-parent-downsizing", kind: "commercial_situation", situation: "An older person downsizing to a smaller home and needing scaled-down furniture that still feels quality — the child often helping choose the pieces", conversionMoment: "New appropriately-scaled pieces selected — the downsizing purchase, often facilitated by adult children", visualRepresentation: "Elderly parent and adult child in showroom, measuring smaller space requirements, choosing quality pieces that fit the new context", industryIds: ["furniture"], tags: ["downsizing", "elderly", "adult-child", "smaller-space"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── In-showroom upsell & conversion (15) ─────────────────────────────────────
  { id: "commercial_situation:furniture:sofa-upgrade-in-showroom", kind: "commercial_situation", situation: "Customer arriving for a mid-range sofa who sits in a premium model and cannot go back — the in-person experience creating the upgrade that no online channel could", conversionMoment: "Premium sofa selected over original budget choice — the physical experience justifying the upgrade spend", visualRepresentation: "Customer settled in premium sofa, associate explaining what's different, the mid-range sofa walked past without looking, the upgrade confirmed", industryIds: ["furniture"], tags: ["sofa", "upgrade", "in-person", "premium"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "commercial_situation:furniture:fabric-protection-plan-added", kind: "commercial_situation", situation: "Customer adding a fabric protection plan at the point of sofa purchase — the peace-of-mind add-on that makes the premium investment feel secure", conversionMoment: "Protection plan sold alongside sofa — attachment product increasing total transaction value", visualRepresentation: "Associate presenting protection plan options, family with children mentioned, the plan added to the order at the recommendation", industryIds: ["furniture"], tags: ["protection-plan", "fabric", "add-on", "family"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:furniture:matching-coffee-table-added", kind: "commercial_situation", situation: "Customer buying a sofa and then accepting the associate's suggestion to see the coordinating coffee table — the set completing naturally in the showroom", conversionMoment: "Coffee table added to sofa order — the set principle working at the point of the original sale", visualRepresentation: "Sofa chosen, associate guiding to coordinating table, customer seeing the room coming together, second piece added", industryIds: ["furniture"], tags: ["matching", "coffee-table", "coordinating", "set"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:furniture:room-design-consultation-conversion", kind: "commercial_situation", situation: "Customer using a free room design consultation service and ending up purchasing a complete room scheme — the consultation converting to the highest-value single sale", conversionMoment: "Full room scheme purchased after consultation — the service converting to multiple-piece acquisition", visualRepresentation: "Designer showing 3D room render, customer seeing the whole vision, full room scheme agreed rather than single piece", industryIds: ["furniture"], tags: ["design-consultation", "full-room", "scheme", "multiple-pieces"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "commercial_situation:furniture:customisation-upsell-fabric", kind: "commercial_situation", situation: "Customer choosing the standard fabric who is shown the premium options and upgrades the upholstery — the customisation moment that increases quality and revenue simultaneously", conversionMoment: "Premium fabric selected over standard — the customisation journey adding revenue while improving the customer's outcome", visualRepresentation: "Standard and premium swatches compared, premium texture evident, upgrade agreed, the sofa now exactly right", industryIds: ["furniture"], tags: ["fabric-upgrade", "customisation", "premium", "swatch"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:furniture:outdoor-furniture-seasonal-sale", kind: "commercial_situation", situation: "Customer discovering the outdoor furniture collection during a spring sale — the seasonal occasion creating urgency and enabling a purchase they were already considering", conversionMoment: "Garden set purchased at sale price with delivery timing meeting the summer", visualRepresentation: "Spring sale signage, customer discovering outdoor range, sale price enabling the decision that was pending, garden set selected", industryIds: ["furniture"], tags: ["outdoor", "seasonal-sale", "spring", "urgency"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },

  // ── Online to store & digital conversion (8) ─────────────────────────────────
  { id: "commercial_situation:furniture:online-research-to-showroom-visit", kind: "commercial_situation", situation: "Customer who researched online arriving at a showroom to experience the piece physically before committing — the omnichannel journey where digital starts but physical closes", conversionMoment: "Physical experience confirms online research and purchase is made in-store — the showroom converting the qualified online lead", visualRepresentation: "Customer arriving with phone saved images, finding the specific sofa, sitting in it and immediately confirming, purchase made", industryIds: ["furniture"], tags: ["online-to-store", "research", "physical-confirmation", "closing"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "commercial_situation:furniture:ar-app-room-visualisation", kind: "commercial_situation", situation: "Customer using an AR app to see furniture in their own room before ordering — the visualisation technology removing the biggest online furniture hesitation", conversionMoment: "Purchase completed after AR confirmation — the spatial visualisation removing doubt and enabling digital close", visualRepresentation: "Phone held up in living room, furniture appearing in the space, customer walking around the virtual piece, purchase made confident", industryIds: ["furniture"], tags: ["AR", "visualisation", "digital", "room-placement"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "commercial_situation:furniture:instagram-room-inspiration-to-purchase", kind: "commercial_situation", situation: "Customer discovering a room inspiration image on Instagram featuring identifiable furniture and clicking through to purchase the piece", conversionMoment: "Product purchase from social media inspiration — the styled room image converting through tagged product to sale", visualRepresentation: "Instagram room image with tagged products, tap on product, product page loading, purchase completed", industryIds: ["furniture"], tags: ["instagram", "inspiration", "room-image", "tagged"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:furniture:email-reminder-abandoned-cart", kind: "commercial_situation", situation: "Customer who left a sofa in their cart receiving a follow-up email with saved selections and a small delivery incentive — the abandonment sequence converting the consideration into commitment", conversionMoment: "Purchase completed from cart-recovery email — the follow-up converting the pre-committed customer", visualRepresentation: "Email showing saved sofa with free delivery offer, link clicked, cart returned to, purchase completed", industryIds: ["furniture"], tags: ["abandoned-cart", "email", "recovery", "incentive"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Loyalty & retention (15) ──────────────────────────────────────────────────
  { id: "commercial_situation:furniture:second-room-repeat-purchase", kind: "commercial_situation", situation: "Customer who bought a sofa returning to furnish another room with the same brand — the second room becoming the second relationship milestone", conversionMoment: "Second room furniture selected from existing brand — the brand trust extending beyond first purchase into repeat", visualRepresentation: "Existing customer returning, mentioning the first purchase, consultant noting the relationship, second room furnished", industryIds: ["furniture"], tags: ["repeat", "second-room", "brand-trust", "returning"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "commercial_situation:furniture:social-post-room-reveal-organic", kind: "commercial_situation", situation: "Customer posting their finished room with new furniture tagged — the before-and-after reveal that functions as the most authentic peer recommendation", conversionMoment: "Tagged social post driving new enquiries — the satisfied customer's organic content converting their followers", visualRepresentation: "Before-and-after room photos posted on social media with furniture brand tagged, comments asking where from", industryIds: ["furniture"], tags: ["social-post", "room-reveal", "organic", "before-after"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "commercial_situation:furniture:five-star-review-with-photo", kind: "commercial_situation", situation: "Customer posting a five-star review with photos of the delivered piece in their home — the authenticated quality evidence that new customers trust more than any advertising", conversionMoment: "Review with photos published — future customers converted by the authentic home evidence", visualRepresentation: "Review platform with multiple home photos attached, five stars, specific quality comments, others saving and sharing", industryIds: ["furniture"], tags: ["review", "five-star", "with-photos", "authentic"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "commercial_situation:furniture:lifetime-guarantee-reactivation", kind: "commercial_situation", situation: "Customer returning to use a lifetime or long-term guarantee for repair or replacement — the service commitment that brings the customer back and demonstrates brand confidence", conversionMoment: "Guarantee service provided — customer satisfaction maintained, brand loyalty reaffirmed, next purchase pre-committed", visualRepresentation: "Customer returning with minor defect, guarantee invoked without friction, repair or replacement arranged, loyalty deepened", industryIds: ["furniture"], tags: ["guarantee", "lifetime", "return", "loyalty"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:furniture:recommending-to-friend-buying-home", kind: "commercial_situation", situation: "Existing customer recommending the furniture store to a friend who just bought a house — the moment the personal advocacy creates a new high-intent lead", conversionMoment: "Referred friend becomes a new customer — the referral chain from satisfied customer to equally motivated new buyer", visualRepresentation: "Two friends, one who owns the furniture and one about to furnish a new home, recommendation made, new customer visiting the store", industryIds: ["furniture"], tags: ["referral", "friend", "new-homeowner", "advocacy"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
];
