import type { EmotionalMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const FURNITURE_EMOTIONAL_MOMENTS: EmotionalMomentKnowledgeNode[] = [
  // ── Arrival & first-use peaks (15) ────────────────────────────────────────────
  { id: "emotional_moment:furniture:family-piling-onto-new-sofa", kind: "emotional_moment", moment: "The delivery team leave and the family piles onto the new sofa all at once — children jumping, parents landing beside them, laughter filling the room as the piece takes its first full weight", emotionType: "collective joy", visualSignals: ["multiple people landing simultaneously", "cushions displacing under weight", "laughter visible in every face", "the room momentarily chaotic in the best way"], industryIds: ["furniture"], tags: ["family", "pile-on", "delivery", "collective-joy"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:furniture:first-sleep-new-mattress-peace", kind: "emotional_moment", moment: "Waking after the first night on a new mattress — the particular quality of having slept well that is felt before the eyes open, the body already knowing", emotionType: "deep restorative relief", visualSignals: ["slow waking", "the stillness of someone who slept without interruption", "stretching arms wide into available space", "the satisfied exhale before rising"], industryIds: ["furniture"], tags: ["first-sleep", "mattress", "waking", "restorative"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:furniture:child-first-night-big-bed", kind: "emotional_moment", moment: "A child's first night in a big bed — the parent watching from the door as the child settles into the larger space, pride and tenderness in equal measure", emotionType: "milestone pride and tenderness", visualSignals: ["child spread in large bed", "parent at doorway watching", "the smallness of the child in the bigger space", "the quiet of the watching"], industryIds: ["furniture"], tags: ["child", "first-big-bed", "parent", "milestone"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:furniture:stepping-back-to-see-furnished-room", kind: "emotional_moment", moment: "Stepping back to see a newly furnished room for the first time — all pieces in place, the room finally itself, the realisation that this is exactly what was imagined and it worked", emotionType: "creative satisfaction and arrival", visualSignals: ["person pausing in doorway", "head tilting to take it all in", "the slow nod", "a quiet yes in the expression"], industryIds: ["furniture"], tags: ["stepping-back", "room-complete", "satisfaction", "arrival"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:furniture:unwrapping-dining-table-delivery", kind: "emotional_moment", moment: "Pulling the last of the transit packaging off a new dining table and seeing its surface in full — the grain catching the light, the piece so much better than the website suggested", emotionType: "delighted relief", visualSignals: ["packaging falling away", "surface revealed in sections", "hands touching the wood", "looking at partner or delivery team with delight"], industryIds: ["furniture"], tags: ["unwrapping", "dining-table", "delivery", "surface-reveal"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:furniture:moving-into-first-home-furniture-arrives", kind: "emotional_moment", moment: "Furniture arriving on moving-into-first-home day — the empty space suddenly containing something, the new life becoming real as each piece is placed", emotionType: "life beginning", visualSignals: ["empty room gaining pieces", "couple or person touching first piece placed", "the room transforming with each addition", "the unrepeatable emotion of the first time"], industryIds: ["furniture"], tags: ["first-home", "moving-in", "becoming-real", "life-beginning"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },

  // ── Comfort & domesticity peaks (15) ──────────────────────────────────────────
  { id: "emotional_moment:furniture:finding-the-reading-position", kind: "emotional_moment", moment: "The moment of finding the perfect reading position in an armchair — the pillow adjusted once, the feet up, the lamp exactly right, the book opening, nothing to change", emotionType: "perfect comfort found", visualSignals: ["final small adjustments", "body going still", "book opening", "the face relaxing into reading"], industryIds: ["furniture"], tags: ["reading", "armchair", "perfect-position", "stillness"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:furniture:couple-evening-sofa-silence", kind: "emotional_moment", moment: "A couple sharing a sofa in the evening with the television on but neither really watching — comfortable enough to be together in silence, the sofa holding both of them without effort", emotionType: "domestic intimacy and ease", visualSignals: ["both reclining", "legs tangled", "neither speaking but both present", "the room quiet and warm"], industryIds: ["furniture"], tags: ["couple", "evening", "silence", "ease"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:furniture:sunday-full-family-dinner-table", kind: "emotional_moment", moment: "A Sunday dinner with every chair filled — the table doing its highest function, multiple conversations running, the furniture making the occasion possible", emotionType: "familial abundance", visualSignals: ["every chair occupied", "multiple conversations visible", "food across the table", "the table at full capacity"], industryIds: ["furniture"], tags: ["sunday-dinner", "full-table", "family", "abundance"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:furniture:nap-on-sofa-afternoon-permission", kind: "emotional_moment", moment: "Falling asleep unexpectedly on the sofa mid-afternoon — the body giving in to the comfort before the mind agreed, the sofa doing what a good sofa does", emotionType: "surrendered comfort", visualSignals: ["body fully horizontal", "book or remote dropped", "face completely at rest", "the depth of unconscious ease"], industryIds: ["furniture"], tags: ["nap", "sofa", "afternoon", "surrendered"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:furniture:morning-coffee-routine-established", kind: "emotional_moment", moment: "The morning the new furniture becomes routine — the same chair, the same cup, the light through the same window, the piece no longer new but now entirely familiar and essential", emotionType: "settled belonging", visualSignals: ["person in same position as always now", "coffee cup familiar in hand", "the ease of a settled routine", "the furniture fully absorbed into the life"], industryIds: ["furniture"], tags: ["morning-routine", "established", "belonging", "familiar"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Gifting & milestone peaks (10) ────────────────────────────────────────────
  { id: "emotional_moment:furniture:parents-surprising-child-with-new-room", kind: "emotional_moment", moment: "Parents revealing a newly furnished child's room — the door opened, the child's face transforming from uncertainty to disbelief to delight, the room far beyond what they hoped for", emotionType: "disbelief becoming delight", visualSignals: ["child standing in doorway speechless", "parents watching from behind", "eyes moving across every detail", "the moment before they run inside"], industryIds: ["furniture"], tags: ["parents", "child", "room-reveal", "disbelief"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:furniture:heirloom-piece-arrives-in-new-home", kind: "emotional_moment", moment: "An inherited piece of furniture arriving in a new home — the object carrying someone's absence as much as their presence, being placed carefully where it will live next", emotionType: "grief and continuation", visualSignals: ["careful handling of the piece", "pause before final placement", "touching the surface with specific tenderness", "the room changed by the addition"], industryIds: ["furniture"], tags: ["heirloom", "arriving", "inherited", "grief-and-continuation"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:furniture:assembled-furniture-shared-achievement", kind: "emotional_moment", moment: "The moment flat-pack furniture is finally assembled and standing — the stepping back of two people who built something together, one arm around the other, looking at what they did", emotionType: "shared accomplishment", visualSignals: ["couple side by side looking at assembled piece", "one arm around the other", "the piece standing correctly", "instructions on the floor behind them"], industryIds: ["furniture"], tags: ["assembled", "flat-pack", "together", "accomplishment"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Craft & quality appreciation peaks (10) ───────────────────────────────────
  { id: "emotional_moment:furniture:running-hand-across-grain-revelation", kind: "emotional_moment", moment: "Running a hand across a solid wood surface and feeling the grain for the first time — the warmth of it, the texture, the realisation that this is different from everything else they have owned", emotionType: "material revelation", visualSignals: ["hand moving slowly across surface", "fingers pausing at the grain direction", "slight intake of breath", "looking up with the expression of someone whose benchmark just moved"], industryIds: ["furniture"], tags: ["grain", "hand", "solid-wood", "revelation"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:furniture:craftsperson-finishing-final-piece", kind: "emotional_moment", moment: "A furniture maker applying the final finish to a commissioned piece — the last pass of the cloth, stepping back, the object now complete and ready to leave the workshop", emotionType: "maker's pride and release", visualSignals: ["final cloth pass on surface", "stepping back from the bench", "the maker looking at the whole piece", "the quiet satisfaction of done"], industryIds: ["furniture"], tags: ["craftsperson", "final-finish", "pride", "complete"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:furniture:old-chair-repaired-to-original", kind: "emotional_moment", moment: "A beloved old chair returned from restoration — the broken leg repaired, the fabric reupholstered, the piece restored to its original self as if the damage never happened", emotionType: "restoration and renewed attachment", visualSignals: ["chair placed in its usual spot", "hand touching the repaired area", "sitting in it carefully at first", "the relief of having it back intact"], industryIds: ["furniture"], tags: ["restored", "chair", "reupholstered", "renewal"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
];
