import type { RelationshipKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const FURNITURE_RELATIONSHIPS: RelationshipKnowledgeNode[] = [
  // ── Family relationships with furniture (15) ──────────────────────────────────
  { id: "relationship:furniture:couple-choosing-first-home-pieces", kind: "relationship", description: "A couple choosing furniture for their first shared home — negotiating preferences, finding pieces that speak for both of them, the furniture becoming the first shared grammar of their life together", sceneRoles: ["couple"], industryIds: ["furniture"], tags: ["couple", "first-home", "negotiating", "shared"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "relationship:furniture:parent-child-cot-to-big-bed", kind: "relationship", description: "The transition from cot to first big bed — a parent and child together at this milestone, the furniture marking the developmental moment of growing up", sceneRoles: ["parent", "child"], industryIds: ["furniture"], tags: ["parent", "child", "cot", "big-bed", "milestone"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:furniture:grandparent-and-grandchild-in-favourite-chair", kind: "relationship", description: "A grandparent in their particular armchair with a grandchild perched on the arm or at their feet — the chair as the location of a specific inter-generational relationship", sceneRoles: ["grandparent", "grandchild"], industryIds: ["furniture"], tags: ["grandparent", "grandchild", "armchair", "intergenerational"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:furniture:family-around-the-dining-table", kind: "relationship", description: "A family gathered at the dining table — the table as the room where the family becomes itself, where significant conversations happen alongside ordinary ones", sceneRoles: ["family members"], industryIds: ["furniture"], tags: ["family", "dining-table", "gathering", "centre"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "relationship:furniture:siblings-sharing-bunk-beds", kind: "relationship", description: "Siblings in bunk beds — the negotiation of who gets the top bunk, the rituals developed in the shared space, the furniture enabling the particular closeness of room-sharing", sceneRoles: ["siblings"], industryIds: ["furniture"], tags: ["siblings", "bunk-beds", "sharing", "closeness"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:furniture:parents-choosing-children-room-furniture", kind: "relationship", description: "Parents planning a child's room — measuring, choosing, the furniture expressing the parents' vision of who this child is and who they might become", sceneRoles: ["parents", "child"], industryIds: ["furniture"], tags: ["parents", "planning", "childs-room", "vision"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },

  // ── Social & hosting relationships (12) ───────────────────────────────────────
  { id: "relationship:furniture:host-and-guests-at-dinner-table", kind: "relationship", description: "Host and guests gathered at a dining table — the host who chose and arranged the furniture creating the frame for the gathering that others experience", sceneRoles: ["host", "dinner guests"], industryIds: ["furniture"], tags: ["host", "guests", "dinner-table", "frame"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:furniture:friends-gathered-on-corner-sofa", kind: "relationship", description: "Friends occupying a corner sofa together — each in their place, the large sofa accommodating the whole group, the furniture that was always big enough now proven so", sceneRoles: ["friend group"], industryIds: ["furniture"], tags: ["friends", "corner-sofa", "gathering", "accommodating"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:furniture:new-flatmates-decorating-together", kind: "relationship", description: "New flatmates choosing shared furniture — the negotiation of different aesthetics, the compromise piece that turns out to be the best in the flat", sceneRoles: ["flatmates"], industryIds: ["furniture"], tags: ["flatmates", "shared", "decorating", "compromise"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:furniture:neighbours-admiring-garden-furniture", kind: "relationship", description: "Neighbours leaning over a garden fence admiring new garden furniture — the social approval of the outdoor setup, the conversation starting around the new purchase", sceneRoles: ["homeowner", "neighbours"], industryIds: ["furniture"], tags: ["neighbours", "garden-furniture", "admiring", "social"], priority: 5, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },

  // ── Professional & craft relationships (12) ───────────────────────────────────
  { id: "relationship:furniture:interior-designer-client", kind: "relationship", description: "An interior designer and a client choosing furniture together — the professional's expertise translating the client's feeling into specific pieces, each recommendation a bridge between vision and reality", sceneRoles: ["interior designer", "client"], industryIds: ["furniture"], tags: ["designer", "client", "expertise", "translating-vision"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:furniture:craftsperson-and-commissioner", kind: "relationship", description: "A furniture maker and the person who commissioned a bespoke piece — the trust of handing the vision to skilled hands, the collection being the proof the trust was earned", sceneRoles: ["craftsperson", "commissioner"], industryIds: ["furniture"], tags: ["craftsperson", "commission", "bespoke", "trust"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:furniture:showroom-consultant-first-home-buyer", kind: "relationship", description: "A showroom consultant with a first-time furniture buyer — navigating overwhelm, identifying the specific need beneath the browsing, finding the right first pieces for a new life", sceneRoles: ["showroom consultant", "first-time buyer"], industryIds: ["furniture"], tags: ["consultant", "first-home-buyer", "navigating", "first-pieces"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:furniture:woodworker-apprentice-master", kind: "relationship", description: "A master woodworker and their apprentice — the passing of technique, the correction of a joint, the shared silence over a piece coming together correctly", sceneRoles: ["master craftsperson", "apprentice"], industryIds: ["furniture"], tags: ["woodworker", "apprentice", "master", "technique"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:furniture:estate-sale-buyer-previous-family", kind: "relationship", description: "A buyer acquiring furniture from an estate sale — the pieces moving from one family's story to another, the buyer sometimes knowing and sometimes not knowing what they are inheriting", sceneRoles: ["new buyer", "previous family"], industryIds: ["furniture"], tags: ["estate-sale", "inheritance", "story-carrying", "new-buyer"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── Object-person relationships (11) ──────────────────────────────────────────
  { id: "relationship:furniture:person-and-their-chair", kind: "relationship", description: "The private relationship between a person and the specific chair that is theirs — the one others know not to sit in, the one that holds the shape of their sitting over years", sceneRoles: ["person", "their-chair"], industryIds: ["furniture"], tags: ["personal-chair", "ownership", "shape", "years"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "relationship:furniture:heirloom-furniture-new-generation", kind: "relationship", description: "An heirloom furniture piece being passed down or incorporated into a new home — the old piece in the new context, carrying the previous generation with it", sceneRoles: ["heirloom piece", "new owner"], industryIds: ["furniture"], tags: ["heirloom", "passed-down", "previous-generation", "new-home"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:furniture:desk-and-its-owner-over-decades", kind: "relationship", description: "A person and their desk over many years — the drawer that always sticks, the mark they made in 2009, the desk that has held their entire working life in its surface", sceneRoles: ["person", "desk"], industryIds: ["furniture"], tags: ["desk", "decades", "working-life", "history"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:furniture:the-house-the-furniture-made-a-home", kind: "relationship", description: "The transformation of a house into a home through the specific furniture that went into it — the pieces that turned the empty space into a place that means something", sceneRoles: ["homeowner", "home"], industryIds: ["furniture"], tags: ["house-to-home", "transformation", "meaning", "specific-pieces"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
];
