import type { EmotionalMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const REAL_ESTATE_EMOTIONAL_MOMENTS: EmotionalMomentKnowledgeNode[] = [
  // ── Purchase milestones (20) ───────────────────────────────────────────────
  { id: "emotional_moment:real_estate:offer-accepted-call-reaction", kind: "emotional_moment", moment: "Buyer receiving the call from their agent to say the offer has been accepted — phone to ear, then hand covering mouth", emotionType: "elation", visualSignals: ["hand over mouth", "eyes wide", "sitting down suddenly", "tears forming"], industryIds: ["real-estate"], tags: ["offer-accepted", "phone-call", "joy", "elation"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "emotional_moment:real_estate:keys-received-on-moving-day", kind: "emotional_moment", moment: "Keys placed into new owner's palm on moving day — the weight of the keys and what they represent settling together", emotionType: "pride", visualSignals: ["looking down at keys", "slow smile building", "closing fingers around them", "eyes glistening"], industryIds: ["real-estate"], tags: ["keys", "moving-day", "pride", "ownership"], priority: 2, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:real_estate:first-walk-empty-new-home", kind: "emotional_moment", moment: "New owner walking through their empty property for the first time — footsteps echoing in bare rooms, pausing in each space", emotionType: "wonder", visualSignals: ["slow turning in room", "hands trailing walls", "pausing at window to look out", "quiet smile"], industryIds: ["real-estate"], tags: ["empty-home", "first-walk", "wonder", "new-beginning"], priority: 3, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:real_estate:completion-day-at-solicitor", kind: "emotional_moment", moment: "Buyer signing final document at solicitor's desk and the solicitor saying 'Congratulations, you own the property'", emotionType: "joy", visualSignals: ["pen set down", "leaning back", "exhaling", "face transforming from focus to wide smile"], industryIds: ["real-estate"], tags: ["completion", "solicitor", "joy", "official"], priority: 4, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:real_estate:dream-home-found-after-long-search", kind: "emotional_moment", moment: "Stepping into the property after a long search and immediately knowing this is the one — the feeling arriving before thought", emotionType: "recognition", visualSignals: ["pause at entrance", "hands clasped", "slow turn to partner", "eyes communicating without words"], industryIds: ["real-estate"], tags: ["dream-home", "recognition", "long-search", "certainty"], priority: 5, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:real_estate:above-asking-sale-price-received", kind: "emotional_moment", moment: "Seller receiving call from agent confirming sale above asking price — the number better than hoped, stunned delight", emotionType: "surprise-and-joy", visualSignals: ["sitting forward", "head shaking slowly", "hand to forehead", "laughing with disbelief"], industryIds: ["real-estate"], tags: ["above-asking", "seller", "surprise", "delight"], priority: 6, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:real_estate:agent-delivering-sold-news", kind: "emotional_moment", moment: "Agent calling vendor to say the property has been sold — the news delivered, the seller's reaction immediate and genuine", emotionType: "relief-and-joy", visualSignals: ["eyes closing with relief", "hand on heart", "exhaling visibly", "smile returning"], industryIds: ["real-estate"], tags: ["sold-news", "agent", "vendor", "relief"], priority: 7, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:real_estate:below-asking-offer-accepted", kind: "emotional_moment", moment: "Buyer hearing their below-asking offer has been accepted — quiet, contained joy, the financial saving fully landing", emotionType: "satisfaction", visualSignals: ["quiet smile", "nodding slowly", "looking at partner", "relief visible in body releasing tension"], industryIds: ["real-estate"], tags: ["below-asking", "accepted", "satisfaction", "value"], priority: 8, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:real_estate:exchange-of-contracts-relief", kind: "emotional_moment", moment: "Solicitor confirming exchange — buyer's face moving from weeks of anxiety to sudden, complete relief", emotionType: "relief", visualSignals: ["long exhale", "eyes closing briefly", "shoulders dropping", "soft laugh of relief"], industryIds: ["real-estate"], tags: ["exchange", "relief", "anxiety-released", "milestone"], priority: 9, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:real_estate:mortgage-approval-emotion", kind: "emotional_moment", moment: "First-time buyer reading mortgage approval notification on phone — disbelief then joyous reality flooding in", emotionType: "disbelief-turning-to-joy", visualSignals: ["rereading screen", "looking up at sky", "tears on cheeks", "hand pressed to chest"], industryIds: ["real-estate"], tags: ["mortgage-approval", "first-time-buyer", "tears", "disbelief"], priority: 10, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:real_estate:property-passed-next-generation", kind: "emotional_moment", moment: "Family home passed to the next generation — older parent handing keys to adult child who grew up there", emotionType: "generational-pride", visualSignals: ["keys exchanged between generations", "parent holding adult child's hands around keys", "tears from older generation", "younger smiling through emotion"], industryIds: ["real-estate"], tags: ["generational", "family-home", "keys-passed", "legacy"], priority: 11, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:real_estate:first-night-sleep-new-home", kind: "emotional_moment", moment: "Family waking up on first morning in new home — the light through curtainless windows, the unfamiliar sounds, the profound rightness", emotionType: "belonging", visualSignals: ["waking slowly", "unfamiliar ceiling above", "quiet smile", "reaching for partner"], industryIds: ["real-estate"], tags: ["first-night", "waking", "belonging", "new-home"], priority: 12, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "emotional_moment:real_estate:gifted-deposit-received", kind: "emotional_moment", moment: "First-time buyer receiving cheque for gifted deposit from parent — generosity and love in a single piece of paper", emotionType: "gratitude", visualSignals: ["holding cheque carefully", "eyes bright", "reaching to hug parent", "both emotional"], industryIds: ["real-estate"], tags: ["gifted-deposit", "gratitude", "parent", "generational-love"], priority: 13, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:real_estate:buying-childhood-home", kind: "emotional_moment", moment: "Adult buyer standing outside the house they grew up in, now holding the keys as the new owner — full circle", emotionType: "nostalgia-and-joy", visualSignals: ["looking up at childhood windows", "running hand along childhood fence", "overwhelmed expression", "slow smile"], industryIds: ["real-estate"], tags: ["childhood-home", "full-circle", "nostalgia", "profound"], priority: 14, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:real_estate:gazumped-then-found-better", kind: "emotional_moment", moment: "Buyer who was gazumped finding a better property shortly after — disappointment transformed into gratitude for the redirection", emotionType: "redemption", visualSignals: ["entering better property with cautious hope", "then recognition dawning", "eyes lighting up", "composure giving way to quiet delight"], industryIds: ["real-estate"], tags: ["gazumped", "redirected", "better-property", "redemption"], priority: 15, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:real_estate:self-build-completed", kind: "emotional_moment", moment: "Self-builder standing inside completed home they designed and built — every room carries memory of the decision to build it", emotionType: "profound-achievement", visualSignals: ["slow turn in living room", "touching walls they built", "tears of accomplishment", "sitting on floor overwhelmed"], industryIds: ["real-estate"], tags: ["self-build", "achievement", "completion", "profound"], priority: 16, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:real_estate:renovation-potential-realised", kind: "emotional_moment", moment: "Investor viewing a tired property and suddenly seeing the entire potential — before vision and after reality both clear simultaneously", emotionType: "creative-clarity", visualSignals: ["pausing in dated kitchen", "eyes scanning upward", "nodding slowly", "turning to agent with knowing look"], industryIds: ["real-estate"], tags: ["renovation", "vision", "potential", "clarity"], priority: 17, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:real_estate:right-to-buy-approved", kind: "emotional_moment", moment: "Long-term council tenant receiving right-to-buy approval — the council home they have lived in for years now theirs to own", emotionType: "disbelief-and-pride", visualSignals: ["reading approval letter twice", "looking around familiar home with new eyes", "quiet tears", "hand on familiar wall now owned"], industryIds: ["real-estate"], tags: ["right-to-buy", "approval", "transformation", "pride"], priority: 18, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "emotional_moment:real_estate:planning-permission-granted", kind: "emotional_moment", moment: "Homeowner opening planning permission approval — months of waiting over, extension or development now able to proceed", emotionType: "relief-and-excitement", visualSignals: ["letter held up", "reading confirmation", "fist pump", "immediately calling builder"], industryIds: ["real-estate"], tags: ["planning-permission", "approval", "relief", "excitement"], priority: 19, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:real_estate:chain-completion-all-moved", kind: "emotional_moment", moment: "All parties in a property chain completing on the same day — the domino of moves completing, everyone in their new home by evening", emotionType: "collective-relief", visualSignals: ["agent on final confirmation call", "buyer collapsing into chair with relief", "family hugging in new hallway", "exhausted smiles"], industryIds: ["real-estate"], tags: ["chain", "completion", "collective-relief", "same-day"], priority: 20, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },

  // ── Search & discovery emotions (15) ──────────────────────────────────────
  { id: "emotional_moment:real_estate:first-viewing-right-feeling", kind: "emotional_moment", moment: "Walking into a property on first viewing and knowing immediately — before rooms are seen, before price is discussed", emotionType: "intuitive-recognition", visualSignals: ["pause at the front door", "eyes widening", "breath catching slightly", "looking to partner with raised eyebrow"], industryIds: ["real-estate"], tags: ["first-viewing", "intuition", "recognition", "knowing"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:real_estate:property-portal-notification", kind: "emotional_moment", moment: "Property portal notification arriving for a new listing matching saved search — the possibility in a single notification", emotionType: "anticipation", visualSignals: ["notification seen on phone", "sitting forward to read", "scrolling through photos quickly", "showing screen to partner"], industryIds: ["real-estate"], tags: ["portal", "notification", "anticipation", "discovery"], priority: 2, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "emotional_moment:real_estate:long-search-finally-ending", kind: "emotional_moment", moment: "Buyer after months of searching closing their laptop having accepted an offer — the search over, the journey completed", emotionType: "exhausted-relief", visualSignals: ["laptop closed with finality", "leaning back in chair", "long exhale", "quiet stillness after much activity"], industryIds: ["real-estate"], tags: ["long-search", "ending", "relief", "exhaustion"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:real_estate:rival-bidder-drops-out", kind: "emotional_moment", moment: "Buyer learning their only rival bidder has withdrawn — the competition gone, the property now theirs if they want it", emotionType: "hope-becoming-certainty", visualSignals: ["eyes closing with relief", "sitting forward with renewed energy", "calling partner immediately"], industryIds: ["real-estate"], tags: ["rival-bidder", "withdrawn", "relief", "opportunity"], priority: 4, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "emotional_moment:real_estate:survey-concerns-resolved", kind: "emotional_moment", moment: "Buyer receiving reassurance that survey concerns are minor and not deal-breaking — anxiety that built over days dissolving", emotionType: "relief", visualSignals: ["reading report section again", "nodding as concern dissolves", "calling partner with reassurance", "visible release of tension"], industryIds: ["real-estate"], tags: ["survey", "concerns-resolved", "relief", "reassurance"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:real_estate:new-development-plot-chosen", kind: "emotional_moment", moment: "Couple choosing their plot on the development site plan — the abstract home becoming their home in one pointing gesture", emotionType: "excited-commitment", visualSignals: ["finger tracing plot boundary", "looking at each other for confirmation", "smiling agreement", "nodding to sales consultant"], industryIds: ["real-estate"], tags: ["new-build", "plot-chosen", "excitement", "commitment"], priority: 6, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "emotional_moment:real_estate:new-neighbourhood-love-at-sight", kind: "emotional_moment", moment: "Buyers walking new neighbourhood for first time and feeling the instant rightness of the area — location chosen", emotionType: "belonging-anticipated", visualSignals: ["slowing to look at café or park", "commenting to partner", "looking down street with soft eyes", "turning to say 'I could live here'"], industryIds: ["real-estate"], tags: ["neighbourhood", "love-at-first-sight", "belonging", "location"], priority: 7, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "emotional_moment:real_estate:unexpected-multiple-offers", kind: "emotional_moment", moment: "Agent calling seller to say multiple offers have come in — the property more wanted than expected, a wonderful problem", emotionType: "pleasantly-overwhelmed", visualSignals: ["sitting up straighter", "head shaking in disbelief", "smile growing", "asking agent to repeat the number"], industryIds: ["real-estate"], tags: ["multiple-offers", "seller", "demand", "pleasantly-surprised"], priority: 8, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:real_estate:sealed-bid-winner-shock", kind: "emotional_moment", moment: "Sealed bid winner receiving the call — having submitted their best and final figure, hearing they have won at that price", emotionType: "shock-and-elation", visualSignals: ["standing up suddenly", "other hand slapping desk", "face crumpling with emotion", "immediately hugging whoever is nearby"], industryIds: ["real-estate"], tags: ["sealed-bid", "winner", "shock", "elation"], priority: 9, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:real_estate:auction-win-gavel", kind: "emotional_moment", moment: "Bidder watching gavel fall on their winning bid — the room quiet for a second, then looking around in disbelief", emotionType: "disbelief-then-triumph", visualSignals: ["watching gavel fall", "looking left and right", "fist pump contained", "eyes glistening"], industryIds: ["real-estate"], tags: ["auction", "gavel", "winning", "triumph"], priority: 10, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:real_estate:first-rental-income", kind: "emotional_moment", moment: "Buy-to-let investor seeing first rental payment cleared in their account — the investment beginning to deliver, the plan working", emotionType: "validation", visualSignals: ["checking phone with app open", "number settling in", "quiet nod", "slight smile of validation"], industryIds: ["real-estate"], tags: ["btl", "rental-income", "validation", "investment-working"], priority: 11, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "emotional_moment:real_estate:capital-appreciation-recognised", kind: "emotional_moment", moment: "Homeowner receiving new valuation showing significant appreciation above their purchase price — wealth quietly created", emotionType: "quiet-satisfaction", visualSignals: ["comparing valuation to purchase price on screen", "settling back", "slow smile", "calling to share news"], industryIds: ["real-estate"], tags: ["capital-appreciation", "valuation", "wealth", "satisfaction"], priority: 12, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "emotional_moment:real_estate:long-chain-collapse-then-rescue", kind: "emotional_moment", moment: "Long chain collapsed but chain-free alternative found within 48 hours — the devastation of collapse replaced by relief of resolution", emotionType: "rescue-relief", visualSignals: ["initial despair at news", "then agent calling back with chain-free alternative", "face transforming", "gratitude overwhelming"], industryIds: ["real-estate"], tags: ["chain-collapse", "rescue", "relief", "chain-free"], priority: 13, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:real_estate:probate-sale-family-relief", kind: "emotional_moment", moment: "Family completing sale of inherited property — grief and practicality resolved together, the estate administered, all moving forward", emotionType: "complex-relief", visualSignals: ["signing final document", "family members glancing at each other", "collective exhale", "one member reaching to hold another's hand"], industryIds: ["real-estate"], tags: ["probate", "family", "relief", "closure"], priority: 14, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "emotional_moment:real_estate:downsizing-equity-realised", kind: "emotional_moment", moment: "Retired couple receiving sale proceeds and calculating their downsizing equity for the first time — freedom found in the numbers", emotionType: "freedom", visualSignals: ["looking at the figures together", "one squeezing the other's hand", "smiling at the future visible in numbers", "looking up with plans forming"], industryIds: ["real-estate"], tags: ["downsizing", "equity", "freedom", "retirement"], priority: 15, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
];
