import type { RelationshipKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const REAL_ESTATE_RELATIONSHIPS: RelationshipKnowledgeNode[] = [
  // ── Agent & buyer (12) ────────────────────────────────────────────────────
  { id: "relationship:real_estate:agent-and-first-time-buyer", kind: "relationship", description: "Estate agent guiding first-time buyer through the process — patience, education, trust built across multiple viewings", sceneRoles: ["estate agent", "first-time buyer"], industryIds: ["real-estate"], tags: ["first-time-buyer", "agent", "trust", "guidance"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "relationship:real_estate:couple-buying-together", kind: "relationship", description: "Couple joint-purchasing a property — aligned goals, shared decision-making, buying as a unit with the agent managing both", sceneRoles: ["buyer A", "buyer B"], industryIds: ["real-estate"], tags: ["couple", "joint-purchase", "aligned", "life-decision"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:real_estate:agent-and-cash-buyer", kind: "relationship", description: "Estate agent working with chain-free cash buyer — speed and certainty changing the negotiation dynamic", sceneRoles: ["estate agent", "cash buyer"], industryIds: ["real-estate"], tags: ["cash-buyer", "agent", "chain-free", "speed"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:real_estate:investor-and-agent", kind: "relationship", description: "Property investor working with specialist agent — yield-focused conversation, portfolio discussed, professional to professional", sceneRoles: ["investor", "estate agent"], industryIds: ["real-estate"], tags: ["investor", "agent", "yield", "portfolio"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:real_estate:buyer-and-home-surveyor", kind: "relationship", description: "Buyer and home surveyor discussing survey findings — technical report translated into practical implications", sceneRoles: ["buyer", "surveyor"], industryIds: ["real-estate"], tags: ["buyer", "surveyor", "report", "due-diligence"], priority: 5, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:real_estate:expat-buyer-and-local-agent", kind: "relationship", description: "Expat buyer purchasing property remotely with trusted local agent — video calls, area knowledge, proxy representation", sceneRoles: ["expat buyer", "local agent"], industryIds: ["real-estate"], tags: ["expat", "remote-buyer", "local-agent", "trust"], priority: 6, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:real_estate:agent-and-competing-buyers", kind: "relationship", description: "Agent managing two competing buyers for same property — professional impartiality, sealed bids or negotiation managed fairly", sceneRoles: ["estate agent", "buyer A", "buyer B"], industryIds: ["real-estate"], tags: ["competition", "multiple-buyers", "agent", "management"], priority: 7, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:real_estate:family-upsizing-simultaneous-sale", kind: "relationship", description: "Family selling and buying simultaneously — agent managing both sides, chain stress, the balance of timing", sceneRoles: ["agent", "selling family", "upsizing property vendor"], industryIds: ["real-estate"], tags: ["upsizing", "simultaneous", "chain", "family"], priority: 8, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:real_estate:single-parent-first-time-buyer-with-agent", kind: "relationship", description: "Single parent buying first home with agent — emotional weight of the purchase, child's future at the centre of every decision", sceneRoles: ["estate agent", "single parent buyer"], industryIds: ["real-estate"], tags: ["single-parent", "first-time-buyer", "agent", "emotional"], priority: 9, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:real_estate:long-distance-buyer-and-agent", kind: "relationship", description: "Buyer relocating from another city working with agent over video calls, trusting professional knowledge of local market", sceneRoles: ["relocating buyer", "local agent"], industryIds: ["real-estate"], tags: ["relocation", "long-distance", "video-call", "trust"], priority: 10, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:real_estate:buyer-and-seller-handshake", kind: "relationship", description: "Buyer and seller meeting at handshake moment when offer is accepted — two lives intersecting at a property transaction", sceneRoles: ["buyer", "seller"], industryIds: ["real-estate"], tags: ["buyer", "seller", "handshake", "offer-accepted"], priority: 11, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:real_estate:agent-recommended-by-friend", kind: "relationship", description: "Agent meeting new vendor who was referred by a past client — trust pre-established, relationship warm from first call", sceneRoles: ["estate agent", "referred vendor"], industryIds: ["real-estate"], tags: ["referral", "agent", "trust", "warm-lead"], priority: 12, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Solicitor & legal (8) ─────────────────────────────────────────────────
  { id: "relationship:real_estate:solicitor-and-buyer-at-completion", kind: "relationship", description: "Solicitor and buyer at completion — professional guiding their client through the final legal milestone of property ownership", sceneRoles: ["conveyancing solicitor", "buyer"], industryIds: ["real-estate"], tags: ["solicitor", "completion", "legal", "guidance"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:real_estate:two-solicitors-at-exchange", kind: "relationship", description: "Buyer's solicitor and seller's solicitor at exchange of contracts — professional counterparts completing the legal process", sceneRoles: ["buyer's solicitor", "seller's solicitor"], industryIds: ["real-estate"], tags: ["solicitors", "exchange", "legal", "counterparts"], priority: 2, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:real_estate:executor-and-probate-solicitor", kind: "relationship", description: "Executor managing sale of inherited property with probate solicitor — legal process and emotional weight navigated together", sceneRoles: ["executor", "probate solicitor"], industryIds: ["real-estate"], tags: ["probate", "executor", "solicitor", "inherited-property"], priority: 3, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:real_estate:foreign-national-buyer-and-solicitor", kind: "relationship", description: "Foreign national buyer purchasing UK property with specialist solicitor — additional compliance, trust in professional expertise", sceneRoles: ["foreign buyer", "specialist solicitor"], industryIds: ["real-estate"], tags: ["foreign-national", "buyer", "specialist-solicitor", "compliance"], priority: 4, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "relationship:real_estate:divorce-solicitor-and-joint-sellers", kind: "relationship", description: "Two solicitors representing each side of a divorce managing the sale of jointly owned property — professional intermediaries", sceneRoles: ["solicitor A", "solicitor B", "joint sellers"], industryIds: ["real-estate"], tags: ["divorce", "joint-sale", "solicitors", "mediation"], priority: 5, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "relationship:real_estate:leaseholder-and-freeholder", kind: "relationship", description: "Leaseholder in negotiation with freeholder over lease extension or service charge — navigating the leasehold system", sceneRoles: ["leaseholder", "freeholder"], industryIds: ["real-estate"], tags: ["leasehold", "extension", "service-charge", "negotiation"], priority: 6, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "relationship:real_estate:right-to-buy-tenant-local-authority", kind: "relationship", description: "Long-term council tenant exercising right to buy with local authority — the path to ownership through the scheme", sceneRoles: ["tenant", "local authority"], industryIds: ["real-estate"], tags: ["right-to-buy", "council-tenant", "local-authority", "ownership-path"], priority: 7, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:real_estate:shared-ownership-buyer-and-housing-association", kind: "relationship", description: "Shared ownership buyer completing with housing association — route onto property ladder, partial ownership celebrated", sceneRoles: ["shared ownership buyer", "housing association"], industryIds: ["real-estate"], tags: ["shared-ownership", "housing-association", "first-rung", "milestone"], priority: 8, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── Mortgage & finance (8) ────────────────────────────────────────────────
  { id: "relationship:real_estate:mortgage-advisor-and-client", kind: "relationship", description: "Mortgage advisor and client working through affordability, product options and application together — financial enablement", sceneRoles: ["mortgage advisor", "buyer"], industryIds: ["real-estate"], tags: ["mortgage", "advisor", "affordability", "enablement"], priority: 1, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:real_estate:young-couple-and-mortgage-broker", kind: "relationship", description: "Young couple meeting mortgage broker for first time — nervous energy, the financial reality of buying being laid out", sceneRoles: ["young couple", "mortgage broker"], industryIds: ["real-estate"], tags: ["young-couple", "mortgage-broker", "first-meeting", "financial"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:real_estate:parent-gifting-deposit", kind: "relationship", description: "Parent gifting deposit to first-time buyer child — generational wealth transfer, the family enabling ownership for next generation", sceneRoles: ["parent", "first-time buyer"], industryIds: ["real-estate"], tags: ["gifted-deposit", "parent", "generational", "enablement"], priority: 3, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:real_estate:btl-investor-and-mortgage-broker", kind: "relationship", description: "Buy-to-let investor and specialist BTL mortgage broker — yield discussion, portfolio finance, professional-to-professional", sceneRoles: ["BTL investor", "BTL mortgage broker"], industryIds: ["real-estate"], tags: ["btl", "investor", "broker", "yield"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:real_estate:developer-and-bridging-lender", kind: "relationship", description: "Property developer negotiating bridging facility with lender — project financed, timeline locked, development enabled", sceneRoles: ["developer", "bridging lender"], industryIds: ["real-estate"], tags: ["developer", "bridging-loan", "lender", "finance"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:real_estate:buyer-and-independent-financial-advisor", kind: "relationship", description: "Home buyer meeting independent financial advisor to plan the full financial picture of ownership beyond the mortgage", sceneRoles: ["buyer", "IFA"], industryIds: ["real-estate"], tags: ["ifa", "buyer", "financial-planning", "whole-of-market"], priority: 6, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "relationship:real_estate:help-to-buy-agent-and-buyer", kind: "relationship", description: "First-time buyer navigating Help to Buy with scheme agent — the government-backed route to ownership explained", sceneRoles: ["Help to Buy agent", "first-time buyer"], industryIds: ["real-estate"], tags: ["help-to-buy", "agent", "first-time-buyer", "scheme"], priority: 7, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:real_estate:portfolio-landlord-and-property-manager", kind: "relationship", description: "Portfolio landlord delegating management to professional property manager — the business relationship that enables scale", sceneRoles: ["portfolio landlord", "property manager"], industryIds: ["real-estate"], tags: ["portfolio", "landlord", "property-manager", "delegation"], priority: 8, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },

  // ── Landlord & tenant (8) ─────────────────────────────────────────────────
  { id: "relationship:real_estate:landlord-and-letting-agent", kind: "relationship", description: "Landlord entrusting property to letting agent — management agreement signed, the professional layer of the rental", sceneRoles: ["landlord", "letting agent"], industryIds: ["real-estate"], tags: ["landlord", "letting-agent", "management", "trust"], priority: 1, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:real_estate:landlord-and-tenant-at-signing", kind: "relationship", description: "Landlord and new tenant at tenancy agreement signing — professional and personal, the start of a living relationship", sceneRoles: ["landlord", "tenant"], industryIds: ["real-estate"], tags: ["landlord", "tenant", "tenancy-signing", "start"], priority: 2, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:real_estate:property-manager-and-tenant-issue", kind: "relationship", description: "Property manager mediating a maintenance issue between landlord instruction and tenant need — professional resolution", sceneRoles: ["property manager", "tenant"], industryIds: ["real-estate"], tags: ["property-manager", "tenant", "maintenance", "resolution"], priority: 3, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "relationship:real_estate:landlord-and-maintenance-contractor", kind: "relationship", description: "Landlord instructing trusted maintenance contractor for urgent repair — established working relationship, fast response", sceneRoles: ["landlord", "maintenance contractor"], industryIds: ["real-estate"], tags: ["landlord", "contractor", "maintenance", "urgent"], priority: 4, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },
  { id: "relationship:real_estate:short-term-let-host-and-manager", kind: "relationship", description: "Short-term let host working with property manager to run holiday rental professionally — revenue maximised, guest experience managed", sceneRoles: ["host", "short-term let manager"], industryIds: ["real-estate"], tags: ["short-term-let", "host", "manager", "holiday-rental"], priority: 5, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "relationship:real_estate:developer-and-investor-off-plan", kind: "relationship", description: "Developer selling off-plan units to property investor — early-access deal, the investment before the building exists", sceneRoles: ["developer sales", "investor"], industryIds: ["real-estate"], tags: ["off-plan", "developer", "investor", "early-access"], priority: 6, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:real_estate:developer-and-show-home-buyer", kind: "relationship", description: "Developer sales consultant walking show home with serious buyer — the aspirational future being sold room by room", sceneRoles: ["developer sales consultant", "show home buyer"], industryIds: ["real-estate"], tags: ["show-home", "developer", "buyer", "aspirational"], priority: 7, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:real_estate:retired-couple-downsizing-with-agent", kind: "relationship", description: "Retired couple and agent navigating the downsizing process — the agent as guide through a major life transition", sceneRoles: ["retired couple", "estate agent"], industryIds: ["real-estate"], tags: ["retired", "downsizing", "agent", "life-transition"], priority: 8, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Development & planning (7) ─────────────────────────────────────────────
  { id: "relationship:real_estate:developer-and-planning-consultant", kind: "relationship", description: "Developer briefing planning consultant before major application — strategy discussed, objection risks assessed", sceneRoles: ["developer", "planning consultant"], industryIds: ["real-estate"], tags: ["developer", "planning", "consultant", "strategy"], priority: 1, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "relationship:real_estate:housebuilder-and-land-agent", kind: "relationship", description: "Housebuilder identifying land opportunity with land agent — off-market land discussed, deal before planning even applied for", sceneRoles: ["housebuilder", "land agent"], industryIds: ["real-estate"], tags: ["housebuilder", "land-agent", "land", "opportunity"], priority: 2, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "relationship:real_estate:buyer-and-architect-pre-purchase", kind: "relationship", description: "Buyer bringing architect to view renovation property before offering — potential assessed by expert before commitment", sceneRoles: ["buyer", "architect"], industryIds: ["real-estate"], tags: ["buyer", "architect", "renovation", "pre-purchase"], priority: 3, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:real_estate:auction-house-and-bidder", kind: "relationship", description: "Auction house representative guiding first-time auction bidder — the process explained, confidence given before bidding", sceneRoles: ["auction representative", "bidder"], industryIds: ["real-estate"], tags: ["auction", "representative", "bidder", "first-time"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:real_estate:buyer-and-structural-engineer", kind: "relationship", description: "Buyer instructing structural engineer to assess property before purchase — expert eyes on potential subsidence or concerns", sceneRoles: ["buyer", "structural engineer"], industryIds: ["real-estate"], tags: ["structural-engineer", "buyer", "assessment", "due-diligence"], priority: 5, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "relationship:real_estate:seller-and-home-stager", kind: "relationship", description: "Seller working with professional home stager to present property at its best for market — commercial investment in first impression", sceneRoles: ["seller", "home stager"], industryIds: ["real-estate"], tags: ["seller", "home-stager", "staging", "first-impression"], priority: 6, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:real_estate:buyer-and-interior-designer-post-purchase", kind: "relationship", description: "New homeowner briefing interior designer immediately post-purchase — the property now owned, the transformation commissioned", sceneRoles: ["new homeowner", "interior designer"], industryIds: ["real-estate"], tags: ["interior-designer", "new-homeowner", "post-purchase", "transformation"], priority: 7, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── Community & lifestyle (7) ──────────────────────────────────────────────
  { id: "relationship:real_estate:buyer-and-current-neighbours", kind: "relationship", description: "Buyer chatting with current neighbours during viewing — local knowledge shared, community assessed, decision influenced", sceneRoles: ["buyer", "current neighbours"], industryIds: ["real-estate"], tags: ["neighbours", "buyer", "local-knowledge", "community"], priority: 1, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:real_estate:commercial-tenant-and-landlord-lease", kind: "relationship", description: "Commercial tenant and landlord at lease renewal — negotiating terms, long-term relationship, business accommodation secured", sceneRoles: ["commercial tenant", "landlord"], industryIds: ["real-estate"], tags: ["commercial", "tenant", "landlord", "lease-renewal"], priority: 2, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "relationship:real_estate:agent-and-property-photographer", kind: "relationship", description: "Estate agent directing professional photographer on listing shoot — creative collaboration for maximum property appeal", sceneRoles: ["estate agent", "property photographer"], industryIds: ["real-estate"], tags: ["agent", "photographer", "listing", "collaboration"], priority: 3, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },
  { id: "relationship:real_estate:new-homeowner-and-new-neighbours", kind: "relationship", description: "New homeowner being welcomed by established neighbours — community welcoming a new family to the street", sceneRoles: ["new homeowner", "neighbours"], industryIds: ["real-estate"], tags: ["new-homeowner", "neighbours", "welcome", "community"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:real_estate:adult-children-and-elderly-parent-downsizing", kind: "relationship", description: "Adult children supporting elderly parent through downsizing — emotionally complex, practically shared, love throughout", sceneRoles: ["adult children", "elderly parent"], industryIds: ["real-estate"], tags: ["adult-children", "elderly-parent", "downsizing", "support"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:real_estate:investor-and-renovation-contractor", kind: "relationship", description: "Property investor briefing renovation contractor — scope agreed, budget set, the project that creates the profit", sceneRoles: ["property investor", "renovation contractor"], industryIds: ["real-estate"], tags: ["investor", "contractor", "renovation", "project"], priority: 6, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "relationship:real_estate:charity-and-property-donation", kind: "relationship", description: "Donor gifting property to charity — unusual and generous, the legal and emotional weight of an extraordinary gift", sceneRoles: ["donor", "charity representative"], industryIds: ["real-estate"], tags: ["charity", "donation", "property", "philanthropy"], priority: 7, weight: 0.76, confidence: "high", commercialScore: 75, futureMetadata: fm },
];
