import type { Metadata } from "next";

import { LegalPage } from "@/components/shared/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service — Elevatex AI",
  description: "The terms governing your use of Elevatex AI.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="29 June 2026">
      <p>
        These Terms govern your use of Elevatex AI (the &ldquo;Service&rdquo;). By creating an account, you agree to
        these Terms.
      </p>

      <div className="flex flex-col gap-3">
        <h2>The Service</h2>
        <p>
          Elevatex AI generates marketing videos using AI — from a written brief, or from a video you upload (Talking
          Head). Output quality depends on the AI providers configured for your account and the inputs you provide.
        </p>
      </div>

      <div className="flex flex-col gap-3">
        <h2>Accounts</h2>
        <p>
          You sign in with your Google account or an email and password. You&rsquo;re responsible for keeping access
          to your account credentials secure, and for all activity under your account.
        </p>
      </div>

      <div className="flex flex-col gap-3">
        <h2>Credits, billing, and refunds</h2>
        <ul>
          <li>Credits are consumed for paid actions (AI generation, exports, downloads) as described in-product.</li>
          <li>Subscriptions renew automatically each billing cycle until cancelled; cancelling stops future renewals but doesn&rsquo;t refund the current period.</li>
          <li>Purchased credit packages are generally non-refundable once credits have been spent. Contact us for billing disputes — we review these case by case.</li>
          <li>All payments are processed by our payment provider (Razorpay); we never see or store your card details.</li>
          <li>GST-ready invoices are generated automatically for every payment and available from your Credits page.</li>
        </ul>
      </div>

      <div className="flex flex-col gap-3">
        <h2>Your content</h2>
        <p>
          You retain ownership of the briefs, media, and brand assets you upload, and of the videos Elevatex AI
          generates for you. You&rsquo;re responsible for ensuring you have the rights to any content you upload
          (e.g. footage of people, music, trademarks) and that your use complies with applicable law.
        </p>
      </div>

      <div className="flex flex-col gap-3">
        <h2>Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service to generate unlawful, defamatory, or infringing content.</li>
          <li>Attempt to circumvent rate limits, credit charges, or access controls.</li>
          <li>Upload malware or attempt to compromise the platform&rsquo;s security.</li>
          <li>Resell or sublicense access to the Service without our written agreement.</li>
        </ul>
        <p>We may suspend accounts that violate these terms, including ones flagged by our automated abuse detection.</p>
      </div>

      <div className="flex flex-col gap-3">
        <h2>AI-generated content disclaimer</h2>
        <p>
          Video scripts, visuals, and voiceovers are generated by AI and may occasionally be inaccurate or
          unsuitable for your intended use. Review generated content before publishing it, especially for factual
          claims, regulated industries, or sensitive topics.
        </p>
      </div>

      <div className="flex flex-col gap-3">
        <h2>Service availability</h2>
        <p>
          We aim for high availability but don&rsquo;t guarantee uninterrupted access. Scheduled maintenance and
          third-party provider outages may affect generation or rendering speed.
        </p>
      </div>

      <div className="flex flex-col gap-3">
        <h2>Limitation of liability</h2>
        <p>
          The Service is provided &ldquo;as is&rdquo;. To the maximum extent permitted by law, Elevatex AI is not
          liable for indirect, incidental, or consequential damages arising from your use of the Service.
        </p>
      </div>

      <div className="flex flex-col gap-3">
        <h2>Changes to these terms</h2>
        <p>We may update these Terms from time to time. Continued use after an update constitutes acceptance.</p>
      </div>

      <div className="flex flex-col gap-3">
        <h2>Contact</h2>
        <p>
          Questions about these Terms? Reach us via our <a href="/contact">Contact page</a>.
        </p>
      </div>
    </LegalPage>
  );
}
