import type { BehaviourKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const JEWELLERY_BEHAVIOURS: BehaviourKnowledgeNode[] = [
  // ── Ring examination behaviours (15) ──────────────────────────────────────────
  { id: "behaviour:jewellery:raising-ring-hand-to-window", kind: "behaviour", description: "Person raising their ringed hand slowly toward a window or light source, tilting the wrist to watch diamond facets shift colour across the spectrum", emotionalSignal: "wonder and pride", compatibleHeroes: ["product", "person", "moment"], industryIds: ["jewellery"], tags: ["ring", "light", "examination", "wonder"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "behaviour:jewellery:turning-ring-on-finger", kind: "behaviour", description: "Newly engaged person turning the ring around on their finger — not adjusting but feeling the weight of it, internalising its presence on their hand", emotionalSignal: "adjusting to new reality", compatibleHeroes: ["person", "moment"], industryIds: ["jewellery"], tags: ["ring", "turning", "adjustment", "new"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:jewellery:extending-left-hand-to-show-ring", kind: "behaviour", description: "Person instinctively extending their left hand flat with fingers spread to show the engagement ring to a friend or family member, the gesture both invitation and announcement", emotionalSignal: "pride and excitement", compatibleHeroes: ["person", "moment", "lifestyle"], industryIds: ["jewellery"], tags: ["ring", "extending-hand", "showing", "announcement"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "behaviour:jewellery:holding-ring-box-open-in-both-hands", kind: "behaviour", description: "Person holding an open ring box in both hands at chest height, the box framed by their palms, the offering gesture complete and deliberate", emotionalSignal: "vulnerability and hope", compatibleHeroes: ["moment", "person"], industryIds: ["jewellery"], tags: ["ring-box", "holding", "offering", "two-hands"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "behaviour:jewellery:touching-ring-absentmindedly", kind: "behaviour", description: "Person touching or turning their ring while in thought, conversation or watching TV — the habitual unconscious contact with the object that matters", emotionalSignal: "comfort and attachment", compatibleHeroes: ["lifestyle", "person"], industryIds: ["jewellery"], tags: ["ring", "touching", "habit", "unconscious"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:jewellery:examining-ring-under-loupe", kind: "behaviour", description: "Jeweller or collector examining a piece under a loupe, one eye closed, the loupe held steady, the face entirely concentrated on the object beneath the glass", emotionalSignal: "expert focus", compatibleHeroes: ["person", "product", "moment"], industryIds: ["jewellery"], tags: ["loupe", "examination", "expert", "focus"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:jewellery:friend-grabbing-hand-to-look", kind: "behaviour", description: "Friend immediately grabbing the engaged person's hand to look at the ring — leaning in close, turning it toward the light, the intimacy of inspection before the words come", emotionalSignal: "excited examination", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["jewellery"], tags: ["friend", "hand-grab", "inspection", "excitement"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:jewellery:placing-ring-carefully-in-box", kind: "behaviour", description: "Person placing a ring carefully back into its velvet slot at night — the deliberate care of returning an important object to its place", emotionalSignal: "care and stewardship", compatibleHeroes: ["lifestyle", "product"], industryIds: ["jewellery"], tags: ["ring", "placing", "care", "velvet-box"], priority: 5, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:jewellery:comparing-two-rings-in-hand", kind: "behaviour", description: "Customer holding two rings side by side in the palm of one hand, tilting slightly to compare the stones, the decision visible in the slight furrowing of the brow", emotionalSignal: "careful deliberation", compatibleHeroes: ["moment", "person", "product"], industryIds: ["jewellery"], tags: ["comparison", "two-rings", "decision", "deliberation"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:jewellery:photographing-ring-left-hand-flat", kind: "behaviour", description: "Newly engaged person photographing their ringed hand flat against a surface — flowers, marble, a wooden table — composing the announcement image with care", emotionalSignal: "desire to document and share", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["jewellery"], tags: ["photography", "ring", "flat-hand", "announcement", "social"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:jewellery:stacking-rings-on-one-finger", kind: "behaviour", description: "Person sliding a second and third ring onto the same finger beside the first — the deliberate composition of a stacked-ring look, checking the combination against the others", emotionalSignal: "playful self-expression", compatibleHeroes: ["lifestyle", "person", "product"], industryIds: ["jewellery"], tags: ["stacking", "rings", "composition", "style"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:jewellery:trying-on-in-mirror-tilting-head", kind: "behaviour", description: "Customer at a jewellery counter trying on earrings and tilting their head in the small counter mirror, checking how they move with the movement, looking from different angles", emotionalSignal: "self-assessment and pleasure", compatibleHeroes: ["lifestyle", "person", "product"], industryIds: ["jewellery"], tags: ["trying-on", "earrings", "mirror", "tilting", "assessment"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:jewellery:classifying-hold-over-light-box", kind: "behaviour", description: "Gemmologist holding a gemstone over a light box, the stone between forefinger and thumb, the colour and clarity assessed against the even illumination below", emotionalSignal: "professional assessment", compatibleHeroes: ["person", "product", "moment"], industryIds: ["jewellery"], tags: ["gemmologist", "light-box", "stone", "assessment"], priority: 5, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:jewellery:children-trying-on-mothers-rings", kind: "behaviour", description: "Small child sliding their mother's large rings down their small fingers — the ring reaching the second knuckle, the child delighted by the loose, oversize fit", emotionalSignal: "innocent play and curiosity", compatibleHeroes: ["lifestyle", "person"], industryIds: ["jewellery"], tags: ["child", "play", "mothers-ring", "trying-on"], priority: 6, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:jewellery:clasping-necklace-on-someone-else", kind: "behaviour", description: "One person standing behind another to clasp a necklace around their neck — the helper squinting slightly to connect the tiny clasp while the wearer holds their hair up", emotionalSignal: "intimate service and care", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["jewellery"], tags: ["necklace", "clasping", "helping", "intimate"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },

  // ── Gifting & receiving behaviours (20) ───────────────────────────────────────
  { id: "behaviour:jewellery:opening-small-wrapped-box", kind: "behaviour", description: "Person unwrapping a small jewellery gift — the distinctive weight of the small box already communicating its category before it opens, the ribbon pulled slowly", emotionalSignal: "anticipation and delight", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["jewellery"], tags: ["unwrapping", "gift", "small-box", "anticipation"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "behaviour:jewellery:gasp-on-box-opening", kind: "behaviour", description: "A gasp or intake of breath the moment a jewellery box opens — involuntary, immediate, before any thought or words — the body's honest response to the unexpected beauty", emotionalSignal: "surprise and delight", compatibleHeroes: ["moment", "person"], industryIds: ["jewellery"], tags: ["gasp", "opening", "surprise", "involuntary"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "behaviour:jewellery:giver-watching-face-not-gift", kind: "behaviour", description: "The gift giver watching the recipient's face rather than the jewellery box — the moment of the reveal read entirely through the other person's expression", emotionalSignal: "love through observation", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["jewellery"], tags: ["watching", "giver", "recipient-face", "reading"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:jewellery:tears-on-receiving-heirloom", kind: "behaviour", description: "Visible tears when receiving a family heirloom piece — the emotional weight of the transmission overriding any attempt at composure", emotionalSignal: "grief and gratitude combined", compatibleHeroes: ["moment", "person"], industryIds: ["jewellery"], tags: ["heirloom", "tears", "receiving", "emotional"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "behaviour:jewellery:immediate-putting-on-after-gift", kind: "behaviour", description: "Person immediately putting on the gifted piece before the ribbon is even fully cleared — the can't-wait impulse of wanting to be wearing it right now", emotionalSignal: "impatient delight", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["jewellery"], tags: ["putting-on", "immediate", "gift", "wearing"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:jewellery:husband-choosing-in-store-alone", kind: "behaviour", description: "A man alone in a jewellery store, slightly out of his comfort zone, describing to the sales associate what his partner is like — the earnest attempt to translate a person into a piece", emotionalSignal: "vulnerable and caring", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["jewellery"], tags: ["husband", "alone", "choosing", "describing-partner"], priority: 3, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:jewellery:passing-box-across-table", kind: "behaviour", description: "Person sliding a small jewellery box across a restaurant table — the understated gesture of the quiet giver who prefers to let the object do the speaking", emotionalSignal: "quiet generosity", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["jewellery"], tags: ["passing", "box", "table", "understated"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:jewellery:calling-to-share-news", kind: "behaviour", description: "Newly engaged person on the phone immediately after the proposal — telling someone they love what just happened, the ring visible on the hand holding the phone", emotionalSignal: "joy that must be shared", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["jewellery"], tags: ["phone-call", "sharing-news", "ring-visible", "post-engagement"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:jewellery:texting-ring-photo", kind: "behaviour", description: "Person composing and sending a photo text of their new ring — selecting the image, writing the one-word response 'Yes!!!' or similar, the modern announcement in its immediate form", emotionalSignal: "excitement and digital sharing", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["jewellery"], tags: ["texting", "photo", "ring", "announcement", "digital"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:jewellery:wrapping-gift-with-ribbon", kind: "behaviour", description: "Someone wrapping a jewellery box with care — the ribbon pulled taut, a bow tied, the small package made to be worthy of what it contains", emotionalSignal: "care in presentation", compatibleHeroes: ["lifestyle", "product", "moment"], industryIds: ["jewellery"], tags: ["wrapping", "ribbon", "presentation", "care"], priority: 5, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },

  // ── Wearing & styling behaviours (20) ─────────────────────────────────────────
  { id: "behaviour:jewellery:layering-necklaces-in-mirror", kind: "behaviour", description: "Person layering two or three necklaces at the mirror before going out — adjusting chain lengths, checking how the pendants fall, composing the chest", emotionalSignal: "creative self-curation", compatibleHeroes: ["lifestyle", "person", "product"], industryIds: ["jewellery"], tags: ["layering", "necklaces", "mirror", "styling"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:jewellery:gold-skin-contrast-admiring", kind: "behaviour", description: "Person looking at how gold jewellery sits against their skin tone — the satisfaction of a specific warm metal working with their complexion", emotionalSignal: "aesthetic self-recognition", compatibleHeroes: ["person", "lifestyle", "product"], industryIds: ["jewellery"], tags: ["gold", "skin-tone", "contrast", "aesthetic"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:jewellery:bride-touching-earrings-in-mirror", kind: "behaviour", description: "Bride touching her dangling earrings gently in the mirror on the wedding morning — checking they're secure but really just feeling them, anchoring herself in the moment", emotionalSignal: "nervous excitement and grounding", compatibleHeroes: ["moment", "person", "environment"], industryIds: ["jewellery"], tags: ["bride", "earrings", "mirror", "wedding-morning"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "behaviour:jewellery:removing-earrings-coming-home", kind: "behaviour", description: "Person removing earrings the moment they come through the door — the sigh of relief as they come off, placed on the entry table or bathroom shelf", emotionalSignal: "relief and transition", compatibleHeroes: ["lifestyle", "person"], industryIds: ["jewellery"], tags: ["removing", "earrings", "home", "relief"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:jewellery:selecting-pieces-for-event", kind: "behaviour", description: "Person laying out three or four jewellery options on the bed before an evening event — standing back to look, trying combinations, the pre-event composition ritual", emotionalSignal: "considered self-presentation", compatibleHeroes: ["lifestyle", "person", "product"], industryIds: ["jewellery"], tags: ["selecting", "event", "laying-out", "composition"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:jewellery:minimalist-single-stud-choice", kind: "behaviour", description: "Person selecting a single diamond stud earring and placing it with intention — the deliberate choice of the minimum, the one piece that says everything", emotionalSignal: "confident restraint", compatibleHeroes: ["lifestyle", "person", "product"], industryIds: ["jewellery"], tags: ["minimalist", "stud", "single", "restraint"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:jewellery:bracelet-slide-on-wrist", kind: "behaviour", description: "Person sliding a bangle or bracelet over their wrist — the particular gesture of getting it past the widest part of the hand, then settling it on the wrist bone", emotionalSignal: "habitual pleasure", compatibleHeroes: ["lifestyle", "person", "product"], industryIds: ["jewellery"], tags: ["bracelet", "sliding-on", "wrist", "bangle"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:jewellery:watch-jewellery-cuff-combination", kind: "behaviour", description: "Person pairing a watch with a cuff bracelet on the same wrist — the considered combination of two pieces that work as one, the wrist as a composed object", emotionalSignal: "considered styling", compatibleHeroes: ["lifestyle", "person", "product"], industryIds: ["jewellery"], tags: ["watch", "cuff", "combination", "wrist"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:jewellery:formal-event-full-set-wearing", kind: "behaviour", description: "Person dressed for a formal event — earrings, necklace, bracelet and ring all selected to work together, the full set creating a deliberate complete look", emotionalSignal: "confident completeness", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["jewellery"], tags: ["formal", "full-set", "complete-look", "deliberate"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:jewellery:tan-line-revealing-ring-space", kind: "behaviour", description: "Person noticing the tan line left by their ring after removing it — the white band on the tanned finger that marks the ring's constant presence", emotionalSignal: "evidence of belonging", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["jewellery"], tags: ["tan-line", "ring", "evidence", "presence"], priority: 6, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── In-store & decision behaviours (20) ───────────────────────────────────────
  { id: "behaviour:jewellery:opening-display-case-with-staff", kind: "behaviour", description: "Sales associate opening a glass display case while the customer leans in to see the pieces more closely — the ritual unlocking that signals serious consideration", emotionalSignal: "heightened anticipation", compatibleHeroes: ["moment", "person", "environment"], industryIds: ["jewellery"], tags: ["display-case", "staff", "opening", "consideration"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:jewellery:requesting-piece-to-try", kind: "behaviour", description: "Customer pointing to a piece through the glass and asking to try it — the specific pointing gesture followed by the associate lifting the piece onto the counter", emotionalSignal: "focused desire", compatibleHeroes: ["moment", "person", "environment"], industryIds: ["jewellery"], tags: ["pointing", "requesting", "try-on", "counter"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:jewellery:showing-phone-reference-to-associate", kind: "behaviour", description: "Customer showing a saved Pinterest or Instagram image to a jeweller — 'something like this' — the reference that begins the matching or creation conversation", emotionalSignal: "bridging vision to reality", compatibleHeroes: ["moment", "person", "environment"], industryIds: ["jewellery"], tags: ["phone-reference", "instagram", "showing", "matching"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:jewellery:couple-shopping-together", kind: "behaviour", description: "A couple in a jewellery store together — one trying pieces while the other watches and offers opinions, the decision collaborative and the associate navigating both perspectives", emotionalSignal: "shared decision-making", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["jewellery"], tags: ["couple", "shopping", "together", "collaborative"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:jewellery:budget-conversation-with-associate", kind: "behaviour", description: "Customer having a quiet conversation with the sales associate about budget — the honest, slightly uncomfortable question answered with professionalism that finds the right piece without shame", emotionalSignal: "vulnerability requiring trust", compatibleHeroes: ["moment", "person", "environment"], industryIds: ["jewellery"], tags: ["budget", "conversation", "trust", "associate"], priority: 4, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:jewellery:long-browse-before-narrowing", kind: "behaviour", description: "Customer spending time at every case before returning to the first one — the full survey followed by the knowing return to what caught the eye at the beginning", emotionalSignal: "due diligence followed by certainty", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["jewellery"], tags: ["browsing", "returning", "first-choice", "certainty"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:jewellery:associate-presenting-on-velvet-pad", kind: "behaviour", description: "Sales associate placing a piece on a velvet presentation pad and sliding it toward the customer — the protocol of presentation that makes every piece feel significant", emotionalSignal: "ceremonial importance", compatibleHeroes: ["product", "moment", "environment"], industryIds: ["jewellery"], tags: ["velvet-pad", "presentation", "associate", "protocol"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:jewellery:resizing-ring-returning-to-collect", kind: "behaviour", description: "Customer returning to collect a ring that was left for resizing — the reunion with the piece that is now exactly right, the trying on confirmation that it is", emotionalSignal: "completion and satisfaction", compatibleHeroes: ["moment", "person", "environment"], industryIds: ["jewellery"], tags: ["resizing", "collecting", "reunion", "satisfaction"], priority: 5, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:jewellery:price-tag-look-without-flinching", kind: "behaviour", description: "Customer checking the price of a fine jewellery piece — the moment of processing the number, then continuing to consider the piece, the decision made not to be deterred", emotionalSignal: "considered purchase acceptance", compatibleHeroes: ["moment", "person"], industryIds: ["jewellery"], tags: ["price", "checking", "consideration", "acceptance"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:jewellery:associate-suggesting-upgrade-stone", kind: "behaviour", description: "Jeweller suggesting a slightly larger stone or different grade — showing two stones side by side and explaining the difference, the customer's eyes comparing carefully", emotionalSignal: "informed aspiration", compatibleHeroes: ["moment", "person", "environment"], industryIds: ["jewellery"], tags: ["upgrade", "stone-comparison", "suggestion", "associate"], priority: 4, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Emotional peak behaviours (25) ────────────────────────────────────────────
  { id: "behaviour:jewellery:trembling-hands-during-proposal", kind: "behaviour", description: "Hands shaking visibly while opening the ring box during a proposal — the physical sign of genuine emotion, the trembling that no acting can replicate", emotionalSignal: "overwhelm and love", compatibleHeroes: ["moment", "person"], industryIds: ["jewellery"], tags: ["trembling", "proposal", "hands", "genuine-emotion"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "behaviour:jewellery:hands-to-mouth-on-seeing-ring", kind: "behaviour", description: "Both hands flying to cover the mouth in a single movement when the ring box opens — the involuntary protective gesture of overwhelming emotion", emotionalSignal: "shock and joy", compatibleHeroes: ["moment", "person"], industryIds: ["jewellery"], tags: ["hands-to-mouth", "ring-reveal", "shock", "involuntary"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "behaviour:jewellery:crying-while-saying-yes", kind: "behaviour", description: "Tears running while saying yes — the word barely audible, the nod doing most of the work, the emotion ahead of the language", emotionalSignal: "overwhelmed joy", compatibleHeroes: ["moment", "person"], industryIds: ["jewellery"], tags: ["crying", "yes", "tears", "proposal-acceptance"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "behaviour:jewellery:looking-at-ring-then-person", kind: "behaviour", description: "Person who just received the ring looking at it on their finger, then looking up at the giver — the ring and the person both deserving the look", emotionalSignal: "profound gratitude", compatibleHeroes: ["moment", "person"], industryIds: ["jewellery"], tags: ["looking-at-ring", "looking-at-person", "gratitude", "connection"], priority: 2, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "behaviour:jewellery:long-embrace-after-opening-gift", kind: "behaviour", description: "A long, still embrace immediately after opening a jewellery gift — neither person moving, the jewellery in the open box beside them, the hug being the real answer", emotionalSignal: "deep connection", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["jewellery"], tags: ["embrace", "gift", "still", "connection"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:jewellery:speechless-holding-gift-looking-up", kind: "behaviour", description: "Recipient holding open jewellery box, looking up at the giver without words — the space before speech where the feeling is larger than any sentence", emotionalSignal: "speechless gratitude", compatibleHeroes: ["moment", "person"], industryIds: ["jewellery"], tags: ["speechless", "holding-box", "looking-up", "gratitude"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:jewellery:grandmother-touching-piece-with-memory", kind: "behaviour", description: "An older person touching a piece of jewellery with the particular care of someone who knows its full history — every touch accompanied by a specific memory", emotionalSignal: "layered remembrance", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["jewellery"], tags: ["grandmother", "touching", "memory", "history"], priority: 3, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:jewellery:friends-gathering-to-see-ring", kind: "behaviour", description: "A group of friends all simultaneously reaching toward the engaged person's hand, the ring visible among multiple reaching arms, the collective joy of close friends", emotionalSignal: "collective celebration", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["jewellery"], tags: ["friends", "gathering", "ring", "collective"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:jewellery:laughter-after-tears", kind: "behaviour", description: "Person laughing at themselves for crying about a piece of jewellery — the self-aware awareness that this object has made them more emotional than expected", emotionalSignal: "joyful self-awareness", compatibleHeroes: ["moment", "person", "lifestyle"], industryIds: ["jewellery"], tags: ["laughter-after-tears", "self-aware", "emotion", "unexpected"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:jewellery:touching-wedding-ring-absent-partner", kind: "behaviour", description: "Widowed or long-married person touching their wedding ring when thinking of their partner — the unconscious reach to the constant that carries the relationship", emotionalSignal: "love that endures loss", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["jewellery"], tags: ["wedding-ring", "absent-partner", "touching", "enduring-love"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
];
