import type { EmotionalMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const JEWELLERY_EMOTIONAL_MOMENTS: EmotionalMomentKnowledgeNode[] = [
  // ── Proposal peak moments (15) ────────────────────────────────────────────────
  { id: "emotional_moment:jewellery:ring-box-opening-gasp", kind: "emotional_moment", moment: "The ring box opens and the recipient gasps — hands flying to mouth, eyes wide before the tears start, the body responding before the mind has processed", emotionType: "overwhelming surprise and joy", visualSignals: ["hands raised to mouth", "eyes wide and glistening", "body leaning backward slightly", "the gasped breath visible as shoulders lift"], industryIds: ["jewellery"], tags: ["ring-box", "gasp", "hands-to-mouth", "overwhelming"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "emotional_moment:jewellery:the-yes-spoken-through-tears", kind: "emotional_moment", moment: "The word 'yes' spoken while crying — barely audible, the face wet, the word itself almost secondary to the nodding that confirms it", emotionType: "joyful overwhelm", visualSignals: ["tears on both cheeks", "head nodding while voice breaks", "reaching toward the ring", "the proposer's face collapsing with relief"], industryIds: ["jewellery"], tags: ["yes", "tears", "crying", "joyful-overwhelm"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "emotional_moment:jewellery:ring-on-finger-first-time", kind: "emotional_moment", moment: "The ring settles onto the finger for the first time — both people looking at the hand together, the object now at home in its permanent place", emotionType: "sacred completeness", visualSignals: ["both sets of eyes on the hand", "the ring sitting still for the first time", "intertwined fingers closing around it", "the silence before the first sentence afterward"], industryIds: ["jewellery"], tags: ["ring-on-finger", "first-time", "together-looking", "sacred"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:jewellery:proposer-trembling-hands", kind: "emotional_moment", moment: "The proposer's hands visibly shaking as they open the box — the physical evidence of how much this matters, the involuntary trembling that no performance could replicate", emotionType: "vulnerable love", visualSignals: ["hands trembling on box lid", "voice slightly unsteady", "eye contact held despite nerves", "the ring box itself slightly unsteady"], industryIds: ["jewellery"], tags: ["trembling", "proposer", "vulnerability", "involuntary"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:jewellery:couple-embrace-after-yes", kind: "emotional_moment", moment: "The embrace immediately after the yes — both holding the other tightly, neither speaking, the ring box somewhere on the ground or table, forgotten briefly in the better thing", emotionType: "relief and belonging", visualSignals: ["full-body embrace", "neither person moving to separate", "the ring box visible but ignored", "both faces pressed together"], industryIds: ["jewellery"], tags: ["embrace", "post-yes", "relief", "belonging"], priority: 2, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:jewellery:first-look-at-ring-solo", kind: "emotional_moment", moment: "Newly engaged person alone with their hand, just looking at the ring — the private moment before everything becomes social, the time with the object that is now theirs", emotionType: "private wonder", visualSignals: ["hand held at eye level alone", "slow turning of the wrist", "expression between disbelief and delight", "the quiet of the private moment"], industryIds: ["jewellery"], tags: ["alone", "private", "looking", "wonder"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:jewellery:strangers-applauding-restaurant-proposal", kind: "emotional_moment", moment: "Strangers in a restaurant beginning to applaud after witnessing the proposal — the couple suddenly aware the private moment had an audience, the collective shared joy", emotionType: "private becoming public joy", visualSignals: ["surrounding tables beginning to clap", "couple becoming aware of the room", "laughter breaking through tears", "the proposal expanding beyond the two people"], industryIds: ["jewellery"], tags: ["restaurant", "strangers", "applause", "public-private"], priority: 3, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },

  // ── Gifting emotional peaks (15) ──────────────────────────────────────────────
  { id: "emotional_moment:jewellery:grandmother-heirloom-transmission", kind: "emotional_moment", moment: "A grandmother placing her ring into a grandchild's palm with both hands cupped around the younger hand — the transmission that carries an entire life in the object", emotionType: "generational love and loss", visualSignals: ["older hands cradling younger hands", "the ring between their palms", "both looking at the object not each other", "the grandmother's hands trembling slightly"], industryIds: ["jewellery"], tags: ["grandmother", "heirloom", "transmission", "cupped-hands"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:jewellery:husband-birthday-surprise-reaction", kind: "emotional_moment", moment: "A wife opening a jewellery birthday gift — her husband watching her face from across the table, her expression shifting from curious to delighted to tearful, the arc of feeling visible in seconds", emotionType: "layered surprise and love", visualSignals: ["expression moving through three states", "husband's face reading her face", "hands covering the piece", "reaching for his hand"], industryIds: ["jewellery"], tags: ["birthday", "wife", "husband-watching", "surprise"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:jewellery:christmas-morning-unexpected-gift", kind: "emotional_moment", moment: "Opening an unexpected jewellery box on Christmas morning — the gift that was not anticipated, the small package from the pile that is heavier than it looks", emotionType: "delighted surprise", visualSignals: ["small box emerging from wrapping", "everyone watching", "the first moment of recognition", "looking up at the giver with eyes that say 'you didn't'"], industryIds: ["jewellery"], tags: ["christmas", "unexpected", "small-box", "surprise"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:jewellery:mothers-day-children-presenting", kind: "emotional_moment", moment: "Children presenting a Mother's Day jewellery gift they chose themselves — the pride on their faces matched by the mother's understanding that the imperfect choice is the perfect choice", emotionType: "tender parental love", visualSignals: ["children presenting with formality", "mother's face reading the object and the givers", "tears that the children don't quite understand", "the hug that is longer than usual"], industryIds: ["jewellery"], tags: ["mothers-day", "children-presenting", "tender", "imperfect-perfect"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:jewellery:self-purchase-achievement", kind: "emotional_moment", moment: "A person placing a jewellery purchase on the counter for themselves — the small internal celebration of deciding they deserve it, the clerk unaware of what this moment means", emotionType: "self-recognition and pride", visualSignals: ["card extended across counter alone", "the slight lift of the chin", "the piece going into the bag", "walking out with something different in the posture"], industryIds: ["jewellery"], tags: ["self-purchase", "achievement", "alone", "pride"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Wearing emotional moments (12) ────────────────────────────────────────────
  { id: "emotional_moment:jewellery:wedding-ring-on-widows-hand", kind: "emotional_moment", moment: "A widowed person touching their wedding ring alone — the unconscious reach to the object that still says everything about who they are and who they loved", emotionType: "grief and enduring love", visualSignals: ["one hand going to the ring", "looking away or eyes closed", "the slight pressure of the touch", "everything in the gesture"], industryIds: ["jewellery"], tags: ["widow", "wedding-ring", "touching", "grief"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:jewellery:wearing-mothers-ring-after-loss", kind: "emotional_moment", moment: "Person putting on a deceased parent's ring for the first time after the loss — the ring now on their own hand, the parent's presence contained in the weight of the metal", emotionType: "grief transformed to keeping-close", visualSignals: ["ring placed on finger slowly", "pause before looking at it", "the expression of someone trying not to cry but looking at something they love", "touching it gently with the other hand"], industryIds: ["jewellery"], tags: ["mothers-ring", "loss", "first-wearing", "keeping-close"], priority: 1, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:jewellery:bride-seeing-full-look-in-mirror", kind: "emotional_moment", moment: "A bride seeing herself in the mirror with all her jewellery on for the first time — the earrings, the necklace, the hair pin — the complete bridal picture snapping into place", emotionType: "readiness and self-recognition", visualSignals: ["full mirror reflection", "hand touching earring", "eyes taking in the whole", "the deep breath before the tears that don't quite come"], industryIds: ["jewellery"], tags: ["bride", "full-look", "mirror", "readiness"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:jewellery:daughter-in-mothers-pearl-necklace", kind: "emotional_moment", moment: "A daughter wearing her mother's pearl necklace to a formal event — catching her own reflection and seeing something of her mother in it, the recognition unexpected and sharp", emotionType: "generational recognition", visualSignals: ["reflection caught unexpectedly", "hand going to the necklace", "the complex expression of seeing the parent in yourself", "standing still for a moment before continuing"], industryIds: ["jewellery"], tags: ["daughter", "mothers-pearls", "reflection", "recognition"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── In-store emotional moments (8) ────────────────────────────────────────────
  { id: "emotional_moment:jewellery:finding-exact-right-ring", kind: "emotional_moment", moment: "Customer trying on multiple rings and then finding the one — the moment the right ring is on the finger and everything else falls away, the decision made without needing to be made", emotionType: "certainty and recognition", visualSignals: ["trying on stops", "looking at hand rather than the others", "slight smile before full awareness", "turning to the associate with the knowledge already on the face"], industryIds: ["jewellery"], tags: ["finding-the-one", "certainty", "recognition", "right-ring"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:jewellery:collecting-repaired-heirloom", kind: "emotional_moment", moment: "Collecting an heirloom that was repaired — the piece returned whole again, the particular relief of an irreplaceable object restored to integrity", emotionType: "relief and restoration", visualSignals: ["piece being placed on the counter", "inspection of the repair", "the exhale on seeing it's right", "holding it with different care than before"], industryIds: ["jewellery"], tags: ["repair", "heirloom", "collecting", "restoration"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:jewellery:custom-piece-reveal-at-collection", kind: "emotional_moment", moment: "Collecting a bespoke commissioned piece for the first time — the box opened at the counter, the piece that was only a sketch now in physical form, the maker watching the response", emotionType: "excited anticipation meeting reality", visualSignals: ["box opening at the counter", "the piece visible for the first time", "looking at the jeweller who made it", "the moment of 'it's exactly right'"], industryIds: ["jewellery"], tags: ["bespoke", "collection", "reveal", "maker"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
];
