import type { RelationshipKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const JEWELLERY_RELATIONSHIPS: RelationshipKnowledgeNode[] = [
  // ── Romantic couple relationships (15) ────────────────────────────────────────
  { id: "relationship:jewellery:proposer-and-recipient", kind: "relationship", description: "The person proposing and the person receiving the ring — the initiator and the answerer, the giver of the object and the person who makes it mean something by saying yes", sceneRoles: ["proposer", "recipient"], industryIds: ["jewellery"], tags: ["proposal", "initiator", "recipient", "engagement"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "relationship:jewellery:long-married-couple-anniversary", kind: "relationship", description: "A couple married many years marking an anniversary with a new piece — the original rings still worn, the new piece added alongside them as evidence of continued choosing", sceneRoles: ["long-married couple"], industryIds: ["jewellery"], tags: ["anniversary", "long-married", "new-piece", "continued-choosing"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "relationship:jewellery:boyfriend-choosing-birthday-gift", kind: "relationship", description: "A man choosing a birthday gift for his partner — slightly outside his comfort zone, earnestly trying to match the piece to the person, the sales associate the unlikely bridge", sceneRoles: ["gift giver", "partner", "sales associate"], industryIds: ["jewellery"], tags: ["boyfriend", "birthday-gift", "choosing", "earnest"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:jewellery:newlyweds-first-morning-rings", kind: "relationship", description: "Newlyweds the morning after the ceremony — looking at each other's rings at the breakfast table, the objects still new to both bodies", sceneRoles: ["newlyweds"], industryIds: ["jewellery"], tags: ["newlyweds", "morning-after", "rings", "new-reality"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:jewellery:couple-buying-together", kind: "relationship", description: "A couple choosing their wedding bands together — the democratic process of picking the matching pieces they will wear for the rest of their lives", sceneRoles: ["couple", "jeweller"], industryIds: ["jewellery"], tags: ["couple", "wedding-bands", "choosing-together", "collaborative"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:jewellery:partner-wearing-gifted-piece", kind: "relationship", description: "Person noticing their partner wearing the piece they gave them — the giver spotting their gift on the wearer in an unguarded moment, the mutual awareness without needing to mention it", sceneRoles: ["giver", "wearer"], industryIds: ["jewellery"], tags: ["partner", "wearing", "gifted", "noticing"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Family relationships (15) ─────────────────────────────────────────────────
  { id: "relationship:jewellery:mother-daughter-passing-heirloom", kind: "relationship", description: "A mother giving her daughter a piece of significant family jewellery — the specific combination of grief at the need to pass it and joy in the giving", sceneRoles: ["mother", "daughter"], industryIds: ["jewellery"], tags: ["mother", "daughter", "heirloom", "passing-on"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "relationship:jewellery:grandmother-grandchild-inheritance", kind: "relationship", description: "A grandmother giving a grandchild jewellery — the skipped generation transfer that happens when the grandmother wants the object to outlive the immediate next chapter", sceneRoles: ["grandmother", "grandchild"], industryIds: ["jewellery"], tags: ["grandmother", "grandchild", "inheritance", "generational"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "relationship:jewellery:father-daughters-gift-milestone", kind: "relationship", description: "A father giving his daughter a significant piece for a milestone — graduation, 18th birthday, wedding day — the paternal gesture that marks the transition", sceneRoles: ["father", "daughter"], industryIds: ["jewellery"], tags: ["father", "daughter", "milestone", "transition"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:jewellery:children-and-parents-christmas-morning", kind: "relationship", description: "Children watching a parent open a jewellery gift on Christmas morning — the parent's surprised emotion witnessed by children who chose or contributed to the gift", sceneRoles: ["children", "parent"], industryIds: ["jewellery"], tags: ["children", "parent", "christmas", "witnessing-emotion"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:jewellery:adult-child-gifting-parent", kind: "relationship", description: "An adult child giving a parent a meaningful piece — the reversal of the gifting direction, the child now able to give something significant back", sceneRoles: ["adult child", "parent"], industryIds: ["jewellery"], tags: ["adult-child", "parent-gift", "reversal", "significant"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:jewellery:siblings-sharing-mothers-collection", kind: "relationship", description: "Adult siblings dividing a deceased mother's jewellery collection — the tender, complicated process of distributing objects that carry different memories for each", sceneRoles: ["adult siblings"], industryIds: ["jewellery"], tags: ["siblings", "mother", "collection", "dividing"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },

  // ── Friendship relationships (10) ─────────────────────────────────────────────
  { id: "relationship:jewellery:friends-seeing-engagement-ring", kind: "relationship", description: "Close friends seeing the engagement ring for the first time — the group reaction, the reaching for the hand, the joy that belongs to everyone who loves the person", sceneRoles: ["newly engaged person", "close friends"], industryIds: ["jewellery"], tags: ["friends", "engagement-ring", "group-reaction", "first-seeing"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:jewellery:friend-helping-choose-ring", kind: "relationship", description: "Best friend accompanying the buyer to help choose an engagement ring — the trusted second opinion, the person who knows what the recipient would love", sceneRoles: ["buyer", "best friend", "jeweller"], industryIds: ["jewellery"], tags: ["best-friend", "choosing", "trust", "second-opinion"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:jewellery:friendship-bracelet-gifted", kind: "relationship", description: "Friends exchanging matching or complementary jewellery pieces — the modern friendship bracelet at any age, the piece that marks the bond between two people", sceneRoles: ["friends"], industryIds: ["jewellery"], tags: ["friendship-jewellery", "matching", "bond", "exchange"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:jewellery:self-reward-after-achievement", kind: "relationship", description: "Person buying themselves a significant piece to mark their own achievement — the solo trip to the jeweller, the self-gift that acknowledges hard work without waiting for someone else to do it", sceneRoles: ["self"], industryIds: ["jewellery"], tags: ["self-reward", "achievement", "solo", "independent"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Jeweller relationships (10) ───────────────────────────────────────────────
  { id: "relationship:jewellery:goldsmith-customer-bespoke", kind: "relationship", description: "A goldsmith and a customer working through a bespoke commission — the trust required to hand the vision entirely to someone else's hands, and the pride that comes with the collection", sceneRoles: ["goldsmith", "customer"], industryIds: ["jewellery"], tags: ["goldsmith", "bespoke", "commission", "trust"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:jewellery:senior-associate-new-buyer", kind: "relationship", description: "An experienced sales associate with someone buying an engagement ring for the first time — the expertise that removes shame from questions and transforms anxiety into confidence", sceneRoles: ["experienced associate", "first-time buyer"], industryIds: ["jewellery"], tags: ["associate", "first-time-buyer", "expertise", "confidence"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:jewellery:jeweller-long-term-client", kind: "relationship", description: "A jeweller and a client who has bought from them for decades — the relationship that spans life stages, each piece in the client's collection from this one maker or store", sceneRoles: ["jeweller", "long-term client"], industryIds: ["jewellery"], tags: ["jeweller", "long-term", "decades", "loyalty"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:jewellery:valuation-appraiser-client", kind: "relationship", description: "A professional appraiser examining a client's pieces for insurance or estate purposes — the clinical expertise applied to the most emotionally loaded of objects", sceneRoles: ["appraiser", "client"], industryIds: ["jewellery"], tags: ["appraiser", "valuation", "insurance", "estate"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
];
