// Phase 8.6 — Creative Route Registry.
//
// All commercially-valid execution routes per industry.
// Routes are philosophically distinct — not quality variants.
// Every route is defensible with marketing strategy and commercial psychology.

import type { CreativeRoute } from "./types";

export const ROUTE_REGISTRY: CreativeRoute[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // FOOD & HOSPITALITY
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "food_dish_hero",
    title: "Signature Dish Hero",
    industryId: "food_hospitality",
    hero: "The signature dish at the moment of completion — sauce, garnish, and texture at peak visual state",
    heroType: "product_food",
    composition: "Centred product with radial negative space; dish at golden ratio; foreground and background elements frame without competing",
    photography: "50mm macro at plate height; single overhead key light; warm fill from left; steam or condensation visible; 1/125s",
    layout: "Image 65% | Dish name or restaurant name upper-right 20% | Menu context + reservation CTA lower 15%",
    marketing: "Appetite trigger as the primary conversion mechanism — the viewer sees the dish and wants to order it or visit to experience it",
    emotion: "Appetite and anticipation — 'I want to taste this'",
    productionNote: "The dish must be photographed within 90 seconds of plating — texture and temperature are the hero, not the plate itself",
    bestFor: ["menu", "launch", "food", "dish", "delivery", "order", "taste", "cuisine", "flavour"],
    notFor: ["grand opening", "brand launch", "chef brand", "luxury positioning"],
    baseScore: 82,
  },

  {
    id: "food_chef_hero",
    title: "Chef Hero — Craftsmanship & Authority",
    industryId: "food_hospitality",
    hero: "Executive chef at the decisive moment of plating — the final placement of the garnish, the last adjustment before the dish leaves the pass",
    heroType: "human_chef",
    composition: "Diagonal movement from chef's body (lower-left) to the finished dish (upper-right); chef's hands are the compositional apex",
    photography: "85mm at counter height; warm overhead kitchen light; chef's face partially lit from the right; 1/200s to freeze hand precision",
    layout: "Image 65% | Restaurant name upper-left 20% | Reservation date + CTA lower 15% — no price",
    marketing: "Chef credibility as quality signal — the viewer trusts the kitchen because they trust the person in it",
    emotion: "Craft reverence — 'Someone who cares this much about the detail will care about my experience'",
    productionNote: "Direct the chef to the moment before the dish is released, not mid-preparation — the final review is more powerful than the cooking",
    bestFor: ["chef", "fine dining", "grand opening", "brand", "luxury", "signature", "culinary", "prestige"],
    notFor: ["delivery", "fast food", "casual", "menu promotion", "discount offer"],
    baseScore: 88,
  },

  {
    id: "food_grand_opening_event",
    title: "Grand Opening — The Founders' Threshold",
    industryId: "food_hospitality",
    hero: "Founder or chef at the restaurant entrance at the moment before opening — the threshold between years of planning and the first guest",
    heroType: "human_owner",
    composition: "Founder at threshold with interior warm behind them, street or entrance visible; slight backlight from interior; 30-degree off-centre",
    photography: "35mm at human height; available interior light from behind + natural exterior light; 1/60s — slight softness communicates the live moment",
    layout: "Image 60% | Opening date upper-centre (documentary editorial) 20% | Reservation + location lower 20%",
    marketing: "The founding moment communicates authenticity and personal investment — 'someone put everything into this'",
    emotion: "Beginning and possibility — 'I want to be there at the start'",
    productionNote: "Photograph at actual opening day morning before the first guest arrives — the emotion is real and cannot be staged convincingly",
    bestFor: ["grand opening", "new restaurant", "opening", "launch", "first day", "new location", "founder"],
    notFor: ["menu promotion", "delivery", "established restaurant", "anniversary"],
    baseScore: 85,
  },

  {
    id: "food_luxury_interior",
    title: "Luxury Interior — The Space Itself",
    industryId: "food_hospitality",
    hero: "The dining room at its most composed — tables set, candles lit, no guests yet; the room communicates the experience before anyone sits in it",
    heroType: "environment_interior",
    composition: "Wide architectural interior; tables in the foreground; receding depth to a focal point (fireplace, artwork, or open kitchen); warm light sources visible",
    photography: "24mm at seated eye level; available restaurant light only; f/8 for depth; 1/15s — tripod required; warm 2800K environment",
    layout: "Image 70% | Restaurant name upper overlay 15% | Reservation CTA lower 15% — minimal typography",
    marketing: "The room is the promise — luxury restaurant patrons are buying an environment as much as a meal",
    emotion: "Elevated anticipation — 'I am already imagining sitting here'",
    productionNote: "Photograph one hour before opening service: all tables set, all candles lit, kitchen on but no guests — this is the room at its intentional peak",
    bestFor: ["anniversary", "ambiance", "interior", "design", "luxury", "environment", "restaurant bar", "intimate dining"],
    notFor: ["delivery", "fast food", "casual", "menu promotion", "chef brand"],
    baseScore: 78,
  },

  {
    id: "food_celebration_lifestyle",
    title: "Celebration Lifestyle — The Table They Remember",
    industryId: "food_hospitality",
    hero: "A group of diners at the decisive moment of a celebration — the toast, the laugh, the moment everyone is present at the table simultaneously",
    heroType: "human_customer",
    composition: "Wide table shot; group in the foreground; restaurant environment receding; the food visible on the table but subordinate to the human moment",
    photography: "35mm at seated height; warm restaurant ambient light; 1/80s — slight motion in gestures communicates life; no flash",
    layout: "Image 65% | Occasion headline upper 20% | Restaurant name + booking CTA lower 15%",
    marketing: "Social occasion positioning — the restaurant sells itself as the place where memories are made, not where meals are served",
    emotion: "Belonging and celebration — 'This is where we should be for this occasion'",
    productionNote: "Cast a real group with genuine chemistry; directed happiness reads immediately as staged — the toast should be a real toast to a real reason",
    bestFor: ["occasion", "celebration", "birthday", "anniversary dining", "date night", "group dining", "festive", "special occasion"],
    notFor: ["fine dining solo", "chef brand", "delivery", "fast food"],
    baseScore: 76,
  },

  {
    id: "food_open_kitchen",
    title: "Open Kitchen Story — Transparency as Trust",
    industryId: "food_hospitality",
    hero: "The kitchen brigade visible through an open kitchen window or pass — organised activity, multiple chefs in frame, the controlled chaos of service",
    heroType: "mixed",
    composition: "Shot from the dining room looking through the kitchen opening; kitchen brigade in the background, food in the foreground pass; depth layers create narrative",
    photography: "35mm wide at pass height; warm kitchen light versus cooler dining room light creating natural depth; 1/250s to freeze kitchen activity",
    layout: "Image 65% | 'Nothing hidden here' or brand statement upper 20% | CTA lower 15%",
    marketing: "Kitchen transparency as a trust signal — modern diners respond to visible preparation as a quality and integrity cue",
    emotion: "Trust through visibility — 'I can see exactly how this is made and by whom'",
    productionNote: "Photograph during actual service (mid-afternoon prep service is ideal) — the organised energy of a real kitchen in operation cannot be staged",
    bestFor: ["modern dining", "casual fine dining", "farm to table", "transparency", "health conscious", "contemporary"],
    notFor: ["traditional fine dining", "delivery", "fast food", "chef brand campaign"],
    baseScore: 73,
  },

  {
    id: "food_couple_experience",
    title: "Couple Experience — The Evening That Mattered",
    industryId: "food_hospitality",
    hero: "A couple at the table at the exact moment the evening becomes memorable — not the kiss, not the proposal, but the moment of real connection between people who are genuinely glad to be there",
    heroType: "human_customer",
    composition: "Two-shot across the table; shallow depth of field; the food and restaurant visible but soft; their attention is on each other, not the camera",
    photography: "85mm at seated eye level; available candlelight + restaurant ambient; f/2.0; 1/80s; warm, slightly underexposed — communicates intimacy",
    layout: "Image 70% | Occasion tagline upper 15% | Restaurant name + booking CTA lower 15%",
    marketing: "Romantic occasion positioning for couples — date night, anniversary, proposal venues",
    emotion: "Intimacy and presence — 'This is the place that makes the evening feel right'",
    productionNote: "Cast a real couple with real chemistry; direct them to look at each other mid-conversation, not at the camera or the food — the restaurant exists around them, not between them",
    bestFor: ["date night", "romantic", "couple", "anniversary dinner", "proposal venue", "intimate"],
    notFor: ["family dining", "group dining", "casual", "delivery", "lunch"],
    baseScore: 80,
  },

  {
    id: "food_culinary_art",
    title: "Culinary Art — Abstract Excellence",
    industryId: "food_hospitality",
    hero: "An extreme close-up of the dish that elevates it to visual art — the sauce drop, the micro-herb placement, the textural contrast at 1:1 macro",
    heroType: "product_close_up",
    composition: "Macro abstraction; dish fills the entire frame; the plate edge barely visible; a single detail (foam, leaf, reduction) occupies the compositional apex",
    photography: "100mm macro; single overhead softbox with one side blocked; background utterly dark; 1/200s; the image could be a painting",
    layout: "Image 75% | Restaurant name minimal lower-right 15% | CTA 10% — typography is almost absent",
    marketing: "Positions the restaurant as a culinary art institution; targets the diner who eats with eyes and reviews restaurants on Instagram",
    emotion: "Aesthetic reverence — 'This is not just food; this is considered art that I get to experience'",
    productionNote: "This route requires a food stylist separate from the chef; the dish must be art-directed for the camera, not for eating",
    bestFor: ["michelin", "fine dining", "gastronomy", "premium", "experimental", "tasting menu", "haute cuisine"],
    notFor: ["casual dining", "family restaurant", "delivery", "affordable", "grand opening"],
    baseScore: 71,
  },

  {
    id: "food_delivery_family",
    title: "Delivery Moment — The Family Reach",
    industryId: "food_hospitality",
    hero: "Multiple family hands reaching simultaneously into an open delivery box — the moment everyone gets what they wanted at the same time",
    heroType: "human_family",
    composition: "Bird's-eye view of the open box on the table; multiple hands in frame from different positions; the food visible and inviting; no faces required",
    photography: "24mm overhead; warm kitchen/dining room light; 1/200s to freeze the simultaneous reach; vibrant, warm colour temperature",
    layout: "Image 65% | Time promise headline upper 20% ('30 minutes. Hot when it arrives.') | Order CTA lower 15%",
    marketing: "Family convenience as the conversion trigger — the viewer wants to be the family in that moment",
    emotion: "Family satisfaction — 'Everyone gets what they want and no one has to cook'",
    productionNote: "The overhead shot requires a ladder or elevated position; coordinate the hands to reach simultaneously — timing is the single most important production detail",
    bestFor: ["delivery", "order online", "family meal", "convenience", "quick meal", "home delivery"],
    notFor: ["fine dining", "grand opening", "chef brand", "luxury"],
    baseScore: 83,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // HEALTHCARE / DENTAL
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "dental_patient_discovery",
    title: "Patient Discovery — The Private Smile",
    industryId: "healthcare_dental",
    hero: "A patient seeing their smile for the first time in the mirror — the exact moment of recognition before the full reaction arrives",
    heroType: "human_customer",
    composition: "Mirror frame-within-frame; patient's face in the mirror's reflection; dentist partially visible in background — the patient is the hero, the professional is the proof",
    photography: "50mm at patient eye level; warm natural window + clinic ambient; 1/80s; no clinical equipment in frame",
    layout: "Image 65% | Discovery headline upper 20% | Clinic name + free consultation CTA lower 15%",
    marketing: "Transformation as a personal discovery — the patient is the hero of their own story, not the clinic's portfolio",
    emotion: "Self-recognition — 'That is the smile I have been carrying inside this whole time'",
    productionNote: "Cast a real patient if possible; direct them to look at the mirror as though seeing a result for the first time — the expression must be genuine, not performed happiness",
    bestFor: ["smile makeover", "cosmetic dental", "veneers", "whitening", "transformation", "aesthetic"],
    notFor: ["general checkup", "emergency dental", "pain relief", "family dentistry"],
    baseScore: 88,
  },

  {
    id: "dental_doctor_listening",
    title: "Doctor Who Listens — Trust Through Attention",
    industryId: "healthcare_dental",
    hero: "Dentist or doctor leaning forward with clasped hands, looking at the patient — the specific posture of someone fully listening",
    heroType: "human_professional",
    composition: "Doctor in the foreground-right, slightly lower than patient's eye level; the clinic environment clean and warm behind; patient partially visible in left frame",
    photography: "50mm at patient-chair height; warm clinic ambient + natural window; doctor sharp, background soft; 1/80s",
    layout: "Image 60% | Trust headline upper 25% | Clinic credential + appointment CTA lower 15%",
    marketing: "The doctor who listens as a differentiator in a category where patients feel unheard — 'You will not be rushed'",
    emotion: "Being genuinely heard — the relief of a professional who takes time",
    productionNote: "Direct the doctor to be mid-listen, not mid-speak — eyes focused on where the patient's face would be, posture open and slightly forward",
    bestFor: ["general healthcare", "family doctor", "consultation", "trust", "patient care", "healthcare clinic"],
    notFor: ["emergency", "cosmetic only", "technology showcase"],
    baseScore: 84,
  },

  {
    id: "dental_natural_smile",
    title: "Natural Smile — Confidence in Real Life",
    industryId: "healthcare_dental",
    hero: "A real person in a real moment of genuine laughter or smile — not a posed dental-advertisement smile, but the specific involuntary smile of someone who has forgotten they are being photographed",
    heroType: "human_customer",
    composition: "Three-quarter portrait in a real-life setting (café, street, home) — the clinic is absent from the frame, only the smile is the product",
    photography: "85mm at eye level; natural outdoor or window light; f/2.0; 1/500s; candid or candid-directed",
    layout: "Image 70% | Result headline upper 15% | Clinic name + CTA lower 15%",
    marketing: "The smile as a life upgrade — the before is implied (not shown); the after is real life, not a clinic photograph",
    emotion: "Confident ease — 'She has stopped hiding her smile'",
    productionNote: "Direct to tell a joke or recount a funny story; photograph the genuine response — the photo is taken 2 seconds after the punchline, not during the pose",
    bestFor: ["confidence", "social confidence", "smile", "whitening", "lifestyle", "young adults"],
    notFor: ["clinical procedure", "fear reduction", "emergency", "family dentistry"],
    baseScore: 80,
  },

  {
    id: "dental_clean_technology",
    title: "Advanced Technology — Clean Confidence",
    industryId: "healthcare_dental",
    hero: "The clinic's technology shown in a warm, non-threatening context — a clean digital X-ray display, a modern chair in natural light, equipment that looks precise rather than frightening",
    heroType: "environment_interior",
    composition: "Clean clinic interior; equipment present but contextualised; natural light dominant; no sterile blue-white lighting; one warm detail (plant, artwork) in frame",
    photography: "35mm wide at patient eye level; natural window light primary; warm fill; 1/30s tripod; clinic looks like a considered space, not a medical facility",
    layout: "Image 65% | Technology credential headline 20% | Clinic name + appointment CTA 15%",
    marketing: "Technology as precision and efficiency, not as intimidation — 'this clinic is ahead of others; you will get better care faster'",
    emotion: "Confident trust — 'I am in good hands here'",
    productionNote: "All clinical instruments must be covered or off-frame; only the headline technology should be visible and it should look like a precision instrument, not medical equipment",
    bestFor: ["technology", "digital dentistry", "laser", "painless", "advanced", "specialist"],
    notFor: ["smile makeover", "lifestyle", "family dentistry", "comfort-first messaging"],
    baseScore: 72,
  },

  {
    id: "dental_family_trust",
    title: "Family Dentistry — The Dentist They Trust",
    industryId: "healthcare_dental",
    hero: "A child in the dental chair who is visibly not afraid — looking at the dentist with the specific expression of a child who trusts this person",
    heroType: "human_customer",
    composition: "Child in chair; dentist's face at child's level (kneeling or seated); parent partially visible at frame's edge; the room is warm and unintimidating",
    photography: "50mm at child eye level; warm clinic ambient; 1/80s; no instruments visible; dentist and child are the only in-focus elements",
    layout: "Image 65% | Trust headline upper 20% | Clinic name + family appointment CTA 15%",
    marketing: "Family first visits and fear reduction — 'this is the dentist children are not afraid of'",
    emotion: "Parental relief — 'My child is not scared here'",
    productionNote: "Real child, real dentist; the child must be genuinely comfortable — directed acting for a nervous child reads immediately. If the child is not naturally comfortable, this route should not be used",
    bestFor: ["family dentistry", "children", "kids", "first visit", "fear reduction", "family"],
    notFor: ["cosmetic", "specialist", "adult only"],
    baseScore: 79,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // REAL ESTATE
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "realestate_ownership_moment",
    title: "Ownership Moment — Measuring the Feeling",
    industryId: "real_estate",
    hero: "A future owner experiencing the empty space — arms slightly open, measuring what it will feel like to live here, not looking at the view but at the room",
    heroType: "human_customer",
    composition: "Subject small against the room at golden hour; vast light-filled space around them; they are placing themselves in the space mentally",
    photography: "24mm wide at standing height; golden hour from the windows; subject in the lower-right third; available light only; 1/80s",
    layout: "Image 70% | Ownership feeling headline right 15% | Project name + inquiry CTA lower 15% — no price",
    marketing: "The ownership feeling before the ownership fact — the viewer imagines living here before buying here",
    emotion: "Imagined belonging — 'I am already composing my life in this space'",
    productionNote: "Direct the subject to walk the perimeter of the empty room and stop at the point where they feel the space most — photograph them at that moment of stillness",
    bestFor: ["luxury launch", "new project", "brand campaign", "premium", "lifestyle"],
    notFor: ["affordable homes", "price-led", "urgent sale", "resale"],
    baseScore: 90,
  },

  {
    id: "realestate_family_milestone",
    title: "Family Milestone — The Room That Changes Everything",
    industryId: "real_estate",
    hero: "A child spinning or playing in an empty room while parents watch from the doorway — the specific moment a family understands what this home will mean",
    heroType: "human_family",
    composition: "Wide shot from doorway; child in the room; parents at the threshold; one cardboard box in the corner; available light from windows",
    photography: "35mm at door height; warm afternoon window light; 1/200s to freeze the child's movement; parents slightly soft in the foreground",
    layout: "Image 65% | Family feeling headline upper 20% | RERA + EMI framing + CTA lower 15%",
    marketing: "Family aspiration as the conversion trigger — 'this home creates the childhood I want my child to have'",
    emotion: "Parental love and provision — 'I did this for them'",
    productionNote: "Cast a real family; direct the child to explore the empty room naturally without staging; parents at the doorway watching — their arm tightening around each other is the detail that converts",
    bestFor: ["affordable homes", "family housing", "first home", "2bhk", "3bhk", "family", "children", "new home"],
    notFor: ["luxury launch", "studio apartment", "investment property", "commercial"],
    baseScore: 86,
  },

  {
    id: "realestate_property_architecture",
    title: "Architecture as Promise — The Building Itself",
    industryId: "real_estate",
    hero: "The building's façade at golden hour — architectural lines, the quality of construction visible, the scale communicating aspiration without a person in frame",
    heroType: "environment_exterior",
    composition: "Low angle looking up; building fills the upper two-thirds; sky at golden hour in the upper third; surrounding city context gives scale",
    photography: "24mm ultra-wide; golden hour from street level; 1/250s; architectural composition with converging lines communicating ambition",
    layout: "Image 70% | Project name upper overlay 15% | Location + inquiry CTA lower 15%",
    marketing: "The building as a statement of quality — for buyers who respond to architecture as status",
    emotion: "Aspiration through scale — 'I want to live in something that looks like this'",
    productionNote: "Golden hour timing is not optional — the warm directional light makes concrete look warm and aspirational; grey overcast light makes the same building look institutional",
    bestFor: ["premium launch", "architectural showcase", "high-rise", "luxury tower", "iconic building"],
    notFor: ["affordable homes", "family housing", "interior-led campaign", "possession-ready"],
    baseScore: 75,
  },

  {
    id: "realestate_interior_lifestyle",
    title: "Lifestyle Interior — The Life Already Lived Here",
    industryId: "real_estate",
    hero: "A specific room in the show flat styled to communicate a life in progress — morning light through the kitchen, a book on the reading chair, coffee on the counter",
    heroType: "environment_interior",
    composition: "Interior wide at human eye level; styled with specific personal details; room communicates a specific personality, not a generic show-home",
    photography: "24mm at standing height; natural morning window light + warm interior ambient; 1/30s tripod; no harsh shadows; the room looks lived-in and aspirational simultaneously",
    layout: "Image 70% | Interior lifestyle headline upper 15% | Project name + site visit CTA lower 15%",
    marketing: "The life you will live here — rather than the property you will buy here",
    emotion: "Domestic aspiration — 'I can see myself making coffee in this kitchen'",
    productionNote: "The styling detail that converts: one personal object that has no business being in a show flat — a specific book, a half-full coffee cup, a plant that is slightly imperfect — communicating that a real life would happen here",
    bestFor: ["luxury apartments", "lifestyle positioning", "interior design", "show flat", "premium", "design-led"],
    notFor: ["affordable first home", "under-construction", "plot sale"],
    baseScore: 78,
  },

  {
    id: "realestate_location_advantage",
    title: "Location Advantage — The City From Here",
    industryId: "real_estate",
    hero: "The view from the apartment window or balcony — the specific city, the specific vantage point, the specific quality of this location visible in one frame",
    heroType: "environment_exterior",
    composition: "Shot from inside the apartment looking out through the window; window frame creating the compositional border; city or landscape as the subject; resident in the frame if present, they are a secondary element",
    photography: "35mm at window height; natural exterior light; resident in silhouette if included; f/8 for city sharpness through the window; 1/250s",
    layout: "Image 70% | Location credential headline upper 15% | Project name + site visit CTA lower 15%",
    marketing: "Location as a permanent advantage — 'this view does not depreciate'",
    emotion: "Pride of address — 'This is what I see every morning'",
    productionNote: "Only viable if the location genuinely produces a compelling view — do not use this route for a project with an ordinary view; it will be immediately credible or immediately disqualified",
    bestFor: ["prime location", "sea view", "city view", "location", "connectivity", "metro", "premium"],
    notFor: ["affordable", "interior-led", "under-construction without view"],
    baseScore: 77,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // JEWELRY / LUXURY
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "jewelry_private_moment",
    title: "Private Moment — Before Calling Family",
    industryId: "jewelry_luxury",
    hero: "The bride alone, touching the necklace in the mirror for the first time — the private moment before sharing the moment with family",
    heroType: "human_customer",
    composition: "Mirror-within-frame; bride's reflection in the left two-thirds; her direct back in the right third; the jewellery visible in the reflection at the golden ratio",
    photography: "85mm at mirror height; warm morning window light; f/2.0; 1/200s; no studio lighting",
    layout: "Image 70% | Intimate headline upper-right 15% | Brand name + private consultation CTA lower 15%",
    marketing: "The private moment of self-recognition — the jewellery as the subject of the most personal morning",
    emotion: "Private joy — 'This is the moment before the morning becomes shared'",
    productionNote: "Direct the bride to be alone in the room; do not add a family member for the advertisement — the power is in the solitude before the celebration",
    bestFor: ["bridal", "wedding jewellery", "engagement", "luxury", "occasion", "personal"],
    notFor: ["gifting", "men's jewellery", "everyday jewellery", "promotion"],
    baseScore: 92,
  },

  {
    id: "jewelry_gifting_moment",
    title: "The Gift Reveal — Witnessed Discovery",
    industryId: "jewelry_luxury",
    hero: "The moment of a jewellery gift being received — specifically the instant of discovery when the box is opened, photographed from the giver's perspective",
    heroType: "human_customer",
    composition: "Close on the recipient's face as the box opens; the jewellery is visible but the face is the hero; giver visible in soft focus at the frame's edge",
    photography: "85mm at seated eye level; warm ambient light; f/2.0; 1/160s; the expression of discovery is the photograph",
    layout: "Image 70% | Gifting headline upper 15% | Brand name + gifting CTA lower 15%",
    marketing: "The gift as a memory creation — 'the expression on her face at that moment'",
    emotion: "The pleasure of giving — the giver's pride at the receiver's expression",
    productionNote: "Cast a real couple; the discovery must be genuine — open the box for the first time on camera, not a staged re-opening; genuine surprise is photographable, acted surprise is not",
    bestFor: ["gifting", "anniversary", "birthday gift", "occasion jewellery", "men's purchase", "gift"],
    notFor: ["bridal", "self-purchase", "everyday wear"],
    baseScore: 84,
  },

  {
    id: "jewelry_product_craft",
    title: "Craftsmanship Close-Up — The Jeweller's Hour",
    industryId: "jewelry_luxury",
    hero: "An extreme close-up of the jewellery piece that communicates its craftsmanship — the stone setting, the gold filigree, the precise engraving",
    heroType: "product_close_up",
    composition: "100mm macro; piece fills the frame; single light source from one side creating dimensionality; background dark velvet or marble — nothing competes",
    photography: "100mm macro; single directional light (window or LED panel from left); ring or piece at slight angle; 1/200s; ISO 200 for clean shadow detail",
    layout: "Image 75% | Heritage or craft headline upper 15% | Brand + collection name 10%",
    marketing: "Craftsmanship as heritage — the piece is more than jewellery; it is the product of a tradition",
    emotion: "Aesthetic appreciation — 'I am looking at something made by a person who cared about every detail'",
    productionNote: "A jewellery photo stylist is required; the angle and light direction must be rehearsed with the actual piece — different pieces reveal their craftsmanship differently",
    bestFor: ["heritage brand", "handcrafted", "artisan", "craft", "collection launch", "high jewellery"],
    notFor: ["bridal campaign", "gifting", "occasion", "mass market"],
    baseScore: 79,
  },

  {
    id: "jewelry_lifestyle_occasion",
    title: "Occasion Lifestyle — Jewellery in Its Natural Moment",
    industryId: "jewelry_luxury",
    hero: "A woman wearing the jewellery in the specific occasion it was designed for — at a celebration, at a wedding, at an evening event where the jewellery is part of her story",
    heroType: "human_customer",
    composition: "Full or three-quarter portrait at the occasion; jewellery visible but not isolated; the occasion context communicates who wears this and when",
    photography: "85mm at eye level; occasion lighting (warm ambient, candlelight, or golden hour); f/2.0; 1/200s; documentary feel",
    layout: "Image 70% | Occasion headline upper 15% | Brand + occasion CTA lower 15%",
    marketing: "Jewellery as occasion identity — the piece completes the statement of the evening",
    emotion: "Occasion confidence — 'This is the jewellery that belongs to this moment'",
    productionNote: "The occasion must be visually specific — not a generic 'nice event' but a recognisable Indian celebration context; the jewellery is the consistent element across different occasions",
    bestFor: ["occasion", "festive", "diwali", "wedding guest", "celebration", "lifestyle", "fashion jewellery"],
    notFor: ["heritage craft", "high jewellery", "everyday", "office wear"],
    baseScore: 82,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // FINANCIAL SERVICES
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "finance_responsible_act",
    title: "Responsible Act — The Cover Amount at Midnight",
    industryId: "financial_services",
    hero: "A father at his desk at 11:30 PM, index finger touching the cover amount on his laptop screen — the private act of protection",
    heroType: "human_customer",
    composition: "Desk level; father three-quarter profile; laptop screen as primary light source; family bedroom door visible and slightly open in background",
    photography: "35mm at desk level; laptop screen (warm white) as only light; 1/80s; ISO 1600; slight grain communicates authentic late-night moment",
    layout: "Image 60% | Honest arithmetic headline upper 20% | Brand + calculation CTA lower 20%",
    marketing: "The delayed responsible act made present — 'the father who does the hard thing when everyone is asleep'",
    emotion: "Quiet responsibility — 'I am doing this because they are asleep upstairs'",
    productionNote: "The cold cup of tea on the desk is the production detail that converts — it communicates he has been here since the family went to bed and has not stopped to finish his tea",
    bestFor: ["life insurance", "term plan", "family protection", "insurance", "protection", "cover"],
    notFor: ["investment", "business insurance", "health insurance standalone", "retirement"],
    baseScore: 90,
  },

  {
    id: "finance_retirement_planning",
    title: "Retirement Planning — The Morning After the Career",
    industryId: "financial_services",
    hero: "A couple in their early 60s at the specific moment they understand that everything they planned for is available to them now — looking at the morning, not at a screen",
    heroType: "human_customer",
    composition: "Wide shot of the couple at home in morning light; no phones, no laptops; they are present in the morning they planned for; the house around them communicates comfort",
    photography: "50mm at seated height; warm morning window light; 1/80s; natural, unhurried",
    layout: "Image 65% | Planning horizon headline upper 20% | Brand + planning consultation CTA lower 15%",
    marketing: "The morning after the career — the specific feeling of options being available rather than duties",
    emotion: "Freedom earned — 'Everything we planned for is here now'",
    productionNote: "The couple must not be looking at any screen or device — they are experiencing the morning they planned for; presence is the product",
    bestFor: ["retirement", "pension", "wealth management", "planning", "long-term", "investment"],
    notFor: ["term insurance", "family protection", "young earners", "immediate need"],
    baseScore: 80,
  },

  {
    id: "finance_business_protection",
    title: "Business Protection — The Commitment That Protects Others",
    industryId: "financial_services",
    hero: "An Indian business owner at their desk at a moment of business planning — surrounded by the evidence of a business they built and now protect",
    heroType: "human_owner",
    composition: "Business environment; owner in three-quarter profile looking at plans or accounts; the business artefacts around them communicate investment and value",
    photography: "50mm at desk level; warm office ambient; 1/80s; natural business environment, not a photostudio",
    layout: "Image 60% | Business protection headline upper 25% | Brand + consultation CTA lower 15%",
    marketing: "Business insurance as responsibility to employees and partners — 'the business you built deserves the same protection as the family you built it for'",
    emotion: "Entrepreneurial responsibility — 'If something happens to me, what happens to them?'",
    productionNote: "The business environment must be specific and credible — the objects around the owner should represent their actual business type (retail display, architectural drawings, workshop tools)",
    bestFor: ["business insurance", "MSME", "entrepreneur", "self-employed", "business owner", "commercial"],
    notFor: ["family insurance", "individual term plan", "investment product"],
    baseScore: 77,
  },

  {
    id: "finance_specific_numbers",
    title: "The Honest Arithmetic — Numbers as Trust",
    industryId: "financial_services",
    hero: "A close-up of a hand writing specific numbers on paper — the cover amount, the premium, the arithmetic of protection made visible and personal",
    heroType: "product_item",
    composition: "Close on the hand and paper; warm desk light; specific numbers visible; no abstract imagery; the arithmetic is the hero",
    photography: "85mm macro at desk level; single warm overhead; 1/200s to freeze the writing hand; calculator or pen visible as supporting element",
    layout: "Image 60% | Specific arithmetic headline upper 25% | Brand + calculate CTA lower 15%",
    marketing: "Numbers as the trust signal — 'this brand communicates with specificity, not promises'",
    emotion: "Rational clarity — 'Finally, someone tells me exactly what I am getting for what I pay'",
    productionNote: "The handwritten numbers must be the actual numbers of the product being advertised — the viewer must be able to read them and verify them; fabricated numbers destroy trust if discovered",
    bestFor: ["specific offer", "product launch", "comparison campaign", "direct response", "calculation"],
    notFor: ["brand awareness", "emotional campaign", "retirement planning"],
    baseScore: 74,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // FITNESS / WELLNESS
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "fitness_mid_effort",
    title: "Mid-Effort Moment — The Hardest Point",
    industryId: "fitness_wellness",
    hero: "An Indian person at the hardest point of a specific exercise — not the beginning, not the completion, but the moment of maximum effort",
    heroType: "human_customer",
    composition: "Below-exercise-level; diagonal body line communicating ascent; trainer's hand at the lower frame edge having just let go",
    photography: "35mm below bar/platform level; available gym light; ISO 3200; 1/500s; the image looks like it was taken in a gym, not in a studio",
    layout: "Image 65% | Identity headline upper-right 20% | Month-to-month pricing + free session CTA lower 15%",
    marketing: "Identity formation — the viewer sees who they could be in the act of becoming, not the result of having become",
    emotion: "Identity aspiration — 'The person I am in the third rep is who I become'",
    productionNote: "The trainer's hand at the lower frame edge — just visible, having released — is the production detail that converts; it communicates support without dependence",
    bestFor: ["gym membership", "strength training", "personal training", "fitness", "workout", "first time"],
    notFor: ["yoga", "meditation", "weight loss focus", "group class only"],
    baseScore: 88,
  },

  {
    id: "fitness_group_energy",
    title: "Group Class Energy — The Collective Commitment",
    industryId: "fitness_wellness",
    hero: "A group class at the peak of synchronised effort — multiple people at the same moment of maximum exertion, photographed from the side",
    heroType: "human_customer",
    composition: "Wide side-on view; multiple bodies in similar positions creating rhythm; instructor in front visible but not dominant; the collective creates the energy",
    photography: "35mm at head height from the side; available studio light; 1/500s to freeze the movement peak; slight motion blur in peripheral members communicates energy",
    layout: "Image 65% | Community headline upper 20% | Class schedule + trial class CTA lower 15%",
    marketing: "Community as the commitment mechanism — 'it is easier to come back when they expect you'",
    emotion: "Collective belonging — 'I want to be in this room with these people'",
    productionNote: "Photograph during a real class at the specific exercise peak — staged group synchronisation is immediately visible; the class energy is only present in real classes",
    bestFor: ["group fitness", "yoga", "crossfit", "dance class", "community", "group class", "studio"],
    notFor: ["personal training", "solo gym", "home workout", "individual focus"],
    baseScore: 79,
  },

  {
    id: "fitness_trainer_relationship",
    title: "Trainer Relationship — The Professional Investment",
    industryId: "fitness_wellness",
    hero: "Personal trainer and client at the moment of genuine coaching — trainer's full attention on the client's form, not performing for the camera",
    heroType: "human_professional",
    composition: "Two-shot; trainer at client's side with eyes on the movement, not the camera; client performing the exercise; gym environment around them",
    photography: "50mm at workout height; available gym light; 1/250s; documentary feel — this is real coaching, not a photoshoot",
    layout: "Image 65% | Headline about professional attention 20% | Personal training CTA lower 15%",
    marketing: "Personal training as accountability and expertise — 'someone is watching your form because they care whether you improve'",
    emotion: "Professional investment — 'I have someone who is on my side'",
    productionNote: "Direct the trainer to correct form mid-exercise — the moment of professional attention is genuine only when the trainer is actually doing their job",
    bestFor: ["personal training", "PT", "one-on-one", "form correction", "premium gym", "results"],
    notFor: ["group class", "budget gym", "community focus", "self-directed"],
    baseScore: 81,
  },

  {
    id: "fitness_transformation_real",
    title: "Real Transformation — Progress, Not Perfection",
    industryId: "fitness_wellness",
    hero: "A real member at a measurable progress milestone — the specific moment they achieved something specific (ran 5km, lifted a personal best, completed a programme)",
    heroType: "human_customer",
    composition: "Portrait of the member at the completion moment — no before/after split; the pride of completion visible in their expression",
    photography: "50mm at eye level; available gym or outdoor light; 1/200s; the person is the complete story — no comparison image",
    layout: "Image 65% | Progress headline upper 20% | Member story CTA lower 15%",
    marketing: "Real progress as social proof — specific member, specific achievement, specific timeframe",
    emotion: "Pride of completion — 'I did something specific that I could not do before'",
    productionNote: "This route ONLY works with real members and real achievements — a staged transformation photograph is detectable and destroys trust; use only if the story is verifiable",
    bestFor: ["results", "transformation", "weight loss", "marathon", "programme", "before after story"],
    notFor: ["new gym opening", "product launch", "class promotion"],
    baseScore: 76,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // AUTOMOTIVE
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "auto_ownership_morning",
    title: "Ownership Morning — Keys in Hand",
    industryId: "automotive",
    hero: "New car owner in the driver's seat at the showroom, keys in hand, looking at the open showroom doors before the first drive",
    heroType: "human_customer",
    composition: "Passenger-seat perspective; owner left two-thirds in profile; hand on wheel; open showroom doors with city street ahead in the right third",
    photography: "50mm at passenger-seat height; warm showroom incandescent + natural daylight from open doors; 1/80s",
    layout: "Image 65% | Ownership feeling headline upper-right 20% | Model name + experience drive CTA lower 15%",
    marketing: "The ownership morning as the peak of the car purchase journey — the moment everything planned arrives",
    emotion: "Journey's end and beginning — 'Two years of planning and today it is finally mine'",
    productionNote: "Photograph at actual handover if possible; the salesperson stepping back at the frame's edge is the production detail that communicates ownership transfer",
    bestFor: ["car launch", "new car", "ownership", "sedan", "suv", "purchase", "handover"],
    notFor: ["commercial vehicle", "fleet", "test drive only", "features showcase"],
    baseScore: 92,
  },

  {
    id: "auto_road_freedom",
    title: "Road Freedom — The First Drive",
    industryId: "automotive",
    hero: "The car on a specific real Indian road at golden hour — not a race track, not a mountain highway, but an Indian highway or city road that communicates real ownership",
    heroType: "mixed",
    composition: "Shot from behind the car or from the side; car in motion; road receding ahead; Indian road context visible (highway, cityscape, or coastal road)",
    photography: "100mm tracking shot from vehicle; motion blur in road and surroundings; car sharp; golden hour directional light",
    layout: "Image 70% | Freedom headline upper 15% | Model + test drive CTA lower 15%",
    marketing: "Freedom of movement — the car as the enabler of the specific Indian road ownership experience",
    emotion: "Movement and freedom — 'The road is mine now'",
    productionNote: "Indian road context is mandatory — a generic highway loses all identification; choose a road that viewers in the target market will recognise and associate with freedom",
    bestFor: ["road trip", "highway", "weekend drive", "performance", "adventure", "freedom", "SUV"],
    notFor: ["luxury sedan", "city commute focus", "family utility focus"],
    baseScore: 79,
  },

  {
    id: "auto_family_journey",
    title: "Family Road Trip — Everyone Has Enough Room",
    industryId: "automotive",
    hero: "The family loading into the car for a road trip — organised chaos, the specific moment when the boot closes and everyone is inside and ready",
    heroType: "human_family",
    composition: "Wide exterior shot at street level; family activity visible; the car's practicality communicated through the space they are filling naturally",
    photography: "35mm wide at street level; morning light; 1/250s to capture the movement of loading; documentary feel",
    layout: "Image 65% | Family capability headline upper 20% | Model + boot space / seat specification + CTA lower 15%",
    marketing: "Space and practicality as family identity — 'this car fits the family, the bags, and the dog'",
    emotion: "Family capability — 'We all fit, everything fits, and we are ready'",
    productionNote: "Real family with real luggage, real energy — staged loading with empty bags reads as artificial immediately; the chaos should be real",
    bestFor: ["SUV", "MPV", "family car", "space", "road trip", "7 seater", "family"],
    notFor: ["sports car", "compact", "luxury sedan", "premium brand", "single owner"],
    baseScore: 81,
  },

  {
    id: "auto_tech_interior",
    title: "Technology Interior — What You Drive Inside",
    industryId: "automotive",
    hero: "The car's interior at night or dusk — dashboard illuminated, ambient lighting visible, the technology communicating as a premium environment from inside",
    heroType: "environment_interior",
    composition: "Interior shot from the driver's perspective; dashboard fills upper two-thirds; ambient lighting creates depth; steering wheel in foreground",
    photography: "35mm inside-out; ambient dashboard lighting as primary source; city lights visible through windscreen; 1/30s tripod; no flash",
    layout: "Image 70% | Interior technology headline upper 15% | Model + feature + CTA lower 15%",
    marketing: "The car's interior as a personal space — 'you live inside this car, not outside it'",
    emotion: "Premium personal environment — 'This is my space; it is designed for how I live'",
    productionNote: "All technology screens must show real content from the car's actual software — placeholder screens communicate prototype, not product",
    bestFor: ["electric vehicle", "connected car", "technology", "interior", "premium", "features"],
    notFor: ["exterior design showcase", "road performance", "family utility"],
    baseScore: 76,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // EDUCATION
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "edu_achievement_moment",
    title: "Achievement Moment — The Admission Letter",
    industryId: "education",
    hero: "A student alone at the kitchen table with the admission letter — the private moment before calling the family",
    heroType: "human_customer",
    composition: "Table level; student in three-quarter profile looking at the letter; old textbooks visible at frame edge; warm kitchen overhead light",
    photography: "50mm at table level; warm kitchen overhead light; 1/60s; documentary texture; class 12 textbooks visible at left frame edge",
    layout: "Image 65% | Journey headline upper-right 20% | Institution name + application CTA lower 15%",
    marketing: "The journey acknowledgement — 'we understand how long this took and what it means'",
    emotion: "Private achievement — 'Before it becomes everyone's news, it is mine alone for one more minute'",
    productionNote: "The class 12 textbook with yellow highlighter beside the admission letter is the production detail that converts — it communicates the span of the journey",
    bestFor: ["admissions", "college", "university", "application", "result", "achievement"],
    notFor: ["coaching", "skill course", "corporate training", "mid-career"],
    baseScore: 90,
  },

  {
    id: "edu_study_journey",
    title: "The Study Process — 5 AM and Still Going",
    industryId: "education",
    hero: "A student at the desk in the early hours — focused, not glamorous, in the specific unglamorous reality of serious study",
    heroType: "human_customer",
    composition: "Study desk at 5 AM; warm desk lamp as primary light source; textbooks, notes, and a water bottle; the student's concentration is the hero",
    photography: "50mm at desk level; warm desk lamp only; 1/80s; slight grain from low light; the image looks like study actually looks",
    layout: "Image 60% | Process headline upper 25% | Programme + coaching CTA lower 15%",
    marketing: "Coaching as the multiplier of effort already being made — 'you are already working this hard; we help the work convert into results'",
    emotion: "Earnest effort — 'I recognise this desk; I recognise this hour'",
    productionNote: "The desk must have evidence of real work — not a photogenic study setup but an actual desk where someone is studying: multiple notebooks, highlighted pages, water bottle (not coffee)",
    bestFor: ["coaching", "exam preparation", "JEE", "NEET", "UPSC", "study", "preparation"],
    notFor: ["undergraduate admissions", "online course", "corporate training"],
    baseScore: 83,
  },

  {
    id: "edu_first_campus_day",
    title: "Campus Discovery — First Day",
    industryId: "education",
    hero: "A new student on campus on their first day — specifically the moment they look up at the buildings and understand the scale of what they have started",
    heroType: "human_customer",
    composition: "Wide angle; student small against campus architecture; looking up; campus environment as the aspiration; the student's insignificance is temporary",
    photography: "24mm wide; natural campus light; student in the lower third looking up; buildings and sky in the upper two-thirds; golden hour if possible",
    layout: "Image 70% | Discovery headline upper 15% | Institution + application CTA lower 15%",
    marketing: "The campus experience as the product — the institution's environment as the transformation context",
    emotion: "Beginning and possibility — 'Everything I have been working toward starts here'",
    productionNote: "The student looking up rather than at the camera is the compositional choice that converts — they are in the experience, not performing it for the advertisement",
    bestFor: ["campus", "undergraduate", "MBA", "residential", "placement", "full-time programme"],
    notFor: ["online education", "coaching only", "exam preparation", "skill training"],
    baseScore: 75,
  },

  {
    id: "edu_placement_outcome",
    title: "Career Outcome — The First Day at Work",
    industryId: "education",
    hero: "A graduate on their first day at their first significant job — the specific morning of the career that the education made possible",
    heroType: "human_customer",
    composition: "Wide exterior of the office building or lobby; graduate entering; professional environment communicates the scale of what was achieved",
    photography: "35mm at street level; natural morning light; graduate walking into or standing at entrance; 1/250s; documentary feel",
    layout: "Image 65% | Outcome headline upper 20% | Placement statistic + application CTA lower 15%",
    marketing: "Educational ROI made visible — the career the education built",
    emotion: "Career arrival — 'All of it was worth this morning'",
    productionNote: "The specific company or office type should be identifiable as the kind of placement the programme achieves — generic office building communicates nothing; specific company context communicates the outcome",
    bestFor: ["placement", "MBA", "professional programme", "career", "outcome", "ROI", "salary"],
    notFor: ["undergraduate admissions", "exam preparation", "skill training"],
    baseScore: 78,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BEAUTY / SALON
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "beauty_stylist_watching",
    title: "The Stylist Who Watches — Professional Investment",
    industryId: "beauty_cosmetics",
    hero: "Stylist standing behind the client in the salon chair, watching the client's face in the mirror — not working, watching",
    heroType: "human_professional",
    composition: "Chair level; mirror as compositional centre; stylist in the outer frame watching; client's expression in mirror's reflection at the golden ratio",
    photography: "50mm at chair level; warm salon mirror lighting + natural window from left; 1/80s; mirror frame-within-frame",
    layout: "Image 65% | Discovery headline upper-right 20% | Stylist name + WhatsApp CTA lower 15%",
    marketing: "Professional investment as the differentiator — 'a stylist who watches your face, not the clock'",
    emotion: "Being seen by a professional who cares — 'she watched to see if it was right before I said a word'",
    productionNote: "The stylist's hands must be at her sides — not working, watching; the act of watching without touching communicates professional confidence in the result",
    bestFor: ["premium salon", "hair transformation", "stylist brand", "professional", "colour", "cut"],
    notFor: ["discount salon", "chain salon", "speed service", "nail salon"],
    baseScore: 90,
  },

  {
    id: "beauty_self_care_ritual",
    title: "The Self-Care Ritual — The Morning That Belongs to Her",
    industryId: "beauty_cosmetics",
    hero: "A woman in the specific domestic ritual of pre-salon or post-salon self-care — the morning before, the evening after",
    heroType: "human_customer",
    composition: "Bathroom or bedroom interior; morning light; the ritual as the hero; the woman present in the space without performing for the camera",
    photography: "50mm; natural window morning light; 1/80s; warm white balance; the room communicates care and personal time",
    layout: "Image 65% | Self-care headline upper 20% | Salon name + WhatsApp booking CTA lower 15%",
    marketing: "The salon visit as self-care investment — 'this is time that belongs to me and no one else'",
    emotion: "Personal autonomy — 'This morning is mine'",
    productionNote: "The bathroom or bedroom must be real and specific — not a photoshoot set; one personal detail (a specific cream, a specific mug of tea) makes the space credible",
    bestFor: ["self-care", "wellness", "skincare", "spa", "personal time", "luxury service"],
    notFor: ["quick service", "walk-in", "budget", "event prep focus"],
    baseScore: 79,
  },

  {
    id: "beauty_event_preparation",
    title: "Event Preparation — Getting Ready for Something That Matters",
    industryId: "beauty_cosmetics",
    hero: "A woman at the salon getting ready for a specific important occasion — the wedding she is attending, the event she is hosting, the interview that changes things",
    heroType: "human_customer",
    composition: "Salon chair; the occasion is communicated by one specific detail (the saree hanging nearby, the interview outfit visible); the preparation is the hero",
    photography: "50mm at chair level; warm salon light; 1/80s; the occasion detail is in the background, sharp enough to be identified",
    layout: "Image 65% | Occasion preparation headline upper 20% | Salon + WhatsApp CTA lower 15%",
    marketing: "The salon as the preparation for the important moments — 'the right preparation changes how you show up'",
    emotion: "Occasion readiness — 'I am ready for this'",
    productionNote: "The occasion detail in the background must be specific and identifiable — if it is a wedding, the lehenga or saree is visible; if it is a job interview, the outfit is visible; the occasion is communicated through this one prop",
    bestFor: ["event prep", "wedding guest", "occasion", "party", "interview", "bridal prep"],
    notFor: ["everyday self-care", "wellness retreat", "medical aesthetics"],
    baseScore: 82,
  },

  {
    id: "beauty_bridal_makeover",
    title: "Bridal Transformation — The Last Morning of Just Being Her",
    industryId: "beauty_cosmetics",
    hero: "The bride in the final stage of bridal preparation — the moment before she leaves the preparation room and becomes the bride everyone is waiting for",
    heroType: "human_customer",
    composition: "Preparation room; bride looking at herself in the mirror; one family member or bridesmaids partially visible; this is private before it is public",
    photography: "50mm; warm preparation room light + natural window; 1/80s; the bride's expression is the hero, not the makeup",
    layout: "Image 65% | Bridal headline upper 20% | Bridal package + WhatsApp consultation CTA lower 15%",
    marketing: "The last morning of the bride's own private identity before the public celebration begins",
    emotion: "Bridal transition — 'I am ready; and I am still me'",
    productionNote: "The bride's expression must be the hero — not the makeup or hair; direct her to look at herself in the mirror as though seeing herself for the last time before the wedding, not as though evaluating the styling",
    bestFor: ["bridal makeup", "bridal package", "wedding hair", "bridal salon", "bride"],
    notFor: ["everyday beauty", "men's grooming", "skincare only"],
    baseScore: 85,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // RETAIL / FASHION
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "fashion_occasion_moment",
    title: "The Occasion She Was Made For",
    industryId: "retail_fashion",
    hero: "An Indian woman in the garment at the specific occasion it was designed for — rooftop golden hour, not looking at the camera",
    heroType: "human_customer",
    composition: "85mm three-quarter profile; woman turned 40 degrees from camera; garment visible in movement; occasion context in background",
    photography: "85mm at eye level; golden hour from the right; f/2.8; 1/250s; garment's colour at its most saturated in warm light",
    layout: "Image 70% | Occasion headline left 15% | Brand + collection CTA lower 15%",
    marketing: "The garment as occasion enablement — 'this is the outfit that belongs to that evening'",
    emotion: "Rightness in the moment — 'She looks exactly like herself in this'",
    productionNote: "The laugh before the expression is arranged — photograph in the second after she responds to something off-frame, before she has composed her expression again",
    bestFor: ["ethnic wear", "occasion wear", "kurta", "saree", "festive", "collection launch"],
    notFor: ["everyday casual", "office wear", "flat lay", "product-only"],
    baseScore: 90,
  },

  {
    id: "fashion_editorial_detail",
    title: "Editorial Detail — The Fabric Speaks",
    industryId: "retail_fashion",
    hero: "An extreme close-up of the garment's most distinctive detail — the embroidery, the fabric texture, the print at macro proximity",
    heroType: "product_close_up",
    composition: "Macro close-up; garment on a living subject (partial) or styled; one detail fills the frame; natural or controlled window light revealing texture",
    photography: "100mm macro; directional natural light from one side; f/5.6 for texture depth; 1/200s; no studio flash that flattens fabric texture",
    layout: "Image 75% | Craft or heritage headline upper 15% | Brand + collection name 10%",
    marketing: "Craft positioning — the garment is worth looking at closely because there is something worth seeing",
    emotion: "Aesthetic appreciation — 'I want to touch this fabric'",
    productionNote: "The garment must be worn by a model (partial — hands or torso); fabric on a mannequin has no life; the warmth of a living body under fabric changes the drape and texture",
    bestFor: ["heritage brand", "handloom", "craft", "artisan", "embroidery", "premium fabric"],
    notFor: ["casual wear", "sportswear", "mass market", "collection grid"],
    baseScore: 77,
  },

  {
    id: "fashion_social_lifestyle",
    title: "Social Lifestyle — The Group That Chose Well",
    industryId: "retail_fashion",
    hero: "A group of Indian women at a social occasion where each has dressed specifically for it — each look distinct, all in the same brand family",
    heroType: "human_customer",
    composition: "Wide group shot; natural social scene (rooftop, café, terrace); the garments are visible but the conversation is the hero; 35mm documentary",
    photography: "35mm at eye level; natural outdoor light; 1/250s; candid or candid-directed; the group is not posing for the camera",
    layout: "Image 70% | Social headline upper 15% | Brand + explore CTA lower 15%",
    marketing: "Social occasion dressing — 'the brand that makes the occasion look right, together'",
    emotion: "Collective ease — 'We all look like ourselves at our best'",
    productionNote: "The group must be a real group of friends or at minimum have real chemistry — strangers posing together communicates fashion catalogue; friends communicates social reality",
    bestFor: ["festive collection", "friend group", "brunch", "social occasion", "multiple styles", "range"],
    notFor: ["solo hero campaign", "luxury positioning", "bridal", "specific single garment"],
    baseScore: 75,
  },

  {
    id: "fashion_flat_lay_editorial",
    title: "Flat Lay Editorial — The Curated Choice",
    industryId: "retail_fashion",
    hero: "A precisely styled overhead flat lay of the garment with complementary accessories — styled as a magazine editorial, not an e-commerce listing",
    heroType: "product_item",
    composition: "Overhead bird's-eye; garment as hero; 2-3 accessory props that communicate the occasion; negative space as a design element; marble or linen surface",
    photography: "Overhead; natural window light from one side; f/8 for full flat sharpness; 1/200s; no harsh shadows",
    layout: "Image 70% | Style note or occasion descriptor upper 15% | Shop / Collection CTA lower 15%",
    marketing: "The complete look — styled for the customer who wants to see not just the garment but the decision",
    emotion: "Curation satisfaction — 'I know exactly how to wear this'",
    productionNote: "Flat lay requires a dedicated stylist — accessories must be real, must complement specifically, and must not compete with the garment; the surface matters as much as the objects",
    bestFor: ["instagram", "e-commerce", "look book", "accessories", "gifting", "festive"],
    notFor: ["brand campaign", "occasion emotional", "brand launch"],
    baseScore: 72,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // EVENTS / ENTERTAINMENT
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "events_peak_performance",
    title: "Peak Performance — The Moment Worth Being There For",
    industryId: "events_entertainment",
    hero: "The performer at the specific peak moment of their set — eyes closed, head back, fully inside the music",
    heroType: "mixed",
    composition: "Wide 24mm from elevated crowd position; performer in upper third; crowd with phones in lower two-thirds; stage lighting creating depth",
    photography: "24mm; authentic stage lighting; ISO 3200; 1/500s; grain is not a defect — it is the event",
    layout: "Image 65% | Artist name + experience descriptor upper 20% | Date + single booking platform CTA lower 15%",
    marketing: "The peak moment as the retrospective FOMO trigger — 'you will wish you had been there'",
    emotion: "Collective peak — 'Three thousand people doing the same thing at the same time'",
    productionNote: "Use only real performance photography from actual events — this route is invalidated by studio or rehearsal photography",
    bestFor: ["concert", "music", "live performance", "artist", "show", "festival", "experience"],
    notFor: ["corporate event", "conference", "awards", "theatre"],
    baseScore: 90,
  },

  {
    id: "events_atmosphere",
    title: "Atmosphere — The Room Before the Show",
    industryId: "events_entertainment",
    hero: "The venue in the hour before the event begins — the specific atmosphere of a space about to be filled with something significant",
    heroType: "environment_interior",
    composition: "Wide interior; empty seats or arriving crowd; the specific architecture and lighting of the venue communicating anticipation",
    photography: "24mm wide; venue lighting only; 1/30s tripod for the pre-crowd interior; 1/500s for the arriving crowd",
    layout: "Image 70% | Atmosphere headline upper 15% | Event date + booking CTA lower 15%",
    marketing: "The event as a place as much as a performance — the venue and its atmosphere are part of the experience",
    emotion: "Anticipation — 'I want to be in that room when it fills'",
    productionNote: "Only viable for distinctive venue environments (heritage buildings, open-air amphitheatres, unique architecture); generic conference rooms should use a different route",
    bestFor: ["heritage venue", "unique venue", "festival", "outdoor", "theatre", "jazz", "classical"],
    notFor: ["artist-led campaign", "pop concert", "generic venue"],
    baseScore: 74,
  },

  {
    id: "events_artist_portrait",
    title: "Artist Portrait — The Person Worth Seeing",
    industryId: "events_entertainment",
    hero: "A compelling close-up portrait of the artist — not a promotional headshot but a real moment of the artist being themselves",
    heroType: "human_professional",
    composition: "Portrait; artist filling the frame; natural or dramatic lighting; the expression communicates something about who this artist is, not what they want you to think of them",
    photography: "85mm at eye level; natural or studio dramatic lighting; f/2.0; 1/200s; black and white optional if genre suits",
    layout: "Image 70% | Artist name at 20% weight + one experience descriptor 15% | Date + booking CTA 15%",
    marketing: "Artist name recognition and identity — for artists whose name is the primary conversion trigger",
    emotion: "Artist reverence — 'I want to be in the room with this person'",
    productionNote: "Only viable for artists with strong name recognition in the target market; for emerging artists, the peak performance route is more effective than a portrait",
    bestFor: ["named artist", "celebrity", "comedian", "known performer", "one-person show"],
    notFor: ["emerging artist", "festival with multiple acts", "venue-led campaign"],
    baseScore: 80,
  },

  {
    id: "events_behind_scenes",
    title: "Behind the Scenes — What the Audience Never Sees",
    industryId: "events_entertainment",
    hero: "The artist or crew in the hour before the show — the specific backstage moment of preparation that the audience is not usually invited into",
    heroType: "human_professional",
    composition: "Documentary backstage; artist at the mirror, backstage corridor, or pre-show ritual; the camera is a guest, not a director",
    photography: "35mm; available backstage lighting; ISO 3200; 1/250s; the image should look like it was taken without anyone's permission",
    layout: "Image 65% | Access headline upper 20% | Artist + event details + booking CTA lower 15%",
    marketing: "Exclusive access as a purchase motivation — 'you get to see what most people never do'",
    emotion: "Exclusive access — 'I am being shown something that most audiences never see'",
    productionNote: "This route requires genuine backstage access — fabricated backstage scenes are detectable and undermine the route's entire commercial argument",
    bestFor: ["documentary", "behind the scenes", "access", "storytelling", "brand partnership", "content"],
    notFor: ["event where backstage access is not available", "venue-led without artist access"],
    baseScore: 72,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // TECH / SOFTWARE
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "tech_relief_moment",
    title: "The Relief Moment — Task Completed Itself",
    industryId: "tech_software",
    hero: "An Indian SMB user at their desk at the end of the day — realising that the task they were about to start has already been completed by the software",
    heroType: "human_customer",
    composition: "Desk level; user three-quarter profile; laptop screen as primary light; team has gone home — empty chairs in background",
    photography: "50mm at desk level; laptop screen glow (warm white) as only light; ISO 1600; 1/80s; slight grain",
    layout: "Image 65% | Specific arithmetic headline upper 20% | Software name + free trial CTA lower 15%",
    marketing: "Specific task relief — '4 hours to 6 seconds' converts the person experiencing the specific pain",
    emotion: "The quiet relief of a task completing itself — 'I was about to start this; it is already done'",
    productionNote: "The cold cup of tea on the desk is the production detail — it communicates she has been at this desk long enough for the tea to go cold, and the software ended the evening earlier than expected",
    bestFor: ["SaaS", "automation", "reporting", "productivity", "SMB", "B2B", "software"],
    notFor: ["consumer app", "gaming", "entertainment tech", "hardware"],
    baseScore: 90,
  },

  {
    id: "tech_team_productivity",
    title: "Team Productivity — Everyone Moving Faster",
    industryId: "tech_software",
    hero: "A small Indian team in a real working environment, all engaged simultaneously — the specific energy of a team that has eliminated the friction from their work",
    heroType: "human_customer",
    composition: "Wide team shot; everyone working; no screens visible from the camera (avoid dashboard screenshots by shooting from behind or the side); real office environment",
    photography: "35mm; natural office light; 1/250s; documentary; Indian SMB office environment",
    layout: "Image 65% | Team efficiency headline upper 20% | Team licence pricing + CTA lower 15%",
    marketing: "Team adoption as the B2B conversion trigger — 'this is what a team looks like when the friction is removed'",
    emotion: "Collective competence — 'Everyone knows what to do and has the tools to do it'",
    productionNote: "Real team, real environment, real work — staged teams with too-perfect desks communicate photoshoot, not office; allow the natural messiness of a working team",
    bestFor: ["team plan", "B2B", "enterprise", "collaboration", "multiple seats", "small team"],
    notFor: ["solo user", "consumer app", "freelancer focus"],
    baseScore: 76,
  },

  {
    id: "tech_founder_problem",
    title: "Founder's Problem — The Business Problem This Solves",
    industryId: "tech_software",
    hero: "An Indian founder or business owner at the exact moment they were experiencing the problem the software solves — before the solution",
    heroType: "human_owner",
    composition: "The problem environment — the desk with the manual spreadsheet, the whiteboard with the messy workflow, the stack of receipts",
    photography: "50mm; available office light; 1/80s; the environment communicates the problem clearly; the person communicates the frustration",
    layout: "Image 55% | Problem identification headline upper 25% | Software solution + free trial CTA lower 20%",
    marketing: "Problem-first messaging — 'we named your problem before we told you we solved it'",
    emotion: "Recognition of pain — 'That is exactly my situation'",
    productionNote: "The problem artefacts must be specific and recognisable — a spreadsheet with too many tabs, a calendar with too many manual entries, a pile of receipts that need manual entry; vague 'busy desk' communicates nothing specific",
    bestFor: ["startup", "founder", "SMB owner", "problem-solution", "category education", "market creation"],
    notFor: ["established category", "upgrade campaign", "enterprise features"],
    baseScore: 77,
  },

  {
    id: "tech_outcome_metric",
    title: "Business Outcome — The Number That Changed",
    industryId: "tech_software",
    hero: "A specific business metric that changed after the software was adopted — the number is the hero, contextualised by the person who achieved it",
    heroType: "human_customer",
    composition: "The metric visible and prominent; the person who achieved it present but secondary; the business environment communicating credibility",
    photography: "50mm; natural office light; the metric displayed in context (on a screen, on a whiteboard, on a printed report); 1/80s",
    layout: "Image 55% | The metric as the headline (specific number) upper 25% | Software name + case study CTA lower 20%",
    marketing: "Specific outcome proof — 'this number changed for this business after using this software'",
    emotion: "Commercial confidence — 'I could achieve this number'",
    productionNote: "The metric must be real and verifiable — case study-backed; a fabricated metric in a software advertisement destroys trust permanently when discovered",
    bestFor: ["case study", "results", "ROI", "enterprise", "B2B", "specific industry solution"],
    notFor: ["general awareness", "free trial", "brand campaign", "new product launch"],
    baseScore: 74,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // GENERAL (fallback)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "general_customer_value",
    title: "Customer Value Delivery — The Moment It Matters",
    industryId: "general",
    hero: "A real customer at the specific moment the business's core value is delivered to them",
    heroType: "human_customer",
    composition: "50mm at customer level; the value being delivered visible; the customer's expression of receiving it is the compositional anchor",
    photography: "50mm; available real-environment light; 1/80s; documentary feel",
    layout: "Image 65% | Specific benefit headline upper 20% | Business name + contact CTA lower 15%",
    marketing: "Value delivery as the proof of the business's claim — 'this is what you will receive here'",
    emotion: "Relief of the right solution — 'This business understood exactly what I needed'",
    productionNote: "The customer must be real and the value delivery must be genuine — the only route that works across all categories when nothing more specific is available",
    bestFor: ["brand launch", "general service", "local business", "B2C", "any industry"],
    notFor: [],
    baseScore: 75,
  },

  {
    id: "general_founder_origin",
    title: "Founder Story — Why This Exists",
    industryId: "general",
    hero: "The founder at the moment that explains why they started this business — the specific problem they experienced or the specific belief they are pursuing",
    heroType: "human_owner",
    composition: "Founder in their natural environment; the origin story communicated through the environment; direct and honest",
    photography: "50mm at natural eye level; available light in the founder's genuine environment; 1/80s; no studio",
    layout: "Image 60% | Origin story headline upper 25% | Business CTA lower 15%",
    marketing: "Brand authenticity — 'the business exists because someone cared enough to start it'",
    emotion: "Founding conviction — 'I understand why this exists and I trust the person who built it'",
    productionNote: "The environment must communicate the origin genuinely — if the founder started in their garage, show the garage (or its equivalent); do not show an aspirational environment they have not yet earned",
    bestFor: ["startup", "new business", "brand story", "why", "origin", "mission", "purpose"],
    notFor: ["established brand", "product promotion", "discount campaign"],
    baseScore: 72,
  },

  {
    id: "general_product_in_use",
    title: "Product in Real Use — The Honest Demonstration",
    industryId: "general",
    hero: "The product or service being used in the genuine context of the problem it solves — not on a photoshoot set",
    heroType: "mixed",
    composition: "The product in active use; user and product both in frame; real environment; no props or photoshoot set elements",
    photography: "50mm; available light in actual use environment; 1/200s to capture product in use; documentary",
    layout: "Image 65% | Use-case headline upper 20% | Product name + purchase CTA lower 15%",
    marketing: "Demonstration as proof — 'you can see exactly what this does and who uses it'",
    emotion: "Practical confidence — 'I understand what I will get'",
    productionNote: "The use context must be the actual use context — not a cleaner or more aspirational version of it; the viewer needs to recognise their own situation to convert",
    bestFor: ["product demo", "features", "how it works", "practical benefit", "utility"],
    notFor: ["brand launch", "emotional campaign", "premium brand building"],
    baseScore: 70,
  },

  {
    id: "general_social_proof",
    title: "Community Trust — People Who Chose This",
    industryId: "general",
    hero: "Multiple real customers in a montage or group shot — the visual evidence that others have chosen and benefited from this business",
    heroType: "human_customer",
    composition: "Documentary group or montage of real users; diversity of real customers communicates broad appeal; no single hero subject",
    photography: "Montage of 35mm candid shots from real customer interactions; consistent warm colour treatment; 1/250s each",
    layout: "Image 60% | Social proof statement upper 25% | Business name + conversion CTA lower 15%",
    marketing: "Social proof as trust — 'these real people chose this and are glad they did'",
    emotion: "Safe choice — 'If they chose this, I am not alone in this decision'",
    productionNote: "All individuals must be real customers who have consented to the use of their image; fabricated testimonial photography is a legal and trust liability",
    bestFor: ["testimonials", "reviews", "community", "established brand", "category leadership"],
    notFor: ["new business", "brand launch", "single hero narrative"],
    baseScore: 68,
  },

];

// ─────────────────────────────────────────────────────────────────────────────

/** Returns all candidate routes for a given industryId. */
export function getRoutesForIndustry(industryId: string): CreativeRoute[] {
  const routes = ROUTE_REGISTRY.filter(r => r.industryId === industryId);
  if (routes.length > 0) return routes;
  // Fallback to general if no specific routes found
  return ROUTE_REGISTRY.filter(r => r.industryId === "general");
}
