import type { CommercialSituationKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const RESTAURANT_COMMERCIAL_SITUATIONS: CommercialSituationKnowledgeNode[] = [
  // ── Reservation / discovery (10) ─────────────────────────────────────────────
  { id: "commercial_situation:restaurant:online-reservation-made", kind: "commercial_situation", situation: "Customer makes restaurant reservation online — selecting date, party size, confirming time slot", conversionMoment: "Click confirm on booking screen — the table is secured, the evening is planned", visualRepresentation: "Hand holding phone with booking confirmation screen visible, date and time prominent, check mark or animation", industryIds: ["restaurant"], tags: ["reservation", "online", "booking", "conversion"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "commercial_situation:restaurant:browsing-menu-before-deciding", kind: "commercial_situation", situation: "Potential customer browsing restaurant's online menu before deciding to book", conversionMoment: "Scrolling stops at signature dish photo — the desire created by image drives the decision to book", visualRepresentation: "Phone screen showing menu with hero dish photography, thumb pausing on one item, face reacting to image", industryIds: ["restaurant"], tags: ["menu-browsing", "discovery", "online-menu", "decision"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:restaurant:social-media-find-restaurant", kind: "commercial_situation", situation: "Customer discovering restaurant through food photo on social media — a friend's post or paid ad", conversionMoment: "Tapping 'Book Now' or 'Get Directions' directly from the post — intent to visit triggered by image", visualRepresentation: "Instagram or similar feed with restaurant's hero dish post, finger about to tap the booking link", industryIds: ["restaurant"], tags: ["social-media", "discovery", "food-photo", "book-now"], priority: 3, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "commercial_situation:restaurant:walk-in-seating-decision", kind: "commercial_situation", situation: "Couple walking past restaurant, stopping to read menu board displayed outside", conversionMoment: "One pointing at an item, both agreeing, turning toward the entrance — the impulse decision to walk in", visualRepresentation: "Couple standing before illuminated menu board or chalkboard at entrance, one pointing, both leaning in", industryIds: ["restaurant"], tags: ["walk-in", "impulse", "menu-board", "entrance"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:restaurant:gift-voucher-purchase", kind: "commercial_situation", situation: "Customer purchasing restaurant gift voucher for occasion — birthday or anniversary present", conversionMoment: "Payment confirmed for voucher — the tangible gift of an experience, not a thing", visualRepresentation: "Elegant gift card or digital voucher on screen, person entering recipient's name, celebratory design", industryIds: ["restaurant"], tags: ["gift-voucher", "occasion", "gifting", "purchase"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:restaurant:review-reading-trust-building", kind: "commercial_situation", situation: "Potential customer reading recent reviews before deciding to try the restaurant for the first time", conversionMoment: "Reading a specific positive review that mentions their occasion type — trust threshold crossed, booking begins", visualRepresentation: "Review platform on phone, five-star rating prominent, person nodding while reading, booking app opened next", industryIds: ["restaurant"], tags: ["reviews", "trust", "first-visit", "decision"], priority: 6, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:restaurant:influencer-recommendation", kind: "commercial_situation", situation: "Customer following recommendation from food influencer or trusted friend who has visited", conversionMoment: "Sending the recommendation to partner asking 'Want to go?' — social validation triggering action", visualRepresentation: "Screenshot of influencer post being forwarded, message bubble visible, friend's reply with enthusiasm", industryIds: ["restaurant"], tags: ["influencer", "recommendation", "social-proof", "forwarding"], priority: 7, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:restaurant:special-menu-promotion", kind: "commercial_situation", situation: "Restaurant promotional offer — early bird menu, set price special, seasonal tasting menu announcement", conversionMoment: "Saving or booking from the promotional post — the value perception triggering commitment", visualRepresentation: "Promotional graphic with set menu details, strong price or occasion detail, booking call to action visible", industryIds: ["restaurant"], tags: ["promotion", "set-menu", "offer", "early-bird"], priority: 8, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:restaurant:table-visible-from-street", kind: "commercial_situation", situation: "Passersby able to see diners enjoying meal through restaurant window — vicarious desire", conversionMoment: "Pulling out phone to check if there's availability tonight — the window display converting foot traffic", visualRepresentation: "View from outside looking through window at occupied, happy table — warm light against dark street", industryIds: ["restaurant"], tags: ["window", "vicarious", "street", "impulse"], priority: 9, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:restaurant:corporate-event-booking", kind: "commercial_situation", situation: "Events coordinator booking private dining for corporate function — negotiating package, confirming group size", conversionMoment: "Email confirmation of private dining booking — venue secured for the event, planning complete", visualRepresentation: "Email chain with event details, private dining room inquiry, coordinator and restaurant contact visible", industryIds: ["restaurant"], tags: ["corporate", "events", "private-dining", "group-booking"], priority: 10, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── In-restaurant upsell (10) ─────────────────────────────────────────────────
  { id: "commercial_situation:restaurant:sommelier-wine-recommendation", kind: "commercial_situation", situation: "Sommelier recommending wine pairing at table — describing options, reading guest's preference signals", conversionMoment: "Guest nodding and saying 'Let's try that' — premium wine chosen over house option, upsell complete", visualRepresentation: "Sommelier leaning slightly toward table, menu held, guest listening with interest, wine list between them", industryIds: ["restaurant"], tags: ["sommelier", "wine", "upsell", "recommendation"], priority: 1, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:restaurant:dessert-menu-presented", kind: "commercial_situation", situation: "Dessert menu presented after main course — the strategic pause before additional revenue opportunity", conversionMoment: "Both guests reaching for dessert menu simultaneously — the decision made without deliberation", visualRepresentation: "Leather dessert menu being placed between two diners, both reaching for it, staff stepping back", industryIds: ["restaurant"], tags: ["dessert", "upsell", "menu", "after-main"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:restaurant:truffle-supplement-offered", kind: "commercial_situation", situation: "Server offering truffle supplement on pasta — describing the addition, the price mentioned casually", conversionMoment: "Guest agreeing to supplement — the immediate 'yes' when presented with obvious quality addition", visualRepresentation: "Server beside table with truffle and grater, offering at tableside, guest nodding, portion being added", industryIds: ["restaurant"], tags: ["truffle", "supplement", "tableside", "premium-upsell"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:restaurant:cocktail-menu-before-dinner", kind: "commercial_situation", situation: "Pre-dinner cocktail menu offered while waiting for table — drinks revenue before main service begins", conversionMoment: "First cocktail ordered at bar while waiting — bridge into evening spend established", visualRepresentation: "Cocktail menu opened at bar, bartender nearby, couple reading it, drink being ordered", industryIds: ["restaurant"], tags: ["pre-dinner", "cocktail", "bar", "first-drink"], priority: 4, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:restaurant:chef-recommendation-special", kind: "commercial_situation", situation: "Server delivering chef's special recommendation — 'The chef suggests this for your occasion'", conversionMoment: "Guest ordering the recommended special — social proof of chef authority triggering premium choice", visualRepresentation: "Server leaning toward table, explaining special, guest face showing interest, menu set aside", industryIds: ["restaurant"], tags: ["chef-recommendation", "special", "authority", "premium"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:restaurant:digestif-offered-end", kind: "commercial_situation", situation: "Complimentary digestif offered at meal's end — building goodwill and loyalty for next visit", conversionMoment: "Guest accepting and enjoying digestif — last positive impression sealed, rebooking likelihood increased", visualRepresentation: "Small glass of limoncello or grappa placed on table, server gesturing it is complimentary, guest surprised", industryIds: ["restaurant"], tags: ["digestif", "complimentary", "loyalty", "end-of-meal"], priority: 6, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "commercial_situation:restaurant:tasting-menu-vs-a-la-carte", kind: "commercial_situation", situation: "Server presenting tasting menu option to guests debating ordering approach", conversionMoment: "Agreement to try the tasting menu — higher spend per head confirmed, kitchen sequencing set", visualRepresentation: "Two menus presented side by side, server explaining the tasting menu journey, couple listening", industryIds: ["restaurant"], tags: ["tasting-menu", "conversion", "higher-spend", "experience"], priority: 7, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:restaurant:champagne-for-celebration", kind: "commercial_situation", situation: "Staff acknowledging celebration and offering champagne upgrade — recognising the occasion", conversionMoment: "'Yes, let's have champagne' — the occasion justifying the premium, upgrade accepted", visualRepresentation: "Server pointing to champagne menu, couple at celebration table, both looking willing, bottle being gestured toward", industryIds: ["restaurant"], tags: ["champagne", "celebration", "upgrade", "occasion"], priority: 8, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:restaurant:merchandise-cookbook-purchase", kind: "commercial_situation", situation: "Guest purchasing restaurant cookbook or branded merchandise as souvenir of exceptional meal", conversionMoment: "Taking cookbook to counter and paying — desire to extend the experience at home triggers purchase", visualRepresentation: "Cookbook with restaurant branding displayed at reception, guest holding it, making purchase decision", industryIds: ["restaurant"], tags: ["merchandise", "cookbook", "souvenir", "extension"], priority: 9, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "commercial_situation:restaurant:bottle-service-table", kind: "commercial_situation", situation: "Group upgrading from single cocktails to bottle service — social dynamics pushing premium choice", conversionMoment: "Bottle brought to table with ice bucket — the theatrical delivery marking the upgrade moment", visualRepresentation: "Server approaching with champagne or spirit bottle in ice bucket, table of friends reacting to arrival", industryIds: ["restaurant"], tags: ["bottle-service", "group", "premium", "upgrade"], priority: 10, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── Post-experience / loyalty (10) ────────────────────────────────────────────
  { id: "commercial_situation:restaurant:bill-requested-reluctance", kind: "commercial_situation", situation: "Guests requesting the bill after extended stay — reluctance to leave, the experience was too good", conversionMoment: "Card handed over — satisfaction ensures rebooking; the reluctance is the strongest conversion signal", visualRepresentation: "Hand signal for bill, both guests leaning back, wine almost finished, unhurried conversation still ongoing", industryIds: ["restaurant"], tags: ["bill", "reluctance", "satisfaction", "extended-stay"], priority: 1, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:restaurant:five-star-review-written", kind: "commercial_situation", situation: "Guest writing five-star review while still at table or immediately after — peak satisfaction captured", conversionMoment: "Review submitted — authentic advocacy created, future new guests will be converted by this review", visualRepresentation: "Phone in hand typing review at table, stars being tapped, specific dish name being mentioned in text", industryIds: ["restaurant"], tags: ["review", "five-star", "advocacy", "post-meal"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:restaurant:food-photo-social-post", kind: "commercial_situation", situation: "Guest posting food photo to social media from table — organic content creation in real time", conversionMoment: "Post published — the restaurant's reach extending organically through the guest's network", visualRepresentation: "Phone above beautifully plated dish, caption being typed, restaurant tagged, post being submitted", industryIds: ["restaurant"], tags: ["social-post", "organic-reach", "food-photo", "tagging"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:restaurant:rebooking-at-reception", kind: "commercial_situation", situation: "Guest rebooking as they leave — asking for same table, same night next month — loyalty demonstrated", conversionMoment: "Next booking confirmed on departure — future revenue secured at the most satisfied moment", visualRepresentation: "Guest at reception desk, diary or phone out, confirming next booking date, host smiling", industryIds: ["restaurant"], tags: ["rebooking", "loyalty", "departure", "future-revenue"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:restaurant:telling-friend-about-dish", kind: "commercial_situation", situation: "Day after visit, guest telling colleague or friend about the meal — unprompted advocacy", conversionMoment: "Friend adds restaurant to 'places to try' list — word-of-mouth chain initiated", visualRepresentation: "Two people at coffee, one showing the other a food photo from last night, describing the dish animatedly", industryIds: ["restaurant"], tags: ["word-of-mouth", "advocacy", "recommendation", "day-after"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:restaurant:loyalty-card-stamp", kind: "commercial_situation", situation: "Regular having loyalty card stamped — the ritual of progress toward a free meal or discount", conversionMoment: "Final stamp filling the card — reward claimed, loyalty behaviour reinforced", visualRepresentation: "Loyalty card being stamped, stamp nearly full, guest seeing progress and smiling at how close to reward", industryIds: ["restaurant"], tags: ["loyalty-card", "stamp", "reward", "regular"], priority: 6, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "commercial_situation:restaurant:group-planning-return", kind: "commercial_situation", situation: "Group at table agreeing they must come back — planning next occasion before the current one has ended", conversionMoment: "Date decided at table — the most powerful booking moment is when still in the positive experience", visualRepresentation: "Group consulting phones for dates, one pulling up calendar, agreement on month being discussed", industryIds: ["restaurant"], tags: ["group", "return-planning", "future-booking", "in-table"], priority: 7, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:restaurant:email-newsletter-booking", kind: "commercial_situation", situation: "Past customer receiving restaurant newsletter — seasonal menu announcement triggering return booking", conversionMoment: "Click from email to booking page — re-engagement campaign converting a lapsed customer", visualRepresentation: "Email open on laptop showing seasonal menu with compelling dish photography, Book Now button visible", industryIds: ["restaurant"], tags: ["newsletter", "email", "seasonal", "re-engagement"], priority: 8, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "commercial_situation:restaurant:corporate-account-setup", kind: "commercial_situation", situation: "Business setting up corporate account for regular client entertaining — ongoing relationship formalised", conversionMoment: "Account signed and first booking made — recurring revenue stream established", visualRepresentation: "Business card exchange at restaurant desk, account paperwork, handshake confirming the arrangement", industryIds: ["restaurant"], tags: ["corporate-account", "recurring", "business", "setup"], priority: 9, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "commercial_situation:restaurant:takeaway-app-reorder", kind: "commercial_situation", situation: "Customer reordering favourite meal through delivery app — the habit forming into reliable recurring order", conversionMoment: "Tap Reorder from order history — lowest friction path, highest likelihood of conversion", visualRepresentation: "Delivery app on phone showing previous order, reorder button visible, same familiar items selected", industryIds: ["restaurant"], tags: ["reorder", "delivery-app", "habit", "recurring"], priority: 10, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },

  // ── Occasion-driven (10) ──────────────────────────────────────────────────────
  { id: "commercial_situation:restaurant:mothers-day-booking", kind: "commercial_situation", situation: "Adult child booking restaurant for Mother's Day — selecting the place their mother would love most", conversionMoment: "Booking confirmed with special occasion note added — the thoughtful gift decided", visualRepresentation: "Booking screen with 'Special Occasion: Mother's Day' typed, confirmation email arriving, phone shown to mother", industryIds: ["restaurant"], tags: ["mothers-day", "occasion", "booking", "thoughtful"], priority: 1, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:restaurant:valentines-day-full", kind: "commercial_situation", situation: "Last Valentine's Day table available — urgency of scarcity driving immediate booking decision", conversionMoment: "Booking secured after seeing 'Only 2 tables remaining' — scarcity converted hesitation to action", visualRepresentation: "Booking screen showing limited availability message, couple deciding quickly, confirmation completing", industryIds: ["restaurant"], tags: ["valentines", "scarcity", "urgency", "booking"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "commercial_situation:restaurant:christmas-party-early-booking", kind: "commercial_situation", situation: "Office manager booking Christmas party months in advance — securing the right venue before others do", conversionMoment: "Deposit paid to hold the date — commitment made, calendar secured", visualRepresentation: "Event booking form with December date, party size field, deposit payment screen, confirmation sent to team", industryIds: ["restaurant"], tags: ["christmas-party", "early-booking", "corporate", "deposit"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:restaurant:birthday-special-menu", kind: "commercial_situation", situation: "Restaurant's special birthday package booked — personalised menu, dessert, message on plate arranged", conversionMoment: "Birthday package selected and paid for during booking — premium occasion upsell during reservation", visualRepresentation: "Booking page with 'Birthday Package' checkbox ticked, personalisation fields filled, total price visible", industryIds: ["restaurant"], tags: ["birthday-package", "premium", "personalised", "occasion"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:restaurant:new-year-eve-table", kind: "commercial_situation", situation: "New Year's Eve special booking — fixed price menu, guaranteed midnight celebration, premium experience", conversionMoment: "New Year's booking at premium price confirmed — the occasion justifying the investment", visualRepresentation: "New Year's Eve menu with champagne toast detail, booking button, party of four confirmed, excitement visible", industryIds: ["restaurant"], tags: ["new-years-eve", "premium", "celebration", "fixed-price"], priority: 5, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:restaurant:private-function-enquiry", kind: "commercial_situation", situation: "Private function enquiry — wedding rehearsal, corporate dinner, milestone birthday exclusive hire", conversionMoment: "Initial enquiry sent — interest captured, sales conversation beginning", visualRepresentation: "Events enquiry form with function type, date, approximate numbers, contact details submitted", industryIds: ["restaurant"], tags: ["private-function", "exclusive", "enquiry", "events"], priority: 6, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:restaurant:engagement-dinner-arranged", kind: "commercial_situation", situation: "Future proposer arranging everything in advance — table, ring presentation, champagne on arrival", conversionMoment: "Venue coordinator confirming 'It's all arranged' — the most emotionally loaded booking possible", visualRepresentation: "Proposer on phone with restaurant coordinator, note-taking, detail being confirmed, nervous excitement visible", industryIds: ["restaurant"], tags: ["engagement", "arranged", "coordinator", "proposal"], priority: 7, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "commercial_situation:restaurant:school-reunion-dinner", kind: "commercial_situation", situation: "School reunion dinner — organiser booking large table, the occasion bringing twenty people back together", conversionMoment: "Large group booking confirmed — event anchored, catering for 20+ secured", visualRepresentation: "Group booking form with large party size, reunion occasion noted, multiple dietary requirements submitted", industryIds: ["restaurant"], tags: ["reunion", "school", "large-group", "occasion"], priority: 8, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "commercial_situation:restaurant:hen-party-dinner", kind: "commercial_situation", situation: "Hen party dinner organised at restaurant — cocktail arrival package, special menu, occasion decoration", conversionMoment: "Hen party package booked and deposit paid — group celebration confirmed", visualRepresentation: "Hen party inquiry with sash and accessories visible in planning, phone to restaurant, confirmation celebrated with group", industryIds: ["restaurant"], tags: ["hen-party", "group", "package", "celebration"], priority: 9, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:restaurant:farewell-meal-for-departing", kind: "commercial_situation", situation: "Colleague's farewell dinner organised — chosen by the team as final meaningful gathering", conversionMoment: "Booking made in the departing person's honour — the restaurant chosen as the right level of occasion", visualRepresentation: "Team in restaurant planning chat, booking confirmed, group arriving and being shown to their table", industryIds: ["restaurant"], tags: ["farewell", "team", "occasion", "honouring"], priority: 10, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
];
