import type { EmotionalMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const RESTAURANT_EMOTIONAL_MOMENTS: EmotionalMomentKnowledgeNode[] = [
  // ── Peak delight (12) ────────────────────────────────────────────────────────
  { id: "emotional_moment:restaurant:first-bite-eyes-close", kind: "emotional_moment", moment: "Diner takes first bite and eyes close involuntarily for two full seconds", emotionType: "sensory delight", visualSignals: ["eyelids dropping", "jaw slowing", "shoulders dropping", "faint smile forming at corners of mouth"], industryIds: ["restaurant"], tags: ["first-bite", "delight", "involuntary", "pleasure"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:restaurant:dish-arrival-face-light", kind: "emotional_moment", moment: "Dish arrives and diner's face changes completely — the disappointment of an unimpressive menu moment gives way to wonder", emotionType: "surprise and delight", visualSignals: ["eyebrows raising", "lips parting", "body leaning forward", "head tilting"], industryIds: ["restaurant"], tags: ["dish-arrival", "surprise", "delight", "wonder"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:restaurant:involuntary-moan-pleasure", kind: "emotional_moment", moment: "Diner makes involuntary sound of pleasure on tasting — partner smiles knowingly, the reaction is real", emotionType: "pure pleasure", visualSignals: ["mouth slightly open", "eyes crinkled", "head nodding slowly", "hand unconsciously rising to mouth"], industryIds: ["restaurant"], tags: ["pleasure", "involuntary", "reaction", "authentic"], priority: 3, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:restaurant:sharing-discovery-partner", kind: "emotional_moment", moment: "Diner insists partner tastes their dish — urging across the table, certain the partner must experience this", emotionType: "generous excitement", visualSignals: ["fork extended urgently", "eyes bright", "leaning toward partner", "expectant face waiting for reaction"], industryIds: ["restaurant"], tags: ["sharing", "excitement", "discovery", "urging"], priority: 4, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "emotional_moment:restaurant:licking-plate-clean-abandonment", kind: "emotional_moment", moment: "Diner uses bread to wipe every trace of sauce — slightly embarrassed but unable to stop, fullness abandoned", emotionType: "uninhibited satisfaction", visualSignals: ["bread moving in circular motion", "head bent to plate", "slight smile", "sauce-free white plate emerging"], industryIds: ["restaurant"], tags: ["bread", "sauce", "satisfaction", "abandon"], priority: 5, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:restaurant:laughing-mid-bite", kind: "emotional_moment", moment: "Something funny said at the exact wrong moment — diner covering mouth, eyes watering, still chewing", emotionType: "joyful helplessness", visualSignals: ["hand raised to mouth", "eyes crinkled and wet", "shoulders shaking", "others laughing at the laugher"], industryIds: ["restaurant"], tags: ["laughter", "joy", "mid-bite", "helpless"], priority: 6, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:restaurant:pause-to-smell-aroma", kind: "emotional_moment", moment: "Diner pauses before eating to consciously smell — nose dipped, eyes closed, a deliberate moment of sensory ceremony", emotionType: "conscious pleasure", visualSignals: ["eyes closed", "nose slightly dipped", "breath audibly drawn in", "smile before the bite"], industryIds: ["restaurant"], tags: ["aroma", "pause", "ceremony", "conscious"], priority: 7, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:restaurant:childhood-taste-memory", kind: "emotional_moment", moment: "Diner pauses mid-chew — eyes going distant, transported by taste to a specific childhood memory", emotionType: "bittersweet nostalgia", visualSignals: ["eyes defocusing", "chewing slowing", "slight smile with faraway quality", "hand resting on table"], industryIds: ["restaurant"], tags: ["nostalgia", "childhood", "memory", "taste"], priority: 8, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:restaurant:perfect-bite-perfected", kind: "emotional_moment", moment: "Diner constructs the perfect forkful — all elements balanced, held up briefly before eating — architect of their bite", emotionType: "anticipatory perfectionism", visualSignals: ["fork held with multiple elements", "slight pause before eating", "evaluating look", "deliberate first bite"], industryIds: ["restaurant"], tags: ["perfect-bite", "architecture", "anticipation", "deliberate"], priority: 9, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "emotional_moment:restaurant:hot-noodle-steam-face", kind: "emotional_moment", moment: "Hot bowl placed — steam rising into diner's face, eyes squinting with pleasure at the temperature", emotionType: "heat pleasure", visualSignals: ["steam between diner and bowl", "eyes softly squinting", "face flushing", "hands wrapping bowl"], industryIds: ["restaurant"], tags: ["steam", "heat", "noodles", "temperature"], priority: 10, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "emotional_moment:restaurant:dessert-permission-given", kind: "emotional_moment", moment: "Both people order dessert — the mutual permission glance, then both saying yes at the same time, laughing", emotionType: "shared indulgence", visualSignals: ["eye exchange", "simultaneous speaking", "laughter", "menus lowered"], industryIds: ["restaurant"], tags: ["dessert", "permission", "indulgence", "together"], priority: 11, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "emotional_moment:restaurant:end-of-meal-sigh", kind: "emotional_moment", moment: "End of meal — one person leans back with a deep exhale, hand on stomach, the satisfied animal at rest", emotionType: "complete satisfaction", visualSignals: ["lean back", "deep exhale", "hand on abdomen", "eyes soft and slow"], industryIds: ["restaurant"], tags: ["satisfaction", "end-of-meal", "exhale", "complete"], priority: 12, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Romance / connection (12) ─────────────────────────────────────────────────
  { id: "emotional_moment:restaurant:eye-meeting-over-wine", kind: "emotional_moment", moment: "Eyes meeting over raised wine glasses — the half-second where both know something is understood", emotionType: "romantic recognition", visualSignals: ["glasses at mid-face level", "held gaze longer than social convention", "slight smile from both", "shoulders softening"], industryIds: ["restaurant"], tags: ["eye-contact", "wine", "recognition", "romance"], priority: 1, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:restaurant:hand-touching-across-table", kind: "emotional_moment", moment: "Hand reaches across table and rests on partner's — gentle, not urgent, the quiet architecture of intimacy", emotionType: "tender intimacy", visualSignals: ["one hand covering other", "both faces softer", "slight lean forward", "conversation quieting"], industryIds: ["restaurant"], tags: ["hand-touch", "intimacy", "tender", "quiet"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:restaurant:proposal-frozen-moment", kind: "emotional_moment", moment: "The moment after the question is asked — both frozen, her hand over mouth, the world stopped", emotionType: "overwhelming joy and disbelief", visualSignals: ["hand over mouth", "eyes wide and wet", "frozen posture", "other hand reaching for the ring box"], industryIds: ["restaurant"], tags: ["proposal", "frozen", "disbelief", "joy"], priority: 3, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:restaurant:first-date-laugh-real", kind: "emotional_moment", moment: "First real laugh on a first date — the constructed self dropping away, both now fully present", emotionType: "genuine connection", visualSignals: ["body language opening up", "forward lean", "hand touching arm briefly", "eyes bright and direct"], industryIds: ["restaurant"], tags: ["first-date", "real-laugh", "connection", "opening-up"], priority: 4, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "emotional_moment:restaurant:couple-caught-looking", kind: "emotional_moment", moment: "One partner caught staring at the other — the looked-at one notices, the starer holds the gaze instead of looking away", emotionType: "open admiration", visualSignals: ["direct gaze sustained", "slight blush", "no retreat from being caught", "soft smile"], industryIds: ["restaurant"], tags: ["admiration", "staring", "caught", "held-gaze"], priority: 5, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:restaurant:long-marriage-knowing-look", kind: "emotional_moment", moment: "Long-married couple exchanging a look about another table — a whole conversation in one glance, no words needed", emotionType: "deep familiarity", visualSignals: ["brief eye contact", "suppressed smile", "micro head tilt", "both looking away at the same moment"], industryIds: ["restaurant"], tags: ["long-marriage", "knowing-look", "shared-language", "familiarity"], priority: 6, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Celebration / life moments (14) ──────────────────────────────────────────
  { id: "emotional_moment:restaurant:birthday-song-face-lit", kind: "emotional_moment", moment: "Entire restaurant turning to sing Happy Birthday — the honoured person's face lit by candles, tears forming", emotionType: "public joy and vulnerability", visualSignals: ["face illuminated from below", "eyes glistening", "hands clasped over mouth or chest", "others watching"], industryIds: ["restaurant"], tags: ["birthday", "singing", "candles", "public-joy"], priority: 1, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:restaurant:graduation-parent-pride", kind: "emotional_moment", moment: "Parent at graduation dinner — looking at graduate with visible pride, blinking extra hard, not saying anything adequate", emotionType: "parental pride", visualSignals: ["sustained gaze at child", "chest expanded", "extra blinks", "smile that won't stop"], industryIds: ["restaurant"], tags: ["graduation", "parent", "pride", "milestone"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:restaurant:good-news-announced-gasp", kind: "emotional_moment", moment: "Good news announced at the table — the gasp, then arms reaching across, then all talking at once", emotionType: "shared joy explosion", visualSignals: ["hands flying to faces", "simultaneous movement toward announcer", "all talking at once", "food completely forgotten"], industryIds: ["restaurant"], tags: ["good-news", "announcement", "gasp", "joy"], priority: 3, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:restaurant:retirement-toast-tears", kind: "emotional_moment", moment: "Retirement toast — the honouree trying to give a speech, voice catching, colleagues leaning in", emotionType: "bittersweet achievement", visualSignals: ["voice breaking", "pausing to compose", "others misty-eyed", "raised glasses in solidarity"], industryIds: ["restaurant"], tags: ["retirement", "toast", "speech", "bittersweet"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:restaurant:deal-closed-handshake-relief", kind: "emotional_moment", moment: "Handshake across a restaurant table after deal closes — relief and satisfaction visible in the exhale", emotionType: "professional satisfaction / relief", visualSignals: ["firm handshake", "both exhaling", "shoulders dropping", "first real smile of the meal"], industryIds: ["restaurant"], tags: ["deal", "handshake", "relief", "professional"], priority: 5, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "emotional_moment:restaurant:baby-news-silence-then-eruption", kind: "emotional_moment", moment: "Pregnancy announcement at family dinner — one silent second while everyone processes, then the eruption", emotionType: "joyful shock", visualSignals: ["still faces processing", "then all moving at once", "maternal grandmother's hand to heart", "father blinking fast"], industryIds: ["restaurant"], tags: ["pregnancy-announcement", "shock", "joy", "family"], priority: 6, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:restaurant:new-resident-first-meal-city", kind: "emotional_moment", moment: "Person's first meal in a new city — slightly overwhelmed by menu choices, the feeling of the beginning", emotionType: "nervous excitement", visualSignals: ["wide eyes at menu", "looking around at everything", "small smile at being somewhere new", "deliberate careful choosing"], industryIds: ["restaurant"], tags: ["new-city", "beginning", "overwhelm", "excitement"], priority: 7, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "emotional_moment:restaurant:last-supper-before-move", kind: "emotional_moment", moment: "Last meal at favourite restaurant before moving away — trying to memorise the taste, bittersweetness visible", emotionType: "bittersweet attachment", visualSignals: ["eating slowly and deliberately", "looking around the room", "slightly sad smile", "lingering on each bite"], industryIds: ["restaurant"], tags: ["last-meal", "moving-away", "bittersweet", "memory"], priority: 8, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },

  // ── Belonging / warmth (12) ───────────────────────────────────────────────────
  { id: "emotional_moment:restaurant:regulars-known-by-name", kind: "emotional_moment", moment: "Regular walks in and is greeted by name — their posture changes immediately, they are home", emotionType: "belonging", visualSignals: ["posture lifting on name recognition", "immediate smile", "shoulders relaxing", "quick familiarity with environment"], industryIds: ["restaurant"], tags: ["regular", "known", "belonging", "home"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:restaurant:neighbourhood-table-reserved", kind: "emotional_moment", moment: "Regular's reserved table waiting — 'their' table with a small reserved sign, the ownership of the habitual", emotionType: "privileged belonging", visualSignals: ["reserved sign visible", "regular approaching with recognition", "staff already knowing their order", "proprietary settling-in"], industryIds: ["restaurant"], tags: ["reserved-table", "regular", "belonging", "habit"], priority: 2, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "emotional_moment:restaurant:staff-birthday-surprise", kind: "emotional_moment", moment: "Staff arrive with surprise birthday dessert — the guest not having mentioned it, the restaurant knowing", emotionType: "touched surprise", visualSignals: ["genuine surprise", "hand to chest", "eyes glistening", "looking around to understand how they knew"], industryIds: ["restaurant"], tags: ["birthday", "surprise", "touched", "staff-knowledge"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:restaurant:welcome-back-after-absence", kind: "emotional_moment", moment: "Return after long absence — 'We've missed you' from staff, the guest visibly moved to have been noticed", emotionType: "recognition and warmth", visualSignals: ["guest's eyes widening", "slight flush", "stopping in place before continuing to table", "gratitude in body language"], industryIds: ["restaurant"], tags: ["return", "absence", "missed", "recognition"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "emotional_moment:restaurant:family-table-too-loud", kind: "emotional_moment", moment: "Family table getting too loud — other diners glancing but smiling, the noise is actually warmth, joy visible", emotionType: "uninhibited joy", visualSignals: ["all talking at once", "children animated", "parents unable to control it but not trying hard", "other diners charmed"], industryIds: ["restaurant"], tags: ["family", "loud", "joy", "uninhibited"], priority: 5, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "emotional_moment:restaurant:two-strangers-sharing-table", kind: "emotional_moment", moment: "Two strangers at communal table who become unexpected dining companions — tentative conversation becoming genuine", emotionType: "unexpected connection", visualSignals: ["tentative opening", "body language gradually opening", "shared dish recommendation", "lingering after both have finished"], industryIds: ["restaurant"], tags: ["strangers", "communal-table", "unexpected", "connection"], priority: 6, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
];
