import type { RelationshipKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const RESTAURANT_RELATIONSHIPS: RelationshipKnowledgeNode[] = [
  // ── Romantic (10) ────────────────────────────────────────────────────────────
  { id: "relationship:restaurant:long-term-couple-comfortable", kind: "relationship", description: "Long-term couple at dinner — comfortable silence and easy conversation alternating, decades of trust visible", sceneRoles: ["person A", "person B"], industryIds: ["restaurant"], tags: ["couple", "long-term", "comfort", "trust"], priority: 1, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:restaurant:first-date-tension", kind: "relationship", description: "First date — nervous energy, careful self-presentation, the potential of everything not yet decided", sceneRoles: ["person A", "person B"], industryIds: ["restaurant"], tags: ["first-date", "nervous", "potential", "new"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:restaurant:proposal-moment", kind: "relationship", description: "One partner proposing to the other — the world distilled to this table, this question, this answer", sceneRoles: ["proposer", "recipient"], industryIds: ["restaurant"], tags: ["proposal", "romantic", "life-changing", "intimate"], priority: 3, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:restaurant:anniversary-celebration", kind: "relationship", description: "Anniversary dinner — celebrating a specific number of years, shared memory the meal sits inside", sceneRoles: ["person A", "person B"], industryIds: ["restaurant"], tags: ["anniversary", "celebration", "milestone", "romance"], priority: 4, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:restaurant:new-couple-early-phase", kind: "relationship", description: "New couple — still discovering each other, everything is information, every taste shared is significant", sceneRoles: ["person A", "person B"], industryIds: ["restaurant"], tags: ["new-couple", "discovery", "early", "excitement"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:restaurant:reconciliation-dinner", kind: "relationship", description: "Reconciliation dinner — things unsaid but the gesture of the reservation says enough, hope across the table", sceneRoles: ["person A", "person B"], industryIds: ["restaurant"], tags: ["reconciliation", "hope", "repair", "tension"], priority: 6, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:restaurant:blind-date-meeting", kind: "relationship", description: "Blind date — stranger recognition at entrance, the uncertain first few minutes before ease or awkward", sceneRoles: ["person A", "person B"], industryIds: ["restaurant"], tags: ["blind-date", "stranger", "uncertainty", "possibility"], priority: 7, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:restaurant:reunion-after-distance", kind: "relationship", description: "Reunion dinner after time apart — relief in the embrace at entrance, the familiar re-established over food", sceneRoles: ["person A", "person B"], industryIds: ["restaurant"], tags: ["reunion", "distance", "relief", "familiar"], priority: 8, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:restaurant:date-night-routine-special", kind: "relationship", description: "Regular date night — same restaurant, same wine, the ritual that holds the relationship together", sceneRoles: ["person A", "person B"], industryIds: ["restaurant"], tags: ["routine", "ritual", "stability", "connection"], priority: 9, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:restaurant:elderly-long-married", kind: "relationship", description: "Elderly couple married for 50+ years — each knowing what the other will order, love in the ordinary moment", sceneRoles: ["person A", "person B"], industryIds: ["restaurant"], tags: ["elderly", "long-married", "ordinary-love", "decades"], priority: 10, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Family (10) ──────────────────────────────────────────────────────────────
  { id: "relationship:restaurant:parent-child-celebration-meal", kind: "relationship", description: "Parent treating grown child to celebration meal — pride on the parent's face, the child now adult and peer", sceneRoles: ["parent", "adult child"], industryIds: ["restaurant"], tags: ["parent-child", "celebration", "pride", "adult"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:restaurant:grandparent-grandchild", kind: "relationship", description: "Grandparent and grandchild at restaurant — two generations bridged by food, the older teaching the younger", sceneRoles: ["grandparent", "grandchild"], industryIds: ["restaurant"], tags: ["grandparent", "grandchild", "generational", "teaching"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:restaurant:nuclear-family-sunday-lunch", kind: "relationship", description: "Nuclear family Sunday lunch — parents and children, the weekly gathering that anchors the family's week", sceneRoles: ["parents", "children"], industryIds: ["restaurant"], tags: ["family", "sunday", "weekly-ritual", "anchor"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:restaurant:siblings-reunion", kind: "relationship", description: "Siblings reuniting for dinner — shared references, old jokes, lapsing into childhood dynamic, deep comfort", sceneRoles: ["sibling A", "sibling B"], industryIds: ["restaurant"], tags: ["siblings", "reunion", "shared-history", "comfort"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:restaurant:multigenerational-table", kind: "relationship", description: "Multi-generational family table — four generations, the oldest and youngest at opposite ends, family visible", sceneRoles: ["elders", "parents", "children", "grandchildren"], industryIds: ["restaurant"], tags: ["multigenerational", "four-generations", "family", "continuity"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:restaurant:parent-teen-difficult-phase", kind: "relationship", description: "Parent taking teenage child to restaurant — effort to connect, shared meal as neutral ground", sceneRoles: ["parent", "teenager"], industryIds: ["restaurant"], tags: ["parent", "teenager", "connection", "effort"], priority: 6, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "relationship:restaurant:in-laws-first-meal", kind: "relationship", description: "Meeting future in-laws over dinner — performing best self, navigating new family territory", sceneRoles: ["couple", "parents-in-law"], industryIds: ["restaurant"], tags: ["in-laws", "first-meeting", "performance", "family"], priority: 7, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:restaurant:family-celebration-all-together", kind: "relationship", description: "Whole family at celebration dinner — everyone in one place, the rare gathering that won't happen again for years", sceneRoles: ["all family members"], industryIds: ["restaurant"], tags: ["family", "celebration", "rare", "whole-family"], priority: 8, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:restaurant:parent-teaching-child-to-order", kind: "relationship", description: "Parent coaching young child to order from waiter — whispered guidance, child speaking up, pride in both", sceneRoles: ["parent", "young child"], industryIds: ["restaurant"], tags: ["parent", "teaching", "ordering", "milestone"], priority: 9, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:restaurant:family-regular-known-by-staff", kind: "relationship", description: "Family who comes every week — staff knowing children's names, the restaurant as extended family", sceneRoles: ["family", "staff"], industryIds: ["restaurant"], tags: ["regular-family", "belonging", "known", "community"], priority: 10, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Friendship (10) ──────────────────────────────────────────────────────────
  { id: "relationship:restaurant:close-friends-long-dinner", kind: "relationship", description: "Close friends in long dinner — table still occupied 3 hours later, wine second bottle, nowhere to be", sceneRoles: ["friend A", "friend B", "friend C"], industryIds: ["restaurant"], tags: ["close-friends", "long-dinner", "nowhere-to-be", "ease"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:restaurant:girls-night-celebration", kind: "relationship", description: "Women's celebration dinner — champagne, laughter louder than protocol demands, the collective joy", sceneRoles: ["group of women"], industryIds: ["restaurant"], tags: ["girls-night", "champagne", "laughter", "joy"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:restaurant:old-friends-catching-up", kind: "relationship", description: "Old friends who rarely see each other — each story requires several more, three courses barely enough time", sceneRoles: ["old friend A", "old friend B"], industryIds: ["restaurant"], tags: ["old-friends", "catching-up", "stories", "time"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:restaurant:work-friends-after-win", kind: "relationship", description: "Colleagues celebrating a work win at restaurant — the barrier between professional and social lowering over food", sceneRoles: ["colleague A", "colleague B"], industryIds: ["restaurant"], tags: ["work-friends", "celebration", "win", "transition"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:restaurant:support-after-breakup", kind: "relationship", description: "Friend supporting friend through breakup over dinner — one talking, one listening, wine mediating", sceneRoles: ["supporting friend", "hurting friend"], industryIds: ["restaurant"], tags: ["support", "breakup", "listening", "care"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── Professional (10) ────────────────────────────────────────────────────────
  { id: "relationship:restaurant:business-client-entertaining", kind: "relationship", description: "Host entertaining client — paying attention, guiding the meal, demonstrating status through generosity", sceneRoles: ["host", "client"], industryIds: ["restaurant"], tags: ["business", "client", "entertaining", "status"], priority: 1, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:restaurant:interview-over-lunch", kind: "relationship", description: "Job interview over lunch — semi-formal, candidate revealing character beyond CV, employer assessing over food", sceneRoles: ["interviewer", "candidate"], industryIds: ["restaurant"], tags: ["interview", "lunch", "professional", "assessment"], priority: 2, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "relationship:restaurant:deal-signing-dinner", kind: "relationship", description: "Post-deal dinner — papers signed, now celebrating, the relationship transitioning from negotiation to partnership", sceneRoles: ["partner A", "partner B"], industryIds: ["restaurant"], tags: ["deal", "celebration", "partnership", "transition"], priority: 3, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:restaurant:mentor-mentee-dinner", kind: "relationship", description: "Mentor treating mentee to dinner — advice flowing, career wisdom exchanged, gratitude visible", sceneRoles: ["mentor", "mentee"], industryIds: ["restaurant"], tags: ["mentor", "mentee", "wisdom", "gratitude"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:restaurant:team-farewell-dinner", kind: "relationship", description: "Team farewell dinner for departing colleague — the mix of loss and celebration, speeches and awkward toasts", sceneRoles: ["departing colleague", "team"], industryIds: ["restaurant"], tags: ["farewell", "team", "departure", "mixed-emotions"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── Guest–staff (10) ─────────────────────────────────────────────────────────
  { id: "relationship:restaurant:regular-and-staff", kind: "relationship", description: "Regular guest and their favourite server — first-name basis, standing order anticipated, a relationship of place", sceneRoles: ["regular guest", "server"], industryIds: ["restaurant"], tags: ["regular", "server", "belonging", "known"], priority: 1, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:restaurant:chef-guest-feedback", kind: "relationship", description: "Chef receiving feedback at table — standing over seated guest, genuine exchange, expertise meeting appreciation", sceneRoles: ["chef", "guest"], industryIds: ["restaurant"], tags: ["chef", "guest", "feedback", "appreciation"], priority: 2, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:restaurant:sommelier-guidance", kind: "relationship", description: "Sommelier guiding guest through wine selection — building on guest's hints, no pretension, genuine service", sceneRoles: ["sommelier", "guest"], industryIds: ["restaurant"], tags: ["sommelier", "guidance", "wine", "expertise"], priority: 3, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:restaurant:special-occasion-manager-visit", kind: "relationship", description: "Restaurant manager visiting special occasion table — acknowledging anniversary or birthday, care visible", sceneRoles: ["manager", "special occasion guests"], industryIds: ["restaurant"], tags: ["manager", "special-occasion", "care", "acknowledgement"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:restaurant:nervous-guest-kind-server", kind: "relationship", description: "Nervous first-timer in fine dining — kind server lowering the formality, guest relaxing, trust established", sceneRoles: ["nervous guest", "kind server"], industryIds: ["restaurant"], tags: ["nervous", "kindness", "first-time", "trust"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
];
