import type { SceneTypeKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const RESTAURANT_SCENE_TYPES: SceneTypeKnowledgeNode[] = [
  // ── Fine dining interiors (20) ────────────────────────────────────────────────
  { id: "scene_type:restaurant:candlelit-fine-dining", kind: "scene_type", environment: "Fine dining room — white linen tables, 60cm spacing between chairs, single candle centrepiece, muted walls", lightingCharacter: "2700K candlelight with low fill, deep shadows behind chairs, warm highlights on linen", mood: "Intimate, hushed, occasion-worthy — the world has slowed down", industryIds: ["restaurant"], compatibleHeroTypes: ["moment", "product", "person"], tags: ["candlelight", "fine-dining", "intimate", "linen"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "scene_type:restaurant:private-dining-room", kind: "scene_type", environment: "Private dining room — one table for 8–12, wood panelling or upholstered walls, no other diners visible", lightingCharacter: "Warm pendant light overhead, wall sconces filling edges, no hard shadows", mood: "Exclusive, celebratory, fully contained — the outside world does not exist here", industryIds: ["restaurant"], compatibleHeroTypes: ["moment", "lifestyle", "person"], tags: ["private", "exclusive", "group", "occasion"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "scene_type:restaurant:tasting-menu-dining-room", kind: "scene_type", environment: "Small tasting menu room — 8 tables maximum, sparse decor, each table a performance space", lightingCharacter: "Pinspot lighting on plates, peripheral dark, faces in warm rim light", mood: "Focused, theatrical, reverent — the kitchen is the stage", industryIds: ["restaurant"], compatibleHeroTypes: ["product", "moment", "authority"], tags: ["tasting-menu", "theatre", "pinspot", "intimate"], priority: 3, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "scene_type:restaurant:terrace-evening-city", kind: "scene_type", environment: "Rooftop or garden terrace at evening — city lights below, string lights above, soft landscaping at edges", lightingCharacter: "Warm string lights at 2900K, city glow in background, candles on tables, natural twilight fade", mood: "Romantic, aspirational, open — the city is the backdrop to this moment", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "moment"], tags: ["terrace", "rooftop", "city", "evening"], priority: 4, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "scene_type:restaurant:wine-cellar-dining", kind: "scene_type", environment: "Wine cellar converted to intimate dining — bottles floor to ceiling, stone arches, single table", lightingCharacter: "Very low ambient light, candles primary source, bottle labels catching warm glow", mood: "Cave-like, deeply private, connoisseur — time has no meaning here", industryIds: ["restaurant"], compatibleHeroTypes: ["product", "moment", "person"], tags: ["wine-cellar", "intimate", "stone", "underground"], priority: 5, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "scene_type:restaurant:modern-minimal-dining", kind: "scene_type", environment: "Modern minimal dining room — concrete or stone surfaces, no tablecloths, art as single statement", lightingCharacter: "Architectural downlights at 3000K, very precise shadows, no light spill between tables", mood: "Confident, design-forward, understated luxury — the food does all the talking", industryIds: ["restaurant"], compatibleHeroTypes: ["product", "environment", "moment"], tags: ["minimal", "concrete", "modern", "design"], priority: 6, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "scene_type:restaurant:high-window-botanical", kind: "scene_type", environment: "Dining room with floor-to-ceiling windows and living plant wall — jungle-like but curated, natural abundance", lightingCharacter: "Diffused natural daylight through white film, botanical shadow patterns, green light bounce from plants", mood: "Abundant, fresh, wellness-adjacent but still aspirational", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "product", "person"], tags: ["botanical", "green", "windows", "natural-light"], priority: 7, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:restaurant:heritage-building-repurposed", kind: "scene_type", environment: "Dining inside heritage building — exposed brick or stone, high ceilings, modern furniture in contrast", lightingCharacter: "Industrial pendant lights at 2800K, warm against aged stone, shadows in vaulted ceiling", mood: "Authentic, narrative, the place has memory — you are dining inside history", industryIds: ["restaurant"], compatibleHeroTypes: ["environment", "lifestyle", "person"], tags: ["heritage", "brick", "high-ceilings", "narrative"], priority: 8, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "scene_type:restaurant:chef-table-kitchen-adjacent", kind: "scene_type", environment: "Chef's table at edge of open kitchen — 2 to 6 seats, full view of service, separation by glass or pass", lightingCharacter: "Kitchen bright at 4000K behind, dining dim at 2700K, faces in warm intimacy against cool kitchen glow", mood: "Insider privilege, education, witnessing mastery — you have been let into the inner sanctum", industryIds: ["restaurant"], compatibleHeroTypes: ["authority", "moment", "person"], tags: ["chef-table", "kitchen-view", "exclusive", "insider"], priority: 9, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "scene_type:restaurant:solo-diner-bar-seat", kind: "scene_type", environment: "Bar counter with single seat — broad window ahead, menu open, wine poured, city or kitchen in view", lightingCharacter: "Warm bar lighting at 2700K, natural window light at daylight from outside, single lamp behind", mood: "Self-possessed, adult pleasure, the solo dining experience as treat not compromise", industryIds: ["restaurant"], compatibleHeroTypes: ["person", "lifestyle", "product"], tags: ["solo", "bar", "self-possessed", "urban"], priority: 10, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── Casual / family dining (15) ──────────────────────────────────────────────
  { id: "scene_type:restaurant:rustic-trattoria", kind: "scene_type", environment: "Rustic Italian trattoria — paper tablecloths, wine in carafes, family tables close together, exposed pipes", lightingCharacter: "Warm overhead pendant at 2800K, shadow under tables, faces catching warm fill from walls", mood: "Noisy, generous, familiar — this place has been here 40 years and everything is fine", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "product"], tags: ["trattoria", "rustic", "family", "authentic"], priority: 1, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:restaurant:outdoor-market-terrace", kind: "scene_type", environment: "Outdoor market terrace — mismatched chairs, parasols, people at adjacent tables, market activity beyond", lightingCharacter: "Full diffused daylight, parasol shadow creating pockets, bright background against shaded foreground", mood: "Alive, democratic, European — eating is participation in public life", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "moment"], tags: ["outdoor", "market", "parasol", "daylight"], priority: 2, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:restaurant:family-booth-corner", kind: "scene_type", environment: "Corner booth in family restaurant — built-in bench seating, children's drawings on paper, family contained", lightingCharacter: "Warm ambient at 2900K, even coverage, no hard shadows, faces visible and inviting", mood: "Safe, familiar, the table belongs to this family — the corner booth is always theirs", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "moment"], tags: ["booth", "family", "corner", "warmth"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "scene_type:restaurant:brunch-white-walls-sunlight", kind: "scene_type", environment: "Bright brunch café — white walls, tiled floor, wooden furniture, plants on windowsill, Sunday morning", lightingCharacter: "Brilliant natural light from east-facing window, sharp shadows on white surfaces, soft bounce fill", mood: "Optimistic, slow, civilised morning — the week belongs to them", industryIds: ["restaurant"], compatibleHeroTypes: ["product", "lifestyle", "person"], tags: ["brunch", "white", "sunlight", "weekend"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "scene_type:restaurant:street-food-market-hall", kind: "scene_type", environment: "Indoor market hall with multiple vendors — high industrial ceiling, communal tables, queue of people behind hero", lightingCharacter: "Mixed industrial light and vendor spotlights, high contrast, food illuminated from above by heat lamps", mood: "Democratic, energetic, discovery — the best food in the city for a fraction of the price", industryIds: ["restaurant"], compatibleHeroTypes: ["product", "person", "moment"], tags: ["market-hall", "street-food", "communal", "industrial"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "scene_type:restaurant:noodle-bar-counter", kind: "scene_type", environment: "Noodle bar with counter seating — chefs visible behind, bowls lined up, steam above pass, bar stools", lightingCharacter: "Bright kitchen light behind, warm counter light in front, steam catching back-light", mood: "Focused, fast, masterful — this is about the bowl in front of you", industryIds: ["restaurant"], compatibleHeroTypes: ["product", "authority", "person"], tags: ["noodle-bar", "counter", "steam", "kitchen"], priority: 6, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:restaurant:garden-patio-lunch", kind: "scene_type", environment: "Private garden patio — hedged perimeter, bistro tables, gravel underfoot, flowering plants in pots", lightingCharacter: "Dappled shade from overhead canopy, bright gaps catching faces and plates, golden midday light", mood: "Hidden from the city, elevated leisure, the kind of lunch you remember", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "product", "person"], tags: ["garden", "patio", "dappled", "lunch"], priority: 7, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "scene_type:restaurant:harbourside-waterfront", kind: "scene_type", environment: "Waterfront restaurant — tables at water edge, boats in distance, open sky, natural horizon", lightingCharacter: "Golden hour light reflecting off water, table facing into soft directional sun, background glow", mood: "Expansive, aspirational, the lunch that earns the view", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "product"], tags: ["waterfront", "harbour", "golden-hour", "view"], priority: 8, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:restaurant:deli-counter-morning", kind: "scene_type", environment: "Neighbourhood deli or café counter — cases of pastries, coffee machine in centre, regulars at small tables", lightingCharacter: "Warm service counter light, natural from windows, coffee machine steam backlit", mood: "Habitual, neighbourhood, Tuesday morning — the kind of place you know you belong", industryIds: ["restaurant"], compatibleHeroTypes: ["person", "product", "lifestyle"], tags: ["deli", "neighbourhood", "morning", "regulars"], priority: 9, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "scene_type:restaurant:barbecue-outdoor-grill", kind: "scene_type", environment: "Outdoor BBQ setting — smoke pit visible, picnic tables, string lights at dusk, relaxed posture", lightingCharacter: "Fire and ember glow from pit, string lights at 2700K, dusk sky in background, heavy smoke scatter", mood: "Democratic, primal, communal — the shared smoke binds the group", industryIds: ["restaurant"], compatibleHeroTypes: ["product", "lifestyle", "person"], tags: ["bbq", "smoke", "outdoor", "communal"], priority: 10, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "scene_type:restaurant:lunch-counter-daily-special", kind: "scene_type", environment: "Daily lunch counter — specials on chalkboard, stools at counter, line forming behind, efficient service", lightingCharacter: "Neutral service light, bright kitchen behind, chalkboard lit from above", mood: "Efficient, loyal, local institution — the daily special is a small joy in a working day", industryIds: ["restaurant"], compatibleHeroTypes: ["product", "person", "authority"], tags: ["lunch-counter", "specials", "chalkboard", "local"], priority: 11, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },
  { id: "scene_type:restaurant:pizza-parlour-booth", kind: "scene_type", environment: "Classic pizza parlour — red-checked tablecloth, Chianti bottle with candle wax, photos on wall, families", lightingCharacter: "Warm incandescent at 2700K, candle supplement, slightly dim but not dark, faces warm and visible", mood: "Nostalgic, unpretentious, good cheer — this is the place everyone grows up going to", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "product"], tags: ["pizza", "checked-tablecloth", "nostalgic", "family"], priority: 12, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "scene_type:restaurant:japanese-minimalist-dining", kind: "scene_type", environment: "Japanese minimalist dining — low tables, tatami adjacent, natural wood, ceramic ware, single flower", lightingCharacter: "Soft diffused daylight through shoji screen, minimal shadow, pure and considered light", mood: "Meditative, precise, cultural — eating as a form of respect for ingredient and technique", industryIds: ["restaurant"], compatibleHeroTypes: ["product", "environment", "moment"], tags: ["japanese", "minimal", "tatami", "precision"], priority: 13, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:restaurant:mexican-colorful-walls", kind: "scene_type", environment: "Vibrant Mexican cantina — painted walls in terracotta and blue, papel picado above, open kitchen", lightingCharacter: "Warm ambient with colour reflected from walls, colourful light scatter, daylight at entrance", mood: "Celebratory, generous, the food and the space are both a party", industryIds: ["restaurant"], compatibleHeroTypes: ["product", "lifestyle", "person"], tags: ["mexican", "colourful", "papel-picado", "vibrant"], priority: 14, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "scene_type:restaurant:dimsum-morning-trolleys", kind: "scene_type", environment: "Yum cha restaurant — trolleys moving between tables, large family groups, steam baskets everywhere, noise", lightingCharacter: "Bright functional overhead light, steam diffusing direct light, trolley carts catching overhead", mood: "Alive, communal, tradition-as-choreography — everyone belongs here on Sunday morning", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "product", "person"], tags: ["dimsum", "trolley", "steam", "communal"], priority: 15, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── Kitchen environments (15) ────────────────────────────────────────────────
  { id: "scene_type:restaurant:open-kitchen-pass", kind: "scene_type", environment: "Open kitchen visible to dining room — pass window wide, brigade in whites, plates moving in choreography", lightingCharacter: "Bright 4000K kitchen against 2700K dining, pass rim lit, chef faces in warm spill from dining side", mood: "Theatre of precision, the curtain is gone — watching mastery in real time", industryIds: ["restaurant"], compatibleHeroTypes: ["authority", "environment", "moment"], tags: ["open-kitchen", "pass", "brigade", "theatre"], priority: 1, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "scene_type:restaurant:wood-fire-kitchen", kind: "scene_type", environment: "Wood-fired kitchen — large stone oven dominant, fire visible, heavy smoke extraction, blackened walls", lightingCharacter: "Fire glow as primary source — orange and red at 1800K, ember glow at floor, faces lit dramatically", mood: "Primal, elemental, ancient technique with intentional modern deployment", industryIds: ["restaurant"], compatibleHeroTypes: ["authority", "product", "environment"], tags: ["wood-fire", "oven", "flames", "primal"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "scene_type:restaurant:bakery-production-morning", kind: "scene_type", environment: "Bakery production kitchen at 4am — flour everywhere, industrial mixers, trays of bread proofing", lightingCharacter: "Fluorescent overhead in far background, warm spotlights on work surfaces, window light just beginning", mood: "Before-the-world, dedicated craft — the bread is ready before anyone is awake", industryIds: ["restaurant"], compatibleHeroTypes: ["authority", "product", "environment"], tags: ["bakery", "4am", "flour", "production"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:restaurant:pastry-station", kind: "scene_type", environment: "Pastry station — marble surface, tools laid out with precision, sugar work and tempering equipment", lightingCharacter: "Overhead spot on marble surface, no shadows on work area, soft ambient around edges", mood: "Exacting, quiet concentration — pastry as applied mathematics and art simultaneously", industryIds: ["restaurant"], compatibleHeroTypes: ["authority", "product", "moment"], tags: ["pastry", "marble", "precision", "station"], priority: 4, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "scene_type:restaurant:grill-station-service", kind: "scene_type", environment: "Grill station during service — six proteins on grill, chef managing timing, intense heat visible in air", lightingCharacter: "Grill glow below, harsh extraction light above, faces in dramatic side light from grill", mood: "Pressure, controlled urgency — the station is a battlefield with precise rules", industryIds: ["restaurant"], compatibleHeroTypes: ["authority", "environment", "moment"], tags: ["grill", "service", "heat", "pressure"], priority: 5, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:restaurant:prep-kitchen-morning", kind: "scene_type", environment: "Prep kitchen at 8am — mise en place in progress, calm before service, radio playing, coffee on counter", lightingCharacter: "Natural light from windows dominant at morning, supplemented by task lighting, clean and clear", mood: "Before the storm, purposeful calm — this is where the magic is assembled quietly", industryIds: ["restaurant"], compatibleHeroTypes: ["authority", "environment", "person"], tags: ["prep", "morning", "calm", "mise-en-place"], priority: 6, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "scene_type:restaurant:charcuterie-curing-room", kind: "scene_type", environment: "Curing room — legs of ham hanging from ceiling, controlled temperature, wooden shelves of charcuterie", lightingCharacter: "Low controlled light, product in semi-shadow, cool temperature light consistent with curing environment", mood: "Patient craft, time as ingredient — these products cannot be rushed", industryIds: ["restaurant"], compatibleHeroTypes: ["product", "authority", "environment"], tags: ["charcuterie", "curing", "hanging", "time"], priority: 7, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "scene_type:restaurant:cocktail-bar-setup", kind: "scene_type", environment: "Cocktail bar setup before opening — bottles organised by category, garnishes prepped, shakers polished", lightingCharacter: "Bar under-counter light on bottles, warm at 2700K, bottles as lit sculpture, bar surface reflective", mood: "Ready, thoughtful — every tool in its place, the service has not yet begun", industryIds: ["restaurant"], compatibleHeroTypes: ["authority", "environment", "product"], tags: ["bar", "setup", "bottles", "polished"], priority: 8, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "scene_type:restaurant:plating-station", kind: "scene_type", environment: "Plating station — warm plates arriving from stack, tweezers and sauce spoons at ready, each plate a canvas", lightingCharacter: "Pinspot from above on plate, hands in highlight, background kitchen in darkness, clinical precision", mood: "Art and science — the plate leaves this station as a finished work", industryIds: ["restaurant"], compatibleHeroTypes: ["authority", "product", "moment"], tags: ["plating", "tweezers", "pinspot", "finishing"], priority: 9, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:restaurant:walk-in-produce-arrival", kind: "scene_type", environment: "Walk-in cool room receiving fresh produce — crates of vegetables, chef inspecting arrivals, cool blue-white light", lightingCharacter: "Cool fluorescent at 5000K, cold temperature light matching refrigeration, crisp shadows", mood: "Quality at source — this is where the standard is set before any cooking begins", industryIds: ["restaurant"], compatibleHeroTypes: ["authority", "product", "environment"], tags: ["walk-in", "produce", "inspection", "cold"], priority: 10, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },

  // ── Outdoor / seasonal scenes (15) ──────────────────────────────────────────
  { id: "scene_type:restaurant:winter-fireplace-interior", kind: "scene_type", environment: "Winter dining room — fire burning in stone fireplace, guests close, blankets on chairs, low light", lightingCharacter: "Fireplace as dominant source at 1800–2000K, deep orange warmth, cold blue through windows as contrast", mood: "Refuge, seasonal warmth, there is nowhere to be but here", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "moment"], tags: ["winter", "fireplace", "warmth", "refuge"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "scene_type:restaurant:summer-garden-white-tablecloth", kind: "scene_type", environment: "Summer garden — white tablecloths outside, dappled tree shade, afternoon light, sounds of the garden", lightingCharacter: "Dappled 4500K daylight through canopy, tablecloth filling shadows with bounce, gentle contrast", mood: "High summer abundance, the best table is outside today", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "product", "person"], tags: ["summer", "garden", "white-tablecloth", "dappled"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:restaurant:christmas-dining-table", kind: "scene_type", environment: "Christmas restaurant dining — poinsettia, candles in holly, room full with families, warm glow everywhere", lightingCharacter: "Extra warm candles and pendant at 2600K, twinkling from decorative lights, faces flushed and warm", mood: "Annual ritual, abundance, family — this table is the event of the year", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "moment"], tags: ["christmas", "seasonal", "family", "festive"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "scene_type:restaurant:spring-blossom-terrace", kind: "scene_type", environment: "Terrace with spring blossom overhead — cherry or magnolia petals, fresh air, first warm weekend", lightingCharacter: "Bright spring daylight at 5500K, petals creating soft shadow play, high key with gentle fill", mood: "Renewal, first warmth of the year, the body relieved the cold is over", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "product"], tags: ["spring", "blossom", "terrace", "renewal"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:restaurant:rainy-window-interior", kind: "scene_type", environment: "Rainy day interior — condensation on windows, street activity blurred outside, interior dry and warm", lightingCharacter: "Warm interior against grey exterior light, contrast of warmth inside and cold outside clearly visible", mood: "Sanctuary, the pleasure of being inside while weather justifies the decision", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "product"], tags: ["rain", "window", "contrast", "sanctuary"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "scene_type:restaurant:harvest-table-rustic", kind: "scene_type", environment: "Long harvest table — autumnal decoration, deep wooden surface, produce and leaves as centrepiece", lightingCharacter: "Warm golden-orange autumn light, low raking angle across table surface, long shadows", mood: "Seasonal abundance, gathering before winter — gratitude for harvest", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "product", "moment"], tags: ["harvest", "autumn", "abundance", "seasonal"], priority: 6, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "scene_type:restaurant:poolside-dining", kind: "scene_type", environment: "Poolside dining — table at pool edge, water reflection casting light patterns, resort luxury visible", lightingCharacter: "Reflected pool light as moving fill, direct sun from above, aquamarine bounce, golden hour peak", mood: "Resort luxury, summer peak, earned leisure — the pool is close enough to touch", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "product"], tags: ["pool", "resort", "luxury", "summer"], priority: 7, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "scene_type:restaurant:ski-lodge-apreski", kind: "scene_type", environment: "Ski lodge dining — mountain view through glass, snow outside, fire inside, après-ski crowd", lightingCharacter: "Snow reflection outside providing brilliant fill, fire inside at 2000K, faces lit by both extremes", mood: "Physical satisfaction after exertion, mountain luxury, the best meal because you earned it", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "product"], tags: ["ski-lodge", "mountain", "snow", "fireside"], priority: 8, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "scene_type:restaurant:beach-restaurant-sunset", kind: "scene_type", environment: "Beachside restaurant at sunset — tables on sand, feet optional bare, ocean in background, last light", lightingCharacter: "Deep golden 2200K sunset light, ocean shimmer, long warm shadows, sky pink and orange behind", mood: "The ideal version of today — sun going down on a perfect meal", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "moment"], tags: ["beach", "sunset", "ocean", "barefoot"], priority: 9, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:restaurant:farmers-market-adjacent", kind: "scene_type", environment: "Restaurant seating adjacent to weekend farmers' market — produce stalls visible, kitchen sourcing live", lightingCharacter: "Full outdoor daylight, market activity casting movement, bright and democratic", mood: "Connection to provenance, the farm and the table are metres apart", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "product"], tags: ["farmers-market", "provenance", "outdoor", "community"], priority: 10, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },

  // ── Bar / cocktail spaces (10) ────────────────────────────────────────────────
  { id: "scene_type:restaurant:speakeasy-hidden-bar", kind: "scene_type", environment: "Speakeasy bar — accessed through hidden entrance, low ceilings, leather banquettes, dark wood", lightingCharacter: "Very low ambient, candles and Edison bulbs at 2200K, faces mostly in shadow with warm highlight", mood: "Clandestine pleasure, insider status, the bar that not everyone can find", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "product"], tags: ["speakeasy", "hidden", "intimate", "leather"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "scene_type:restaurant:marble-bar-counter-daylight", kind: "scene_type", environment: "Marble bar counter in daylight — windows at back, bottles organised in front, clean and precise surfaces", lightingCharacter: "Bright daylight at 5500K reflecting off marble, bottle labels vivid, bar staff faces evenly lit", mood: "Upscale casual, the bar as sophisticated social hub at midday", industryIds: ["restaurant"], compatibleHeroTypes: ["authority", "product", "person"], tags: ["marble", "bar", "daylight", "upscale"], priority: 2, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "scene_type:restaurant:whisky-bar-library-wall", kind: "scene_type", environment: "Whisky bar — library wall of bottles from floor to ceiling, rolling ladder, leather chairs, fireplace", lightingCharacter: "Low warm library light, bottles backlit on shelf, fire supplement, amber everywhere", mood: "Connoisseur leisure, the serious pleasure of comparison and depth", industryIds: ["restaurant"], compatibleHeroTypes: ["product", "person", "authority"], tags: ["whisky", "library", "leather", "fire"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:restaurant:rooftop-bar-cityscape", kind: "scene_type", environment: "Rooftop cocktail bar — city skyline, infinity edge or glass balustrade, crowd in cocktail attire", lightingCharacter: "City lights as background illumination, bar lighting at 2700K, golden hour to blue hour sky", mood: "Arrival, status, above the city — tonight is a specific kind of night", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "person", "moment"], tags: ["rooftop", "cocktail", "city", "skyline"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "scene_type:restaurant:natural-wine-bar-casual", kind: "scene_type", environment: "Natural wine bar — terracotta tiles, mismatched glasses on counter, chalkboard list, no pretension", lightingCharacter: "Warm lamp light at 2800K, natural pigment walls reflecting warmth, late afternoon into evening", mood: "Anti-formality, the new expert is relaxed — wine as conversation not ceremony", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "product", "person"], tags: ["natural-wine", "terracotta", "casual", "chalkboard"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── Delivery / contemporary (5) ──────────────────────────────────────────────
  { id: "scene_type:restaurant:modern-home-dining", kind: "scene_type", environment: "Modern home dining room — restaurant-quality meal delivered, real plates, candles for the occasion", lightingCharacter: "Home pendant warm at 2700K, candle supplement, room slightly dim, restaurant quality framing", mood: "The restaurant brought to you — the occasion without the reservation", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "product", "person"], tags: ["home", "delivery", "elevated", "modern"], priority: 1, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "scene_type:restaurant:park-picnic-premium", kind: "scene_type", environment: "Premium picnic in park — linen, real cutlery, charcuterie and wine, green grass, private space", lightingCharacter: "Full afternoon daylight, dappled tree cover, bright and fresh, shadows on linen visible", mood: "Urban luxury outdoors — the restaurant experience transported to grass", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "product", "person"], tags: ["picnic", "park", "luxury", "outdoor"], priority: 2, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "scene_type:restaurant:sofa-takeaway-night", kind: "scene_type", environment: "Sofa delivery scene — coffee table with takeaway containers, glass of wine, TV off, attention on food", lightingCharacter: "Warm lamp at 2700K, containers catching soft side light, comfortable and low ambiance", mood: "Permission to be comfortable — this meal is a reward for the day's demands", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "product", "person"], tags: ["sofa", "takeaway", "home", "night"], priority: 3, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },
  { id: "scene_type:restaurant:food-photography-studio", kind: "scene_type", environment: "Clean food photography surface — slate or marble, perfect negative space, single element composition", lightingCharacter: "Controlled studio light — large diffusion from left, subtle fill from right, zero spill", mood: "Clinical clarity — this shot is entirely about the food's beauty", industryIds: ["restaurant"], compatibleHeroTypes: ["product"], tags: ["studio", "photography", "clean", "product"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "scene_type:restaurant:meal-kit-unboxing-counter", kind: "scene_type", environment: "Kitchen counter with meal kit unboxed — ingredients arranged, recipe card visible, anticipation of cooking", lightingCharacter: "Bright kitchen overhead at 4000K, natural window supplementing, ingredients vivid and clear", mood: "Agency and delight — cooking this meal is part of the experience", industryIds: ["restaurant"], compatibleHeroTypes: ["lifestyle", "product", "person"], tags: ["meal-kit", "counter", "unboxing", "cooking"], priority: 5, weight: 0.77, confidence: "high", commercialScore: 76, futureMetadata: fm },
];
