import type { BehaviourKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const HOSPITAL_BEHAVIOURS: BehaviourKnowledgeNode[] = [
  // ── Doctor explaining with model or scan (10) ─────────────────────────────
  { id: "behaviour:hospital:doctor-pointing-at-scan-on-screen", kind: "behaviour", description: "Doctor pointing to specific area on patient's scan on screen — tracing the anatomy with finger, narrating what the image shows in plain language", emotionalSignal: "educational clarity", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["doctor", "scan", "pointing", "education"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:hospital:consultant-drawing-anatomy-on-paper", kind: "behaviour", description: "Consultant drawing quick anatomical diagram on paper to explain surgical approach — pen in hand, patient watching the sketch form", emotionalSignal: "expert simplification", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["drawing", "anatomy", "consultant", "pen"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:hospital:doctor-holding-model-to-explain-joint", kind: "behaviour", description: "Orthopaedic surgeon holding anatomical joint model — rotating it to show where the problem lies, patient following the movement", emotionalSignal: "tangible understanding", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["model", "joint", "surgeon", "rotating"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:hospital:radiologist-narrating-findings-to-referring-team", kind: "behaviour", description: "Radiologist narrating scan findings to referring clinical team over the image — each finding called out as the scroll progresses through slices", emotionalSignal: "expert authority", compatibleHeroes: ["authority", "environment"], industryIds: ["hospital"], tags: ["radiologist", "findings", "team", "narrating"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:hospital:doctor-using-tablet-to-show-patient-diagram", kind: "behaviour", description: "Doctor turning tablet screen toward patient to show medical illustration — tapping on areas of interest, the digital anatomy explanation", emotionalSignal: "modern transparent care", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["tablet", "illustration", "doctor", "modern"], priority: 5, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:hospital:oncologist-tracing-tumour-extent-on-scan", kind: "behaviour", description: "Oncologist tracing tumour extent on displayed scan — defining the boundaries, explaining what is involved and what is not, patient and family watching", emotionalSignal: "precise information", compatibleHeroes: ["authority", "person", "lifestyle"], industryIds: ["hospital"], tags: ["oncologist", "tumour", "tracing", "explaining"], priority: 6, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:hospital:cardiologist-pointing-to-ecg-features", kind: "behaviour", description: "Cardiologist pointing to specific ECG features on printout — PQRST complex explained at the trace, the pattern made meaningful for the patient", emotionalSignal: "cardiac literacy", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["ecg", "cardiologist", "trace", "features"], priority: 7, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:hospital:neurosurgeon-explaining-brain-anatomy-on-mri", kind: "behaviour", description: "Neurosurgeon walking patient through brain MRI on display — naming structures, locating the abnormality, the extraordinary privilege of being shown your own brain", emotionalSignal: "profound transparency", compatibleHeroes: ["authority", "person", "moment"], industryIds: ["hospital"], tags: ["neurosurgeon", "brain", "mri", "anatomy"], priority: 8, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:hospital:physio-using-movement-to-demonstrate-problem", kind: "behaviour", description: "Physiotherapist demonstrating the movement problem by mirroring the patient's posture — the body as its own teaching tool", emotionalSignal: "embodied understanding", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["physio", "mirroring", "movement", "demonstration"], priority: 6, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:hospital:doctor-comparing-before-after-scans-side-by-side", kind: "behaviour", description: "Doctor placing before-treatment and current scans side by side on dual screen — the visual evidence of treatment working, patient studying the comparison", emotionalSignal: "evidence of progress", compatibleHeroes: ["authority", "person", "moment"], industryIds: ["hospital"], tags: ["before-after", "comparison", "dual-screen", "evidence"], priority: 5, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },

  // ── Patient asking questions and engaging (10) ────────────────────────────
  { id: "behaviour:hospital:patient-asking-question-with-list-in-hand", kind: "behaviour", description: "Patient consulting written list of questions during consultation — methodical, prepared, asserting their right to understand their own care", emotionalSignal: "empowered advocacy", compatibleHeroes: ["person", "lifestyle"], industryIds: ["hospital"], tags: ["patient", "list", "questions", "prepared"], priority: 1, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:hospital:patient-leaning-forward-to-understand", kind: "behaviour", description: "Patient leaning forward in chair toward doctor — physically closing the knowledge gap, engagement visible in posture", emotionalSignal: "active engagement", compatibleHeroes: ["person", "moment"], industryIds: ["hospital"], tags: ["leaning-forward", "engagement", "posture", "listening"], priority: 2, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:hospital:patient-asking-for-explanation-again", kind: "behaviour", description: "Patient asking doctor to explain again — not embarrassed, asserting their need to genuinely understand before they agree to anything", emotionalSignal: "self-advocacy", compatibleHeroes: ["person", "authority"], industryIds: ["hospital"], tags: ["repeat-explanation", "self-advocacy", "understanding", "asserting"], priority: 3, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:hospital:patient-looking-at-own-scan-image", kind: "behaviour", description: "Patient studying their own scan image on screen — hands near face, processing what they see, trying to make sense of their own interior", emotionalSignal: "self-directed understanding", compatibleHeroes: ["person", "moment"], industryIds: ["hospital"], tags: ["patient", "scan", "studying", "interior"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:hospital:family-member-asking-on-patient-behalf", kind: "behaviour", description: "Family member asking clarifying question on behalf of patient — the patient nodding in relief that someone is asking what they could not", emotionalSignal: "supported advocacy", compatibleHeroes: ["lifestyle", "person", "authority"], industryIds: ["hospital"], tags: ["family-member", "asking", "behalf", "support"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:hospital:patient-writing-notes-in-consultation", kind: "behaviour", description: "Patient taking notes during consultation — pen and paper or phone, ensuring nothing is forgotten, the informed patient in action", emotionalSignal: "active information management", compatibleHeroes: ["person", "lifestyle"], industryIds: ["hospital"], tags: ["notes", "patient", "pen", "consultation"], priority: 6, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:hospital:elderly-patient-listening-with-concentration", kind: "behaviour", description: "Elderly patient concentrating intently on doctor's explanation — leaning in slightly, processing carefully, the effort of taking complex medical information in", emotionalSignal: "concentrated reception", compatibleHeroes: ["person", "authority"], industryIds: ["hospital"], tags: ["elderly", "concentration", "listening", "complex"], priority: 7, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:hospital:patient-declining-treatment-option", kind: "behaviour", description: "Patient respectfully declining a treatment option and explaining why — the autonomous decision being made thoughtfully, doctor listening to the reasoning", emotionalSignal: "autonomous decision", compatibleHeroes: ["person", "authority", "moment"], industryIds: ["hospital"], tags: ["declining", "autonomous", "decision", "respectful"], priority: 8, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:hospital:patient-typing-on-phone-after-consultation", kind: "behaviour", description: "Patient looking up information on phone immediately after consultation — confirming what they heard, extending understanding, the modern informed patient", emotionalSignal: "self-directed learning", compatibleHeroes: ["person", "lifestyle"], industryIds: ["hospital"], tags: ["phone", "looking-up", "informed", "modern-patient"], priority: 6, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },
  { id: "behaviour:hospital:patient-reviewing-discharge-letter-carefully", kind: "behaviour", description: "Patient reading their discharge letter very carefully before leaving — checking they understand each point, the document that bridges hospital and home", emotionalSignal: "careful comprehension", compatibleHeroes: ["person", "moment"], industryIds: ["hospital"], tags: ["discharge-letter", "reading", "careful", "bridge"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── Nursing care behaviours (12) ──────────────────────────────────────────
  { id: "behaviour:hospital:nurse-taking-blood-pressure-recording", kind: "behaviour", description: "Nurse applying blood pressure cuff, inflating, reading, and recording — the systematic routine observation that catches deterioration early", emotionalSignal: "systematic vigilance", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["blood-pressure", "cuff", "recording", "vital-signs"], priority: 1, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-checking-patient-wristband-before-medication", kind: "behaviour", description: "Nurse checking patient wristband and asking name before administering medication — the safety ritual that prevents wrong-patient errors", emotionalSignal: "careful safety culture", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["wristband", "check", "medication", "safety"], priority: 2, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-changing-wound-dressing-carefully", kind: "behaviour", description: "Nurse changing surgical wound dressing — aseptic technique, gentle removal, close inspection of healing progress, redressing with care", emotionalSignal: "skilled gentle care", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["wound-dressing", "aseptic", "gentle", "healing"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-repositioning-immobile-patient", kind: "behaviour", description: "Two nurses repositioning immobile patient — coordinated movement, pressure area care, the invisible work that prevents secondary complications", emotionalSignal: "preventive care", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["repositioning", "pressure-care", "coordinated", "preventive"], priority: 4, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-connecting-iv-line-carefully", kind: "behaviour", description: "Nurse connecting IV line to cannula — checking for patency, flushing, connecting infusion, the technical care at every line access", emotionalSignal: "technical precision", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["iv-line", "cannula", "infusion", "technical"], priority: 5, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-calling-emergency-response-from-ward", kind: "behaviour", description: "Nurse at patient bedside recognising deterioration and calling emergency response — calm, clear call, staying with patient while help assembles", emotionalSignal: "clinical vigilance into action", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["emergency-call", "deterioration", "nurse", "vigilance"], priority: 6, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-handwashing-before-entering-bay", kind: "behaviour", description: "Nurse stopping at hand hygiene station before entering patient bay — the repeated ritual of infection prevention that protects every patient", emotionalSignal: "infection control discipline", compatibleHeroes: ["authority", "environment"], industryIds: ["hospital"], tags: ["handwashing", "hygiene", "ritual", "infection"], priority: 7, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-sitting-at-eye-level-to-communicate", kind: "behaviour", description: "Nurse sitting or crouching to be at patient's eye level — the deliberate physical choice that changes the power dynamic in the patient's favour", emotionalSignal: "relational equality", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["eye-level", "sitting", "communication", "equality"], priority: 8, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-providing-anti-nausea-medication-promptly", kind: "behaviour", description: "Nurse responding quickly to patient requesting anti-nausea medication — the rapid response to symptom that makes post-operative recovery bearable", emotionalSignal: "responsive symptom care", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["anti-nausea", "prompt-response", "symptom", "post-op"], priority: 6, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:hospital:night-nurse-torchlight-check-sleeping-patient", kind: "behaviour", description: "Night nurse using torchlight to check sleeping patient — not waking them, ensuring the four-hourly observation without disrupting rest", emotionalSignal: "protective watching", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["night-nurse", "torchlight", "sleeping", "observation"], priority: 5, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-advocate-speaking-for-patient-in-ward-round", kind: "behaviour", description: "Nurse speaking up for patient's perspective during ward round — adding what the patient told them that the patient could not say in the round themselves", emotionalSignal: "patient advocacy", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["advocacy", "ward-round", "voice", "patient-perspective"], priority: 4, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-documenting-observation-in-epr-immediately", kind: "behaviour", description: "Nurse documenting clinical observation in EPR immediately at bedside — real-time recording, no reliance on memory, the discipline of contemporaneous notes", emotionalSignal: "meticulous documentation", compatibleHeroes: ["authority"], industryIds: ["hospital"], tags: ["epr", "documentation", "real-time", "bedside"], priority: 3, weight: 0.77, confidence: "high", commercialScore: 76, futureMetadata: fm },

  // ── Surgical team behaviours (10) ─────────────────────────────────────────
  { id: "behaviour:hospital:surgeon-scrubbing-in-at-sink", kind: "behaviour", description: "Surgeon at scrub sink — systematic nail-to-elbow wash with timed brush, the ritual preparation before entering sterility", emotionalSignal: "professional ritual", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["scrubbing-in", "sink", "ritual", "preparation"], priority: 1, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:hospital:scrub-nurse-counting-instruments-aloud", kind: "behaviour", description: "Scrub nurse counting instruments aloud before and after procedure — methodical tally, each item named, the safety count that prevents retained instruments", emotionalSignal: "rigorous safety", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["counting", "instruments", "safety", "scrub-nurse"], priority: 2, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:hospital:surgeon-calling-time-out-before-incision", kind: "behaviour", description: "Surgeon calling surgical time-out before first incision — whole team pausing, patient ID confirmed, site verified, the ritual that prevents wrong-site surgery", emotionalSignal: "safety culture pride", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["time-out", "safety-check", "incision", "team"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:hospital:anaesthetist-securing-airway-intubation", kind: "behaviour", description: "Anaesthetist securing airway with endotracheal tube — laryngoscope withdrawn, tube taped, capnography confirming position, the airway secured for the procedure", emotionalSignal: "critical skill precision", compatibleHeroes: ["authority", "product"], industryIds: ["hospital"], tags: ["intubation", "airway", "anaesthetist", "capnography"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:hospital:surgical-assistant-retracting-tissue", kind: "behaviour", description: "Surgical assistant providing retraction — holding tissue away from operative field, maintaining exposure, the supportive role that makes the surgeon's view possible", emotionalSignal: "team coordination", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["retraction", "tissue", "assistant", "exposure"], priority: 5, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:hospital:surgeon-tying-suture-with-precision", kind: "behaviour", description: "Surgeon tying suture with deliberate precision — instrument tie, exactly the right tension, each knot placed and locked, the closure of the wound", emotionalSignal: "precise completion", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["suture", "knot", "precision", "closure"], priority: 6, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:hospital:theatre-team-whispering-to-communicate", kind: "behaviour", description: "Theatre team communicating in low voices during critical operative moment — the acoustic discipline of the theatre, communication without disruption", emotionalSignal: "focused collective", compatibleHeroes: ["authority", "environment"], industryIds: ["hospital"], tags: ["whisper", "theatre", "communication", "focus"], priority: 7, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "behaviour:hospital:surgeon-pausing-to-reassess-midprocedure", kind: "behaviour", description: "Surgeon pausing mid-procedure to reassess anatomy — instruments down, moment of thought, the decision to look again before proceeding", emotionalSignal: "deliberate expertise", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["reassessing", "pausing", "anatomy", "deliberate"], priority: 8, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:hospital:scrub-nurse-passing-instrument-without-words", kind: "behaviour", description: "Scrub nurse passing requested instrument without verbal exchange — the team so well practised that the surgeon's hand position alone communicates the request", emotionalSignal: "seamless expertise", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["passing-instrument", "non-verbal", "team", "practised"], priority: 6, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:hospital:circulating-nurse-documenting-in-real-time", kind: "behaviour", description: "Circulating nurse documenting procedure in real time — time of incision, implant batch numbers, everything recorded as it happens", emotionalSignal: "meticulous theatre record", compatibleHeroes: ["authority", "environment"], industryIds: ["hospital"], tags: ["circulating-nurse", "documentation", "real-time", "theatre"], priority: 5, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },

  // ── Family support behaviours (10) ─────────────────────────────────────────
  { id: "behaviour:hospital:family-holding-patient-hand-at-bedside", kind: "behaviour", description: "Family member holding patient's hand at bedside — sitting forward, contact maintained, the simple presence that medicine cannot provide", emotionalSignal: "protective love", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["hospital"], tags: ["hand-holding", "family", "bedside", "presence"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:hospital:partner-stroking-patients-hair-in-bed", kind: "behaviour", description: "Partner gently stroking patient's hair as they lie in bed — the small gesture of love that transcends the clinical context entirely", emotionalSignal: "intimate love in clinical space", compatibleHeroes: ["lifestyle", "person"], industryIds: ["hospital"], tags: ["partner", "stroking", "gentle", "intimate"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:hospital:family-bringing-personal-items-to-bedside", kind: "behaviour", description: "Family arranging personal items around hospital bed — framed photo placed, familiar blanket folded, the personalisation of an institutional space", emotionalSignal: "humanising the clinical", compatibleHeroes: ["lifestyle", "environment"], industryIds: ["hospital"], tags: ["personal-items", "photo", "blanket", "humanising"], priority: 3, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:hospital:father-reading-to-child-patient-in-bed", kind: "behaviour", description: "Father reading aloud to child patient in hospital bed — book open, child following even in discomfort, the normal bedtime made hospital possible", emotionalSignal: "normality preserved", compatibleHeroes: ["lifestyle", "person"], industryIds: ["hospital"], tags: ["father", "reading", "child-patient", "normal"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:hospital:family-eating-together-in-hospital-room", kind: "behaviour", description: "Family sharing meal in patient's private room — bringing food in, eating together, the everyday act that makes the hospital feel less total", emotionalSignal: "everyday reclaimed", compatibleHeroes: ["lifestyle", "person"], industryIds: ["hospital"], tags: ["family-meal", "sharing", "private-room", "everyday"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:hospital:sibling-playing-game-with-child-patient", kind: "behaviour", description: "Sibling playing board game at child patient's bedside — hospital tray as game board, normal rivalry momentarily suspended, illness shared", emotionalSignal: "sibling solidarity", compatibleHeroes: ["lifestyle", "person"], industryIds: ["hospital"], tags: ["sibling", "game", "child-patient", "solidarity"], priority: 6, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:hospital:adult-child-visiting-elderly-parent", kind: "behaviour", description: "Adult child beside elderly parent in hospital — bringing news from home, speaking slowly, the generational care running in reverse", emotionalSignal: "generational role reversal", compatibleHeroes: ["lifestyle", "person"], industryIds: ["hospital"], tags: ["adult-child", "elderly-parent", "generational", "reversal"], priority: 7, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:hospital:family-member-photographing-discharge-moment", kind: "behaviour", description: "Family member photographing the moment the patient is discharged — documenting the milestone, the evidence that it is over, the picture for the family album", emotionalSignal: "milestone documented", compatibleHeroes: ["lifestyle", "moment"], industryIds: ["hospital"], tags: ["photographing", "discharge", "milestone", "family"], priority: 8, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:hospital:friends-laughing-at-bedside-lifting-patient", kind: "behaviour", description: "Friends making patient laugh at bedside — normal conversation, jokes, the laughter that changes the biochemistry and the mood simultaneously", emotionalSignal: "joy as medicine", compatibleHeroes: ["lifestyle", "person"], industryIds: ["hospital"], tags: ["friends", "laughing", "bedside", "joy"], priority: 6, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:hospital:family-praying-quietly-at-bedside", kind: "behaviour", description: "Family member praying quietly at patient's bedside — personal ritual in institutional space, the spiritual dimension of being with a person who is seriously ill", emotionalSignal: "spiritual coping", compatibleHeroes: ["lifestyle", "person", "moment"], industryIds: ["hospital"], tags: ["praying", "spiritual", "quiet", "bedside"], priority: 5, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },

  // ── Allied health and physiotherapy (10) ──────────────────────────────────
  { id: "behaviour:hospital:physio-encouraging-patient-to-take-next-step", kind: "behaviour", description: "Physiotherapist encouragement as patient takes hesitant next step — verbal coaching, hands-near-ready positioning, the precise balance of support and independence", emotionalSignal: "coached courage", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["physio", "encouragement", "step", "coaching"], priority: 1, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:hospital:physio-measuring-joint-range-with-goniometer", kind: "behaviour", description: "Physiotherapist measuring joint range of motion with goniometer — precise angle recorded, the quantification of progress", emotionalSignal: "progress measured", compatibleHeroes: ["authority", "product"], industryIds: ["hospital"], tags: ["goniometer", "range-of-motion", "measuring", "physio"], priority: 2, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:hospital:occupational-therapist-assessing-hand-function", kind: "behaviour", description: "Occupational therapist assessing hand function with peg test — timed, counted, the functional assessment of fine motor skills needed for independence", emotionalSignal: "functional baseline", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["ot", "hand-function", "peg-test", "fine-motor"], priority: 3, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:hospital:dietitian-reviewing-food-chart-with-patient", kind: "behaviour", description: "Dietitian reviewing patient's food and fluid intake chart — calculating nutrition, asking about appetite, the clinical attention to eating as medicine", emotionalSignal: "nutritional care", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["dietitian", "food-chart", "nutrition", "appetite"], priority: 4, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },
  { id: "behaviour:hospital:speech-therapist-testing-safe-swallow", kind: "behaviour", description: "Speech and language therapist conducting swallow assessment — small amounts of thickened fluid, patient concentrating, the safety of eating assessed before any meal", emotionalSignal: "protective assessment", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["swallow-assessment", "speech-therapy", "thickened", "safety"], priority: 5, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:hospital:physio-applying-tens-machine-to-shoulder", kind: "behaviour", description: "Physiotherapist placing TENS electrodes on patient's shoulder — explaining the sensation before switching on, the non-pharmacological pain management in action", emotionalSignal: "pain management without drugs", compatibleHeroes: ["authority", "product"], industryIds: ["hospital"], tags: ["tens", "shoulder", "physio", "non-pharmacological"], priority: 6, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },
  { id: "behaviour:hospital:physio-walking-behind-patient-on-stairs", kind: "behaviour", description: "Physiotherapist walking one step behind patient ascending stairs — hands ready without touching, the confidence-giving presence that makes the attempt possible", emotionalSignal: "safety enabling courage", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["stairs", "physio", "behind", "safety"], priority: 7, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:hospital:ot-teaching-dressing-technique-post-hip", kind: "behaviour", description: "Occupational therapist teaching dressing technique to hip replacement patient — long-handled reacher demonstrated, hip precautions maintained, independence rebuilt", emotionalSignal: "practical independence", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["ot", "dressing", "hip-replacement", "independence"], priority: 8, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:hospital:social-worker-arranging-discharge-care", kind: "behaviour", description: "Social worker arranging discharge care package — on phone coordinating home carers, typing referral, ensuring the patient is not discharged into an unsafe situation", emotionalSignal: "systemic care", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["social-worker", "discharge", "care-package", "coordinating"], priority: 5, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "behaviour:hospital:psychologist-sitting-with-patient-on-ward", kind: "behaviour", description: "Clinical psychologist visiting patient on ward — the conversation about the psychological impact of serious illness, happening in the clinical space", emotionalSignal: "psychological acknowledgment", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["psychologist", "ward-visit", "psychological", "serious-illness"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── Medical team briefing and ward round (8) ──────────────────────────────
  { id: "behaviour:hospital:consultant-leading-ward-round", kind: "behaviour", description: "Consultant leading ward round — team following at respectful distance, notes reviewed before each room, the organised progression of senior clinical oversight", emotionalSignal: "ordered clinical authority", compatibleHeroes: ["authority", "environment"], industryIds: ["hospital"], tags: ["ward-round", "consultant", "leading", "team"], priority: 1, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:hospital:team-briefing-outside-bay-before-entering", kind: "behaviour", description: "Medical team pausing outside bay to review patient's notes before entering — the private review that makes the bedside conversation informed", emotionalSignal: "informed preparation", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["briefing", "outside-bay", "review", "notes"], priority: 2, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:hospital:junior-doctor-presenting-patient-to-consultant", kind: "behaviour", description: "Junior doctor presenting patient to consultant on ward round — structured SBAR presentation, consultant listening then asking targeted questions", emotionalSignal: "teaching through service", compatibleHeroes: ["authority", "environment"], industryIds: ["hospital"], tags: ["junior-doctor", "presenting", "sbar", "consultant"], priority: 3, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:hospital:multidisciplinary-team-meeting-around-table", kind: "behaviour", description: "MDT meeting — doctors, nurses, allied health professionals around table reviewing complex patient together, the collective intelligence of coordinated care", emotionalSignal: "collective expertise", compatibleHeroes: ["authority", "environment"], industryIds: ["hospital"], tags: ["mdt", "meeting", "table", "coordinated"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:hospital:doctor-calling-colleague-for-urgent-advice", kind: "behaviour", description: "Doctor calling specialist colleague on phone for urgent clinical advice — describing the presentation, asking the expert question, the specialist network in action", emotionalSignal: "clinical network", compatibleHeroes: ["authority"], industryIds: ["hospital"], tags: ["calling-colleague", "urgent", "specialist-advice", "network"], priority: 5, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:hospital:team-debriefing-after-resuscitation", kind: "behaviour", description: "Team debriefing after resuscitation attempt — the brief honest review of what went well and what could be improved, the learning culture of good emergency medicine", emotionalSignal: "reflective learning", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["debrief", "resuscitation", "review", "learning"], priority: 6, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:hospital:handover-at-shift-change-verbal", kind: "behaviour", description: "Nurse handover at shift change — structured verbal transmission of each patient's status, flags, and pending tasks from outgoing to incoming team", emotionalSignal: "continuity of care", compatibleHeroes: ["authority", "environment"], industryIds: ["hospital"], tags: ["handover", "shift-change", "verbal", "continuity"], priority: 7, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "behaviour:hospital:doctor-escalating-concern-to-senior", kind: "behaviour", description: "Junior doctor escalating clinical concern to senior — the professional courage to say I am worried about this patient, the safety culture that saves lives", emotionalSignal: "professional courage", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["escalating", "concern", "junior-doctor", "courage"], priority: 8, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Patient navigating hospital (8) ───────────────────────────────────────
  { id: "behaviour:hospital:patient-walking-corridor-on-crutches", kind: "behaviour", description: "Patient navigating hospital corridor on crutches — concentrating on technique, non-weight-bearing, the independence of getting from bed to scan without a bed", emotionalSignal: "mobile independence", compatibleHeroes: ["person", "lifestyle"], industryIds: ["hospital"], tags: ["crutches", "corridor", "navigating", "independence"], priority: 1, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:hospital:patient-in-wheelchair-being-pushed-to-appointment", kind: "behaviour", description: "Patient in wheelchair being pushed to appointment — porter navigating busy corridor, patient holding folder, the logistics of getting between departments", emotionalSignal: "managed dependency", compatibleHeroes: ["person", "authority", "lifestyle"], industryIds: ["hospital"], tags: ["wheelchair", "porter", "corridor", "appointment"], priority: 2, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "behaviour:hospital:patient-checking-in-at-clinic-reception", kind: "behaviour", description: "Outpatient checking in at clinic reception — handing over letter or giving name, the administrative arrival that precedes clinical care", emotionalSignal: "the beginning of the appointment journey", compatibleHeroes: ["person", "lifestyle"], industryIds: ["hospital"], tags: ["checking-in", "clinic-reception", "outpatient", "arrival"], priority: 3, weight: 0.77, confidence: "high", commercialScore: 76, futureMetadata: fm },
  { id: "behaviour:hospital:patient-walking-with-zimmer-frame-in-corridor", kind: "behaviour", description: "Elderly patient walking with Zimmer frame in ward corridor — each step concentrated, physio nearby, the slow triumphant progress of rehabilitation", emotionalSignal: "triumphant slow progress", compatibleHeroes: ["person", "moment"], industryIds: ["hospital"], tags: ["zimmer-frame", "elderly", "corridor", "triumph"], priority: 4, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:hospital:patient-going-outside-hospital-for-fresh-air", kind: "behaviour", description: "Inpatient patient going outside for fresh air — dressing gown, IV pole alongside, sitting in healing garden, the short outdoor respite", emotionalSignal: "reclaimed normality", compatibleHeroes: ["person", "lifestyle", "environment"], industryIds: ["hospital"], tags: ["outside", "fresh-air", "garden", "respite"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:hospital:patient-holding-discharge-letter-at-exit", kind: "behaviour", description: "Patient holding their discharge letter at hospital exit — document of survival, the paperwork that proves the journey is over", emotionalSignal: "documentary relief", compatibleHeroes: ["person", "moment"], industryIds: ["hospital"], tags: ["discharge-letter", "exit", "survival", "proof"], priority: 6, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:hospital:patient-being-helped-to-ambulance-on-discharge", kind: "behaviour", description: "Patient being assisted into waiting car by nurse at discharge — handover at car door, car finally pulling away, the physical end of the inpatient stay", emotionalSignal: "departure and freedom", compatibleHeroes: ["person", "authority", "moment"], industryIds: ["hospital"], tags: ["ambulance", "discharge", "car", "departure"], priority: 7, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "behaviour:hospital:patient-stopping-to-thank-nurse-in-corridor", kind: "behaviour", description: "Discharged patient stopping in corridor to thank a nurse by name — the specific gratitude for the specific care, the named acknowledgment of what was done", emotionalSignal: "personal gratitude", compatibleHeroes: ["person", "authority"], industryIds: ["hospital"], tags: ["thanking", "nurse", "corridor", "gratitude"], priority: 8, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Patient holding discharge documents (7) ───────────────────────────────
  { id: "behaviour:hospital:patient-reading-discharge-summary", kind: "behaviour", description: "Patient reading discharge summary document carefully — reading each medication listed, noting follow-up date, the informed exit from hospital care", emotionalSignal: "informed transition", compatibleHeroes: ["person", "lifestyle"], industryIds: ["hospital"], tags: ["discharge-summary", "reading", "medications", "follow-up"], priority: 1, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:hospital:patient-signing-consent-form", kind: "behaviour", description: "Patient reading and signing consent form for procedure — taking their time, asking a last question, the informed consent that authorises care", emotionalSignal: "informed autonomy", compatibleHeroes: ["person", "authority"], industryIds: ["hospital"], tags: ["consent-form", "signing", "procedure", "informed"], priority: 2, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "behaviour:hospital:patient-packing-belongings-for-discharge", kind: "behaviour", description: "Patient packing their belongings into bag on discharge day — placing familiar items from locker, the reverse unpacking of arrival, going home", emotionalSignal: "departure anticipation", compatibleHeroes: ["person", "moment"], industryIds: ["hospital"], tags: ["packing", "belongings", "discharge", "going-home"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "behaviour:hospital:patient-changing-out-of-hospital-gown", kind: "behaviour", description: "Patient changing from hospital gown into their own clothes — a private milestone, the return of their own identity in fabric", emotionalSignal: "identity restored", compatibleHeroes: ["person", "moment"], industryIds: ["hospital"], tags: ["own-clothes", "gown", "changing", "identity"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "behaviour:hospital:patient-receiving-medications-at-discharge", kind: "behaviour", description: "Patient receiving medications to take home at discharge — pharmacist explaining each one, confirming understanding, the bridge between hospital and community care", emotionalSignal: "continuity ensured", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["medications", "discharge", "pharmacist", "explaining"], priority: 5, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:hospital:patient-booking-follow-up-appointment", kind: "behaviour", description: "Patient booking follow-up appointment before leaving clinic — receptionist and patient selecting date, the next step already secured", emotionalSignal: "continuity secured", compatibleHeroes: ["person", "lifestyle"], industryIds: ["hospital"], tags: ["follow-up", "booking", "receptionist", "next-step"], priority: 6, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },
  { id: "behaviour:hospital:patient-asking-about-returning-to-work", kind: "behaviour", description: "Patient asking doctor about when they can return to work — the practical life question that follows the clinical one, medicine meeting real-life consequences", emotionalSignal: "life continuity concern", compatibleHeroes: ["person", "authority"], industryIds: ["hospital"], tags: ["return-to-work", "practical", "life", "timing"], priority: 7, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },

  // ── Clinical procedures (10) ──────────────────────────────────────────────
  { id: "behaviour:hospital:phlebotomist-drawing-blood-from-arm", kind: "behaviour", description: "Phlebotomist drawing blood sample — tourniquet applied, vein found, needle inserted with confidence, the routine that fuels the diagnostic engine", emotionalSignal: "routine clinical skill", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["phlebotomy", "blood-draw", "tourniquet", "venepuncture"], priority: 1, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "behaviour:hospital:doctor-inserting-cannula-back-of-hand", kind: "behaviour", description: "Doctor inserting IV cannula in back of hand — patient looking away, doctor confident, cannula flushed and taped, the access established for future medications", emotionalSignal: "access established", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["cannula", "iv-access", "inserting", "hand"], priority: 2, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-administering-subcutaneous-injection", kind: "behaviour", description: "Nurse administering subcutaneous injection — skin pinched, insulin or anticoagulant injected at 45-degree angle, the small procedure repeated daily for care", emotionalSignal: "skilled routine care", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["injection", "subcutaneous", "nurse", "insulin"], priority: 3, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },
  { id: "behaviour:hospital:doctor-performing-lumbar-puncture", kind: "behaviour", description: "Doctor performing lumbar puncture — patient curled in foetal position, space identified, sterile technique, the procedure that gives the cerebrospinal fluid its answer", emotionalSignal: "high-stakes technical precision", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["lumbar-puncture", "csf", "sterile", "foetal-position"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-removing-urinary-catheter", kind: "behaviour", description: "Nurse removing urinary catheter — patient informed, removal done gently, the milestone of catheter-free recovery marking progress", emotionalSignal: "recovery milestone", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["catheter-removal", "milestone", "nurse", "recovery"], priority: 5, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },
  { id: "behaviour:hospital:doctor-examining-abdomen-with-stethoscope", kind: "behaviour", description: "Doctor examining abdomen — stethoscope for bowel sounds, palpation with warmed hands, the physical examination as clinical artistry", emotionalSignal: "expert physical assessment", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["abdomen", "stethoscope", "palpation", "examination"], priority: 6, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-removing-surgical-drain", kind: "behaviour", description: "Nurse removing surgical drain — patient warned and breathing out on cue, drain removed steadily, site cleaned and dressed, the managed clinical transition", emotionalSignal: "managed clinical milestone", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["drain-removal", "nurse", "surgical", "milestone"], priority: 7, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "behaviour:hospital:doctor-percussing-chest-listening-carefully", kind: "behaviour", description: "Doctor percussing patient's chest and listening carefully — fingers positioned, tapping at intervals, the physical diagnostic examination of the lungs", emotionalSignal: "physical diagnostic art", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["percussion", "chest", "stethoscope", "lungs"], priority: 8, weight: 0.77, confidence: "high", commercialScore: 76, futureMetadata: fm },
  { id: "behaviour:hospital:radiographer-positioning-patient-for-xray", kind: "behaviour", description: "Radiographer positioning patient for chest X-ray — plate behind back, patient arms forward, breath held on instruction, the positioning precision of diagnostic imaging", emotionalSignal: "technical positioning", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["radiographer", "positioning", "x-ray", "chest"], priority: 6, weight: 0.78, confidence: "high", commercialScore: 77, futureMetadata: fm },
  { id: "behaviour:hospital:ecg-technician-placing-electrodes", kind: "behaviour", description: "ECG technician placing twelve electrodes — named positions on limbs and chest, gel applied, the preparation of the full twelve-lead recording", emotionalSignal: "systematic technical preparation", compatibleHeroes: ["authority", "person", "product"], industryIds: ["hospital"], tags: ["ecg", "electrodes", "twelve-lead", "gel"], priority: 5, weight: 0.77, confidence: "high", commercialScore: 76, futureMetadata: fm },

  // ── Emergency response behaviours (5) ────────────────────────────────────
  { id: "behaviour:hospital:cpr-compression-on-patient-in-corridor", kind: "behaviour", description: "Nurse performing CPR on patient who has collapsed in corridor — compressions ongoing, colleague running with crash trolley, bystanders moving aside", emotionalSignal: "urgent skilled response", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["cpr", "compressions", "collapsed", "response"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:hospital:paramedic-managing-airway-on-scene", kind: "behaviour", description: "Paramedic managing patient airway on scene — jaw thrust, bag-valve-mask in use, partner doing compressions, the two-person pre-hospital resuscitation", emotionalSignal: "pre-hospital mastery", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["airway", "paramedic", "bag-valve", "pre-hospital"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:hospital:trauma-team-leader-directing-response", kind: "behaviour", description: "Trauma team leader standing at patient's feet directing the response — not doing any one task, coordinating all, the conducting of organised emergency care", emotionalSignal: "calm authority in chaos", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["trauma-leader", "directing", "coordinating", "calm"], priority: 3, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:hospital:nurse-starting-oxygen-emergency", kind: "behaviour", description: "Nurse applying oxygen mask to distressed patient — selecting non-rebreathe at 15 litres, securing straps, checking seal, the emergency oxygen response", emotionalSignal: "acute intervention", compatibleHeroes: ["authority", "person"], industryIds: ["hospital"], tags: ["oxygen-mask", "emergency", "non-rebreathe", "acute"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:hospital:doctor-calling-anaesthetics-for-airway-support", kind: "behaviour", description: "Doctor calling anaesthetics team urgently for airway support — identifying patient, explaining urgency, the rapid specialist escalation that protects the compromised airway", emotionalSignal: "urgent escalation", compatibleHeroes: ["authority", "moment"], industryIds: ["hospital"], tags: ["anaesthetics", "airway", "escalation", "urgent"], priority: 5, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
];
