import type { CommercialSituationKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const HOSPITAL_COMMERCIAL_SITUATIONS: CommercialSituationKnowledgeNode[] = [
  // ── Private hospital procedure booking (7) ────────────────────────────────
  { id: "commercial_situation:hospital:booking-private-elective-surgery", kind: "commercial_situation", situation: "Patient deciding to book private elective surgery after waiting on NHS list — the decision to pay for speed and choice", conversionMoment: "Procedure date confirmed, deposit paid — the decision made and committed", visualRepresentation: "Person on phone or laptop booking private surgery, selecting date from calendar, card details entered, confirmation received", industryIds: ["hospital"], tags: ["private-surgery", "elective", "booking", "nhs-wait"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "commercial_situation:hospital:private-hospital-website-procedure-search", kind: "commercial_situation", situation: "Prospective patient searching private hospital website for procedure they need — comparing prices, reading consultant profiles, looking at the pathway", conversionMoment: "Enquiry form submitted or phone number called — the decision to engage after the research", visualRepresentation: "Hospital website on screen, procedure section open, consultant profile viewed, enquiry form being completed", industryIds: ["hospital"], tags: ["website", "procedure-search", "consultant-profile", "enquiry"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "commercial_situation:hospital:executive-health-screening-corporate", kind: "commercial_situation", situation: "Company purchasing executive health screening packages for senior leadership team — the corporate health investment", conversionMoment: "Corporate agreement signed, all appointments scheduled — the bulk health investment committed", visualRepresentation: "HR manager on call with private hospital coordinator, multiple names on booking list, corporate PO number being taken", industryIds: ["hospital"], tags: ["executive-health", "corporate", "screening", "bulk-booking"], priority: 3, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "commercial_situation:hospital:individual-health-screening-self-pay", kind: "commercial_situation", situation: "Individual booking comprehensive health screening for peace of mind — self-pay, motivated by family history or lifestyle concern", conversionMoment: "Screening package selected and payment taken — the investment in knowing", visualRepresentation: "Individual on hospital website selecting screening package, adding blood markers, confirming payment, appointment confirmation sent", industryIds: ["hospital"], tags: ["individual", "self-pay", "peace-of-mind", "screening-package"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:hospital:private-gp-appointment-booked-fast-access", kind: "commercial_situation", situation: "Person booking private GP appointment for same-week access — unwilling to wait NHS appointment time for a symptom that concerns them", conversionMoment: "Same-week appointment booked and paid — the premium of not waiting purchased", visualRepresentation: "Online booking portal showing same-week slots, 'Private GP' selected, fast slot chosen, payment completed", industryIds: ["hospital"], tags: ["private-gp", "same-week", "fast-access", "concern"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:hospital:cosmetic-procedure-consultation-booked", kind: "commercial_situation", situation: "Patient booking cosmetic procedure consultation at private hospital — initial no-obligation consultation leading to procedure discussion", conversionMoment: "Consultation appointment booked — the first step in a commercial pathway with high conversion value", visualRepresentation: "Cosmetic procedures page on screen, 'Book Free Consultation' clicked, specific procedure selected, date chosen", industryIds: ["hospital"], tags: ["cosmetic", "consultation", "no-obligation", "pathway"], priority: 6, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:hospital:diagnostic-test-self-pay", kind: "commercial_situation", situation: "Patient paying privately for diagnostic test not available quickly on NHS — MRI, blood panel, or scan purchased directly", conversionMoment: "Test booked and paid, appointment within days — the diagnostic access purchased", visualRepresentation: "Diagnostic test selected from menu, price shown with fast-access slot, payment completed, same-week appointment confirmed", industryIds: ["hospital"], tags: ["diagnostic-test", "self-pay", "fast-access", "mri"], priority: 7, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Specialist referral conversion (5) ────────────────────────────────────
  { id: "commercial_situation:hospital:gp-letter-to-private-specialist", kind: "commercial_situation", situation: "GP writing referral letter directly to private specialist at patient's request — the self-directed pathway to faster specialist access", conversionMoment: "Referral letter sent and specialist appointment confirmed — the private referral pathway engaged", visualRepresentation: "GP dictating letter naming specific private consultant, patient confirming they want private referral, appointment coordinated", industryIds: ["hospital"], tags: ["gp-referral", "private-specialist", "patient-request", "fast-pathway"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "commercial_situation:hospital:patient-self-referring-to-private-consultant", kind: "commercial_situation", situation: "Patient self-referring directly to private consultant without GP referral — knowing what they need, choosing who they want", conversionMoment: "Consultation appointment booked directly — bypassing GP, the direct specialist access model", visualRepresentation: "Consultant's profile on hospital website, 'Book Directly' option taken, self-referral form completed, appointment confirmed", industryIds: ["hospital"], tags: ["self-referral", "direct", "consultant", "bypassing-gp"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:hospital:second-opinion-referral-paid", kind: "commercial_situation", situation: "Patient paying for second opinion consultation — bringing NHS notes and scans to private specialist for independent view", conversionMoment: "Second opinion appointment booked and paid — the reassurance or confirmation purchased", visualRepresentation: "Patient with NHS folder of notes at private hospital, booking second opinion, scans being uploaded to portal", industryIds: ["hospital"], tags: ["second-opinion", "paid", "nhs-notes", "independent"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:hospital:corporate-occupational-health-contract", kind: "commercial_situation", situation: "Company contracting private hospital for occupational health services — annual contract, employee health support, return-to-work assessments", conversionMoment: "Occupational health contract signed — recurring commercial relationship established", visualRepresentation: "Corporate meeting with hospital business development team, contract document being reviewed, signatures being exchanged", industryIds: ["hospital"], tags: ["occupational-health", "corporate-contract", "annual", "return-to-work"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:hospital:insurer-network-patient-using-benefit", kind: "commercial_situation", situation: "Patient with private health insurance using their policy to access private hospital — calling insurer, getting authorisation, booking within the network", conversionMoment: "Insurance authorisation received and appointment booked — the policy benefit accessed", visualRepresentation: "Patient calling insurer for authorisation, noting reference number, booking with private hospital, insurance details confirmed", industryIds: ["hospital"], tags: ["private-insurance", "authorisation", "network", "policy-benefit"], priority: 5, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },

  // ── Online appointment booking (5) ────────────────────────────────────────
  { id: "commercial_situation:hospital:online-booking-outpatient-appointment", kind: "commercial_situation", situation: "Patient booking outpatient consultant appointment online — browsing consultant profiles, checking availability, completing the booking flow", conversionMoment: "Appointment confirmed online with pre-payment — digital booking completed without phone call", visualRepresentation: "Hospital booking portal on phone, consultant profiles visible, speciality filter applied, date selected, payment completed", industryIds: ["hospital"], tags: ["online-booking", "outpatient", "consultant-profile", "digital"], priority: 1, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:hospital:app-based-appointment-reminder-rebooking", kind: "commercial_situation", situation: "Patient receiving appointment reminder via hospital app and confirming or rescheduling digitally — the digital engagement that reduces no-shows", conversionMoment: "Appointment confirmed via app — digital engagement reducing cancellation risk", visualRepresentation: "Hospital app notification, patient confirming attendance, option to reschedule visible, confirmation sent", industryIds: ["hospital"], tags: ["app", "reminder", "confirmation", "digital-engagement"], priority: 2, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "commercial_situation:hospital:video-consultation-booked-for-follow-up", kind: "commercial_situation", situation: "Patient booking video consultation for follow-up rather than attending in person — the hybrid care model accessed for convenience", conversionMoment: "Video consultation booked and confirmed — the remote engagement maintaining the relationship", visualRepresentation: "Hospital portal showing video consultation option, booking selected, confirmation with video link sent, patient diary entry made", industryIds: ["hospital"], tags: ["video-consultation", "follow-up", "remote", "hybrid"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:hospital:chatbot-initial-enquiry-to-booking", kind: "commercial_situation", situation: "Hospital website chatbot fielding initial enquiry and routing to booking — the digital first contact converting to appointment", conversionMoment: "Chatbot conversation ending in appointment booking or callback request — digital to human conversion", visualRepresentation: "Chat window on hospital website, symptom described, chatbot recommending relevant consultant, booking link provided", industryIds: ["hospital"], tags: ["chatbot", "enquiry", "routing", "digital-conversion"], priority: 4, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "commercial_situation:hospital:gp-referral-portal-submission", kind: "commercial_situation", situation: "GP practice submitting electronic referral to private hospital via portal — digital referral pathway replacing paper and fax", conversionMoment: "Referral received and appointment offered — the digital referral pathway creating speed and efficiency", visualRepresentation: "GP portal screen, patient details entered, consultant selected, referral submitted, acknowledgement received immediately", industryIds: ["hospital"], tags: ["gp-portal", "electronic-referral", "digital", "fast-pathway"], priority: 5, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── Private health insurance (5) ──────────────────────────────────────────
  { id: "commercial_situation:hospital:new-policy-holder-first-claim", kind: "commercial_situation", situation: "New private health insurance policy holder making first claim — the policy bought for peace of mind now being used for the first time", conversionMoment: "Claim authorised and hospital appointment booked under policy — the policy proving its value", visualRepresentation: "New policy holder calling insurer, first claim process explained, authorisation received, appointment at private hospital confirmed", industryIds: ["hospital"], tags: ["first-claim", "new-policy", "authorisation", "proving-value"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:hospital:corporate-health-insurance-employee", kind: "commercial_situation", situation: "Employee using corporate health insurance benefit for the first time — the employer benefit becoming real in a moment of medical need", conversionMoment: "Employee appointment booked through corporate policy — the workplace benefit delivering its value", visualRepresentation: "Employee on HR portal finding health insurance details, calling insurer with employer policy number, specialist booked", industryIds: ["hospital"], tags: ["corporate-insurance", "employee-benefit", "first-use", "workplace"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:hospital:upgrading-insurance-policy-after-diagnosis", kind: "commercial_situation", situation: "Person upgrading their health insurance policy following a health scare — the near-miss motivating the better coverage", conversionMoment: "Upgraded policy purchased — the health event converting to premium insurance spend", visualRepresentation: "Insurer website showing policy comparison, comprehensive cover selected, higher premium acknowledged, policy upgraded", industryIds: ["hospital"], tags: ["upgrade", "health-scare", "better-coverage", "motivated"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:hospital:family-health-insurance-policy-purchased", kind: "commercial_situation", situation: "Family purchasing health insurance policy after parent has health scare — the generational conversation about protection converting to a premium", conversionMoment: "Family policy purchased — the multi-person cover commitment made", visualRepresentation: "Family at kitchen table reviewing policy options, children listed on policy, direct debit set up, welcome pack ordered", industryIds: ["hospital"], tags: ["family-policy", "parent-scare", "generational", "multi-person"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:hospital:health-cash-plan-claim-for-specialist", kind: "commercial_situation", situation: "Patient claiming health cash plan benefit for specialist consultation costs — the cash plan product delivering partial reimbursement", conversionMoment: "Claim submitted and processed — the cash plan benefit reducing net cost to patient", visualRepresentation: "Patient completing online claim form, uploading receipt from private consultation, payment processing confirmation", industryIds: ["hospital"], tags: ["cash-plan", "claim", "specialist", "reimbursement"], priority: 5, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },

  // ── Hospital charity giving (3) ──────────────────────────────────────────
  { id: "commercial_situation:hospital:grateful-patient-donating-to-charity", kind: "commercial_situation", situation: "Patient making charitable donation to hospital following exceptional care — the gratitude converting to philanthropic commitment", conversionMoment: "Donation made and charity relationship established — the grateful patient becoming a donor", visualRepresentation: "Patient on charity donation page, specifying ward or department to support, donation amount selected, regular giving option considered", industryIds: ["hospital"], tags: ["donation", "grateful-patient", "charity", "philanthropic"], priority: 1, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:hospital:family-fundraising-for-hospital-appeal", kind: "commercial_situation", situation: "Family of a patient recovered from serious illness fundraising for hospital department — the organised community event as gratitude", conversionMoment: "Fundraising event delivering major donation — the community mobilised around a hospital's specific appeal", visualRepresentation: "Community fundraising event banner, family collecting donations in hospital branded bucket, cheque being presented to hospital", industryIds: ["hospital"], tags: ["fundraising", "family", "community-event", "appeal"], priority: 2, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "commercial_situation:hospital:legacy-gift-to-hospital", kind: "commercial_situation", situation: "Patient leaving a legacy gift to hospital in their will — the long-term relationship converted into a philanthropic commitment beyond their lifetime", conversionMoment: "Legacy gift added to will — the hospital benefiting from an enduring relationship that outlasts the donor", visualRepresentation: "Older patient meeting hospital charitable foundation representative, legacy gift paperwork, will amendment confirmed", industryIds: ["hospital"], tags: ["legacy-gift", "will", "long-term", "enduring"], priority: 3, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },

  // ── Medical tourism (5) ───────────────────────────────────────────────────
  { id: "commercial_situation:hospital:international-patient-booking-procedure", kind: "commercial_situation", situation: "International patient booking complex procedure at UK private hospital — medical tourism driven by reputation, expertise, or waiting time", conversionMoment: "Procedure booked with international patient services team — the international booking confirmed", visualRepresentation: "International patient services page, enquiry from overseas submitted, coordinator response, pathway document exchanged, booking confirmed", industryIds: ["hospital"], tags: ["medical-tourism", "international-patient", "procedure", "reputation"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "commercial_situation:hospital:overseas-cancer-patient-second-opinion", kind: "commercial_situation", situation: "Overseas cancer patient seeking second opinion from UK specialist — the hospital's oncology reputation attracting international cases", conversionMoment: "Second opinion consultation booked internationally — the reputation-driven conversion", visualRepresentation: "Patient from overseas uploading scan files to hospital portal, international patient coordinator engaged, video pre-consultation arranged", industryIds: ["hospital"], tags: ["overseas-patient", "cancer", "second-opinion", "reputation"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:hospital:medical-tourism-package-booked", kind: "commercial_situation", situation: "Patient booking packaged medical tourism — procedure plus accommodation, transport, aftercare, the complete international healthcare experience", conversionMoment: "Complete medical tourism package confirmed and paid — the comprehensive pathway booked", visualRepresentation: "Medical tourism package on screen, procedure and hotel room both shown, total cost displayed, payment completed", industryIds: ["hospital"], tags: ["package", "accommodation", "aftercare", "complete"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:hospital:arabic-speaking-patient-services-engaged", kind: "commercial_situation", situation: "Arabic-speaking family engaging hospital's dedicated international patient services — language support, cultural considerations, family accommodation needs", conversionMoment: "International patient services engaged and pathway confirmed — the specialist service delivering the conversion", visualRepresentation: "International patient services brochure in Arabic, coordinator conversation, family visiting schedule confirmed, accommodation arranged", industryIds: ["hospital"], tags: ["arabic", "international-patient-services", "cultural", "family-accommodation"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "commercial_situation:hospital:referral-from-overseas-hospital", kind: "commercial_situation", situation: "Referral from an overseas hospital for complex case requiring UK specialist expertise — hospital-to-hospital commercial pathway", conversionMoment: "International clinical referral accepted and pathway confirmed — the B2B medical referral converting", visualRepresentation: "Clinical referral documentation arriving, international team reviewing, accepting referral, patient journey coordinated between hospitals", industryIds: ["hospital"], tags: ["overseas-referral", "hospital-to-hospital", "complex-case", "expertise"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Premium private room selection (4) ───────────────────────────────────
  { id: "commercial_situation:hospital:upgrading-to-private-room-for-stay", kind: "commercial_situation", situation: "Inpatient paying to upgrade to private room from standard admission — choosing privacy, en suite, and quiet for recovery", conversionMoment: "Upgrade paid for and private room assigned — the premium environment secured", visualRepresentation: "Room upgrade option shown at admission, prices displayed, credit card presented, key to private room issued", industryIds: ["hospital"], tags: ["room-upgrade", "private", "en-suite", "premium"], priority: 1, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:hospital:premium-suite-booked-for-complex-surgery", kind: "commercial_situation", situation: "Family booking premium suite for patient undergoing complex surgery — wanting the best environment for a long and difficult recovery", conversionMoment: "Premium suite confirmed and deposit paid — the top-tier experience purchased for the highest-need moment", visualRepresentation: "Premium suite shown on hospital website, luxury features listed, partner accommodation included, full payment confirmed", industryIds: ["hospital"], tags: ["premium-suite", "complex-surgery", "luxury", "long-recovery"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:hospital:maternity-suite-selected-premium-birth", kind: "commercial_situation", situation: "Couple selecting premium maternity suite for the birth — private midwife, luxury room, spa-standard amenities, the premium birth experience", conversionMoment: "Maternity suite booked and birth plan confirmed — the premium birth environment secured", visualRepresentation: "Maternity suite virtual tour on website, options compared, birth plan form, birthing suite confirmed, package payment received", industryIds: ["hospital"], tags: ["maternity-suite", "premium-birth", "private-midwife", "luxury"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:hospital:corporate-vip-treatment-room-booked", kind: "commercial_situation", situation: "Corporate VIP healthcare package — top-floor suite, dedicated consultant, personal health coordinator, the top-of-market private hospital experience", conversionMoment: "VIP package confirmed and annual fee paid — the premium retention secured", visualRepresentation: "VIP healthcare brochure, personal coordinator introduced, suite shown, annual membership fee charged, welcome meeting arranged", industryIds: ["hospital"], tags: ["vip", "top-floor", "personal-coordinator", "annual-membership"], priority: 4, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Post-operative care plan (4) ──────────────────────────────────────────
  { id: "commercial_situation:hospital:post-op-care-plan-sold-at-discharge", kind: "commercial_situation", situation: "Post-operative care package sold at discharge — at-home nursing visits, physio follow-up, wound checks, the extended care pathway purchased", conversionMoment: "Care package payment taken at discharge — the ongoing relationship secured at the point of leaving", visualRepresentation: "Discharge nurse presenting care package options, services listed with schedule, payment taken, first visit date confirmed", industryIds: ["hospital"], tags: ["post-op-care", "home-nursing", "discharge", "extended"], priority: 1, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "commercial_situation:hospital:remote-monitoring-post-discharge", kind: "commercial_situation", situation: "Patient signing up for remote monitoring subscription post-discharge — wearable device data reviewed by clinical team, the digital post-op care model", conversionMoment: "Remote monitoring package purchased and device issued — the digital care pathway activated", visualRepresentation: "Wearable device shown, monitoring app on phone, subscription cost, first data upload within 24 hours, clinical review scheduled", industryIds: ["hospital"], tags: ["remote-monitoring", "wearable", "subscription", "digital-care"], priority: 2, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "commercial_situation:hospital:physio-follow-up-course-booked-post-surgery", kind: "commercial_situation", situation: "Physiotherapy course booked following joint replacement surgery — eight sessions, clinic-based, the evidence-based rehabilitation pathway", conversionMoment: "Full physio course booked and first session scheduled — the complete rehabilitation pathway committed to", visualRepresentation: "Physio team presenting course schedule post-surgery, eight sessions outlined, full payment or payment plan selected, first session booked", industryIds: ["hospital"], tags: ["physio-course", "joint-replacement", "eight-sessions", "rehabilitation"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:hospital:nutrition-plan-post-bariatric-surgery", kind: "commercial_situation", situation: "Bariatric surgery patient purchasing nutritional support programme post-operatively — dietitian access, supplement supply, long-term support", conversionMoment: "Nutritional support programme purchased — the long-term follow-up care secured", visualRepresentation: "Bariatric team presenting nutrition plan, twelve-month support outlined, supplement starter pack shown, programme payment taken", industryIds: ["hospital"], tags: ["bariatric", "nutrition", "twelve-month", "supplements"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── GP referral to private specialist (4) ─────────────────────────────────
  { id: "commercial_situation:hospital:patient-asking-gp-for-private-referral", kind: "commercial_situation", situation: "Patient explicitly asking GP for private referral rather than NHS pathway — the informed patient choosing the private route with GP support", conversionMoment: "GP issues private referral letter — the GP acting as the gateway to private specialist access", visualRepresentation: "Patient in GP surgery requesting private referral, GP writing letter to named specialist, referral given to patient to present", industryIds: ["hospital"], tags: ["gp", "private-referral", "patient-request", "gateway"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:hospital:gp-recommending-private-specialist-pathway", kind: "commercial_situation", situation: "GP recommending the private specialist pathway to patient due to wait times for their condition — the clinical recommendation that directs private spend", conversionMoment: "Patient accepts GP's recommendation and books private — the clinical endorsement converting", visualRepresentation: "GP explaining wait times for NHS pathway, recommending private as better for this condition, providing consultant name, patient acting on it", industryIds: ["hospital"], tags: ["gp-recommendation", "wait-times", "private-pathway", "clinical-endorsement"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:hospital:private-gp-concierge-service", kind: "commercial_situation", situation: "Patient subscribing to private concierge GP service — same-day access, home visits, direct consultant access, the premium primary care relationship", conversionMoment: "Annual concierge GP membership purchased — the premium primary care committed to", visualRepresentation: "Concierge GP brochure, membership benefits listed, annual fee displayed, direct access promised, application form submitted", industryIds: ["hospital"], tags: ["concierge-gp", "same-day-access", "home-visits", "membership"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "commercial_situation:hospital:specialist-recommending-private-facility", kind: "commercial_situation", situation: "NHS specialist recommending their private practice to patient for faster access — the dual-practising consultant directing commercial referral", conversionMoment: "Patient books at private facility with the same specialist — the private parallel pathway engaged", visualRepresentation: "Specialist giving patient private clinic card, explaining same-week availability privately, patient booking at private clinic", industryIds: ["hospital"], tags: ["dual-practising", "specialist-recommendation", "private-clinic", "same-week"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Health screening package purchase (4) ────────────────────────────────
  { id: "commercial_situation:hospital:birthday-health-screening-gift", kind: "commercial_situation", situation: "Comprehensive health screening purchased as significant birthday gift — partner or family buying the full MOT for a 50th or 60th birthday", conversionMoment: "Screening package purchased as gift and appointment set — the significant occasion creating the health investment", visualRepresentation: "Gift voucher for health screening on screen, comprehensive package selected, birthday occasion noted, gift certificate emailed", industryIds: ["hospital"], tags: ["birthday-gift", "health-screening", "significant-birthday", "voucher"], priority: 1, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "commercial_situation:hospital:family-history-driven-screening-purchase", kind: "commercial_situation", situation: "Person purchasing targeted screening package because of family history — cancer, cardiac, or genetic screening motivated by personal risk awareness", conversionMoment: "Screening package selected and booked — the family history converting to screening investment", visualRepresentation: "Screening packages page showing disease-specific options, family history checkbox on selection form, targeted tests chosen, booked", industryIds: ["hospital"], tags: ["family-history", "targeted-screening", "cancer", "cardiac"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "commercial_situation:hospital:corporate-wellbeing-screening-event", kind: "commercial_situation", situation: "Corporate wellness day with on-site health screening — blood pressure, cholesterol, blood sugar checks provided for entire workforce at office", conversionMoment: "Corporate wellness event booked and paid — the B2B screening event committed to", visualRepresentation: "Corporate wellness day proposal, on-site equipment list, per-head pricing, event date confirmed, consent forms prepared", industryIds: ["hospital"], tags: ["corporate-wellness", "on-site", "workforce", "event"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "commercial_situation:hospital:new-year-resolution-health-check", kind: "commercial_situation", situation: "New Year health resolution converting to comprehensive private health check booking — the seasonal motivation to know one's numbers", conversionMoment: "Health check booked in January — the resolution becoming a committed appointment", visualRepresentation: "January health check promotional page, comprehensive package on offer, new patient discount applied, appointment selected for February", industryIds: ["hospital"], tags: ["new-year", "resolution", "comprehensive", "seasonal"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
];
