import type { EmotionalMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const HOSPITAL_EMOTIONAL_MOMENTS: EmotionalMomentKnowledgeNode[] = [
  // ── All-clear scan result (5) ─────────────────────────────────────────────
  { id: "emotional_moment:hospital:all-clear-delivered-exhale", kind: "emotional_moment", moment: "Doctor saying 'everything is clear' after scan result — the patient's exhale, the months of fear leaving in one breath", emotionType: "relief at threat removed", visualSignals: ["deep visible exhale", "eyes closing momentarily", "hand going to face or chest", "body releasing held tension"], industryIds: ["hospital"], tags: ["all-clear", "exhale", "relief", "threat-removed"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "emotional_moment:hospital:cancer-screening-all-clear", kind: "emotional_moment", moment: "Cancer screening result all clear — patient sitting in quiet room as the news arrives, the specific relief of a worry that has been carried silently", emotionType: "quiet profound relief", visualSignals: ["stillness before reaction", "then slow smile", "tears gathering", "calling someone immediately"], industryIds: ["hospital"], tags: ["cancer-screening", "quiet-relief", "carried-worry", "calling-someone"], priority: 2, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:hospital:heart-scan-no-abnormality-found", kind: "emotional_moment", moment: "Cardiologist confirming no cardiac abnormality found — the patient who has worried about their heart for months hearing 'your heart is fine'", emotionType: "liberation from chronic fear", visualSignals: ["relief spreading physically from shoulders", "involuntary laugh of release", "leaning back", "face unclenching"], industryIds: ["hospital"], tags: ["cardiac", "no-abnormality", "liberation", "chronic-fear"], priority: 3, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:hospital:biopsy-result-benign", kind: "emotional_moment", moment: "Biopsy result confirmed benign — patient who has waited two weeks for the result, the days of imagining worst-case scenarios ending in a single word", emotionType: "aftermath of imagined catastrophe", visualSignals: ["processing before reaction", "then visible collapse of tension", "eyes glistening", "turning to share with companion"], industryIds: ["hospital"], tags: ["biopsy", "benign", "two-week-wait", "imagined-catastrophe"], priority: 4, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:hospital:neurological-scan-normal-reassurance", kind: "emotional_moment", moment: "Neurologist confirming brain scan normal — patient who feared the worst possible diagnosis receiving 'I am reassured by what I see here'", emotionType: "feared diagnosis averted", visualSignals: ["question 'are you sure?' instinct", "then accepting the reassurance", "physical settling", "gratitude visible"], industryIds: ["hospital"], tags: ["neurological", "normal-scan", "feared-diagnosis", "reassured"], priority: 5, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },

  // ── Surgeon delivering good news (8) ──────────────────────────────────────
  { id: "emotional_moment:hospital:surgeon-tells-family-operation-success", kind: "emotional_moment", moment: "Surgeon in scrubs finding the waiting family to say the operation was successful — the family's reaction when the impossible anxiety resolves in one sentence", emotionType: "collective relief breaking simultaneously", visualSignals: ["family members' simultaneous reaction", "tears in multiple faces", "embraces forming spontaneously", "surgeon's quiet satisfaction"], industryIds: ["hospital"], tags: ["surgeon", "family", "successful", "collective-relief"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "emotional_moment:hospital:patient-waking-and-told-its-over", kind: "emotional_moment", moment: "Patient coming round from surgery and nurse saying 'it all went really well' — the disorientation of waking, then the news landing, the surgery is done", emotionType: "disoriented relief", visualSignals: ["blinking confusion", "words registering slowly", "then face softening", "involuntary tear or smile"], industryIds: ["hospital"], tags: ["post-op-waking", "it-went-well", "disoriented", "landing"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:hospital:cancer-surgery-clear-margins-news", kind: "emotional_moment", moment: "Oncologist reporting clear surgical margins from cancer operation — the technical phrase 'clear margins' meaning the cancer has been fully removed", emotionType: "technical news with enormous emotional weight", visualSignals: ["patient asking 'what does that mean'", "then explanation arriving", "then the emotional weight registering", "partner reaching for hand"], industryIds: ["hospital"], tags: ["clear-margins", "oncology", "technical-news", "enormous-weight"], priority: 3, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:hospital:cardiac-repair-successful-told", kind: "emotional_moment", moment: "Cardiac patient told their heart repair was successful — the person who came in with a failing heart being told the repair is done and working", emotionType: "restored faith in continuation", visualSignals: ["hand going to chest instinctively", "eyes closing", "the deeply private relief of cardiac life restored", "quiet tears"], industryIds: ["hospital"], tags: ["cardiac", "successful-repair", "heart", "continuation"], priority: 4, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:hospital:premature-baby-update-doing-well", kind: "emotional_moment", moment: "NICU doctor telling parents their premature baby is doing much better than expected — the update that changes the room's atmosphere immediately", emotionType: "unexpected positive exceeding fear", visualSignals: ["parents' faces lifting", "hands reaching for each other", "asking 'really?' in disbelief", "then the tears of positive news"], industryIds: ["hospital"], tags: ["premature-baby", "doing-well", "exceeding-fear", "parents"], priority: 5, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:hospital:stroke-patient-better-prognosis-revised", kind: "emotional_moment", moment: "Neurologist revising stroke prognosis upward — 'they are doing much better than we initially expected', the original fear replaced by a different future", emotionType: "revised future for the better", visualSignals: ["family leaning in to hear", "the revision landing", "the better future beginning to be possible", "permission to hope again"], industryIds: ["hospital"], tags: ["stroke", "revised-prognosis", "better-than-expected", "permission-to-hope"], priority: 6, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:hospital:spinal-surgeon-delivers-good-outcome", kind: "emotional_moment", moment: "Spinal surgeon reporting successful operation on patient feared to be at risk of paralysis — the worst fear not realised, the news that restores the future", emotionType: "averted catastrophe", visualSignals: ["family's visible collapse of worst-case thinking", "the relief physically overwhelming", "laughter and tears simultaneously"], industryIds: ["hospital"], tags: ["spinal", "paralysis-fear", "averted", "future-restored"], priority: 7, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:hospital:anaesthetic-reaction-patient-recovers", kind: "emotional_moment", moment: "Anaesthetic team informing family that the patient had an unexpected reaction but is now stable and recovering — the scare that ended safely", emotionType: "fear resolved into relief", visualSignals: ["the initial fear reaction at the news", "then 'but they are fine now'", "the double release of fright and then relief", "family needing a moment"], industryIds: ["hospital"], tags: ["anaesthetic-reaction", "stable-and-recovering", "double-release", "scare"], priority: 8, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },

  // ── Family reunion after ICU (6) ──────────────────────────────────────────
  { id: "emotional_moment:hospital:icu-patient-transferred-to-ward", kind: "emotional_moment", moment: "ICU patient transferred to regular ward — the bed moving out of ICU, the patient awake enough to know, the family knowing the worst is over", emotionType: "threshold crossed to recovery", visualSignals: ["bed moving through ICU doors", "patient watching the surroundings change", "family walking alongside", "faces lighter than days before"], industryIds: ["hospital"], tags: ["icu-transfer", "ward", "threshold", "lighter"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:hospital:patient-recognises-family-after-sedation", kind: "emotional_moment", moment: "Sedated ICU patient opening eyes and recognising family — the moment of recognition after days of unconsciousness, the family's faces the first thing understood", emotionType: "recognition after absence", visualSignals: ["eyes opening slowly", "scanning the room", "eyes stopping at a face", "recognition arriving — the word or gesture that proves they are back"], industryIds: ["hospital"], tags: ["recognition", "sedation-end", "family", "proving-back"], priority: 2, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "emotional_moment:hospital:first-proper-conversation-after-intubation", kind: "emotional_moment", moment: "Patient speaking their first coherent sentence after extubation — the family hearing the voice again, the voice being the proof of return", emotionType: "voice as proof of survival", visualSignals: ["patient's hoarse first words", "family leaning in", "the disbelief and joy of hearing them speak", "someone repeating what they said"], industryIds: ["hospital"], tags: ["extubation", "first-words", "voice", "proof-of-return"], priority: 3, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:hospital:child-seeing-parent-awake-in-ward", kind: "emotional_moment", moment: "Child entering ward and seeing their parent awake and alert — running forward, the reunion that the child has been kept from for days of ICU", emotionType: "child's reunification joy", visualSignals: ["child running", "parent's face changing at the sight of their child", "the embrace", "child's full-body relief"], industryIds: ["hospital"], tags: ["child", "parent-awake", "running", "reunification"], priority: 4, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:hospital:partner-sleeping-in-chair-woken-by-patient", kind: "emotional_moment", moment: "Partner who has fallen asleep in bedside chair woken by the patient saying their name — the most private of reunion moments", emotionType: "intimate private reunion", visualSignals: ["partner startling awake", "hearing their name", "seeing the patient looking at them", "the intimate shock of being called by name by someone who couldn't speak"], industryIds: ["hospital"], tags: ["partner", "asleep", "name-spoken", "intimate"], priority: 5, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:hospital:icu-discharge-back-to-family-home", kind: "emotional_moment", moment: "ICU patient finally discharged to go home — weeks after the crisis, leaving through the main entrance, the person the family thought they might lose walking out", emotionType: "survival made physical in departure", visualSignals: ["patient walking toward exit", "family on each side", "the deliberate last look back", "the doors opening to the world"], industryIds: ["hospital"], tags: ["icu-discharge", "home", "walking-out", "survival-physical"], priority: 6, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },

  // ── First steps in physiotherapy (5) ─────────────────────────────────────
  { id: "emotional_moment:hospital:first-steps-after-joint-replacement", kind: "emotional_moment", moment: "First steps after hip or knee replacement — physio on one side, walker in hand, the joint that has been painful for years now moving differently", emotionType: "first movement of a new joint", visualSignals: ["cautious first weight-bearing", "surprise at the different sensation", "physio encouraging", "face concentrating then relaxing as it works"], industryIds: ["hospital"], tags: ["joint-replacement", "first-steps", "new-sensation", "physio"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:hospital:stroke-patient-arm-moves-first-time", kind: "emotional_moment", moment: "Stroke patient's previously paralysed arm making its first voluntary movement in physio — tiny, deliberate, the brain rewiring made visible", emotionType: "neural breakthrough", visualSignals: ["intense concentration", "the small movement arriving", "patient noticing it first", "physio's controlled excitement", "patient starting to cry"], industryIds: ["hospital"], tags: ["stroke", "arm-movement", "paralysis-breaking", "neural-breakthrough"], priority: 2, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:hospital:spinal-patient-stands-for-first-time", kind: "emotional_moment", moment: "Spinal injury patient standing upright for first time since injury — the team gathered, the patient gripping frame, the vertical axis of the human body regained", emotionType: "vertical axis restored", visualSignals: ["team gathered and watching", "patient rising slowly", "reaching full height", "the team's collective exhale", "patient's face at ceiling height for first time in weeks"], industryIds: ["hospital"], tags: ["spinal", "standing", "vertical", "team-gathered"], priority: 3, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:hospital:elderly-patient-walks-to-window", kind: "emotional_moment", moment: "Elderly patient walking to window unaided for first time since surgery — each step controlled, reaching the window and looking out at the world they are returning to", emotionType: "world reclaimed in view", visualSignals: ["each step deliberate", "hand not needed on wall", "reaching window", "looking out", "the world visible to someone returning to it"], industryIds: ["hospital"], tags: ["elderly", "window", "unaided", "world-reclaimed"], priority: 4, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:hospital:physio-discharge-assessment-passed", kind: "emotional_moment", moment: "Patient passing physiotherapy discharge assessment — completing all tasks independently, physio making the final mark on the form, 'you're ready to go home'", emotionType: "earned readiness", visualSignals: ["completing the last task", "looking to physio", "physio marking form", "saying 'you're ready'", "patient's quiet pride"], industryIds: ["hospital"], tags: ["discharge-assessment", "passed", "earned", "ready"], priority: 5, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },

  // ── Newborn first hold (6) ────────────────────────────────────────────────
  { id: "emotional_moment:hospital:mother-first-holds-newborn", kind: "emotional_moment", moment: "Mother holding her newborn baby for the first time — the extraordinary weight of a new person, the face looking up at the face that will matter most", emotionType: "annihilating love", visualSignals: ["cradling arms", "looking at the face", "the new person looking back", "the world contracting to this person and this moment", "tears on the mother's face"], industryIds: ["hospital"], tags: ["first-hold", "newborn", "mother", "annihilating-love"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "emotional_moment:hospital:father-first-holds-newborn", kind: "emotional_moment", moment: "Father holding his newborn for the first time — often the surprise of the emotion arriving, the man who wasn't sure what he would feel suddenly certain", emotionType: "unexpected overwhelming arrival of love", visualSignals: ["uncertainty in how to hold", "then the weight settling", "face changing as the love arrives", "the private processing of becoming a father"], industryIds: ["hospital"], tags: ["father", "first-hold", "unexpected-love", "processing"], priority: 2, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:hospital:premature-baby-first-held-outside-incubator", kind: "emotional_moment", moment: "Premature baby held outside incubator for first time — the weeks of looking through glass, then the weight in hands, the body of the baby finally felt not just seen", emotionType: "glass barrier finally crossed", visualSignals: ["baby bundled carefully", "leads managed by nurse", "parent receiving the weight", "the difference between seeing and holding made emotional"], industryIds: ["hospital"], tags: ["premature", "first-hold-outside", "incubator", "weight-finally-felt"], priority: 3, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:hospital:grandparent-meeting-grandchild-first-time", kind: "emotional_moment", moment: "Grandparent meeting newborn grandchild for first time at hospital — the continuity of the family made visible in the small face, the generation extending", emotionType: "generational wonder", visualSignals: ["grandparent looking carefully at the baby", "finding resemblances", "telling the parents who the baby looks like", "the continuity of family in one face"], industryIds: ["hospital"], tags: ["grandparent", "first-meeting", "resemblance", "continuity"], priority: 4, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:hospital:sibling-meets-new-baby-in-hospital", kind: "emotional_moment", moment: "Young sibling meeting new baby in hospital for the first time — prepared for this moment but still surprised by it, the small face of their competition and companion", emotionType: "sibling world rearranging", visualSignals: ["sibling looking carefully", "reaching out a hand", "mother watching the meeting", "the family configuration changing visibly"], industryIds: ["hospital"], tags: ["sibling", "meeting-new-baby", "rearranging", "hospital"], priority: 5, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:hospital:newborn-taken-home-after-neonatal-stay", kind: "emotional_moment", moment: "Premature baby leaving NICU for home after weeks in care — the car seat that seemed impossible, the nurses gathered to say goodbye, the departure that represents everything", emotionType: "impossible made possible", visualSignals: ["car seat being fitted", "nurses gathering at the unit door", "waving goodbye", "baby going through doors that have defined the weeks"], industryIds: ["hospital"], tags: ["nicu-discharge", "car-seat", "nurses-goodbye", "impossible-possible"], priority: 6, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },

  // ── Unexpected recovery (5) ───────────────────────────────────────────────
  { id: "emotional_moment:hospital:doctor-reports-unexpected-improvement", kind: "emotional_moment", moment: "Doctor reporting that a patient has improved far more than expected — the revision of the prognosis upward, the better news nobody dared hope for", emotionType: "hope exceeding its allowed limits", visualSignals: ["family receiving the update", "the words 'much better than we expected'", "the permission to hope more", "quiet joy as the better future appears"], industryIds: ["hospital"], tags: ["unexpected-improvement", "better-than-expected", "prognosis-revised", "permission-to-hope"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:hospital:cancer-patient-complete-response", kind: "emotional_moment", moment: "Cancer patient told they have had a complete response to treatment — no evidence of disease, the scan that shows the cancer has gone", emotionType: "complete resolution", visualSignals: ["patient unable to speak initially", "then asking 'does that mean...'", "confirmation arriving", "the weight of it landing slowly"], industryIds: ["hospital"], tags: ["complete-response", "cancer", "no-evidence", "resolution"], priority: 2, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:hospital:coma-patient-waking-earlier-than-forecast", kind: "emotional_moment", moment: "Coma patient waking days earlier than predicted — the medical team surprised, the family informed, the impossibility of predicting recovery illustrated", emotionType: "medicine exceeded", visualSignals: ["team surprise", "family urgently called in", "patient awake and communicating", "the revision of expectations in real time"], industryIds: ["hospital"], tags: ["coma", "waking-early", "medicine-exceeded", "surprise"], priority: 3, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:hospital:patient-walks-who-was-feared-not-to", kind: "emotional_moment", moment: "Patient walks out of rehabilitation who was initially thought unlikely to walk — the gap between the initial prognosis and this exit moment visible to all", emotionType: "the body surpassing the forecast", visualSignals: ["patient walking deliberately", "staff who remember the early days watching", "the exit from the building", "family who were told to prepare for worse"], industryIds: ["hospital"], tags: ["walking-out", "initial-prognosis", "surpassing", "unlikely-to-walk"], priority: 4, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:hospital:rare-condition-effectively-treated", kind: "emotional_moment", moment: "Patient with rare condition told their treatment has worked — the person whose condition was described as difficult to treat now being told the treatment succeeded", emotionType: "rare vindication", visualSignals: ["patient's disbelief at first", "the medical team's genuine satisfaction", "the unusual nature of the success acknowledged", "patient looking at their own hands as if seeing differently"], industryIds: ["hospital"], tags: ["rare-condition", "treatment-success", "vindication", "unusual"], priority: 5, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },

  // ── Discharge day walking out (6) ─────────────────────────────────────────
  { id: "emotional_moment:hospital:discharge-day-walking-through-main-doors", kind: "emotional_moment", moment: "Patient walking through hospital main entrance doors on discharge day — the automatic doors opening, outside air hitting their face, the world returning", emotionType: "world reclaimed", visualSignals: ["automatic doors opening", "outside air visible", "patient stepping through", "face changing with first outdoor air in days or weeks", "family either side"], industryIds: ["hospital"], tags: ["discharge", "main-doors", "outside-air", "world-reclaimed"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:hospital:long-stay-patient-finally-going-home", kind: "emotional_moment", moment: "Patient going home after unexpectedly long stay — the bags packed, the person changed by the experience, the world they left no longer quite the world they return to", emotionType: "the changed person departing", visualSignals: ["bags in hand", "looking back once", "stepping toward the exit", "the sense of a changed person in familiar clothes"], industryIds: ["hospital"], tags: ["long-stay", "going-home", "changed-person", "departure"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:hospital:cancer-patient-leaving-after-treatment-complete", kind: "emotional_moment", moment: "Cancer patient completing treatment and leaving oncology unit — the end of the treatment chapter, the bell rung, the team gathered, the unit they have come to know being left", emotionType: "treatment chapter ending", visualSignals: ["bell rung", "applause from staff", "walking toward the exit", "the mixed emotion of relief and strangeness at ending a routine that kept them alive"], industryIds: ["hospital"], tags: ["cancer", "treatment-complete", "bell", "mixed-emotion"], priority: 3, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:hospital:new-mother-leaving-hospital-with-baby", kind: "emotional_moment", moment: "New mother leaving hospital with baby for the first time — car seat strapped in, the couple with their baby looking at each other above the car seat, the world about to start", emotionType: "the world about to start", visualSignals: ["car seat clipped in", "both looking at the baby", "then at each other", "the car pulling away", "the institution releasing them to their family"], industryIds: ["hospital"], tags: ["new-mother", "baby", "car-seat", "world-starting"], priority: 4, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "emotional_moment:hospital:patient-discharge-nurse-goodbye", kind: "emotional_moment", moment: "Patient saying goodbye to the nurse who has cared for them throughout admission — the specific gratitude for the specific person, the acknowledgment of what was given", emotionType: "specific named gratitude", visualSignals: ["patient stopping to say goodbye specifically", "nurse's name spoken", "embrace or handshake", "the parting that marks the end of care"], industryIds: ["hospital"], tags: ["goodbye", "named-nurse", "specific-gratitude", "parting"], priority: 5, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:hospital:patient-turns-back-once-at-hospital-exit", kind: "emotional_moment", moment: "Departing patient turning back once to look at the hospital entrance — the private acknowledgment of what happened inside, the silent farewell to the building that saved them", emotionType: "silent farewell to the place of survival", visualSignals: ["stopping at exit", "turning to look back at building", "a pause", "then turning forward and leaving", "the private acknowledgment visible only in the pause"], industryIds: ["hospital"], tags: ["turning-back", "silent-farewell", "acknowledgment", "private"], priority: 6, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Diagnosis explaining symptoms (6) ─────────────────────────────────────
  { id: "emotional_moment:hospital:diagnosis-that-explains-years-of-symptoms", kind: "emotional_moment", moment: "Receiving a diagnosis that finally explains years of unexplained symptoms — the validation of years of being told nothing was wrong", emotionType: "years of dismissal vindicated", visualSignals: ["patient saying 'so it was real'", "tears of validation", "the processing of being believed after years of doubt", "asking 'what happens now' as the future opens"], industryIds: ["hospital"], tags: ["diagnosis", "years-of-symptoms", "validated", "vindicated"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:hospital:rare-diagnosis-named-for-first-time", kind: "emotional_moment", moment: "Rare condition named for first time after years of wrong diagnoses — the patient who had been told they had other conditions finally hearing the correct name", emotionType: "the correct name's relief", visualSignals: ["patient repeating the name quietly", "asking to see it written", "looking it up on phone", "the relief of a name that fits"], industryIds: ["hospital"], tags: ["rare-diagnosis", "correct-name", "years-wrong", "fits"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:hospital:mental-health-diagnosis-reducing-self-blame", kind: "emotional_moment", moment: "Mental health diagnosis reducing the patient's self-blame — the moment the condition is named as a condition, not a character failing", emotionType: "self-blame lifting", visualSignals: ["patient's expression changing at the diagnosis", "the implicit permission to stop blaming themselves", "asking questions about the condition", "visible weight lifting"], industryIds: ["hospital"], tags: ["mental-health", "diagnosis", "self-blame-lifting", "condition"], priority: 3, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:hospital:genetic-condition-found-explaining-family-history", kind: "emotional_moment", moment: "Genetic condition identified that explains the family's medical history — the patient looking back through generations, the pattern suddenly visible", emotionType: "retrospective understanding", visualSignals: ["patient going through family history mentally", "making connections aloud", "the retrospective understanding of what happened to relatives", "the mixed emotion of knowledge and legacy"], industryIds: ["hospital"], tags: ["genetic", "family-history", "pattern", "retrospective"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "emotional_moment:hospital:autoimmune-diagnosis-after-dismissal", kind: "emotional_moment", moment: "Autoimmune diagnosis after years of 'there's nothing wrong with you' — the patient's vindication at seeing their blood results confirming what they always knew", emotionType: "laboratory vindication", visualSignals: ["patient pointing to the results", "saying they knew something was wrong", "the lab values as physical proof", "relief mixed with retrospective frustration"], industryIds: ["hospital"], tags: ["autoimmune", "blood-results", "dismissed", "vindication"], priority: 5, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "emotional_moment:hospital:adhd-diagnosis-in-adulthood", kind: "emotional_moment", moment: "Adult receiving ADHD diagnosis after a lifetime of struggling without explanation — the diagnosis arriving decades after it could have been made, still bringing relief", emotionType: "lifetime explained at last", visualSignals: ["patient going quiet", "looking at their own hands", "saying 'that explains so much'", "tears for their younger self", "then questions about what now"], industryIds: ["hospital"], tags: ["adhd", "adult-diagnosis", "lifetime-explained", "younger-self"], priority: 6, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Reassurance from specialist (3) ──────────────────────────────────────
  { id: "emotional_moment:hospital:specialist-says-this-is-manageable", kind: "emotional_moment", moment: "Specialist telling patient their condition is manageable — the moment 'manageable' becomes the most important word, the future containing livable rather than unlivable", emotionType: "future revised to livable", visualSignals: ["patient's body language opening", "question 'are you sure it's manageable?'", "the confirmation", "beginning to imagine living with it rather than dying from it"], industryIds: ["hospital"], tags: ["manageable", "specialist", "future-livable", "confirmation"], priority: 1, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "emotional_moment:hospital:second-opinion-confirms-first-doctor", kind: "emotional_moment", moment: "Second opinion specialist confirming the original diagnosis and plan — the patient who came for reassurance finding it, the plan validated by independent eyes", emotionType: "reassurance through confirmation", visualSignals: ["patient's tension visibly easing", "the second opinion confirming", "the plan now carried by two experts", "permission to proceed with confidence"], industryIds: ["hospital"], tags: ["second-opinion", "confirmation", "reassurance", "proceed-with-confidence"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "emotional_moment:hospital:specialist-says-patient-is-doing-everything-right", kind: "emotional_moment", moment: "Specialist confirming the patient is doing everything right in their self-management — the validation of the effort and discipline that nobody else sees", emotionType: "effort validated", visualSignals: ["patient's quiet pride at the validation", "asking 'are you sure?'", "the specialist confirming specifics", "the self-management finally acknowledged"], industryIds: ["hospital"], tags: ["validation", "self-management", "effort", "doing-right"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
];
