import type { HeroMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const HOSPITAL_HERO_MOMENTS: HeroMomentKnowledgeNode[] = [
  // ── Diagnosis breakthrough — clarity and relief (12) ─────────────────────────
  { id: "hero_moment:hospital:doctor-delivers-diagnosis-with-clarity", kind: "hero_moment", subject: "Doctor delivering diagnosis clearly to seated patient — scan images on screen behind them, patient's face shifting from uncertainty to understanding", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["brand_trust", "specialist_referral"], behaviourIds: [], tags: ["diagnosis", "clarity", "doctor", "understanding"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "hero_moment:hospital:patient-sees-scan-that-explains-symptoms", kind: "hero_moment", subject: "Patient seeing their own MRI scan for the first time — doctor pointing to area that finally explains years of unexplained symptoms", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["brand_trust", "technology"], behaviourIds: [], tags: ["scan", "mri", "explanation", "symptoms"], priority: 2, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "hero_moment:hospital:specialist-names-condition-patient-suspected", kind: "hero_moment", subject: "Specialist naming the condition the patient has long suspected — the validation after years of dismissed symptoms, patient leaning forward", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["specialist_referral", "brand_trust"], behaviourIds: [], tags: ["diagnosis", "validation", "specialist", "relief"], priority: 3, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:hospital:all-clear-scan-result-delivered", kind: "hero_moment", subject: "Doctor delivering all-clear scan result — the moment of relief when 'everything looks completely clear' lands, patient's exhale visible", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["health_screening", "brand_trust"], behaviourIds: [], tags: ["all-clear", "relief", "scan", "good-news"], priority: 4, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:hospital:doctor-showing-scan-to-patient-in-consultation", kind: "hero_moment", subject: "Doctor showing scan images directly to patient on screen — pointing to anatomy, translating medical language into meaning the patient can grasp", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["brand_trust", "technology"], behaviourIds: [], tags: ["scan", "education", "transparency", "consultation"], priority: 5, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:hospital:diagnosis-after-years-of-searching", kind: "hero_moment", subject: "Patient finally receiving a definitive diagnosis after years of inconclusive tests — tears, disbelief, and relief in one expression", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["brand_trust", "specialist_referral"], behaviourIds: [], tags: ["diagnosis", "relief", "years-of-searching", "definitive"], priority: 6, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:hospital:neurologist-explaining-mri-findings", kind: "hero_moment", subject: "Neurologist at lightbox explaining MRI brain scan findings — tracing anatomy on film, patient fully attentive to the specialist they finally reached", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["specialist_referral", "technology"], behaviourIds: [], tags: ["neurology", "mri", "brain", "specialist"], priority: 7, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:hospital:pathology-result-confirms-diagnosis", kind: "hero_moment", subject: "Pathology result shown to patient confirming diagnosis — printed report, doctor explaining what each finding means in clear terms", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["brand_trust"], behaviourIds: [], tags: ["pathology", "result", "confirmed", "report"], priority: 8, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "hero_moment:hospital:patient-leaving-consultation-with-answers", kind: "hero_moment", subject: "Patient leaving consultation room with notes in hand — walking with purpose, the relief of finally having a plan visible in posture", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["brand_trust", "patient_acquisition"], behaviourIds: [], tags: ["consultation", "answers", "plan", "relief"], priority: 7, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:hospital:second-opinion-confirming-plan", kind: "hero_moment", subject: "Second opinion appointment — specialist confirming the existing treatment plan is correct, patient's shoulders visibly dropping with reassurance", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["specialist_referral", "brand_trust"], behaviourIds: [], tags: ["second-opinion", "reassurance", "confirmation", "specialist"], priority: 6, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:hospital:consultant-drawing-to-explain-anatomy", kind: "hero_moment", subject: "Consultant drawing a quick anatomy diagram on paper to explain surgical approach — pen in hand, patient leaning in to understand", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["brand_trust", "surgery"], behaviourIds: [], tags: ["diagram", "anatomy", "explanation", "surgeon"], priority: 5, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "hero_moment:hospital:doctor-and-patient-reviewing-results-together", kind: "hero_moment", subject: "Doctor and patient sitting side by side reviewing test results — shared screen, equal engagement, the collaborative model of modern medicine", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["brand_trust"], behaviourIds: [], tags: ["collaborative", "results", "shared", "modern"], priority: 4, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Surgical success — delivering good news (12) ────────────────────────────
  { id: "hero_moment:hospital:surgeon-stepping-out-to-deliver-good-news", kind: "hero_moment", subject: "Surgeon stepping out of theatre doors in scrubs to tell waiting family the operation was a success — mask pulled down, hands raised, the moment that changes everything", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["surgery", "brand_trust"], behaviourIds: [], tags: ["surgeon", "good-news", "family", "success"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "hero_moment:hospital:surgery-complete-team-removing-gloves", kind: "hero_moment", subject: "Surgical team removing gloves after a successful procedure — the collective exhale, the shared satisfaction of a team that executed perfectly", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["surgery", "brand_trust"], behaviourIds: [], tags: ["surgical-team", "gloves", "complete", "collective"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:hospital:surgeon-speaking-to-waiting-family", kind: "hero_moment", subject: "Surgeon speaking to waiting family in quiet room — the controlled calm of the professional delivering life-changing news with compassion", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["surgery", "brand_trust"], behaviourIds: [], tags: ["surgeon", "family", "compassion", "news"], priority: 3, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:hospital:patient-waking-from-anaesthesia", kind: "hero_moment", subject: "Patient waking from anaesthesia to see nurse beside them — the first confused blink, then the reassurance 'It went well' settling them immediately", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["surgery", "nursing_care"], behaviourIds: [], tags: ["anaesthesia", "waking", "reassurance", "nurse"], priority: 4, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:hospital:theatre-team-moment-after-successful-surgery", kind: "hero_moment", subject: "Theatre team in the brief moment after surgery — instruments being counted, the shared wordless acknowledgment of a good result", heroType: "environment", industryIds: ["hospital"], campaignTypeIds: ["surgery"], behaviourIds: [], tags: ["theatre-team", "post-surgery", "shared-moment", "team"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:hospital:laparoscopic-surgery-on-screen", kind: "hero_moment", subject: "Laparoscopic surgery on monitors — high-definition internal imagery, surgeon's hands precise at instrument handles, the body's interior visible with extraordinary clarity", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["surgery", "technology"], behaviourIds: [], tags: ["laparoscopic", "screen", "precision", "minimally-invasive"], priority: 6, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:hospital:robotic-surgery-console-surgeon-focused", kind: "hero_moment", subject: "Surgeon at robotic surgery console — headset on, hands on precision controls, the extraordinary capability of robotic-assisted surgery in action", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["surgery", "technology"], behaviourIds: [], tags: ["robotic", "console", "precision", "technology"], priority: 7, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:hospital:orthopaedic-surgery-joint-complete", kind: "hero_moment", subject: "Orthopaedic surgeon completing joint replacement — final component seated, the satisfying confirmation that function has been restored", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["surgery"], behaviourIds: [], tags: ["orthopaedic", "joint-replacement", "complete", "function"], priority: 6, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:hospital:cardiac-surgery-team-in-action", kind: "hero_moment", subject: "Cardiac surgical team operating around the illuminated chest cavity — every specialist at their position, coordinated silence punctuated by precise instruction", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["surgery", "brand_trust"], behaviourIds: [], tags: ["cardiac", "surgical-team", "coordinated", "precision"], priority: 5, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:hospital:neurosurgeon-completing-delicate-procedure", kind: "hero_moment", subject: "Neurosurgeon completing a delicate brain procedure — precision magnified through surgical microscope, the extraordinary stillness of hands doing impossible work", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["surgery", "technology", "specialist_referral"], behaviourIds: [], tags: ["neurosurgeon", "brain", "microscope", "precision"], priority: 4, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:hospital:anaesthetist-monitoring-vital-signs", kind: "hero_moment", subject: "Anaesthetist monitoring vital signs throughout surgery — watching screens, adjusting infusions, the invisible guardian making surgery possible", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["surgery", "brand_trust"], behaviourIds: [], tags: ["anaesthetist", "monitoring", "vitals", "guardian"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "hero_moment:hospital:post-surgery-patient-stable-transferred", kind: "hero_moment", subject: "Post-surgery patient being transferred from theatre to recovery ward — bed moving through corridor, nurse at head end, the journey toward healing begun", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["surgery", "nursing_care"], behaviourIds: [], tags: ["post-surgery", "recovery", "transfer", "healing"], priority: 6, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },

  // ── Patient recovery milestones (15) ────────────────────────────────────────
  { id: "hero_moment:hospital:first-steps-after-major-surgery", kind: "hero_moment", subject: "Patient taking first steps after major surgery — physio on one side, walking frame in hand, the enormous achievement of those two metres down the ward", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["rehabilitation", "brand_trust"], behaviourIds: [], tags: ["first-steps", "surgery", "physio", "milestone"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "hero_moment:hospital:patient-walking-corridor-with-physio", kind: "hero_moment", subject: "Patient walking hospital corridor with physiotherapist — mobile IV pole alongside, both focused forward, the progress visible in every step", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["rehabilitation", "nursing_care"], behaviourIds: [], tags: ["walking", "corridor", "physio", "progress"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:hospital:discharge-day-walking-out-hospital-doors", kind: "hero_moment", subject: "Discharge day — patient walking out through hospital main entrance, family beside them, the moment they return to the world", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["brand_trust", "patient_acquisition"], behaviourIds: [], tags: ["discharge", "walking-out", "milestone", "family"], priority: 3, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "hero_moment:hospital:patient-eating-first-meal-after-operation", kind: "hero_moment", subject: "Patient eating first full meal after operation — sitting up in bed, tray in front of them, the simple pleasure of appetite returning", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["nursing_care", "rehabilitation"], behaviourIds: [], tags: ["eating", "first-meal", "appetite", "recovery"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:hospital:wound-healing-check-consultant-impressed", kind: "hero_moment", subject: "Wound check at follow-up — consultant examining healing incision, visibly impressed by recovery, explaining to patient what excellent healing looks like", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["surgery", "brand_trust"], behaviourIds: [], tags: ["wound", "healing", "follow-up", "impressed"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "hero_moment:hospital:patient-breathing-without-oxygen-support", kind: "hero_moment", subject: "ICU patient having oxygen mask removed — first unassisted breaths, nurse watching saturation monitor, the independence milestone", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["nursing_care", "rehabilitation"], behaviourIds: [], tags: ["oxygen", "removed", "breathing", "independence"], priority: 6, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:hospital:icu-patient-waking-family-beside-bed", kind: "hero_moment", subject: "ICU patient waking from induced coma — eyes opening to see family gathered beside the bed, recognition arriving on their face", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["nursing_care", "brand_trust"], behaviourIds: [], tags: ["icu", "waking", "family", "recognition"], priority: 7, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:hospital:first-words-after-surgery", kind: "hero_moment", subject: "Patient saying their first coherent words after major surgery — nurse leaning in to hear, understanding confirmed, the mind intact", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["nursing_care", "surgery"], behaviourIds: [], tags: ["first-words", "post-surgery", "nurse", "coherent"], priority: 8, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:hospital:stroke-patient-lifting-arm-in-physio", kind: "hero_moment", subject: "Stroke patient lifting previously paralysed arm in physio session — the effort visible, physio guiding, the extraordinary return of movement", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["rehabilitation", "brand_trust"], behaviourIds: [], tags: ["stroke", "paralysis", "arm-lifting", "return"], priority: 7, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:hospital:cancer-patient-ringing-bell-end-of-treatment", kind: "hero_moment", subject: "Cancer patient ringing the end-of-treatment bell on the oncology ward — wide smile, tears, nursing team clapping around them", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["oncology", "brand_trust"], behaviourIds: [], tags: ["bell", "cancer", "treatment-complete", "celebration"], priority: 6, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "hero_moment:hospital:sitting-up-in-bed-for-first-time", kind: "hero_moment", subject: "Patient sitting up unaided in bed for the first time after surgery — positioning themselves, the effort and pride of that small independence", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["rehabilitation", "nursing_care"], behaviourIds: [], tags: ["sitting-up", "independence", "unaided", "milestone"], priority: 5, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "hero_moment:hospital:patient-climbing-stairs-in-rehab", kind: "hero_moment", subject: "Patient climbing stairs in rehabilitation gym — physio spotting from behind, handrail gripped, the test of real-world recovery", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["rehabilitation"], behaviourIds: [], tags: ["stairs", "rehabilitation", "climbing", "test"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:hospital:spinal-patient-standing-upright-frame", kind: "hero_moment", subject: "Spinal surgery patient standing upright for the first time using walking frame — physiotherapist steadying, the vertical posture they feared they would never regain", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["rehabilitation", "surgery"], behaviourIds: [], tags: ["spinal", "standing", "frame", "upright"], priority: 3, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:hospital:patient-looking-in-mirror-recovery", kind: "hero_moment", subject: "Patient looking in ward mirror as they recover — noticing colour returning to their face, the visible evidence of their own improvement", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["rehabilitation", "brand_trust"], behaviourIds: [], tags: ["mirror", "recovery", "colour", "improvement"], priority: 5, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "hero_moment:hospital:first-unaided-steps-without-frame", kind: "hero_moment", subject: "Physio stepping back as patient takes first steps without walking frame — those few unassisted strides, the room holding its breath", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["rehabilitation", "brand_trust"], behaviourIds: [], tags: ["unaided", "first-steps", "physio", "unassisted"], priority: 2, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },

  // ── Emergency team in coordinated action (10) ──────────────────────────────
  { id: "hero_moment:hospital:a-and-e-team-surrounding-crash-trolley", kind: "hero_moment", subject: "A&E resuscitation team around a crash trolley — each professional at their designated position, rapid precise communication, the choreography of crisis care", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["emergency_care", "brand_trust"], behaviourIds: [], tags: ["resuscitation", "team", "crash-trolley", "coordinated"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:hospital:paramedics-handing-over-to-emergency-team", kind: "hero_moment", subject: "Paramedics handing over to emergency department team — verbal handover, patient transfer, the seamless continuation of care across teams", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["emergency_care"], behaviourIds: [], tags: ["paramedics", "handover", "emergency", "continuity"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:hospital:rapid-response-team-arriving-on-ward", kind: "hero_moment", subject: "Rapid response team arriving on ward to deteriorating patient — crash bag over shoulder, team assembled in sixty seconds from call", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["emergency_care", "brand_trust"], behaviourIds: [], tags: ["rapid-response", "ward", "deteriorating", "speed"], priority: 3, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:hospital:emergency-triage-nurse-assessing", kind: "hero_moment", subject: "Emergency triage nurse assessing newly arrived patient — calm amid chaos, methodical, the steady anchor of the emergency department entrance", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["emergency_care", "nursing_care"], behaviourIds: [], tags: ["triage", "nurse", "assessment", "calm"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:hospital:defibrillator-applied-cardiac-arrest", kind: "hero_moment", subject: "Defibrillator pads applied during cardiac arrest response — team clear, charge delivered, the moment of electrical intervention", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["emergency_care", "technology"], behaviourIds: [], tags: ["defibrillator", "cardiac-arrest", "intervention", "team"], priority: 5, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:hospital:emergency-surgeon-being-briefed", kind: "hero_moment", subject: "Emergency surgeon called in and being briefed en route to theatre — taking notes on glove, theatre team assembling ahead", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["emergency_care", "surgery"], behaviourIds: [], tags: ["emergency-surgeon", "briefing", "theatre", "en-route"], priority: 6, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:hospital:trauma-team-response-patient-arrives", kind: "hero_moment", subject: "Trauma team meeting ambulance bay — standing ready as doors open, each role known, the preparedness that saves lives in those first minutes", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["emergency_care", "brand_trust"], behaviourIds: [], tags: ["trauma-team", "ambulance-bay", "prepared", "first-minutes"], priority: 7, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:hospital:emergency-blood-transfusion-in-progress", kind: "hero_moment", subject: "Emergency blood transfusion in progress — blood bag raised, nurse checking group label, the urgent replenishment of life", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["emergency_care"], behaviourIds: [], tags: ["blood-transfusion", "emergency", "urgent", "life"], priority: 8, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:hospital:stroke-team-racing-to-scan-patient", kind: "hero_moment", subject: "Stroke team racing patient to CT scanner — bed moving at pace through corridor, every second of the golden hour in focus", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["emergency_care", "technology"], behaviourIds: [], tags: ["stroke", "ct-scan", "golden-hour", "racing"], priority: 7, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:hospital:emergency-c-section-team-assembling", kind: "hero_moment", subject: "Emergency caesarean team assembling in theatre — each specialist taking position, scrub nurse opening sterile pack, the controlled urgency of birth crisis care", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["emergency_care", "maternity"], behaviourIds: [], tags: ["emergency-caesarean", "team", "theatre", "maternity"], priority: 6, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Doctor-patient trust conversation (8) ────────────────────────────────
  { id: "hero_moment:hospital:doctor-sitting-at-patient-bedside-listening", kind: "hero_moment", subject: "Doctor pulling chair to sit at patient bedside — not standing over them, choosing to be at eye level, the posture of genuine listening", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["brand_trust", "patient_acquisition"], behaviourIds: [], tags: ["doctor", "bedside", "listening", "eye-level"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:hospital:consultant-giving-patient-full-attention", kind: "hero_moment", subject: "Consultant giving patient their complete attention — notes set aside, phone out of hand, the rare gift of undivided focus in a busy hospital", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["brand_trust"], behaviourIds: [], tags: ["consultant", "attention", "undivided", "trust"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:hospital:doctor-knocking-before-entering-ward-room", kind: "hero_moment", subject: "Doctor knocking before entering patient's room — the small gesture of respect that signals how this practice treats the person, not just the condition", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["brand_trust", "nursing_care"], behaviourIds: [], tags: ["knocking", "respect", "patient-dignity", "gesture"], priority: 3, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "hero_moment:hospital:specialist-answering-questions-patiently", kind: "hero_moment", subject: "Specialist taking time to answer all the patient's questions without any sign of impatience — the rarity and value of a specialist who explains", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["brand_trust", "specialist_referral"], behaviourIds: [], tags: ["specialist", "questions", "patience", "explaining"], priority: 4, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:hospital:doctor-explaining-treatment-plan-clearly", kind: "hero_moment", subject: "Doctor explaining treatment plan in plain language — printed plan in hand, pointing to each stage, translating clinical into human", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["brand_trust", "patient_acquisition"], behaviourIds: [], tags: ["treatment-plan", "plain-language", "clarity", "printed"], priority: 5, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:hospital:patient-and-doctor-shared-decision", kind: "hero_moment", subject: "Shared decision-making moment — doctor laying out treatment options and genuinely inviting the patient's choice, the patient engaging as equal partner", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["brand_trust"], behaviourIds: [], tags: ["shared-decision", "options", "patient-choice", "partnership"], priority: 6, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:hospital:gp-referral-conversation-building-trust", kind: "hero_moment", subject: "GP writing referral letter while patient watches — explaining which specialist and why, the bridge between primary and specialist care", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["specialist_referral", "brand_trust"], behaviourIds: [], tags: ["gp", "referral", "bridge", "specialist"], priority: 7, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "hero_moment:hospital:consultant-listening-while-patient-speaks", kind: "hero_moment", subject: "Consultant with pen down, listening fully as patient describes their experience — the notes can wait, the person is speaking first", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["brand_trust"], behaviourIds: [], tags: ["consultant", "listening", "pen-down", "person-first"], priority: 8, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Medical technology in use (10) ───────────────────────────────────────
  { id: "hero_moment:hospital:mri-scanner-patient-entering-bore", kind: "hero_moment", subject: "Patient entering MRI scanner bore — the large white machine, calm patient sliding in on table, the diagnostic precision of the moment", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["technology", "brand_trust"], behaviourIds: [], tags: ["mri", "scanner", "bore", "diagnostic"], priority: 1, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:hospital:ct-scan-images-appearing-on-screen", kind: "hero_moment", subject: "CT scan cross-sections appearing on radiologist's screen in real time — anatomy revealed slice by slice, the extraordinary diagnostic window", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["technology", "brand_trust"], behaviourIds: [], tags: ["ct-scan", "radiologist", "cross-sections", "diagnostic"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:hospital:da-vinci-robotic-surgical-arms", kind: "hero_moment", subject: "Da Vinci robotic surgical arms in operating position — four arms extended over draped patient, the machine that makes the impossible possible", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["technology", "surgery"], behaviourIds: [], tags: ["da-vinci", "robotic", "arms", "surgical"], priority: 3, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:hospital:ultrasound-on-abdomen-screen-image", kind: "hero_moment", subject: "Ultrasound probe on patient's abdomen — real-time image on screen beside them, the non-invasive window into the body's interior", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["technology", "maternity"], behaviourIds: [], tags: ["ultrasound", "abdomen", "real-time", "non-invasive"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:hospital:ecg-machine-showing-heart-rhythm", kind: "hero_moment", subject: "ECG machine producing continuous heart rhythm trace — the patient calm while the machine reads, vital signs made visible in waves", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["technology", "emergency_care"], behaviourIds: [], tags: ["ecg", "heart-rhythm", "trace", "cardiac"], priority: 5, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "hero_moment:hospital:portable-ultrasound-bedside", kind: "hero_moment", subject: "Bedside portable ultrasound being used by doctor — laptop-sized device, immediate imaging at the patient's side, technology brought to the patient", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["technology", "brand_trust"], behaviourIds: [], tags: ["portable-ultrasound", "bedside", "immediate", "point-of-care"], priority: 6, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "hero_moment:hospital:digital-pathology-slide-on-screen", kind: "hero_moment", subject: "Pathologist examining digital slide on high-resolution screen — magnification controls adjusted, the extraordinary detail of cellular anatomy", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["technology", "specialist_referral"], behaviourIds: [], tags: ["digital-pathology", "slide", "screen", "cellular"], priority: 7, weight: 0.81, confidence: "high", commercialScore: 80, futureMetadata: fm },
  { id: "hero_moment:hospital:endoscopy-image-on-screen", kind: "hero_moment", subject: "Endoscopy image live on screen during procedure — the camera navigating the internal landscape in extraordinary colour, physician guiding with precision", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["technology", "surgery"], behaviourIds: [], tags: ["endoscopy", "internal", "camera", "precision"], priority: 8, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "hero_moment:hospital:pacemaker-implantation-fluoroscopy", kind: "hero_moment", subject: "Pacemaker lead being guided by fluoroscopy — the real-time X-ray image showing wire threading to heart position, technology and skill united", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["technology", "surgery"], behaviourIds: [], tags: ["pacemaker", "fluoroscopy", "lead", "cardiac"], priority: 7, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "hero_moment:hospital:ai-diagnostic-tool-flagging-finding", kind: "hero_moment", subject: "AI diagnostic tool highlighting area of interest on scan — radiologist and AI in dialogue, the technology augmenting human expertise", heroType: "product", industryIds: ["hospital"], campaignTypeIds: ["technology", "brand_trust"], behaviourIds: [], tags: ["ai-diagnostic", "scan", "flagging", "augmented"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Nursing care moments (10) ────────────────────────────────────────────
  { id: "hero_moment:hospital:nurse-4am-bedside-check-corridor-dark", kind: "hero_moment", subject: "4am ward round — nurse checking sleeping patient by torchlight, corridor dark outside, the unseen care that happens while families sleep", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["nursing_care", "brand_trust"], behaviourIds: [], tags: ["4am", "night-shift", "bedside-check", "unseen-care"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "hero_moment:hospital:nurse-holding-hand-during-procedure", kind: "hero_moment", subject: "Nurse holding patient's hand during a frightening procedure — not asked to, choosing to, the human connection that makes clinical care bearable", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["nursing_care", "brand_trust"], behaviourIds: [], tags: ["hand-holding", "nurse", "procedure", "connection"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:hospital:nurse-adjusting-iv-drip-carefully", kind: "hero_moment", subject: "Nurse adjusting IV drip rate with careful attention — checking prescription, calculating flow, the precision behind what looks like a simple task", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["nursing_care"], behaviourIds: [], tags: ["iv-drip", "adjustment", "precision", "medication"], priority: 3, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "hero_moment:hospital:nurse-explaining-medication-clearly", kind: "hero_moment", subject: "Nurse explaining each medication to patient before administering — name, purpose, timing, the informed consent that makes every dose a partnership", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["nursing_care", "brand_trust"], behaviourIds: [], tags: ["medication", "explaining", "informed-consent", "nurse"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "hero_moment:hospital:night-nurse-dimming-ward-lights", kind: "hero_moment", subject: "Night nurse dimming ward lights for patient sleep — the environmental care that supports healing, the thoughtfulness of healing by stealth", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["nursing_care"], behaviourIds: [], tags: ["night-nurse", "dimming-lights", "sleep", "healing"], priority: 5, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "hero_moment:hospital:nurse-comforting-distressed-patient", kind: "hero_moment", subject: "Nurse sitting beside distressed patient — not rushing to fix, simply being present, the therapeutic power of witnessed feeling", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["nursing_care", "brand_trust"], behaviourIds: [], tags: ["comfort", "distressed", "present", "therapeutic"], priority: 6, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:hospital:nurse-checking-blood-pressure-recording", kind: "hero_moment", subject: "Nurse taking blood pressure with cuff and recording in chart — systematic, frequent, the monitoring that catches deterioration before crisis", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["nursing_care"], behaviourIds: [], tags: ["blood-pressure", "monitoring", "systematic", "chart"], priority: 7, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "hero_moment:hospital:palliative-care-nurse-with-patient", kind: "hero_moment", subject: "Palliative care nurse sitting in quiet room with patient — the distinctive compassion of end-of-life nursing, presence as the intervention", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["nursing_care", "brand_trust"], behaviourIds: [], tags: ["palliative", "compassion", "presence", "end-of-life"], priority: 8, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:hospital:nurse-welcoming-patient-to-ward", kind: "hero_moment", subject: "Nurse welcoming nervous patient arriving on ward — showing their bed, explaining the routine, the first kindness in an unfamiliar place", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["nursing_care", "patient_acquisition"], behaviourIds: [], tags: ["welcome", "ward", "nervous-patient", "first-kindness"], priority: 3, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "hero_moment:hospital:ward-sister-briefing-nursing-team", kind: "hero_moment", subject: "Ward sister briefing nursing team at shift handover — each patient's status reviewed, priorities set, the invisible management that keeps care continuous", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["nursing_care", "brand_trust"], behaviourIds: [], tags: ["ward-sister", "briefing", "handover", "continuous-care"], priority: 2, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── Family receiving good news (8) ─────────────────────────────────────
  { id: "hero_moment:hospital:family-embracing-after-good-news", kind: "hero_moment", subject: "Family embracing in hospital corridor after surgeon delivers good news — the release of hours of fear in that single embrace", heroType: "lifestyle", industryIds: ["hospital"], campaignTypeIds: ["surgery", "brand_trust"], behaviourIds: [], tags: ["family", "embrace", "relief", "corridor"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "hero_moment:hospital:partner-crying-with-relief-waiting-room", kind: "hero_moment", subject: "Partner breaking down with relief in waiting room after receiving good news — the private moment of release after hours of waiting", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["surgery", "brand_trust"], behaviourIds: [], tags: ["partner", "relief", "tears", "waiting-room"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:hospital:children-reuniting-with-parent-after-surgery", kind: "hero_moment", subject: "Children rushing to hug a parent who has returned from surgery — the overwhelming small-person joy at mum or dad being back", heroType: "lifestyle", industryIds: ["hospital"], campaignTypeIds: ["surgery", "brand_trust"], behaviourIds: [], tags: ["children", "parent", "reunion", "surgery"], priority: 3, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "hero_moment:hospital:family-first-seeing-patient-after-icu", kind: "hero_moment", subject: "Family seeing their loved one for the first time after ICU discharge — entering the ward, the person awake, alert, the worst behind them", heroType: "lifestyle", industryIds: ["hospital"], campaignTypeIds: ["nursing_care", "brand_trust"], behaviourIds: [], tags: ["icu-discharge", "family", "first-sight", "awake"], priority: 4, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:hospital:phone-call-from-hospital-good-news", kind: "hero_moment", subject: "Family member receiving phone call from hospital with good news — hand going to mouth, eyes closing, the relief reaching down the line", heroType: "lifestyle", industryIds: ["hospital"], campaignTypeIds: ["brand_trust"], behaviourIds: [], tags: ["phone-call", "good-news", "relief", "family"], priority: 5, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:hospital:parents-seeing-baby-neonatal-unit", kind: "hero_moment", subject: "Parents standing at neonatal incubator seeing their premature baby for the first time — hand through porthole, the love that crosses every barrier", heroType: "lifestyle", industryIds: ["hospital"], campaignTypeIds: ["maternity", "brand_trust"], behaviourIds: [], tags: ["neonatal", "premature", "parents", "incubator"], priority: 6, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:hospital:family-gathering-at-bedside-recovery", kind: "hero_moment", subject: "Family gathered at bedside as patient recovers — three generations, the patient at the centre, the love that surrounds a person in hospital", heroType: "lifestyle", industryIds: ["hospital"], campaignTypeIds: ["brand_trust", "nursing_care"], behaviourIds: [], tags: ["family-gathering", "bedside", "three-generations", "love"], priority: 7, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:hospital:grandfather-back-grandchildren-visit", kind: "hero_moment", subject: "Grandfather returned from surgery to ward where grandchildren are waiting — the small visitors' faces lighting up, the patient straightening in the bed", heroType: "lifestyle", industryIds: ["hospital"], campaignTypeIds: ["brand_trust"], behaviourIds: [], tags: ["grandfather", "grandchildren", "ward-visit", "joy"], priority: 8, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Neonatal and maternity (10) ──────────────────────────────────────────
  { id: "hero_moment:hospital:mother-first-skin-contact-newborn", kind: "hero_moment", subject: "Mother holding newborn on her chest in first skin-to-skin contact — cord recently cut, baby alert, the meeting that reorders a person's entire world", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["maternity", "brand_trust"], behaviourIds: [], tags: ["skin-contact", "newborn", "mother", "first-meeting"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "hero_moment:hospital:father-cutting-umbilical-cord", kind: "hero_moment", subject: "Father cutting umbilical cord — midwife guiding scissor position, the act that marks the child's entry into separate existence", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["maternity", "brand_trust"], behaviourIds: [], tags: ["father", "cord-cutting", "midwife", "birth"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:hospital:midwife-placing-baby-on-chest", kind: "hero_moment", subject: "Midwife lifting newborn and placing directly onto mother's chest — the careful tender transfer, the first placement", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["maternity", "nursing_care"], behaviourIds: [], tags: ["midwife", "placement", "chest", "newborn"], priority: 3, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:hospital:neonatal-nurse-premature-baby-care", kind: "hero_moment", subject: "Neonatal nurse adjusting premature baby's position in incubator — gloved hands gentle through portholes, the specialised care for the most vulnerable patients", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["maternity", "nursing_care"], behaviourIds: [], tags: ["neonatal-nurse", "premature", "incubator", "gentle"], priority: 4, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:hospital:parents-looking-newborn-in-incubator", kind: "hero_moment", subject: "Parents looking at their premature baby through incubator glass — the helplessness and wonder and love of that vigil", heroType: "lifestyle", industryIds: ["hospital"], campaignTypeIds: ["maternity", "brand_trust"], behaviourIds: [], tags: ["parents", "incubator", "premature", "vigil"], priority: 5, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:hospital:baby-being-weighed-after-birth", kind: "hero_moment", subject: "Newborn being weighed on hospital scales — midwife recording the number, parents watching, the first measurement of the new person", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["maternity"], behaviourIds: [], tags: ["newborn", "weighed", "scales", "first-measurement"], priority: 6, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "hero_moment:hospital:scan-revealing-twins-parents-reaction", kind: "hero_moment", subject: "Antenatal scan revealing twins — sonographer turning screen toward parents, the moment of double news landing on both faces simultaneously", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["maternity", "technology"], behaviourIds: [], tags: ["twins", "scan", "revelation", "antenatal"], priority: 7, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:hospital:labour-partner-holding-hand-contractions", kind: "hero_moment", subject: "Birth partner holding labouring mother's hand through contraction — the grip, the focus, two people completely present in one of life's most intense moments", heroType: "lifestyle", industryIds: ["hospital"], campaignTypeIds: ["maternity"], behaviourIds: [], tags: ["labour", "partner", "hand-holding", "contraction"], priority: 8, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:hospital:mother-breastfeeding-with-midwife-support", kind: "hero_moment", subject: "Mother breastfeeding for first time with midwife beside her — gentle positioning guidance, the learning that needs patience and presence", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["maternity", "nursing_care"], behaviourIds: [], tags: ["breastfeeding", "midwife", "first-time", "guidance"], priority: 7, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "hero_moment:hospital:family-leaving-hospital-with-new-baby", kind: "hero_moment", subject: "Family leaving hospital with new baby in car seat — both parents looking slightly overwhelmed, the transition from hospital care to the world", heroType: "lifestyle", industryIds: ["hospital"], campaignTypeIds: ["maternity", "brand_trust"], behaviourIds: [], tags: ["discharge", "new-baby", "car-seat", "world"], priority: 6, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Oncology, rehabilitation, and preventive (5) ─────────────────────────
  { id: "hero_moment:hospital:oncology-positive-response-to-treatment", kind: "hero_moment", subject: "Oncologist showing patient scan comparison — tumour measurably reduced, the visual proof of treatment working, patient leaning in to compare", heroType: "authority", industryIds: ["hospital"], campaignTypeIds: ["oncology", "technology"], behaviourIds: [], tags: ["oncology", "tumour-reduction", "scan-comparison", "treatment"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:hospital:cancer-patient-final-chemotherapy", kind: "hero_moment", subject: "Cancer patient's final chemotherapy session — nurse removing last infusion line, patient and nurse exchanging a look of shared accomplishment", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["oncology", "nursing_care"], behaviourIds: [], tags: ["final-chemo", "infusion", "accomplishment", "nurse"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:hospital:health-screening-all-clear-relief", kind: "hero_moment", subject: "Executive health screening results appointment — doctor saying 'everything is clear, you're in excellent health' — relief and reassurance in equal measure", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["health_screening", "prevention"], behaviourIds: [], tags: ["health-screening", "all-clear", "excellent-health", "relief"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:hospital:rehabilitation-patient-regaining-independence", kind: "hero_moment", subject: "Rehabilitation patient completing their discharge assessment — performing tasks independently that were impossible six weeks ago, physio marking form complete", heroType: "person", industryIds: ["hospital"], campaignTypeIds: ["rehabilitation", "brand_trust"], behaviourIds: [], tags: ["rehabilitation", "independence", "discharge", "assessment"], priority: 4, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:hospital:chronic-patient-management-breakthrough", kind: "hero_moment", subject: "Chronic condition patient and specialist reviewing management plan that has finally stabilised their condition — six months of data showing control achieved", heroType: "moment", industryIds: ["hospital"], campaignTypeIds: ["specialist_referral", "brand_trust"], behaviourIds: [], tags: ["chronic-condition", "stabilised", "management", "breakthrough"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
];
