import type { RelationshipKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const HOSPITAL_RELATIONSHIPS: RelationshipKnowledgeNode[] = [
  // ── Doctor–patient trust (8) ──────────────────────────────────────────────
  { id: "relationship:hospital:patient-trusting-consultant-after-explanation", kind: "relationship", description: "Patient who came in afraid, leaving the consultation with trust — the consultant who earned it through time, clarity, and genuine listening", sceneRoles: ["patient", "consultant"], industryIds: ["hospital"], tags: ["trust", "consultant", "earned", "clarity"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "relationship:hospital:long-term-specialist-patient", kind: "relationship", description: "Long-term specialist and patient who has been under their care for years — the clinical relationship that has weathered crises, built on accumulated shared knowledge", sceneRoles: ["specialist", "long-term patient"], industryIds: ["hospital"], tags: ["long-term", "specialist", "years", "accumulated"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:hospital:newly-referred-patient-first-specialist-visit", kind: "relationship", description: "Newly referred patient at first specialist appointment — guarded, evaluating, the specialist demonstrating why the GP's confidence was well placed", sceneRoles: ["new patient", "specialist"], industryIds: ["hospital"], tags: ["first-visit", "referred", "evaluating", "earning-confidence"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:hospital:patient-who-has-lost-confidence-in-system", kind: "relationship", description: "Patient who has been through poor care elsewhere and a doctor who is rebuilding that trust — the extra patience the rebuilt relationship requires", sceneRoles: ["distrustful patient", "rebuilding doctor"], industryIds: ["hospital"], tags: ["distrust", "rebuilding", "previous-poor-care", "patience"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:hospital:gp-and-patient-ongoing-chronic-disease", kind: "relationship", description: "GP and patient managing chronic disease together over years — the primary care relationship that coordinates everything, knows the whole person", sceneRoles: ["gp", "chronic disease patient"], industryIds: ["hospital"], tags: ["gp", "chronic", "long-term", "whole-person"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:hospital:doctor-delivering-difficult-news-with-care", kind: "relationship", description: "Doctor delivering serious diagnosis and the patient receiving it — the impossible conversation handled with extraordinary human skill", sceneRoles: ["doctor", "patient receiving news"], industryIds: ["hospital"], tags: ["difficult-news", "diagnosis", "handling", "human-skill"], priority: 6, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:hospital:patient-advocate-accompanying-patient", kind: "relationship", description: "Patient advocate accompanying person with learning disability to hospital — translating, clarifying, ensuring the patient's consent is genuine and informed", sceneRoles: ["patient advocate", "patient with learning disability", "doctor"], industryIds: ["hospital"], tags: ["advocate", "learning-disability", "consent", "translating"], priority: 7, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:hospital:interpreter-patient-doctor-trilateral", kind: "relationship", description: "Medical interpreter with patient and doctor — the three-way relationship where language is no barrier to clinical safety and informed consent", sceneRoles: ["interpreter", "non-English patient", "doctor"], industryIds: ["hospital"], tags: ["interpreter", "language", "safety", "informed-consent"], priority: 8, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── Nurse–patient continuity of care (6) ──────────────────────────────────
  { id: "relationship:hospital:named-nurse-patient-continuity", kind: "relationship", description: "Named nurse with patient throughout admission — the same face each day, the relationship that distinguishes care from treatment, person from condition", sceneRoles: ["named nurse", "inpatient"], industryIds: ["hospital"], tags: ["named-nurse", "continuity", "same-face", "person-centred"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:hospital:night-nurse-vulnerable-patient-overnight", kind: "relationship", description: "Night nurse and the patient who is most frightened after dark — the special relationship of the four-hour check when fear is loudest", sceneRoles: ["night nurse", "frightened patient"], industryIds: ["hospital"], tags: ["night-nurse", "fear", "dark", "presence"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:hospital:palliative-care-nurse-patient-family", kind: "relationship", description: "Palliative care nurse with dying patient and their family — the three-way relationship that holds what medicine cannot treat, the presence that matters most", sceneRoles: ["palliative nurse", "dying patient", "family"], industryIds: ["hospital"], tags: ["palliative", "dying", "family", "presence"], priority: 3, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:hospital:nurse-specialist-cancer-patient-navigation", kind: "relationship", description: "Cancer nurse specialist navigating a patient through their treatment journey — the clinical specialist who is also the human guide through the system", sceneRoles: ["cancer nurse specialist", "oncology patient"], industryIds: ["hospital"], tags: ["cancer-nurse", "navigation", "specialist", "guide"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:hospital:icu-nurse-comatose-patient", kind: "relationship", description: "ICU nurse caring for comatose patient — speaking to them as though they can hear, repositioning with care, the care given without expectation of any response", sceneRoles: ["icu nurse", "comatose patient"], industryIds: ["hospital"], tags: ["icu-nurse", "comatose", "speaking-to", "unconditional"], priority: 5, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:hospital:community-nurse-and-housebound-patient", kind: "relationship", description: "Community nurse visiting housebound patient at home — the relationship that brings clinical care to those who cannot reach it, built across many visits", sceneRoles: ["community nurse", "housebound patient"], industryIds: ["hospital"], tags: ["community-nurse", "housebound", "home-visit", "clinical-care"], priority: 6, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Surgical team relationships (4) ──────────────────────────────────────
  { id: "relationship:hospital:surgeon-and-scrub-nurse-practiced-team", kind: "relationship", description: "Surgeon and scrub nurse who have worked together for years — the instrument passed before it is fully requested, the team that operates as one", sceneRoles: ["surgeon", "scrub nurse"], industryIds: ["hospital"], tags: ["surgeon", "scrub-nurse", "practiced", "seamless"], priority: 1, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:hospital:anaesthetist-and-surgeon-partnership", kind: "relationship", description: "Anaesthetist and surgeon — the parallel partnership of the operating theatre, each responsible for the patient from different aspects simultaneously", sceneRoles: ["anaesthetist", "surgeon"], industryIds: ["hospital"], tags: ["anaesthetist", "surgeon", "parallel", "partnership"], priority: 2, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:hospital:consultant-and-surgical-registrar-teaching", kind: "relationship", description: "Consultant and registrar working together in theatre — the teaching relationship that transfers surgical skill, supervision and progressive independence", sceneRoles: ["consultant surgeon", "registrar"], industryIds: ["hospital"], tags: ["consultant", "registrar", "teaching", "progressive-independence"], priority: 3, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:hospital:patient-and-surgical-team-pre-op-meeting", kind: "relationship", description: "Patient meeting the surgical team before going to theatre — surgeon, anaesthetist, scrub nurse all introducing themselves, the humanity before the procedure", sceneRoles: ["patient", "surgical team"], industryIds: ["hospital"], tags: ["pre-op-meeting", "team", "humanity", "introduction"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Family member and hospitalised loved one (7) ──────────────────────────
  { id: "relationship:hospital:partner-and-hospitalised-spouse", kind: "relationship", description: "Partner and hospitalised spouse — the relationship stressed and deepened by illness, visiting every day, the love that organises itself around hospital visiting times", sceneRoles: ["visiting partner", "inpatient spouse"], industryIds: ["hospital"], tags: ["partner", "spouse", "visiting", "daily"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:hospital:parent-and-hospitalised-child", kind: "relationship", description: "Parent and hospitalised child — the specific torment and fierce protectiveness of a parent whose child is unwell, refusing to leave the ward", sceneRoles: ["parent", "hospitalised child"], industryIds: ["hospital"], tags: ["parent", "child-patient", "fierce", "refusing-to-leave"], priority: 2, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "relationship:hospital:adult-child-and-elderly-hospitalised-parent", kind: "relationship", description: "Adult child caring for hospitalised elderly parent — the role reversal, the advocacy on the parent's behalf, the management of their own fear and the parent's", sceneRoles: ["adult child carer", "elderly patient-parent"], industryIds: ["hospital"], tags: ["role-reversal", "advocacy", "elderly-parent", "adult-child"], priority: 3, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:hospital:siblings-supporting-parent-in-hospital", kind: "relationship", description: "Siblings supporting each other through a parent's hospitalisation — rota of visiting, sharing information, the family system managing the crisis together", sceneRoles: ["sibling group", "hospitalised parent"], industryIds: ["hospital"], tags: ["siblings", "rota", "sharing", "family-system"], priority: 4, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:hospital:grandparent-and-grandchild-in-icu", kind: "relationship", description: "Grandparent in ICU with young grandchild permitted to visit — the child's confusion and love, the elder's recognition even through critical illness", sceneRoles: ["grandparent in ICU", "young grandchild"], industryIds: ["hospital"], tags: ["grandparent", "grandchild", "icu", "recognition"], priority: 5, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:hospital:family-and-palliative-patient-final-days", kind: "relationship", description: "Family gathering in final days of a palliative patient — the gathering of love around a person who is leaving, the conversations that matter most", sceneRoles: ["family members", "palliative patient"], industryIds: ["hospital"], tags: ["palliative", "final-days", "gathering", "love"], priority: 6, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:hospital:new-parents-and-premature-baby-neonatal", kind: "relationship", description: "New parents and their premature baby in NICU — the relationship formed through incubator glass, the love that cannot hold the person it loves yet", sceneRoles: ["new parents", "premature baby"], industryIds: ["hospital"], tags: ["new-parents", "premature", "nicu", "through-glass"], priority: 7, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },

  // ── Specialist and referring GP (4) ──────────────────────────────────────
  { id: "relationship:hospital:specialist-and-referring-gp-communication", kind: "relationship", description: "Specialist and GP in communication about shared patient — the formal letter as the bridge, the informal phone call when things get complex", sceneRoles: ["specialist", "referring gp"], industryIds: ["hospital"], tags: ["specialist", "gp", "shared-patient", "communication"], priority: 1, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "relationship:hospital:gp-patient-specialist-referral-explained", kind: "relationship", description: "GP explaining specialist referral to patient — why this person, what to expect, the bridge that prepares the patient for the next step", sceneRoles: ["gp", "patient", "referral-recipient"], industryIds: ["hospital"], tags: ["gp", "referral", "preparation", "bridge"], priority: 2, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:hospital:specialist-returning-patient-to-gp", kind: "relationship", description: "Specialist discharging patient back to GP care — clear letter, stable condition, the handover to primary care that completes the specialist episode", sceneRoles: ["specialist", "gp", "patient"], industryIds: ["hospital"], tags: ["discharge-letter", "returning", "primary-care", "stable"], priority: 3, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "relationship:hospital:second-opinion-specialist-and-original-team", kind: "relationship", description: "Second opinion specialist reviewing case with patient — the respectful engagement with the original team's management, the value of independent assessment", sceneRoles: ["second-opinion specialist", "patient"], industryIds: ["hospital"], tags: ["second-opinion", "independent", "respectful", "assessment"], priority: 4, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },

  // ── Consultant and junior doctor (4) ─────────────────────────────────────
  { id: "relationship:hospital:consultant-teaching-junior-at-bedside", kind: "relationship", description: "Consultant teaching junior doctor at patient bedside — the Socratic question, the learning that happens in the presence of the patient", sceneRoles: ["consultant", "junior doctor", "patient"], industryIds: ["hospital"], tags: ["teaching", "bedside", "socratic", "learning"], priority: 1, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "relationship:hospital:registrar-and-senior-house-officer", kind: "relationship", description: "Registrar supporting senior house officer in clinical decision — the mentoring chain, the safety net, the hierarchy that exists to protect patients and train doctors", sceneRoles: ["registrar", "senior house officer"], industryIds: ["hospital"], tags: ["registrar", "sho", "mentoring", "support"], priority: 2, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
  { id: "relationship:hospital:consultant-reviewing-junior-plan", kind: "relationship", description: "Consultant reviewing junior doctor's clinical plan — accepting some, modifying others, the collaborative refinement that shapes good medical decisions", sceneRoles: ["consultant", "junior doctor"], industryIds: ["hospital"], tags: ["reviewing-plan", "modifying", "collaborative", "refinement"], priority: 3, weight: 0.79, confidence: "high", commercialScore: 78, futureMetadata: fm },
  { id: "relationship:hospital:junior-doctor-escalating-to-consultant", kind: "relationship", description: "Junior doctor calling consultant about concern — the professional courage to escalate, the consultant's response that shapes the junior's confidence to call again", sceneRoles: ["junior doctor", "on-call consultant"], industryIds: ["hospital"], tags: ["escalating", "concern", "courage", "response"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },

  // ── Patient and physiotherapist (4) ──────────────────────────────────────
  { id: "relationship:hospital:physio-and-reluctant-patient", kind: "relationship", description: "Physiotherapist working with patient who does not believe recovery is possible — the relationship that turns reluctance into attempt", sceneRoles: ["physiotherapist", "reluctant patient"], industryIds: ["hospital"], tags: ["reluctance", "physio", "turning-point", "belief"], priority: 1, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:hospital:physio-patient-celebrating-milestone", kind: "relationship", description: "Physiotherapist and patient celebrating rehabilitation milestone together — the shared achievement, the relationship that has fought for this moment", sceneRoles: ["physiotherapist", "patient"], industryIds: ["hospital"], tags: ["milestone", "celebrating", "shared", "fought-for"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:hospital:daily-physio-relationship-inpatient", kind: "relationship", description: "Daily physio sessions with same patient over weeks — the rehabilitation relationship that accumulates trust through repeated honest work", sceneRoles: ["physiotherapist", "long-stay patient"], industryIds: ["hospital"], tags: ["daily", "accumulated", "repeated", "honest-work"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:hospital:patient-and-physio-planning-discharge-targets", kind: "relationship", description: "Patient and physiotherapist setting targets for discharge together — the collaborative goal-setting that makes rehabilitation purposeful and measurable", sceneRoles: ["patient", "physiotherapist"], industryIds: ["hospital"], tags: ["targets", "discharge", "collaborative", "goal-setting"], priority: 4, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Oncology (3) ─────────────────────────────────────────────────────────
  { id: "relationship:hospital:oncologist-patient-months-of-treatment", kind: "relationship", description: "Oncologist and cancer patient through months of treatment — the relationship that sees them at their worst and celebrates their response to treatment", sceneRoles: ["oncologist", "cancer patient"], industryIds: ["hospital"], tags: ["oncologist", "months", "worst-and-best", "celebration"], priority: 1, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "relationship:hospital:chemotherapy-nurse-and-regular-patient", kind: "relationship", description: "Chemotherapy day unit nurse and regular patient — the fortnightly relationship that provides consistency through the disorientation of cancer treatment", sceneRoles: ["chemotherapy nurse", "regular patient"], industryIds: ["hospital"], tags: ["chemo-nurse", "fortnightly", "regular", "consistency"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:hospital:patient-and-peer-support-cancer", kind: "relationship", description: "Cancer patient and peer supporter who has completed the same treatment — the lived experience relationship that clinical care cannot replicate", sceneRoles: ["cancer patient", "peer supporter"], industryIds: ["hospital"], tags: ["peer-support", "lived-experience", "cancer", "unreplicable"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Midwife and labouring mother (3) ─────────────────────────────────────
  { id: "relationship:hospital:midwife-and-labouring-mother-trust", kind: "relationship", description: "Midwife and labouring mother — the relationship built in hours of the most intense physical experience, trust earned breath by breath through transition", sceneRoles: ["midwife", "labouring mother"], industryIds: ["hospital"], tags: ["midwife", "labour", "trust", "breath-by-breath"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "relationship:hospital:continuity-of-midwife-known-before-birth", kind: "relationship", description: "Continuity of care midwife who has seen the mother throughout pregnancy and is present at birth — the known face at the hardest moment", sceneRoles: ["continuity midwife", "mother"], industryIds: ["hospital"], tags: ["continuity", "known-face", "throughout", "hardest-moment"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:hospital:midwife-supporting-birth-partner-too", kind: "relationship", description: "Midwife supporting both mother and birth partner during labour — the partner also needs guidance, the midwife managing two people's fear and effort simultaneously", sceneRoles: ["midwife", "labouring mother", "birth partner"], industryIds: ["hospital"], tags: ["birth-partner", "dual-support", "guidance", "managing"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Paramedic and emergency patient (2) ──────────────────────────────────
  { id: "relationship:hospital:paramedic-patient-first-contact", kind: "relationship", description: "Paramedic and emergency patient — the first clinical relationship, often beginning with the patient unable to speak, the paramedic reading what the body says", sceneRoles: ["paramedic", "emergency patient"], industryIds: ["hospital"], tags: ["first-contact", "paramedic", "non-verbal", "reading-body"], priority: 1, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:hospital:cardiac-arrest-patient-aftermath", kind: "relationship", description: "Paramedic and patient who survived cardiac arrest — the brief connection after successful resuscitation, the patient beginning to understand what just happened", sceneRoles: ["paramedic", "resuscitated patient"], industryIds: ["hospital"], tags: ["cardiac-arrest", "survived", "brief-connection", "realisation"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Patient support group (2) ────────────────────────────────────────────
  { id: "relationship:hospital:patient-support-group-shared-condition", kind: "relationship", description: "Patient support group for specific condition — people who understand each other without explanation, the peer community that medicine recognises as essential", sceneRoles: ["patient group members"], industryIds: ["hospital"], tags: ["support-group", "shared-condition", "peer-community", "understanding"], priority: 1, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },
  { id: "relationship:hospital:online-patient-community-hospital-facilitated", kind: "relationship", description: "Online patient community facilitated by the hospital — people connecting between appointments, the hospital extending its care into the spaces between visits", sceneRoles: ["patient community members", "hospital facilitator"], industryIds: ["hospital"], tags: ["online-community", "between-appointments", "extending-care", "connecting"], priority: 2, weight: 0.80, confidence: "high", commercialScore: 79, futureMetadata: fm },
];
