import type { UniversalPrompt } from "../schema";
import type { CreativeBrief } from "../creative-director";
import type { IndustryProfile, PromptRichnessTier } from "./types";

export interface MarketingEnrichment {
  style: Pick<UniversalPrompt["style"], "mood" | "aesthetic" | "luxuryLevel" | "modernLevel" | "minimalism">;
  typography: Pick<UniversalPrompt["typography"], "treatment" | "fontStyle">;
  marketing: { psychologyHooks: string[] } & Pick<UniversalPrompt["marketing"], "goal" | "targetAudience">;
}

// Reads the Creative Director's already-reasoned strategy (echoed onto the
// prompt by builder.ts) — never re-infers marketingObjective/targetAudience/
// brandPersonality from scratch, since that duplicates buildCreativeBrief().
export function buildMarketingEnrichment(
  prompt: UniversalPrompt,
  profile: IndustryProfile,
  tier: PromptRichnessTier
): MarketingEnrichment {
  const brief = prompt.creativeBrief as CreativeBrief | undefined;
  const richTier = tier === "luxury" || tier === "cinematic";
  const marketingTier = tier !== "simple";

  const mood = [prompt.style.mood, brief?.visualStrategy?.emotionalDirection].filter(Boolean).join(", ") || "confident and emotionally engaging";

  const aesthetic = [
    prompt.style.aesthetic || (richTier ? "premium luxury advertising aesthetic" : "modern commercial advertising aesthetic"),
    brief?.brandPersonality,
    prompt.branding.brandVoice,
  ]
    .filter(Boolean)
    .join(" — ");

  const luxuryLevel = prompt.style.luxuryLevel || brief?.visualStrategy?.luxuryLevel || (richTier ? "high" : "moderate");
  const modernLevel = prompt.style.modernLevel || brief?.visualStrategy?.realismLevel || "contemporary";
  const minimalism = prompt.style.minimalism || brief?.visualStrategy?.minimalismLevel || "balanced";

  const treatment = [
    prompt.typography.treatment || brief?.typographyStrategy,
    "premium typography placed in clean, brand-safe areas",
  ]
    .filter(Boolean)
    .join(", ");
  const fontStyle = prompt.typography.fontStyle || "a clean, modern commercial typeface";

  // Creative Director 2.0 — primaryMessage and valueProposition (Step 1)
  const goal = [prompt.marketing.goal, brief?.marketingObjective, brief?.messagingStrategy?.primaryMessage, brief?.valueProposition]
    .filter(Boolean)
    .join(" — ") || "maximum attention and engagement";

  const targetAudience = prompt.marketing.targetAudience || brief?.targetAudience || "the brand's core audience";

  const psychologyHooks = Array.from(
    new Set(
      [
        ...(prompt.marketing.psychologyHooks ?? []),
        ...(brief?.messagingStrategy?.trustSignals ?? []),
        brief?.messagingStrategy?.secondaryMessage,
        brief?.attentionHook,
        // Step 9 — Scroll-Stopping Strategy
        brief?.scrollStoppingStrategy,
        brief?.callToAction ? `clear call-to-action: ${brief.callToAction}` : undefined,
        // Image Quality Stabilization — copywriting section: actual marketing
        // text generated by the Director flows into the psychology/marketing
        // section of the provider prompt alongside the strategic hooks above.
        ...(brief?.copywriting?.benefitTitles ?? []),
        ...(brief?.copywriting?.trustStatements ?? []),
        brief?.copywriting?.badgeText,
        ...profile.trustElements,
        marketingTier ? "designed to encourage shares and saves" : undefined,
      ].filter((v): v is string => Boolean(v))
    )
  );

  return {
    style: { mood, aesthetic, luxuryLevel, modernLevel, minimalism },
    typography: { treatment, fontStyle },
    marketing: { goal, targetAudience, psychologyHooks },
  };
}
