// Phase 10.4.0 — Industry knowledge registry.
// Each industry exports: HERO_MOMENTS, CAMPAIGN_TYPES, ROUTES arrays.
// All arrays are empty in Phase 10.4.0 — populated in Phase 10.4.1.
//
// To add a new industry:
//   1. Create industries/{name}/index.ts following the restaurant scaffold
//   2. Add its exports below
//   3. Register nodes via store.registerAll() in the InMemoryKnowledgeStore initialiser
//
// Industries:
//   restaurant  — 8 campaign types, 8 hero moments (Phase 10.4.1)
//   dental      — Phase 10.4.2
//   real_estate — Phase 10.4.2
//   jewellery   — Phase 10.4.2
//   fitness     — Phase 10.4.2
//   beauty      — Phase 10.4.2
//   education   — Phase 10.4.2
//   automotive  — Phase 10.4.3
//   healthcare  — Phase 10.4.3
//   finance     — Phase 10.4.3
//   events      — Phase 10.4.3
//   retail      — Phase 10.4.3
//   technology  — Phase 10.4.3
//   generic     — Phase 10.4.1 (cross-industry fallback nodes)

export {
  RESTAURANT_HERO_MOMENTS,
  RESTAURANT_SCENE_TYPES,
  RESTAURANT_BEHAVIOURS,
  RESTAURANT_RELATIONSHIPS,
  RESTAURANT_EMOTIONAL_MOMENTS,
  RESTAURANT_COMMERCIAL_SITUATIONS,
  RESTAURANT_CAMPAIGN_TYPES,
  RESTAURANT_ROUTES,
} from "./restaurant/index";

export {
  DENTAL_HERO_MOMENTS,
  DENTAL_SCENE_TYPES,
  DENTAL_BEHAVIOURS,
  DENTAL_RELATIONSHIPS,
  DENTAL_EMOTIONAL_MOMENTS,
  DENTAL_COMMERCIAL_SITUATIONS,
  DENTAL_CAMPAIGN_TYPES,
  DENTAL_ROUTES,
} from "./dental/index";

export {
  SALON_HERO_MOMENTS,
  SALON_SCENE_TYPES,
  SALON_BEHAVIOURS,
  SALON_RELATIONSHIPS,
  SALON_EMOTIONAL_MOMENTS,
  SALON_COMMERCIAL_SITUATIONS,
  SALON_CAMPAIGN_TYPES,
  SALON_ROUTES,
} from "./salon/index";

export {
  JEWELLERY_HERO_MOMENTS,
  JEWELLERY_SCENE_TYPES,
  JEWELLERY_BEHAVIOURS,
  JEWELLERY_RELATIONSHIPS,
  JEWELLERY_EMOTIONAL_MOMENTS,
  JEWELLERY_COMMERCIAL_SITUATIONS,
  JEWELLERY_CAMPAIGN_TYPES,
  JEWELLERY_ROUTES,
} from "./jewellery/index";

export {
  FURNITURE_HERO_MOMENTS,
  FURNITURE_SCENE_TYPES,
  FURNITURE_BEHAVIOURS,
  FURNITURE_RELATIONSHIPS,
  FURNITURE_EMOTIONAL_MOMENTS,
  FURNITURE_COMMERCIAL_SITUATIONS,
  FURNITURE_CAMPAIGN_TYPES,
  FURNITURE_ROUTES,
} from "./furniture/index";

export {
  HOSPITAL_HERO_MOMENTS,
  HOSPITAL_SCENE_TYPES,
  HOSPITAL_BEHAVIOURS,
  HOSPITAL_RELATIONSHIPS,
  HOSPITAL_EMOTIONAL_MOMENTS,
  HOSPITAL_COMMERCIAL_SITUATIONS,
  HOSPITAL_CAMPAIGN_TYPES,
  HOSPITAL_ROUTES,
} from "./hospital/index";

export {
  REAL_ESTATE_HERO_MOMENTS,
  REAL_ESTATE_SCENE_TYPES,
  REAL_ESTATE_BEHAVIOURS,
  REAL_ESTATE_RELATIONSHIPS,
  REAL_ESTATE_EMOTIONAL_MOMENTS,
  REAL_ESTATE_COMMERCIAL_SITUATIONS,
  REAL_ESTATE_CAMPAIGN_TYPES,
  REAL_ESTATE_ROUTES,
} from "./real-estate/index";

export {
  SCHOOL_HERO_MOMENTS,
  SCHOOL_SCENE_TYPES,
  SCHOOL_BEHAVIOURS,
  SCHOOL_RELATIONSHIPS,
  SCHOOL_EMOTIONAL_MOMENTS,
  SCHOOL_COMMERCIAL_SITUATIONS,
  SCHOOL_CAMPAIGN_TYPES,
  SCHOOL_ROUTES,
} from "./school/index";

export {
  RETAIL_HERO_MOMENTS,
  RETAIL_SCENE_TYPES,
  RETAIL_BEHAVIOURS,
  RETAIL_RELATIONSHIPS,
  RETAIL_EMOTIONAL_MOMENTS,
  RETAIL_COMMERCIAL_SITUATIONS,
  RETAIL_CAMPAIGN_TYPES,
  RETAIL_ROUTES,
} from "./retail/index";

export {
  INTERIOR_DESIGN_HERO_MOMENTS,
  INTERIOR_DESIGN_SCENE_TYPES,
  INTERIOR_DESIGN_BEHAVIOURS,
  INTERIOR_DESIGN_RELATIONSHIPS,
  INTERIOR_DESIGN_EMOTIONAL_MOMENTS,
  INTERIOR_DESIGN_COMMERCIAL_SITUATIONS,
  INTERIOR_DESIGN_CAMPAIGN_TYPES,
  INTERIOR_DESIGN_ROUTES,
} from "./interior-design/index";

export {
  GENERIC_HERO_MOMENTS,
  GENERIC_SCENE_TYPES,
  GENERIC_BEHAVIOURS,
  GENERIC_RELATIONSHIPS,
  GENERIC_EMOTIONAL_MOMENTS,
  GENERIC_COMMERCIAL_SITUATIONS,
  GENERIC_CAMPAIGN_TYPES,
  GENERIC_ROUTES,
} from "./generic/index";
