export { evaluateImage } from "./engine";
export type {
  ImageCriticInput,
  ImageEvaluationReport,
  EvaluationField,
  EvaluationScore,
  EvaluationConfidence,
  EvaluationSource,
  HeroEvaluation,
  CompositionEvaluation,
  LightingEvaluation,
  MarketingEvaluation,
  BrandingEvaluation,
  RealismEvaluation,
  ArtifactEvaluation,
  TypographySafeAreaEvaluation,
  QualityScores,
  Recommendation,
  RecommendationPriority,
  RecommendationCategory,
  EvaluationMethod,
} from "./types";
