import type { BehaviourKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const INTERIOR_DESIGN_BEHAVIOURS: BehaviourKnowledgeNode[] = [
  // ── In consultation (20) ───────────────────────────────────────────────────────
  { id: "behaviour:interior_design:client-explaining-vision-with-hands", kind: "behaviour", description: "A client explaining their vision using their hands to gesture the proportions, the layout, the feeling they want — the physical gesture filling in what words alone cannot convey", emotionalSignal: "creative investment and communicative effort", compatibleHeroes: ["person", "moment"], industryIds: ["interior"], tags: ["consultation", "gesturing", "vision", "communicating"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:interior_design:opening-a-sample-book-together", kind: "behaviour", description: "A designer and client opening a large fabric or wallpaper sample book together — the pages turned slowly, each sample considered briefly, the conversation held at a quiet register that matches the looking", emotionalSignal: "collaborative deliberation", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["sample-book", "fabric", "together", "deliberating"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:interior_design:holding-swatch-to-wall", kind: "behaviour", description: "Holding a fabric swatch or paint chip to an existing wall in the client's home — the arm extended, the swatch flat against the surface, the comparison between the proposed material and the existing context", emotionalSignal: "practical imagination — visualising the unrealised", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["swatch", "wall", "holding", "comparison"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "behaviour:interior_design:sketching-quick-idea-on-notepad", kind: "behaviour", description: "A designer sketching a quick layout or furniture arrangement idea on a notepad during consultation — the hand moving fast, the sketch imprecise but immediately communicative to the client watching it form", emotionalSignal: "generative confidence — idea formation in real time", compatibleHeroes: ["person", "moment"], industryIds: ["interior"], tags: ["sketch", "notepad", "quick", "generative"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:interior_design:client-pointing-at-reference-image", kind: "behaviour", description: "A client pointing at a reference image — on a phone, a magazine, a printed page — the pointing specific, zooming in on a detail: 'this — this thing right here is what I want'", emotionalSignal: "specific desire clearly identified", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["reference-image", "pointing", "specific", "desire"], priority: 1, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:interior_design:writing-detailed-brief-notes", kind: "behaviour", description: "A designer writing detailed notes during a client brief — every preference noted, nothing assumed, the notepad or tablet filling with the specifics that will govern the project for months", emotionalSignal: "professional attentiveness and respect for client's vision", compatibleHeroes: ["person", "moment"], industryIds: ["interior"], tags: ["brief", "notes", "detailed", "attentive"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:interior_design:reviewing-floor-plan-on-table", kind: "behaviour", description: "Designer and client reviewing a floor plan laid flat on a table — both leaning in, fingers moving across the plan, the rooms understood in their abstracted form as they plan the furniture placement", emotionalSignal: "spatial imagination made social", compatibleHeroes: ["person", "moment"], industryIds: ["interior"], tags: ["floor-plan", "reviewing", "table", "spatial"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:interior_design:presenting-mood-board-with-care", kind: "behaviour", description: "A designer presenting a mood board to a client — holding it up or propping it, explaining the reasoning behind each element, watching the client's face for the response that words might not immediately give", emotionalSignal: "creative vulnerability and professional investment", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["mood-board", "presenting", "reasoning", "watching-face"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "behaviour:interior_design:client-immediately-responding-to-render", kind: "behaviour", description: "A client seeing a 3D render for the first time and responding before they have thought about their response — a lean forward, a sharp intake of breath, a spontaneous 'oh' of recognition", emotionalSignal: "immediate visceral response to visualised future", compatibleHeroes: ["person", "moment"], industryIds: ["interior"], tags: ["render", "immediate-response", "lean-forward", "visceral"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "behaviour:interior_design:running-finger-along-material-sample", kind: "behaviour", description: "Running a finger along the surface of a material sample — feeling the texture of the stone, the weave of the fabric, the grain of the wood — the tactile assessment that precedes or confirms the visual decision", emotionalSignal: "sensory investigation and material judgement", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["material", "touching", "texture", "tactile"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },

  // ── In the space (25) ─────────────────────────────────────────────────────────
  { id: "behaviour:interior_design:standing-in-empty-room-imagining", kind: "behaviour", description: "A designer standing in an empty client property, still, looking at the space from different angles — the quiet of the professional who is seeing what will be there rather than what currently is", emotionalSignal: "spatial vision and professional imagination", compatibleHeroes: ["person", "environment", "moment"], industryIds: ["interior"], tags: ["empty-room", "standing", "imagining", "still"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:interior_design:measuring-room-with-tape", kind: "behaviour", description: "Measuring a room methodically with a tape measure — the dimension called and recorded, the tape extended corner to corner, the physical survey that grounds every subsequent design decision in reality", emotionalSignal: "methodical professional groundwork", compatibleHeroes: ["person", "environment"], industryIds: ["interior"], tags: ["measuring", "tape", "methodical", "surveying"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:interior_design:moving-furniture-in-space", kind: "behaviour", description: "Physically moving or rearranging furniture in the space — the designer and client or contractor trying a sofa in different positions until the arrangement clicks, the spatial decision made through movement rather than plan", emotionalSignal: "physical problem-solving and spatial intuition", compatibleHeroes: ["person", "environment", "moment"], industryIds: ["interior"], tags: ["furniture", "rearranging", "trying", "physical"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:interior_design:placing-decorative-object-precisely", kind: "behaviour", description: "Placing a decorative object — a vase, a lamp, a sculptural piece — and adjusting it a centimetre left, a centimetre forward, stepping back to look, adjusting again, the precision of the trained eye", emotionalSignal: "aesthetic perfectionism — the eye that knows when it is right", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["decorative-object", "placing", "adjusting", "precision"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:interior_design:looking-at-light-at-different-hours", kind: "behaviour", description: "Observing how natural light moves through a room at different times of day — the designer noting where the morning light falls, how the south window performs at noon, where shadow appears at dusk", emotionalSignal: "the long patience of designing for time as well as space", compatibleHeroes: ["person", "environment"], industryIds: ["interior"], tags: ["natural-light", "observing", "hours", "shadow"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:interior_design:unwrapping-delivered-furniture", kind: "behaviour", description: "Unwrapping a delivered piece of furniture in situ — the protective blankets removed, the packaging cut away, the piece revealed in the room for which it was chosen, the first assessment of whether it performs as expected", emotionalSignal: "anticipatory appraisal — vision meets reality", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["delivery", "unwrapping", "revealing", "appraisal"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:interior_design:checking-paint-colour-in-natural-light", kind: "behaviour", description: "Checking a freshly painted wall in natural light — the painted sample or the new room colour assessed at the window, the designer comparing the actual dried colour against the chip that was approved weeks before", emotionalSignal: "colour accuracy anxiety and professional verification", compatibleHeroes: ["person", "environment", "moment"], industryIds: ["interior"], tags: ["paint", "natural-light", "checking", "accuracy"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:interior_design:adjusting-lighting-levels", kind: "behaviour", description: "Adjusting dimmer levels in a newly installed lighting scheme — trying each circuit at different percentages, combining them, the designer finding the right combination for the specific mood and time of day", emotionalSignal: "the fine-tuning of atmosphere — precision in the immaterial", compatibleHeroes: ["person", "environment", "moment"], industryIds: ["interior"], tags: ["lighting", "dimmer", "adjusting", "atmosphere"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:interior_design:standing-back-from-complete-room", kind: "behaviour", description: "Standing at the doorway of a completed room and looking at it whole — the designer's final assessment before the client arrives, the composed stillness of someone making a last professional judgement", emotionalSignal: "professional completion and composed self-assessment", compatibleHeroes: ["person", "environment", "moment"], industryIds: ["interior"], tags: ["doorway", "looking", "complete", "assessment"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "behaviour:interior_design:photographing-completed-room", kind: "behaviour", description: "Photographing a completed room — adjusting cushions and styling details for the camera, the designer both the producer of the space and its first documentarian, capturing it at its designed best before it is lived in", emotionalSignal: "the pride of authorship and the discipline of documentation", compatibleHeroes: ["person", "environment", "moment"], industryIds: ["interior"], tags: ["photographing", "styling", "documentation", "authorship"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Design craft (20) ─────────────────────────────────────────────────────────
  { id: "behaviour:interior_design:building-mood-board", kind: "behaviour", description: "Building a mood board — cutting and pinning, dragging and arranging, the physical or digital collage assembling the aesthetic vision of a project from its reference materials", emotionalSignal: "creative synthesis — making the vision visible to others", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["mood-board", "building", "collage", "vision"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:interior_design:hand-drawing-interior-sketch", kind: "behaviour", description: "Drawing an interior perspective sketch by hand — the line flowing from the horizon point, the room taking shape in pencil, the analogue skill that sees in three dimensions before the 3D software confirms it", emotionalSignal: "craft confidence — the skilled hand making the invisible visible", compatibleHeroes: ["person", "product"], industryIds: ["interior"], tags: ["hand-drawing", "sketch", "perspective", "analogue"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:interior_design:selecting-from-material-library", kind: "behaviour", description: "Selecting materials from a library wall — pulling samples, comparing them together, making groupings that cohere, returning some and keeping others as a palette develops around the designer's hands", emotionalSignal: "the curatorial eye — editing toward a specific language", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["material-library", "selecting", "comparing", "palette"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:interior_design:comparing-paint-chips-together", kind: "behaviour", description: "Comparing paint chips held together — two or three neutrals assessed side by side, the differences between them only apparent in comparison, the eye making distinctions the label cannot describe", emotionalSignal: "the discernment of subtle colour distinction", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["paint-chips", "comparing", "subtle", "neutral"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:interior_design:working-in-design-software", kind: "behaviour", description: "Working in interior design software — a floor plan open, furniture blocks being dragged into position, elevations generated from the plan, the digital craft that translates spatial thinking into communicable drawings", emotionalSignal: "technical craft combined with spatial intelligence", compatibleHeroes: ["person", "moment"], industryIds: ["interior"], tags: ["design-software", "floor-plan", "digital", "technical"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:interior_design:sourcing-from-trade-showroom", kind: "behaviour", description: "A designer moving through a trade showroom — photographing pieces, checking dimensions on a phone, pulling brochures, the professional procurement visit that builds the specification for a client project", emotionalSignal: "purposeful professional acquisition — curating on behalf of another", compatibleHeroes: ["person", "environment", "moment"], industryIds: ["interior"], tags: ["showroom", "trade", "sourcing", "procurement"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:interior_design:reviewing-supplier-invoice", kind: "behaviour", description: "Reviewing a supplier specification sheet or invoice — checking dimensions, lead times, finishes and pricing, the administrative precision that supports the creative vision in practice", emotionalSignal: "professional responsibility — the unglamorous rigour behind the design", compatibleHeroes: ["person", "moment"], industryIds: ["interior"], tags: ["specification", "invoice", "lead-time", "rigour"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "behaviour:interior_design:making-scale-model", kind: "behaviour", description: "Making a scale model of a room or building — cutting the card walls, gluing the floor, placing tiny furniture, the analogue three-dimensional communication tool that clients respond to differently from any drawing", emotionalSignal: "patient craft in service of communication — making the spatial tangible", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["scale-model", "card", "analogue", "communication"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Emotional peak moments (20) ───────────────────────────────────────────────
  { id: "behaviour:interior_design:client-first-view-of-completed-home", kind: "behaviour", description: "A client seeing their completed home for the first time — the designer opening the door, the client stepping through and stopping, the room that was described and planned and specified for months now exactly as it was imagined", emotionalSignal: "the peak experience of interior design — vision made real", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["interior"], tags: ["first-view", "completed", "stopping", "peak"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "behaviour:interior_design:touching-surface-of-new-kitchen", kind: "behaviour", description: "Running a hand across the worktop surface of a newly installed kitchen — the material exactly as specified, smooth and solid, the quality confirmed by touch as much as sight", emotionalSignal: "sensory confirmation of investment realised", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["worktop", "touching", "new-kitchen", "confirming"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:interior_design:client-showing-finished-room-to-guest", kind: "behaviour", description: "A client showing a finished room to a friend or family member — the slightly theatrical quality of the reveal, the client now the presenter of the space that was designed for them", emotionalSignal: "pride of ownership in the designed space — the client as curator", compatibleHeroes: ["person", "environment", "moment"], industryIds: ["interior"], tags: ["showing-guest", "theatrical", "pride", "reveal"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:interior_design:sitting-for-first-time-in-new-space", kind: "behaviour", description: "Sitting down for the first time in a newly designed space — the furniture that was a specification now a physical thing being sat on, the sofa or chair carrying the client's weight and proving its quality", emotionalSignal: "physical embodiment of the designed space — testing the lived reality", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["sitting", "first-time", "new-space", "physical"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:interior_design:designer-reviewing-portfolio-photograph", kind: "behaviour", description: "A designer reviewing the final portfolio photographs of a completed project — scrolling or paging through, the work that will define the studio in future pitches captured here, the professional satisfaction of documented quality", emotionalSignal: "professional pride and the permanence of documented achievement", compatibleHeroes: ["person", "moment"], industryIds: ["interior"], tags: ["portfolio", "photograph", "reviewing", "pride"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:interior_design:sharing-finished-project-on-instagram", kind: "behaviour", description: "A client sharing photographs of their finished home on social media — the home that was private labour now presented publicly, the personal pride in the designed environment made available for others", emotionalSignal: "the public pride of sharing the private — design as social expression", compatibleHeroes: ["person", "environment", "moment"], industryIds: ["interior"], tags: ["social-media", "sharing", "finished", "public-pride"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:interior_design:waking-in-newly-designed-bedroom", kind: "behaviour", description: "Waking up in the newly designed bedroom — the morning light falling in the calculated direction, the space exactly as intended, the daily experience of the room's quality beginning", emotionalSignal: "the quiet daily pleasure of well-designed habitation", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["interior"], tags: ["waking", "bedroom", "morning-light", "daily-pleasure"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:interior_design:hosting-in-newly-completed-space", kind: "behaviour", description: "Hosting friends for the first time in the newly completed living room or dining room — the designed space serving its social function, the conversation flowing in an environment created specifically for it", emotionalSignal: "the fulfilment of domestic design — the room performing as intended socially", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["interior"], tags: ["hosting", "first-time", "social-function", "performing"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "behaviour:interior_design:child-entering-redesigned-bedroom", kind: "behaviour", description: "A child entering their redesigned bedroom for the first time — the immediate move to explore, to touch, to sit on the bed and look around, the room that was made for them immediately recognised as theirs", emotionalSignal: "the pure and immediate recognition of a space made just for you", compatibleHeroes: ["person", "environment", "moment"], industryIds: ["interior"], tags: ["child", "bedroom", "first-time", "recognition"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:interior_design:designer-and-client-handshake-completion", kind: "behaviour", description: "The designer and client handshake or embrace at project completion — the professional relationship that has navigated months of decisions and logistics arriving at the moment the project is handed over, complete", emotionalSignal: "the relational completion of a professional creative collaboration", compatibleHeroes: ["person", "moment"], industryIds: ["interior"], tags: ["handshake", "completion", "relational", "handing-over"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:interior_design:before-to-after-revelation", kind: "behaviour", description: "Showing a client the before and after photographs side by side — the original state of the room and its designed transformation, the distance travelled in the project made visible in a single comparison", emotionalSignal: "the validated transformation — before made meaningful by after", compatibleHeroes: ["person", "moment", "environment"], industryIds: ["interior"], tags: ["before-after", "photographs", "transformation", "comparison"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "behaviour:interior_design:receiving-project-on-design-website", kind: "behaviour", description: "A completed project appearing on a design publication or awards website — the designer notified, the public recognition of the studio's work arriving through a screen in the office", emotionalSignal: "professional recognition and the public legitimisation of creative work", compatibleHeroes: ["person", "moment"], industryIds: ["interior"], tags: ["publication", "awards", "recognition", "public"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "behaviour:interior_design:walking-through-renovated-home", kind: "behaviour", description: "A couple walking through their renovated home together — room by room, the project reviewed as a whole for the first time, the investment and disruption resolved into the liveable designed space", emotionalSignal: "shared relief and satisfaction — the disruption justified by the result", compatibleHeroes: ["person", "environment", "lifestyle"], industryIds: ["interior"], tags: ["couple", "walking-through", "room-by-room", "satisfaction"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:interior_design:buying-investment-furniture-piece", kind: "behaviour", description: "Purchasing a significant furniture investment — the sofa, the dining table, the bed frame — the decision made with a quality and longevity calculation that is different from any other retail purchase", emotionalSignal: "the serious commitment of an investment purchase — deliberate and lasting", compatibleHeroes: ["person", "product", "moment"], industryIds: ["interior"], tags: ["investment", "furniture", "deliberate", "lasting"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:interior_design:reading-in-designed-corner", kind: "behaviour", description: "Reading in a designed reading corner — the chair that was specified for exactly this use, the light at exactly the right angle, the space performing the function it was made for with daily invisible precision", emotionalSignal: "the quiet everyday proof of good design — purpose perfectly served", compatibleHeroes: ["lifestyle", "person", "environment"], industryIds: ["interior"], tags: ["reading", "corner", "daily", "purpose-served"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
];
