import type { HeroMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const INTERIOR_DESIGN_HERO_MOMENTS: HeroMomentKnowledgeNode[] = [
  // ── Room transformation reveal — before and after (15) ─────────────────────
  { id: "hero_moment:interior_design:client-sees-finished-room-first-time", kind: "hero_moment", subject: "Client entering finished room for the very first time — hands going to face, standing still, the silence before the reaction arrives", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["reveal", "before_after"], behaviourIds: [], tags: ["reveal", "first-look", "silence", "reaction"], priority: 1, weight: 0.97, confidence: "high", commercialScore: 96, futureMetadata: fm },
  { id: "hero_moment:interior_design:before-after-living-room-reveal", kind: "hero_moment", subject: "Living room before-and-after reveal — the side-by-side of bare walls and the finished layered space, the transformation made undeniable by comparison", heroType: "transformation", industryIds: ["interior"], campaignTypeIds: ["before_after", "reveal"], behaviourIds: [], tags: ["before-after", "living-room", "transformation", "comparison"], priority: 2, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:interior_design:couple-reveals-reaction-stepping-into-room", kind: "hero_moment", subject: "Couple stepping into finished room together — one sees it first, grabs the other's arm, then both standing in the space they could not imagine from the mood board", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["reveal", "before_after"], behaviourIds: [], tags: ["couple", "reveal", "stepping-in", "imagined"], priority: 3, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:interior_design:empty-apartment-transformed-into-home", kind: "hero_moment", subject: "Empty new-build apartment transformed into a fully realised home — the developer's blank canvas becoming a person's sanctuary", heroType: "transformation", industryIds: ["interior"], campaignTypeIds: ["before_after", "new_home"], behaviourIds: [], tags: ["new-build", "transformation", "sanctuary", "blank-canvas"], priority: 4, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:interior_design:victorian-terrace-stripped-back-then-completed", kind: "hero_moment", subject: "Victorian terrace taken back to brick then completed — the reveal of how original character and contemporary design can coexist in one room", heroType: "transformation", industryIds: ["interior"], campaignTypeIds: ["before_after", "renovation"], behaviourIds: [], tags: ["victorian", "stripped-back", "contemporary", "character"], priority: 5, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:interior_design:before-after-photos-side-by-side", kind: "hero_moment", subject: "Before-and-after photography presented side by side — same angle, same light, the precise comparison that makes the designer's work undeniable", heroType: "product", industryIds: ["interior"], campaignTypeIds: ["before_after", "brand_awareness"], behaviourIds: [], tags: ["photography", "same-angle", "precise", "designer-work"], priority: 6, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "hero_moment:interior_design:unused-spare-room-becomes-home-office", kind: "hero_moment", subject: "Unused spare room transformed into considered home office — the junk room that became a productive beautiful space, the function created where none existed", heroType: "transformation", industryIds: ["interior"], campaignTypeIds: ["renovation", "before_after"], behaviourIds: [], tags: ["spare-room", "home-office", "function", "considered"], priority: 7, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:open-plan-knock-through-reveal", kind: "hero_moment", subject: "Wall knocked through to reveal open-plan kitchen-diner — the moment the space doubles, the two rooms becoming one generous flowing space", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["renovation", "before_after"], behaviourIds: [], tags: ["knock-through", "open-plan", "space-doubles", "flowing"], priority: 8, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:interior_design:dark-corridor-transformation-light-filled", kind: "hero_moment", subject: "Dark narrow corridor transformed into a light-filled entrance — mirror, glass, considered lighting, the worst space in the house made remarkable", heroType: "transformation", industryIds: ["interior"], campaignTypeIds: ["renovation", "before_after"], behaviourIds: [], tags: ["corridor", "light", "mirror", "entrance"], priority: 7, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "hero_moment:interior_design:dated-bedroom-luxury-reveal", kind: "hero_moment", subject: "Dated 1990s bedroom transformed into a luxury hotel-standard suite — the personal space elevated beyond what the owners thought their house could contain", heroType: "transformation", industryIds: ["interior"], campaignTypeIds: ["reveal", "before_after"], behaviourIds: [], tags: ["bedroom", "hotel-standard", "luxury", "dated-to-elevated"], priority: 6, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:interior_design:show-house-fully-dressed-photographer-arrives", kind: "hero_moment", subject: "Show house fully dressed and photographer arriving — every surface considered, every accessory placed, the complete styling of a house to sell the dream", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["show_home", "developer"], behaviourIds: [], tags: ["show-house", "fully-dressed", "photographer", "dream"], priority: 5, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:interior_design:property-listing-before-after-shoot", kind: "hero_moment", subject: "Property listing photography before and after interior styling — the estate agent's photos transformed by a stylist, the difference in appeal immediately visible", heroType: "product", industryIds: ["interior"], campaignTypeIds: ["before_after", "show_home"], behaviourIds: [], tags: ["listing", "photography", "styling", "appeal"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:dining-room-reveal-table-laid", kind: "hero_moment", subject: "Dining room reveal with table fully laid — clients seeing the room they will eat in for decades, with the table as the centrepiece they chose together", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["reveal", "before_after"], behaviourIds: [], tags: ["dining-room", "table-laid", "centrepiece", "decades"], priority: 5, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:hallway-reveal-first-impression-delivered", kind: "hero_moment", subject: "Hallway reveal — the first impression of a home finally matching the warmth and personality of the people who live inside it", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["reveal", "renovation"], behaviourIds: [], tags: ["hallway", "first-impression", "warmth", "personality"], priority: 6, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "hero_moment:interior_design:studio-apartment-maximised-reveal", kind: "hero_moment", subject: "Small studio apartment fully maximised reveal — every square foot used intelligently, the constraint producing a space of ingenuity and character", heroType: "transformation", industryIds: ["interior"], campaignTypeIds: ["reveal", "renovation"], behaviourIds: [], tags: ["studio", "maximised", "constraint", "ingenuity"], priority: 7, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Client seeing finished room for first time (10) ────────────────────────
  { id: "hero_moment:interior_design:client-hand-on-face-seeing-bedroom", kind: "hero_moment", subject: "Client standing at bedroom doorway with hand raised to face — the involuntary gesture of someone processing something more beautiful than they expected", heroType: "person", industryIds: ["interior"], campaignTypeIds: ["reveal"], behaviourIds: [], tags: ["bedroom", "doorway", "involuntary", "more-beautiful"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "hero_moment:interior_design:client-spinning-slowly-to-take-in-room", kind: "hero_moment", subject: "Client slowly turning full circle in the centre of the finished room — taking in every wall, every decision, the 360-degree reality of what was designed on paper", heroType: "person", industryIds: ["interior"], campaignTypeIds: ["reveal"], behaviourIds: [], tags: ["spinning", "360-degree", "taking-in", "paper-to-reality"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:interior_design:client-running-hand-along-bespoke-joinery", kind: "hero_moment", subject: "Client running hand along bespoke joinery — feeling the craftsmanship that was specified, the tactile confirmation that the investment is real", heroType: "person", industryIds: ["interior"], campaignTypeIds: ["reveal", "luxury_design"], behaviourIds: [], tags: ["joinery", "bespoke", "tactile", "craftsmanship"], priority: 3, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:interior_design:client-sitting-in-sofa-first-time", kind: "hero_moment", subject: "Client sitting in their new sofa in the finished room for the first time — the whole space framing them, the room finally inhabited, the design proved by use", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["reveal"], behaviourIds: [], tags: ["sofa", "inhabiting", "design-proved", "first-sit"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:client-photographing-room-for-family", kind: "hero_moment", subject: "Client photographing the finished room immediately to send to family — the proof shared before the designer has even left, pride converting to evidence", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["reveal", "brand_awareness"], behaviourIds: [], tags: ["photographing", "family", "sharing", "pride"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:client-noticing-detail-that-was-remembered", kind: "hero_moment", subject: "Client noticing the detail the designer remembered from a conversation months ago — the small thing placed that says they truly listened", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["reveal", "brand_awareness"], behaviourIds: [], tags: ["remembered-detail", "listened", "small-thing", "months-ago"], priority: 6, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:interior_design:client-surprised-by-colour-working", kind: "hero_moment", subject: "Client surprised that the bold colour they were nervous about works perfectly in context — the designer proved right, the client's faith in the process vindicated", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["reveal"], behaviourIds: [], tags: ["bold-colour", "nervous", "works", "trust-vindicated"], priority: 7, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:interior_design:client-lighting-different-scenes", kind: "hero_moment", subject: "Client discovering the lighting scenes in the finished room — pressing each scene, watching the room transform through them, the atmosphere changing with each press", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["reveal", "luxury_design"], behaviourIds: [], tags: ["lighting-scenes", "atmosphere", "transforming", "discovering"], priority: 8, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:elderly-client-in-redesigned-safe-home", kind: "hero_moment", subject: "Elderly client in their redesigned home — all the practical adaptations hidden within beautiful design, the care not visible but the freedom visible in their movement", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["renovation", "reveal"], behaviourIds: [], tags: ["elderly", "adaptations-hidden", "freedom", "safety"], priority: 7, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "hero_moment:interior_design:client-calling-designer-back-to-room", kind: "hero_moment", subject: "Client calling the designer back into the room to look at something together — the shared ownership of the finished space, the mutual pride in what was made", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["reveal", "brand_awareness"], behaviourIds: [], tags: ["calling-back", "shared-ownership", "mutual-pride", "together"], priority: 6, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Designer presenting mood board (8) ───────────────────────────────────
  { id: "hero_moment:interior_design:mood-board-presentation-client-leaning-in", kind: "hero_moment", subject: "Designer presenting mood board to clients — spread on table or mounted on board, clients leaning in to touch swatches and study images, the vision becoming concrete", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["consultation", "brand_awareness"], behaviourIds: [], tags: ["mood-board", "swatches", "clients-leaning-in", "vision-concrete"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:interior_design:digital-mood-board-on-large-screen", kind: "hero_moment", subject: "Designer presenting digital mood board on large screen — reference images, material swatches photographed at scale, the digital vision board scrolled with the client", heroType: "product", industryIds: ["interior"], campaignTypeIds: ["consultation", "brand_awareness"], behaviourIds: [], tags: ["digital", "large-screen", "references", "scrolling"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:client-approving-mood-board-direction", kind: "hero_moment", subject: "Clients agreeing on the mood board direction — pointing to what excites them, the designer seeing alignment and moving toward the detail", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["consultation"], behaviourIds: [], tags: ["approval", "alignment", "direction", "excitement"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:unexpected-mood-board-direction-client-love", kind: "hero_moment", subject: "Designer presenting an unexpected direction the client had not considered — the moment they see something they did not know they wanted and recognise it instantly", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["consultation", "brand_awareness"], behaviourIds: [], tags: ["unexpected", "direction", "recognition", "did-not-know"], priority: 4, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:interior_design:mood-board-physical-tactile-presentation", kind: "hero_moment", subject: "Physical mood board with real swatches and samples — fabric pinned, paint chip attached, tile sample included, the tactile presentation that screens cannot replicate", heroType: "product", industryIds: ["interior"], campaignTypeIds: ["consultation"], behaviourIds: [], tags: ["physical", "swatches", "pinned", "tactile"], priority: 5, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:interior_design:3d-visualisation-presented-to-client", kind: "hero_moment", subject: "3D photorealistic visualisation of the room presented to clients — seeing their space fully designed before a single item is ordered, the future room made visible", heroType: "product", industryIds: ["interior"], campaignTypeIds: ["consultation", "technology"], behaviourIds: [], tags: ["3d-visualisation", "photorealistic", "future-room", "before-ordering"], priority: 6, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:interior_design:vr-walkthrough-of-proposed-design", kind: "hero_moment", subject: "Client experiencing VR walkthrough of proposed design — headset on, walking through the room that does not yet exist, the technology that makes imagination concrete", heroType: "product", industryIds: ["interior"], campaignTypeIds: ["consultation", "technology"], behaviourIds: [], tags: ["vr", "walkthrough", "headset", "not-yet-exists"], priority: 7, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:interior_design:mood-board-revision-client-input-incorporated", kind: "hero_moment", subject: "Revised mood board presented incorporating client's feedback — their suggestions made part of the vision, the collaborative refinement visible in what changed", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["consultation"], behaviourIds: [], tags: ["revision", "feedback-incorporated", "collaborative", "refined"], priority: 8, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },

  // ── Fabric and material selection (10) ────────────────────────────────────
  { id: "hero_moment:interior_design:client-choosing-fabric-at-design-studio", kind: "hero_moment", subject: "Client surrounded by fabric samples at design studio — pulling rolls out, draping against each other, the sensory pleasure of choosing material for a room they love", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["consultation", "luxury_design"], behaviourIds: [], tags: ["fabric", "samples", "draping", "sensory"], priority: 1, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:interior_design:tile-selection-held-against-light", kind: "hero_moment", subject: "Designer holding tile sample in natural light — the client watching the glaze shift with the angle, understanding at last how the material will live in their room", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["consultation"], behaviourIds: [], tags: ["tile", "natural-light", "glaze", "shift"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:fabric-swatch-against-paint-chip", kind: "hero_moment", subject: "Designer layering fabric swatch against paint chip against stone sample — building the material palette piece by piece, the combination emerging from the accumulation", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["consultation", "brand_awareness"], behaviourIds: [], tags: ["swatch", "paint-chip", "stone", "palette"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:interior_design:client-running-hand-across-velvet-fabric", kind: "hero_moment", subject: "Client running hand across velvet fabric sample — the pile moving against the stroke, the luxury of the material felt before it is chosen", heroType: "person", industryIds: ["interior"], campaignTypeIds: ["luxury_design", "consultation"], behaviourIds: [], tags: ["velvet", "hand", "pile", "luxury-felt"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:stone-supplier-showroom-slab-selection", kind: "hero_moment", subject: "Designer and client at stone yard selecting marble slab — the unique veining of each piece, pointing to specific movement in the stone that will face into the kitchen", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["kitchen_bathroom", "luxury_design"], behaviourIds: [], tags: ["marble-slab", "stone-yard", "veining", "unique"], priority: 5, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:interior_design:wood-sample-end-grain-selection", kind: "hero_moment", subject: "Designer selecting wood sample — studying grain pattern, considering how the light will move across it, the material understood as a living changing surface", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["consultation"], behaviourIds: [], tags: ["wood", "grain", "light", "living-surface"], priority: 6, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "hero_moment:interior_design:carpet-sample-underfoot-test", kind: "hero_moment", subject: "Client stepping onto carpet sample to feel it underfoot — the physical test of a material before committing to it in every bedroom", heroType: "person", industryIds: ["interior"], campaignTypeIds: ["consultation"], behaviourIds: [], tags: ["carpet", "underfoot", "physical-test", "bedroom"], priority: 7, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
  { id: "hero_moment:interior_design:wallpaper-sample-on-wall-assessment", kind: "hero_moment", subject: "Large wallpaper sample pinned to wall and assessed from across the room — the scale that cannot be judged from the book, standing back to see the pattern at distance", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["consultation"], behaviourIds: [], tags: ["wallpaper", "pinned", "scale", "standing-back"], priority: 8, weight: 0.83, confidence: "high", commercialScore: 82, futureMetadata: fm },
  { id: "hero_moment:interior_design:material-library-designer-curating", kind: "hero_moment", subject: "Designer in material library curating palette for a client — pulling samples across categories, building coherence, the expert edit that clients cannot do themselves", heroType: "authority", industryIds: ["interior"], campaignTypeIds: ["brand_awareness", "consultation"], behaviourIds: [], tags: ["material-library", "curating", "palette", "expert-edit"], priority: 6, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:paint-colour-test-patch-on-wall", kind: "hero_moment", subject: "Paint test patches on wall being assessed at different times of day — morning, noon, and evening light read differently, the informed choice made over 24 hours", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["consultation", "renovation"], behaviourIds: [], tags: ["paint-patch", "times-of-day", "informed-choice", "24-hours"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Show house complete and kitchen/bathroom reveal (8) ────────────────────
  { id: "hero_moment:interior_design:show-house-completed-developer-walkthrough", kind: "hero_moment", subject: "Developer walking through completed show house for the first time — every room dressed, the product that will sell all the others in the development", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["show_home", "developer"], behaviourIds: [], tags: ["show-house", "developer", "walkthrough", "selling-tool"], priority: 1, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:interior_design:new-kitchen-installation-complete", kind: "hero_moment", subject: "New kitchen installation complete — clients entering for the first time, running hands along worktop, opening drawers, the room that transforms daily life revealed", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["kitchen_bathroom", "reveal"], behaviourIds: [], tags: ["kitchen", "installation", "worktop", "daily-life"], priority: 2, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "hero_moment:interior_design:bathroom-renovation-reveal", kind: "hero_moment", subject: "Bathroom renovation reveal — the builder's yard of the week before now a sanctuary of tiles, light, and luxury fixtures, the transformation total", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["kitchen_bathroom", "reveal"], behaviourIds: [], tags: ["bathroom", "sanctuary", "tiles", "luxury-fixtures"], priority: 3, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:interior_design:kitchen-island-first-breakfast", kind: "hero_moment", subject: "Family having first breakfast at new kitchen island — the mundane made meaningful by the space that was designed to host exactly this, the room working as intended", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["kitchen_bathroom", "brand_awareness"], behaviourIds: [], tags: ["kitchen-island", "first-breakfast", "mundane-meaningful", "intended"], priority: 4, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:interior_design:penthouse-interior-complete", kind: "hero_moment", subject: "Penthouse interior complete — every surface at the quality its elevation deserves, designer and client standing together at the window with the city below", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["luxury_design", "reveal"], behaviourIds: [], tags: ["penthouse", "elevation", "city-below", "quality"], priority: 5, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "hero_moment:interior_design:hotel-suite-interior-handover", kind: "hero_moment", subject: "Hotel suite interior handover to hotel management — the designer's work assessed in the context of the bed made, towels folded, the hospitality environment complete", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["developer", "show_home"], behaviourIds: [], tags: ["hotel-suite", "handover", "hospitality", "management"], priority: 6, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:show-apartment-photographed-for-marketing", kind: "hero_moment", subject: "Show apartment fully dressed and being photographed — the furniture, art, and styling creating images that will sell a thousand units", heroType: "product", industryIds: ["interior"], campaignTypeIds: ["show_home", "developer"], behaviourIds: [], tags: ["show-apartment", "photographed", "marketing", "units"], priority: 7, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:restaurant-interior-opening-night-first-service", kind: "hero_moment", subject: "Restaurant interior experienced on opening night — the design working in real candlelight with real people and real noise for the first time, the designer attending quietly", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["reveal", "brand_awareness"], behaviourIds: [], tags: ["restaurant", "opening-night", "candlelight", "real-people"], priority: 8, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Child's room transformation (5) ─────────────────────────────────────
  { id: "hero_moment:interior_design:childs-room-surprise-reveal", kind: "hero_moment", subject: "Child's eyes covered as they are brought into redesigned bedroom — hands removed, the reaction visible across their whole body as they process the room made for them", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["reveal", "before_after"], behaviourIds: [], tags: ["child", "eyes-covered", "reveal", "reaction"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "hero_moment:interior_design:nursery-completed-before-birth", kind: "hero_moment", subject: "Nursery completed before the baby arrives — parents standing in the room that is ready to receive the person they have not met yet, the preparation as love", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["reveal", "renovation"], behaviourIds: [], tags: ["nursery", "ready", "before-birth", "preparation-as-love"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:interior_design:teen-bedroom-redesigned-for-independence", kind: "hero_moment", subject: "Teenager's bedroom redesigned from childhood to suit their current self — the room that finally fits the person living in it, not the child they used to be", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["renovation", "reveal"], behaviourIds: [], tags: ["teenager", "independence", "current-self", "not-child-anymore"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:playroom-designed-for-imagination", kind: "hero_moment", subject: "Playroom design reveal — every element chosen to inspire play and imagination, the child immediately beginning to use the space exactly as intended", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["reveal"], behaviourIds: [], tags: ["playroom", "imagination", "immediately-using", "intended"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:siblings-sharing-room-reorganised", kind: "hero_moment", subject: "Siblings' shared room reorganised to give each child their own zone — the conflict-reducing design that gives two people their own world in the same space", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["renovation", "reveal"], behaviourIds: [], tags: ["siblings", "shared-room", "zones", "conflict-reducing"], priority: 5, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Empty space becoming home (5) ─────────────────────────────────────────
  { id: "hero_moment:interior_design:first-night-in-completed-home", kind: "hero_moment", subject: "Family spending their first night in the completed home — the project done, the people inside it for the first time as residents not visitors", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["new_home", "reveal"], behaviourIds: [], tags: ["first-night", "completed", "residents", "not-visitors"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:interior_design:moving-day-into-designed-home", kind: "hero_moment", subject: "Moving day into a designed home — the furniture arriving and placed perfectly as specified, each piece landing in exactly the position the designer planned", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["new_home", "reveal"], behaviourIds: [], tags: ["moving-day", "furniture-arriving", "placed-perfectly", "planned"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:bare-concrete-floor-becomes-warm-interior", kind: "hero_moment", subject: "Industrial concrete shell of a new build transformed into a warm layered home — the contrast between the before and the after impossible to overstate", heroType: "transformation", industryIds: ["interior"], campaignTypeIds: ["new_home", "before_after"], behaviourIds: [], tags: ["industrial", "warm", "layered", "impossible-contrast"], priority: 3, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:interior_design:holiday-home-completion", kind: "hero_moment", subject: "Holiday home completed — the family arriving for the first stay, the retreat designed to be everything the primary residence is not, the contrast intentional", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["new_home", "reveal"], behaviourIds: [], tags: ["holiday-home", "first-stay", "retreat", "intentional-contrast"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:clients-making-house-a-home-completion", kind: "hero_moment", subject: "Newly built house made into a home — all the design decisions making their full impact only when the people are inside, living and moving in the space", heroType: "lifestyle", industryIds: ["interior"], campaignTypeIds: ["new_home", "brand_awareness"], behaviourIds: [], tags: ["house-to-home", "impact", "people-inside", "living"], priority: 5, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Lighting design transformation (8) ───────────────────────────────────
  { id: "hero_moment:interior_design:lighting-design-at-night-first-switch-on", kind: "hero_moment", subject: "Room lighting switched on for first time at dusk — the evening mode revealing how the space works in darkness, the room becoming something entirely different from its daytime self", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["reveal", "luxury_design"], behaviourIds: [], tags: ["lighting", "dusk", "evening-mode", "entirely-different"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:interior_design:pendant-light-placed-over-dining-table", kind: "hero_moment", subject: "Statement pendant light suspended over dining table — the final fitting that completes the room, its scale and position transforming the space beneath it", heroType: "product", industryIds: ["interior"], campaignTypeIds: ["reveal"], behaviourIds: [], tags: ["pendant", "dining-table", "statement", "scale"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:interior_design:accent-lighting-artwork-revealed-at-night", kind: "hero_moment", subject: "Artwork accent lighting switched on for the first time — the painting seen in its true gallery light, the designer's lighting specification proving its intent", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["luxury_design", "reveal"], behaviourIds: [], tags: ["accent-lighting", "artwork", "gallery-light", "proving-intent"], priority: 3, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:under-stair-lighting-installation", kind: "hero_moment", subject: "Staircase underlit for the first time — the floating effect of the treads, the lit recess, the transformation of a functional element into a sculptural one", heroType: "product", industryIds: ["interior"], campaignTypeIds: ["reveal", "luxury_design"], behaviourIds: [], tags: ["staircase", "underlit", "floating", "sculptural"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:kitchen-lighting-task-ambient-reveal", kind: "hero_moment", subject: "Kitchen lighting commission revealed — task lighting over worktop, warm ambient beneath cabinets, island pendants all simultaneously active, the kitchen in its full intended light", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["kitchen_bathroom", "reveal"], behaviourIds: [], tags: ["kitchen-lighting", "task", "ambient", "pendants"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "hero_moment:interior_design:smart-lighting-system-demonstrated", kind: "hero_moment", subject: "Smart lighting system demonstrated to client — scenes created for different times of day, voice control shown, the client delighted that the room has a setting for everything", heroType: "product", industryIds: ["interior"], campaignTypeIds: ["technology", "luxury_design"], behaviourIds: [], tags: ["smart-lighting", "scenes", "voice-control", "settings"], priority: 6, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "hero_moment:interior_design:exterior-lighting-garden-at-night", kind: "hero_moment", subject: "Garden exterior lighting seen at night for the first time — uplighters on trees, pathway light, terrace ambient, the garden extending the house into the dark", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["reveal", "luxury_design"], behaviourIds: [], tags: ["exterior-lighting", "garden", "night", "extending"], priority: 7, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:bathroom-illuminated-mirror-reveal", kind: "hero_moment", subject: "Illuminated bathroom mirror switched on — the face-level light eliminating shadows, the bathroom transformed from functional to vanity-standard by the right light", heroType: "product", industryIds: ["interior"], campaignTypeIds: ["kitchen_bathroom", "reveal"], behaviourIds: [], tags: ["illuminated-mirror", "face-level", "shadow-free", "vanity"], priority: 8, weight: 0.84, confidence: "high", commercialScore: 83, futureMetadata: fm },

  // ── Art placement and furniture arrangement (5) ───────────────────────────
  { id: "hero_moment:interior_design:artwork-placed-in-final-position", kind: "hero_moment", subject: "Artwork hung in its final position — designer and client stepping back together, the long-chosen piece now in the room it was selected for, the scale proven right", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["luxury_design", "reveal"], behaviourIds: [], tags: ["artwork", "final-position", "stepping-back", "scale-proven"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:interior_design:furniture-layout-finally-right", kind: "hero_moment", subject: "Furniture arrangement finding its right configuration — the sofa moved one last time, everyone stepping back, knowing without discussion that this is correct", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["consultation", "reveal"], behaviourIds: [], tags: ["furniture-layout", "configuration", "stepping-back", "correct"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:bespoke-furniture-delivery-placed", kind: "hero_moment", subject: "Bespoke furniture delivered and placed — the piece made to specification landing in the room it was made for, the wait justified by the fit", heroType: "product", industryIds: ["interior"], campaignTypeIds: ["luxury_design", "reveal"], behaviourIds: [], tags: ["bespoke-furniture", "delivered", "specification", "fit"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:interior_design:antique-piece-integrated-into-modern-scheme", kind: "hero_moment", subject: "Antique piece placed into a contemporary scheme — the old and new in dialogue, the designer proving that heritage and modernity share the same room without conflict", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["luxury_design", "brand_awareness"], behaviourIds: [], tags: ["antique", "contemporary", "dialogue", "heritage"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:rug-placed-anchoring-seating-group", kind: "hero_moment", subject: "Statement rug placed under seating arrangement — the furniture becoming a unified group, the room acquiring its anchor, the difference between a rug and no rug made dramatic", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["reveal"], behaviourIds: [], tags: ["rug", "anchoring", "unified-group", "dramatic-difference"], priority: 5, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },

  // ── Colour transforming the room (6) ─────────────────────────────────────
  { id: "hero_moment:interior_design:paint-applied-room-transforms", kind: "hero_moment", subject: "First full wall painted and the room transformed — the colour changing everything around it, the client seeing what the designer saw in the chip", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["renovation", "reveal"], behaviourIds: [], tags: ["paint", "wall", "transforms", "chip-to-reality"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:interior_design:dark-ceiling-applied-room-lowers-intimacy", kind: "hero_moment", subject: "Dark ceiling colour applied — the room dropping in height intentionally, the intimacy created by lowering the ceiling through colour rather than architecture", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["renovation"], behaviourIds: [], tags: ["dark-ceiling", "intimacy", "dropping", "intentional"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:bold-colour-client-nervous-then-delighted", kind: "hero_moment", subject: "Bold colour client was nervous about fully applied — the designer's confidence vindicated, the client seeing that the bravery was right, the room transformed by courage", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["reveal", "brand_awareness"], behaviourIds: [], tags: ["bold", "nervous", "delighted", "courage-vindicated"], priority: 3, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "hero_moment:interior_design:all-white-scheme-contrasted-with-one-dark-wall", kind: "hero_moment", subject: "White scheme punctuated by a single dark accent wall — the drama of contrast, the focus created where everything else recedes, the one wall becoming the room", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["renovation"], behaviourIds: [], tags: ["white", "dark-accent", "contrast", "focus"], priority: 4, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:colour-drenching-ceiling-walls-woodwork", kind: "hero_moment", subject: "Colour drenching completed — walls, ceiling, and woodwork all in the same deep colour, the immersive effect only visible when the room is complete", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["renovation", "reveal"], behaviourIds: [], tags: ["colour-drenching", "immersive", "woodwork", "same-colour"], priority: 5, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "hero_moment:interior_design:colour-consultation-client-commits-to-choice", kind: "hero_moment", subject: "Colour consultation resulting in a committed choice — the client who arrived uncertain leaving with the specific colour ordered, the decision made with professional support", heroType: "moment", industryIds: ["interior"], campaignTypeIds: ["consultation"], behaviourIds: [], tags: ["colour-consultation", "committed", "uncertain-to-decided", "ordered"], priority: 6, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Loft conversion and garden reveal (5) ────────────────────────────────
  { id: "hero_moment:interior_design:loft-conversion-reveals-sky-through-velux", kind: "hero_moment", subject: "Loft conversion complete — standing in the space that was roof storage looking through new Velux windows at sky, the unused volume now a room of light", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["renovation", "reveal"], behaviourIds: [], tags: ["loft-conversion", "velux", "sky", "unused-volume"], priority: 1, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "hero_moment:interior_design:garden-redesign-spring-reveal", kind: "hero_moment", subject: "Garden redesign revealed in first spring — the planting beginning to establish, the client seeing the bones of the design for the first time in leaf", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["reveal", "renovation"], behaviourIds: [], tags: ["garden", "spring", "planting", "bones-of-design"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "hero_moment:interior_design:roof-terrace-designed-space-urban", kind: "hero_moment", subject: "Urban rooftop terrace designed and completed — looking out over the city from a considered outdoor space that transforms a flat roof into a destination", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["luxury_design", "reveal"], behaviourIds: [], tags: ["rooftop-terrace", "urban", "destination", "city-views"], priority: 3, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "hero_moment:interior_design:outbuilding-converted-to-studio", kind: "hero_moment", subject: "Garden outbuilding converted to a working studio — the unused structure transformed into a productive beautiful space, the garden gaining a room", heroType: "transformation", industryIds: ["interior"], campaignTypeIds: ["renovation", "reveal"], behaviourIds: [], tags: ["outbuilding", "studio", "garden-room", "unused-to-productive"], priority: 4, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:swimming-pool-house-interior-designed", kind: "hero_moment", subject: "Pool house interior completed — the leisure environment that extends the home to the garden, every element chosen for its capacity to survive the humidity and light", heroType: "environment", industryIds: ["interior"], campaignTypeIds: ["luxury_design", "reveal"], behaviourIds: [], tags: ["pool-house", "leisure", "humidity", "garden-extension"], priority: 5, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },

  // ── Designer's own moments (3) ────────────────────────────────────────────
  { id: "hero_moment:interior_design:designer-collection-photography-day", kind: "hero_moment", subject: "Interior designer on their own collection photography day — standing back as the photographer captures work they have spent months creating, the satisfaction of the image that will speak for the year's work", heroType: "authority", industryIds: ["interior"], campaignTypeIds: ["brand_awareness"], behaviourIds: [], tags: ["collection", "photography-day", "satisfaction", "year's-work"], priority: 1, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "hero_moment:interior_design:designer-portfolio-room-final-photos", kind: "hero_moment", subject: "Designer at final portfolio photography of a room — overseeing every detail before the lens records it, the perfectionism of the creative professional at the moment of documentation", heroType: "authority", industryIds: ["interior"], campaignTypeIds: ["brand_awareness"], behaviourIds: [], tags: ["portfolio", "photography", "overseeing", "perfectionism"], priority: 2, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "hero_moment:interior_design:award-shortlisted-project-photographed", kind: "hero_moment", subject: "Award-shortlisted project being photographed — the designer's work being documented for its entry, the recognition of the industry for a room that deserved attention", heroType: "authority", industryIds: ["interior"], campaignTypeIds: ["brand_awareness"], behaviourIds: [], tags: ["award", "shortlisted", "documented", "recognition"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
];
