import type { RelationshipKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const INTERIOR_DESIGN_RELATIONSHIPS: RelationshipKnowledgeNode[] = [
  // ── Designer–client relationships (12) ────────────────────────────────────────
  { id: "relationship:interior_design:designer-and-residential-client", kind: "relationship", description: "An interior designer and their residential client — the relationship built over months of decisions, the designer seeing the inside of the client's life and home more intimately than almost any professional", sceneRoles: ["interior designer", "residential client"], industryIds: ["interior"], tags: ["designer", "client", "residential", "intimate"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "relationship:interior_design:designer-and-first-time-homeowner", kind: "relationship", description: "A designer working with a first-time homeowner — the client with no design vocabulary but a clear emotional vision, the designer translating the feeling into the language of decisions", sceneRoles: ["interior designer", "first-time homeowner"], industryIds: ["interior"], tags: ["first-time", "homeowner", "translating", "vocabulary"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:interior_design:interior-architect-and-developer", kind: "relationship", description: "An interior architect working with a property developer — the commercial brief requiring design quality at scale, the architect's vision applied to multiple units or the show home that sells the development", sceneRoles: ["interior architect", "property developer"], industryIds: ["interior"], tags: ["interior-architect", "developer", "commercial", "scale"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:interior_design:designer-and-returning-client", kind: "relationship", description: "A designer and a client they have worked with before — the relationship that has survived a project and earned the next one, the shorthand between them more efficient than any new professional relationship could be", sceneRoles: ["interior designer", "returning client"], industryIds: ["interior"], tags: ["returning", "shorthand", "earned", "efficient"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:interior_design:design-director-and-junior-designer", kind: "relationship", description: "A design director and a junior designer in the studio — the transmission of taste and judgement from senior to junior, the apprenticeship relationship that builds design skill through proximity to more experienced practice", sceneRoles: ["design director", "junior designer"], industryIds: ["interior"], tags: ["design-director", "junior", "transmission", "apprenticeship"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:interior_design:designer-and-contractor", kind: "relationship", description: "An interior designer and the contractor who builds their designs — the relationship requiring trust in both directions, the designer's specification translated by the contractor's skill, the result dependent on both", sceneRoles: ["interior designer", "contractor"], industryIds: ["interior"], tags: ["contractor", "trust", "specification", "skill"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:interior_design:designer-and-specialist-craftsperson", kind: "relationship", description: "A designer working with a specialist craftsperson — the joiner, the plasterer, the upholsterer — the rare specialist whose skill realises the specific element that the design depends on", sceneRoles: ["interior designer", "specialist craftsperson"], industryIds: ["interior"], tags: ["craftsperson", "specialist", "joiner", "upholsterer"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:interior_design:designer-and-supplier-rep", kind: "relationship", description: "A designer and a trade supplier representative — the ongoing relationship with a company whose products the designer specifies regularly, the rep who knows the designer's preferences and flags new products that suit them", sceneRoles: ["interior designer", "supplier representative"], industryIds: ["interior"], tags: ["supplier", "trade", "ongoing", "preferences"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },

  // ── Couple & family design relationships (10) ──────────────────────────────────
  { id: "relationship:interior_design:couple-agreeing-on-design", kind: "relationship", description: "A couple negotiating their shared home design — two aesthetic sensibilities finding the compromise that honours both, the home becoming the physical expression of the relationship's ongoing negotiation", sceneRoles: ["couple"], industryIds: ["interior"], tags: ["couple", "negotiation", "shared", "compromise"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "relationship:interior_design:parent-designing-for-child", kind: "relationship", description: "A parent designing or commissioning a room for their child — the empathetic exercise of imagining what the child needs and what will make them happy, the room as a gift that will shape years of childhood", sceneRoles: ["parent", "child"], industryIds: ["interior"], tags: ["parent", "child-room", "empathetic", "childhood"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:interior_design:family-renovating-together", kind: "relationship", description: "A family navigating a home renovation together — the shared disruption, the temporary living arrangements, the shared vision of the end state that keeps the inconvenience in perspective", sceneRoles: ["family"], industryIds: ["interior"], tags: ["family", "renovation", "shared-disruption", "shared-vision"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:interior_design:adult-child-redesigning-family-home", kind: "relationship", description: "An adult child working with parents to redesign the family home — the home that shaped them now being transformed, the authority reversed, the adult child using professional knowledge to help the people who raised them", sceneRoles: ["adult child", "parents"], industryIds: ["interior"], tags: ["adult-child", "family-home", "authority-reversed", "professional"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },

  // ── Object-person relationships (8) ───────────────────────────────────────────
  { id: "relationship:interior_design:person-and-inherited-furniture", kind: "relationship", description: "A person incorporating inherited furniture into a newly designed space — the piece that carries family history now placed within a contemporary context, the design challenge of honouring the old within the new", sceneRoles: ["homeowner", "inherited piece"], industryIds: ["interior"], tags: ["inherited", "furniture", "family-history", "honouring"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:interior_design:person-and-art-collection-in-space", kind: "relationship", description: "A collector displaying their art in a designed space — the room designed around the collection, the art and the architecture in conversation, the design that subordinates itself to serve the works it contains", sceneRoles: ["art collector", "art collection"], industryIds: ["interior"], tags: ["art", "collection", "display", "subordinate"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:interior_design:homeowner-and-beloved-armchair", kind: "relationship", description: "A homeowner and the single beloved armchair that has been carried from home to home — the object with continuity, the relationship between person and chair that the designer is asked to build the room around", sceneRoles: ["homeowner", "beloved object"], industryIds: ["interior"], tags: ["armchair", "beloved", "continuity", "build-around"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:interior_design:designer-and-bespoke-commission", kind: "relationship", description: "A designer commissioning a bespoke piece — a joinery unit, a one-off light fitting, a custom sofa — the relationship with the maker that realises the specific object the design requires and no catalogue can supply", sceneRoles: ["designer", "commissioned maker"], industryIds: ["interior"], tags: ["bespoke", "commission", "maker", "one-off"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },

  // ── Hospitality & commercial relationships (10) ───────────────────────────────
  { id: "relationship:interior_design:hotel-owner-and-designer", kind: "relationship", description: "A hotel owner and their interior designer — the commercial brief requiring that every design decision serves guest experience and operational efficiency, the relationship more structured than residential but no less collaborative", sceneRoles: ["hotel owner", "interior designer"], industryIds: ["interior"], tags: ["hotel", "commercial", "guest-experience", "operational"], priority: 3, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "relationship:interior_design:restaurant-owner-and-hospitality-designer", kind: "relationship", description: "A restaurant owner and a hospitality interior designer — the brief requiring atmosphere, acoustic management, material durability and the specific palette that suits the food being served, all balanced in the design", sceneRoles: ["restaurant owner", "hospitality designer"], industryIds: ["interior"], tags: ["restaurant", "atmosphere", "acoustic", "durability"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:interior_design:architect-and-interior-designer", kind: "relationship", description: "An architect and an interior designer working on the same project — the relationship between the structural and spatial professional and the finishing and furnishing professional, the handoff moment when one's work ends and the other's begins", sceneRoles: ["architect", "interior designer"], industryIds: ["interior"], tags: ["architect", "collaboration", "handoff", "structural-spatial"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:interior_design:project-manager-and-design-team", kind: "relationship", description: "A project manager coordinating the design team, contractors and supplier deliveries — the logistics relationship that keeps the creative project on time and on budget, the person who makes the design possible in practice", sceneRoles: ["project manager", "design team"], industryIds: ["interior"], tags: ["project-manager", "coordinating", "logistics", "on-time"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:interior_design:stylist-and-photographer", kind: "relationship", description: "An interior stylist and photographer working together on a room shoot — the stylist adjusting, the photographer framing, the collaboration that translates the three-dimensional designed space into the two-dimensional portfolio image", sceneRoles: ["interior stylist", "photographer"], industryIds: ["interior"], tags: ["stylist", "photographer", "shoot", "portfolio-image"], priority: 3, weight: 0.85, confidence: "high", commercialScore: 84, futureMetadata: fm },
  { id: "relationship:interior_design:design-editor-and-featured-home", kind: "relationship", description: "A design magazine editor and the homeowner whose home is being featured — the home made public, the private space opened to the lens and the editorial story that will reach the publication's audience", sceneRoles: ["design editor", "homeowner"], industryIds: ["interior"], tags: ["editor", "featured", "magazine", "public"], priority: 4, weight: 0.82, confidence: "high", commercialScore: 81, futureMetadata: fm },
];
