import type { BehaviourKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const GENERIC_BEHAVIOURS: BehaviourKnowledgeNode[] = [
  // ── Universal human connection behaviours (20) ─────────────────────────────────
  { id: "behaviour:generic:two-people-making-eye-contact", kind: "behaviour", description: "Two people making genuine eye contact — the moment of mutual recognition between people in conversation or interaction, the eye contact that signals full presence and attention", emotionalSignal: "genuine connection and mutual presence", compatibleHeroes: ["person", "moment", "lifestyle"], tags: ["eye-contact", "connection", "mutual", "present"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "behaviour:generic:genuine-laugh-involuntary", kind: "behaviour", description: "A genuine involuntary laugh — the head back, the sound real, the physical expression of amusement that cannot be manufactured, the laughter that the viewer immediately wants to understand the source of", emotionalSignal: "authentic joy that invites participation", compatibleHeroes: ["person", "lifestyle", "moment"], tags: ["laugh", "genuine", "involuntary", "joy"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "behaviour:generic:person-receiving-something-unexpected", kind: "behaviour", description: "A person receiving something unexpected — the transition from ordinary to surprised, the face working through incomprehension to recognition to delight in a sequence that no posed photograph can replicate", emotionalSignal: "the authentic surprise response — the emotion that precedes any decision about showing it", compatibleHeroes: ["person", "moment"], tags: ["receiving", "surprise", "unexpected", "authentic"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "behaviour:generic:person-reading-with-full-absorption", kind: "behaviour", description: "A person completely absorbed in reading — the body language of full cognitive engagement, the world receding as the attention narrows to the page or screen, the particular posture of someone entirely elsewhere", emotionalSignal: "complete absorption — the highest expression of attention as a compliment to content", compatibleHeroes: ["lifestyle", "person", "product"], tags: ["reading", "absorbed", "cognitive", "full-attention"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:generic:person-experiencing-something-delicious", kind: "behaviour", description: "A person experiencing something delicious — the food, drink or flavour causing an involuntary expression of pleasure: closed eyes, the slight forward lean, the held moment of pure sensory experience", emotionalSignal: "involuntary sensory pleasure — the body's response that cannot be suppressed", compatibleHeroes: ["person", "product", "lifestyle"], tags: ["delicious", "sensory-pleasure", "involuntary", "closed-eyes"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:generic:person-in-moment-of-physical-exertion", kind: "behaviour", description: "A person at a moment of physical exertion — running, lifting, stretching or training, the body at work, the focus visible in the face and posture, the commitment to physical effort", emotionalSignal: "purposeful physical commitment and the pride of effort", compatibleHeroes: ["person", "lifestyle", "moment"], tags: ["exertion", "physical", "commitment", "effort"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:generic:person-looking-at-horizon-or-view", kind: "behaviour", description: "A person looking at a view or horizon — the body still, the gaze extended into the distance, the contemplative posture of someone who has paused to take in something larger than the immediate task", emotionalSignal: "contemplative aspiration — the looking out that communicates perspective and possibility", compatibleHeroes: ["person", "lifestyle", "environment"], tags: ["horizon", "view", "contemplative", "perspective"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:generic:person-discovering-something-new", kind: "behaviour", description: "A person discovering something for the first time — the physical lean forward, the eyes widening, the moment of first contact with information or experience that changes what they know", emotionalSignal: "the open-eyed discovery moment — curiosity rewarded and the world enlarged", compatibleHeroes: ["person", "product", "moment"], tags: ["discovery", "first-time", "curiosity", "lean-forward"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:generic:person-checking-phone-with-delight", kind: "behaviour", description: "A person checking their phone and finding something delightful — the expression changing as the screen delivers good news, a message, a confirmation, the digital good moment that brightens the physical face", emotionalSignal: "the contemporary moment of good-news-received — the digital experience made physically visible", compatibleHeroes: ["person", "lifestyle", "moment"], tags: ["phone", "delight", "good-news", "contemporary"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:generic:person-choosing-carefully-from-options", kind: "behaviour", description: "A person choosing carefully from a set of options — the hand moving toward one and then another, the focused expression of deliberate selection, the moment between decision and commitment", emotionalSignal: "deliberate consideration — the care that communicates that this choice matters", compatibleHeroes: ["person", "product", "moment"], tags: ["choosing", "deliberate", "options", "consideration"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },

  // ── Universal social behaviours (20) ─────────────────────────────────────────
  { id: "behaviour:generic:group-leaning-in-to-look-together", kind: "behaviour", description: "A group of people leaning in to look at something together — the physical coalescence around a point of shared interest, the bodies drawn together by collective curiosity or excitement", emotionalSignal: "collective focus and shared engagement", compatibleHeroes: ["person", "lifestyle", "moment"], tags: ["group", "leaning-in", "collective", "shared"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:generic:handing-something-to-another-person", kind: "behaviour", description: "One person handing something to another — the physical transaction that carries the meaning of the exchange: the gift, the payment, the document, the tool, the object transferred from one set of hands to another", emotionalSignal: "the physical moment of transfer that carries all the relational meaning of the exchange", compatibleHeroes: ["person", "product", "moment"], tags: ["handing", "transfer", "exchange", "relational"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:generic:side-by-side-looking-at-same-thing", kind: "behaviour", description: "Two people standing side by side looking at the same thing — the shared viewing that communicates a common focus, a shared problem, a shared aspiration, two people oriented together toward the same object", emotionalSignal: "shared orientation — the side-by-side position that communicates partnership without confrontation", compatibleHeroes: ["person", "lifestyle", "moment"], tags: ["side-by-side", "shared", "partnership", "common-focus"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:generic:celebrating-together-raised-glasses", kind: "behaviour", description: "A group raising their glasses together — the celebratory toast, the moment of group acknowledgement of something worth marking, the social ritual of shared congratulation", emotionalSignal: "collective celebration — the group acknowledgement of a shared achievement or occasion", compatibleHeroes: ["lifestyle", "person", "moment"], tags: ["toast", "raised-glasses", "celebration", "collective"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:generic:person-helping-another-person", kind: "behaviour", description: "One person helping another — physically, practically or emotionally, the human gesture of assistance that is one of the most universally positive images any brand can associate itself with", emotionalSignal: "care and human generosity — the helping gesture that communicates service without words", compatibleHeroes: ["person", "moment", "lifestyle"], tags: ["helping", "care", "assistance", "generosity"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:generic:person-teaching-another-person", kind: "behaviour", description: "One person teaching another — the orientation of the teacher toward the learner, the knowledge transfer from one to another, the relationship of expertise generously shared", emotionalSignal: "the generosity of expertise — teaching as care", compatibleHeroes: ["person", "moment", "lifestyle"], tags: ["teaching", "expertise", "transfer", "care"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:generic:welcoming-someone-arrived", kind: "behaviour", description: "Welcoming someone who has arrived — the open door, the greeting, the physical expression of someone being received with warmth, the first moment of hospitality", emotionalSignal: "the warmth of welcome — being received as if your arrival matters", compatibleHeroes: ["person", "moment", "lifestyle"], tags: ["welcoming", "arrival", "warm", "hospitality"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:generic:shaking-hands-introduction", kind: "behaviour", description: "A handshake at an introduction or agreement — the physical professional greeting or commitment, the gesture that communicates trust established and commitment made", emotionalSignal: "professional trust and relational commitment physically expressed", compatibleHeroes: ["person", "moment"], tags: ["handshake", "introduction", "professional", "trust"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:generic:applause-recognition", kind: "behaviour", description: "Applause — the collective gesture of recognition, appreciation and acknowledgement, the physical expression of the group's positive response to something that deserved recognition", emotionalSignal: "collective appreciation — the audience's body language confirming value", compatibleHeroes: ["moment", "person", "lifestyle"], tags: ["applause", "recognition", "collective", "appreciation"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:generic:person-alone-in-contentment", kind: "behaviour", description: "A person alone in a moment of contentment — sitting with a coffee in the morning, walking in the park, the moments of private pleasure and self-sufficiency that are as valuable to document as social joy", emotionalSignal: "contented solitude — the internal self-sufficiency that is the aim of every wellbeing brand and the quiet aspiration of many people's self-image", compatibleHeroes: ["lifestyle", "person", "environment"], tags: ["solitude", "contentment", "private", "self-sufficient"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Universal work and professional behaviours (15) ────────────────────────────
  { id: "behaviour:generic:person-working-with-focus", kind: "behaviour", description: "A person working with obvious focus — the laptop, the notebook, the tool in hand, the body language of cognitive engagement and purposeful work", emotionalSignal: "purposeful professional engagement — the focus that communicates competence", compatibleHeroes: ["person", "lifestyle", "moment"], tags: ["working", "focus", "cognitive", "competence"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:generic:completing-a-task-with-satisfaction", kind: "behaviour", description: "Completing a task — the physical gesture of finishing: closing the laptop, putting down the pen, stepping back from the finished work, the satisfaction visible in the body language of completion", emotionalSignal: "completion satisfaction — the physical expression of a task finished", compatibleHeroes: ["person", "moment", "lifestyle"], tags: ["completing", "finishing", "stepping-back", "satisfaction"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:generic:reviewing-results-or-progress", kind: "behaviour", description: "Reviewing results or progress — the chart, the data, the physical evidence of what has been achieved reviewed with the expression of someone assessing the return on their effort", emotionalSignal: "the analytical satisfaction of effort evidenced by results", compatibleHeroes: ["person", "product", "lifestyle"], tags: ["reviewing", "results", "progress", "analytical"], priority: 2, weight: 0.87, confidence: "high", commercialScore: 86, futureMetadata: fm },
  { id: "behaviour:generic:confident-presentation-or-explanation", kind: "behaviour", description: "A person presenting or explaining confidently — the upright posture, the eye contact with the audience, the assured quality of someone who knows what they know and is sharing it without hesitation", emotionalSignal: "confident expertise — the posture of someone who has something worth hearing", compatibleHeroes: ["person", "moment"], tags: ["presenting", "confident", "expertise", "assured"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:generic:person-making-a-decision-and-acting", kind: "behaviour", description: "A person making a decision and acting on it — the moment of commitment after deliberation, the purposeful movement that follows the decision, the resolve visible in the changed quality of the movement", emotionalSignal: "decisive action — the conversion from consideration to commitment", compatibleHeroes: ["person", "moment"], tags: ["decision", "action", "decisive", "commitment"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },

  // ── Universal sensory and tactile behaviours (15) ─────────────────────────────
  { id: "behaviour:generic:touching-surface-with-attention", kind: "behaviour", description: "Touching a surface with focused attention — feeling texture, material or quality, the hands as the instrument of direct material assessment, the tactile investigation that visual images alone cannot satisfy", emotionalSignal: "sensory investigation — the hands engaging where eyes are insufficient", compatibleHeroes: ["person", "product", "moment"], tags: ["touching", "surface", "tactile", "quality-assessment"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "behaviour:generic:smelling-something-with-pleasure", kind: "behaviour", description: "Smelling something with evident pleasure — the face lowered toward the source, the eyes often closed, the expression of sensory engagement with a scent that is rewarding", emotionalSignal: "olfactory pleasure — the most memory-linked sense made visible", compatibleHeroes: ["person", "product", "moment"], tags: ["smelling", "pleasure", "eyes-closed", "olfactory"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "behaviour:generic:holding-something-with-both-hands", kind: "behaviour", description: "Holding something with both hands — the two-handed grip that signals the object's value or fragility, the care taken communicating how much the thing being held matters", emotionalSignal: "the value of careful handling — two hands saying this matters enough to hold with intention", compatibleHeroes: ["person", "product", "moment"], tags: ["holding", "both-hands", "care", "value"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:generic:first-taste-or-first-bite", kind: "behaviour", description: "The first bite or first taste — the fork or spoon raised, the anticipation before the moment, the expression immediately after, the sensory sequence of food or drink experienced for the first time", emotionalSignal: "anticipation transitioning to sensory judgment — the first-impression moment of taste", compatibleHeroes: ["person", "product", "moment"], tags: ["first-bite", "taste", "anticipation", "sensory"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "behaviour:generic:person-sensing-comfort-or-relaxation", kind: "behaviour", description: "A person settling into physical comfort — sitting back, closing eyes briefly, the physical release of tension as the body finds ease in a comfortable chair, bed, or space", emotionalSignal: "the physical expression of comfort — the body announcing that it is in a good place", compatibleHeroes: ["lifestyle", "person", "environment"], tags: ["comfort", "settling", "tension-release", "ease"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:generic:person-in-motion-purposeful", kind: "behaviour", description: "A person moving with purpose — walking confidently, the stride of someone going somewhere they want to go, the body language of direction and intent", emotionalSignal: "purposeful momentum — the human body in motion toward a clear destination", compatibleHeroes: ["person", "lifestyle", "environment"], tags: ["motion", "purposeful", "stride", "direction"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "behaviour:generic:quiet-early-morning-ritual", kind: "behaviour", description: "A quiet early morning ritual — coffee made alone, the first look at a phone, the space before others are awake, the specific quality of the solitary early morning that belongs entirely to the person living it", emotionalSignal: "the private morning ritual — the protected daily time that grounds the day", compatibleHeroes: ["lifestyle", "person", "product"], tags: ["morning", "ritual", "quiet", "alone"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "behaviour:generic:person-after-a-challenge-succeeded", kind: "behaviour", description: "A person immediately after succeeding at a challenge — the physical release of the effort held, the expression shifting from concentration to accomplishment, the particular bodily state of having just done something hard", emotionalSignal: "post-achievement physical release — the body's expression of effort vindicated by result", compatibleHeroes: ["person", "moment", "lifestyle"], tags: ["succeeded", "post-challenge", "release", "accomplishment"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:generic:giving-attention-fully-to-another-person", kind: "behaviour", description: "Giving full attention to another person — facing them directly, phone put down or away, the quality of engaged listening that communicates genuine interest in what the other person is saying", emotionalSignal: "the gift of full attention — presence as the most fundamental form of care", compatibleHeroes: ["person", "moment", "lifestyle"], tags: ["full-attention", "listening", "phone-down", "presence"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "behaviour:generic:person-opening-something-special", kind: "behaviour", description: "A person opening something special — a door to a new space, an envelope with important news, a box with a meaningful gift, the physical act of opening that is also the act of entering a new state", emotionalSignal: "the threshold moment — opening as the physical metaphor for transition and the new", compatibleHeroes: ["person", "product", "moment"], tags: ["opening", "threshold", "transition", "new-state"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
];
