import type { EmotionalMomentKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const GENERIC_EMOTIONAL_MOMENTS: EmotionalMomentKnowledgeNode[] = [
  // ── Universal achievement peaks (12) ─────────────────────────────────────────
  { id: "emotional_moment:generic:completing-long-worked-toward-goal", kind: "emotional_moment", moment: "The moment of completing something that was long worked toward — the mixed release of effort, pride and disbelief that it is finally done, the physical and emotional unwinding of sustained tension", emotionType: "completion relief and achieved pride", visualSignals: ["the held breath released", "eyes closing briefly", "hands unclenching or going to the face", "the particular expression of someone who has just arrived somewhere they worked hard to reach"], industryIds: ["generic"], tags: ["completion", "long-worked", "relief", "arrived"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "emotional_moment:generic:receiving-recognition-for-work", kind: "emotional_moment", moment: "Receiving recognition for work done — the award, the review, the acknowledgement from someone whose opinion matters, the external validation that the effort was visible and valued", emotionType: "validated pride", visualSignals: ["the face that tries to contain its response and fails slightly", "the specific quality of the smile when genuine", "the way the recipient looks at the award or looks at the person giving it", "the moment of absorbing the reality of the recognition"], industryIds: ["generic"], tags: ["recognition", "award", "validation", "pride"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:generic:sharing-news-of-success-with-family", kind: "emotional_moment", moment: "Sharing news of a success with family — the call, the message, the gathering where the thing that was hoped for is now announced as having happened, the family's collective response multiplying the joy", emotionType: "reflected and multiplied joy", visualSignals: ["the person telling and the family receiving", "the response that travels through the group", "the hug that follows", "the specific quality of collective celebration in a family context"], industryIds: ["generic"], tags: ["sharing", "success", "family", "collective-joy"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:generic:first-independent-success", kind: "emotional_moment", moment: "A first independent success — doing something for the first time alone and having it work, the specific pride of self-sufficiency that no assisted success can fully replicate", emotionType: "self-proved capability — I did this alone and it worked", visualSignals: ["the particular quality of pride when there is no one else to credit", "the expression of self-confirmation", "the slight disbelief that quickly becomes certainty", "the immediate desire to tell someone"], industryIds: ["generic"], tags: ["first-time", "independent", "self-sufficient", "capable"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:generic:unexpected-positive-outcome", kind: "emotional_moment", moment: "An unexpected positive outcome — the result that was hoped for but not relied on arriving, the surprise of better-than-expected that is one of the highest moments in commercial emotional experience", emotionType: "delighted surprise at the positive outcome", visualSignals: ["the double-take response", "the re-reading or re-checking to confirm it is real", "the expression resolving from surprise to delight", "the immediate sharing impulse"], industryIds: ["generic"], tags: ["unexpected", "positive", "better-than-expected", "surprise"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },

  // ── Universal connection peaks (10) ──────────────────────────────────────────
  { id: "emotional_moment:generic:reunion-after-long-separation", kind: "emotional_moment", moment: "A reunion after a long separation — the moment of seeing again someone who was missed, the physical greeting carrying all the emotional load of the time apart", emotionType: "reunion joy — the relief of presence restored", visualSignals: ["the moment of recognition from a distance", "the movement toward each other", "the embrace that holds longer than the first greeting usually would", "the expressions immediately after separating that are still absorbing the reality of being together"], industryIds: ["generic"], tags: ["reunion", "separation", "missed", "relief"], priority: 1, weight: 0.95, confidence: "high", commercialScore: 94, futureMetadata: fm },
  { id: "emotional_moment:generic:belonging-accepted-by-group", kind: "emotional_moment", moment: "Being accepted by a group — the moment of inclusion after the uncertainty of whether you would belong, the relief and warmth of finding that you do, the social need met", emotionType: "belonging relief — inclusion after uncertainty", visualSignals: ["the group opening to receive the person", "the expression shifting from social tension to ease", "the body language relaxing", "the first real laugh in the group, uninhibited by performance"], industryIds: ["generic"], tags: ["belonging", "acceptance", "inclusion", "relief"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:generic:being-seen-and-understood", kind: "emotional_moment", moment: "The moment of being seen and understood by another person — the expression on a face when someone else has articulated exactly what you were feeling but could not say, the particular gratitude of being known", emotionType: "the relief of being understood — the deepest human need met", visualSignals: ["the eyes that widen slightly at recognition", "the exhale of relief", "the yes that is larger than its usual meaning", "the particular warmth in the face of someone who just felt seen"], industryIds: ["generic"], tags: ["seen", "understood", "articulated", "known"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:generic:unexpected-act-of-kindness", kind: "emotional_moment", moment: "An unexpected act of kindness — the thing done for you that you did not ask for and did not anticipate, the specific emotional response of being on the receiving end of generosity without having earned it", emotionType: "touched gratitude — the warmth of unprompted human care", visualSignals: ["the expression of genuine surprise", "the held moment before responding", "the particular quality of thank-you that is genuinely felt", "the trace of it on the face for some time after"], industryIds: ["generic"], tags: ["kindness", "unexpected", "generosity", "gratitude"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:generic:first-meeting-with-the-right-person", kind: "emotional_moment", moment: "A first meeting with a person who will matter — the conversation that exceeds expectation, the quality of ease and interest that distinguishes a significant meeting from any ordinary one", emotionType: "recognition of significance — this is not an ordinary encounter", visualSignals: ["the forward lean of genuine interest", "the conversation that continues past the expected end", "the expressions of two people who are actively enjoying each other", "the slightly surprised quality of finding someone this good to talk to"], industryIds: ["generic"], tags: ["first-meeting", "significant", "ease", "recognition"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },

  // ── Universal purchase and commercial peaks (10) ──────────────────────────────
  { id: "emotional_moment:generic:making-a-significant-purchase-confidently", kind: "emotional_moment", moment: "Making a significant purchase confidently — the considered decision that has been reached and acted on without the hesitation of doubt, the particular quality of a purchase made from genuine conviction", emotionType: "confident investment — the decision made without regret before it is even tested", visualSignals: ["the decisive nature of the transaction", "no lingering at the counter", "the item taken with the quality of ownership already assumed", "the expression of someone who has finished deliberating and simply done it"], industryIds: ["generic"], tags: ["significant-purchase", "confident", "decided", "ownership"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:generic:product-working-exactly-as-hoped", kind: "emotional_moment", moment: "A product or service working exactly as hoped — the moment of first use when the quality matches the expectation, the purchase validated by its performance, the decision confirmed by the result", emotionType: "purchase validated by performance — the decision confirmed", visualSignals: ["the quality of use that has no frustration in it", "the expression of someone whose expectation was met", "the small moment of noted satisfaction", "the implicit contrast with every time a product did not perform as hoped"], industryIds: ["generic"], tags: ["product", "works-as-hoped", "validated", "performance"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:generic:problem-being-solved-quickly", kind: "emotional_moment", moment: "A problem being solved quickly and correctly — the particular relief of a pain point removed efficiently, the gratitude for a service that delivered what it promised without friction or delay", emotionType: "friction-removed relief — the problem gone", visualSignals: ["the expression of the problem resolved", "the tension that was visible now released", "the return to ordinary life that was interrupted by the problem", "the specific gratitude directed toward whoever solved it"], industryIds: ["generic"], tags: ["problem-solved", "quick", "friction-removed", "relief"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },

  // ── Universal transition and milestone peaks (10) ─────────────────────────────
  { id: "emotional_moment:generic:beginning-something-new", kind: "emotional_moment", moment: "The beginning of something new — the first day, the first step, the threshold moment between the old state and the new one, the particular mix of excitement and apprehension that only exists at beginnings", emotionType: "the mixed-feeling threshold of beginning — anticipation and apprehension balanced", visualSignals: ["the pause at the threshold", "the expression that is not quite settled because the new thing has not proven itself yet", "the forward lean of someone starting something", "the quality of attention that only exists when everything is still new"], industryIds: ["generic"], tags: ["beginning", "new", "threshold", "first-day"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:generic:end-of-chapter-looking-back", kind: "emotional_moment", moment: "The end of a chapter — the retirement, the graduation, the move, the project completed, the looking back at what was done before turning toward what comes next, the particular emotional richness of a transition moment", emotionType: "retrospective gratitude and forward anticipation combined", visualSignals: ["the stillness of someone taking stock", "the expression that holds both backward and forward", "the gathered quality of a person who knows this is one of those moments", "the emotional complexity that is too full for a simple expression"], industryIds: ["generic"], tags: ["end-of-chapter", "transition", "looking-back", "milestone"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:generic:telling-people-the-good-news", kind: "emotional_moment", moment: "The telling of good news — the person who is about to share something wonderful with people they love, the moment just before or during the sharing when the reaction of others is anticipated or witnessed", emotionType: "the joy of sharing joy — anticipation of others' happiness", visualSignals: ["the expression of someone who knows what they are about to give", "the gathering of the people being told", "the moment of telling and the response arriving", "the particular quality of watching someone else learn your good news"], industryIds: ["generic"], tags: ["good-news", "sharing", "telling", "anticipation"], priority: 2, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "emotional_moment:generic:something-beautiful-encountered-unexpectedly", kind: "emotional_moment", moment: "Encountering something beautiful unexpectedly — the view around a corner, the piece of music that comes on at exactly the right moment, the unexpected aesthetic experience that interrupts the ordinary day", emotionType: "aesthetic surprise — the unexpected beauty that temporarily stops everything else", visualSignals: ["the physical stopping", "the attention fully given", "the expression of someone receiving something they did not know they needed", "the held quality of the attention before ordinary life resumes"], industryIds: ["generic"], tags: ["beautiful", "unexpected", "aesthetic", "stopping"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:generic:doing-something-purely-for-joy", kind: "emotional_moment", moment: "Doing something purely for the joy of it — the activity with no agenda, no outcome, no productivity, the human experience of pleasure for its own sake that reminds a person of what they are made of beyond their usefulness", emotionType: "pure recreational joy — existence without purpose beyond pleasure", visualSignals: ["the expression of someone entirely in the present", "no looking at the phone", "the quality of absorption that only comes from doing something for its own sake", "the ease of a face that has no performance in it"], industryIds: ["generic"], tags: ["joy", "pure", "recreation", "present"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
  { id: "emotional_moment:generic:moment-of-quiet-gratitude", kind: "emotional_moment", moment: "A moment of quiet personal gratitude — the recognition of something good in one's life, the private acknowledgement of fortune, the internal counterpart to the external expressions of joy", emotionType: "private gratitude — the internal acknowledgement of what is good", visualSignals: ["the particular quality of stillness", "the expression that is turned inward rather than outward", "the eyes that might close briefly", "the sense of a person taking stock and finding more than they expected"], industryIds: ["generic"], tags: ["gratitude", "quiet", "internal", "stillness"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:generic:confidence-found-in-trying-something-new", kind: "emotional_moment", moment: "Finding confidence in trying something new — the moment after attempting something unfamiliar when it works and the internal story about what is possible shifts, the new capability inscribed by a single successful attempt", emotionType: "expanded self-belief — the boundary moved outward by evidence", visualSignals: ["the expression after the attempt succeeds", "the slight surprise that quickly becomes confidence", "the quality of someone whose world is slightly larger than it was a moment ago", "the move to try again with the lightness of someone who now knows they can"], industryIds: ["generic"], tags: ["confidence", "new-attempt", "self-belief", "expanded"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "emotional_moment:generic:letter-or-message-that-changes-everything", kind: "emotional_moment", moment: "Reading a letter or message that changes everything — the email with the offer, the message with the news, the physical or digital document that marks the before and after of a life chapter", emotionType: "the transformative read — the moment a document changes the landscape", visualSignals: ["the reading posture", "the expression changing as the meaning arrives", "the re-reading to confirm", "the expression after it has been fully absorbed — the new state visible on the face"], industryIds: ["generic"], tags: ["letter", "message", "transformative", "before-after"], priority: 2, weight: 0.92, confidence: "high", commercialScore: 91, futureMetadata: fm },
];
