import type { RelationshipKnowledgeNode } from "../../node";
import { EMPTY_FUTURE_METADATA as fm } from "../../node";

export const GENERIC_RELATIONSHIPS: RelationshipKnowledgeNode[] = [
  // ── Universal human relationships (15) ────────────────────────────────────────
  { id: "relationship:generic:parent-and-child", kind: "relationship", description: "A parent and their child — the fundamental human care relationship, the asymmetry of protective love and total dependency, the relationship that communicates unconditional investment in another person's wellbeing", sceneRoles: ["parent", "child"], tags: ["parent", "child", "care", "unconditional"], priority: 1, weight: 0.96, confidence: "high", commercialScore: 95, futureMetadata: fm },
  { id: "relationship:generic:close-friends-long-term", kind: "relationship", description: "Close long-term friends — the relationship built over years that requires no performance, the friends whose company is the most comfortable and whose opinion matters most", sceneRoles: ["friends"], tags: ["friends", "long-term", "comfortable", "trust"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "relationship:generic:romantic-couple", kind: "relationship", description: "A romantic couple — the intimate partnership of two people who have chosen each other, the relationship that communicates love, trust and the particular ease of being known by one other person", sceneRoles: ["couple"], tags: ["romantic", "couple", "intimate", "chosen"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:generic:grandparent-and-grandchild", kind: "relationship", description: "A grandparent and grandchild — the generational relationship that skips a generation's anxieties, the ease between old and very young that is one of the most emotionally resonant human pairings in visual communication", sceneRoles: ["grandparent", "grandchild"], tags: ["grandparent", "grandchild", "generational", "ease"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "relationship:generic:mentor-and-learner", kind: "relationship", description: "A mentor and their learner — the transmission of experience and capability from one who has it to one who is building it, the relationship of generous expertise freely given", sceneRoles: ["mentor", "learner"], tags: ["mentor", "learner", "transmission", "generous"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:generic:siblings", kind: "relationship", description: "Siblings — the relationship formed by shared origin and shared history, the people who knew you before you became who you are, the complex intimacy of growing up together", sceneRoles: ["siblings"], tags: ["siblings", "shared-history", "intimacy", "growing-up"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:generic:trusted-advisor-and-client", kind: "relationship", description: "A trusted advisor and their client — the professional relationship built on expertise, consistency and the client's confidence that the advisor's interest is aligned with theirs", sceneRoles: ["trusted advisor", "client"], tags: ["advisor", "trust", "expertise", "aligned-interest"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:generic:teacher-and-student", kind: "relationship", description: "A teacher and student — the relationship of knowledge freely given and received with effort, the connection between someone who knows and someone who wants to know", sceneRoles: ["teacher", "student"], tags: ["teacher", "student", "knowledge", "effort"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:generic:business-partners", kind: "relationship", description: "Business partners — the professional relationship of mutual commitment to a shared enterprise, the trust required to share financial risk and creative direction with another person", sceneRoles: ["business partners"], tags: ["business", "partners", "mutual-commitment", "shared-enterprise"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:generic:customer-and-loyal-brand", kind: "relationship", description: "A customer and a brand they are loyal to — the commercial relationship that has crossed from transaction into preference, the customer who chooses the same brand repeatedly from genuine satisfaction", sceneRoles: ["loyal customer", "brand"], tags: ["loyal-customer", "brand", "preference", "repeat"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },

  // ── Universal service relationships (15) ─────────────────────────────────────
  { id: "relationship:generic:expert-and-person-being-helped", kind: "relationship", description: "An expert and the person they are helping — the service relationship in its most fundamental form: one person with knowledge or skill providing it to another who needs it", sceneRoles: ["expert", "person being helped"], tags: ["expert", "help", "service", "need-met"], priority: 1, weight: 0.93, confidence: "high", commercialScore: 92, futureMetadata: fm },
  { id: "relationship:generic:provider-and-loyal-customer", kind: "relationship", description: "A provider and their loyal customer — the relationship formed over repeated positive interactions, the customer who asks for the same person and the provider who knows what they prefer", sceneRoles: ["provider", "loyal customer"], tags: ["provider", "loyal", "repeated", "preference-known"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },
  { id: "relationship:generic:neighbour-community-member", kind: "relationship", description: "A neighbour or community member — the relationship of proximate shared life, the people whose world overlaps with yours without being chosen in the way that friends are chosen", sceneRoles: ["neighbours", "community members"], tags: ["neighbour", "community", "proximate", "shared"], priority: 3, weight: 0.86, confidence: "high", commercialScore: 85, futureMetadata: fm },
  { id: "relationship:generic:colleague-work-team", kind: "relationship", description: "Colleagues in a work team — the relationship of shared professional purpose, the people working toward a common goal whose success depends on how well each serves the shared objective", sceneRoles: ["colleagues", "team"], tags: ["colleagues", "team", "shared-purpose", "common-goal"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:generic:brand-advocate-and-network", kind: "relationship", description: "A brand advocate and their social network — the person whose positive experience generates recommendations, the word-of-mouth that is the highest-value marketing any brand can receive", sceneRoles: ["brand advocate", "network"], tags: ["advocate", "network", "recommendation", "word-of-mouth"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },

  // ── Universal human-product relationships (10) ────────────────────────────────
  { id: "relationship:generic:person-and-cherished-object", kind: "relationship", description: "A person and an object they cherish — the watch, the book, the photograph, the thing whose value is not in the market but in the meaning assigned to it through use and time", sceneRoles: ["person", "cherished object"], tags: ["cherished", "object", "meaning", "personal-value"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
  { id: "relationship:generic:first-time-user-and-new-product", kind: "relationship", description: "A first-time user encountering a new product — the initial investigation, the first use, the forming of the first impression that will determine whether the relationship continues", sceneRoles: ["first-time user", "new product"], tags: ["first-use", "new", "initial", "forming-impression"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:generic:creator-and-their-work", kind: "relationship", description: "A creator and the work they have made — the particular relationship between the person who made something and the thing they made, the pride and vulnerability of authorship", sceneRoles: ["creator", "their work"], tags: ["creator", "work", "authorship", "pride"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:generic:person-and-habitual-daily-object", kind: "relationship", description: "A person and an object that is part of their daily life — the coffee cup, the pen, the tool used every day, the object whose relationship with the user is built through repetition and reliability", sceneRoles: ["person", "daily object"], tags: ["habitual", "daily", "reliability", "repetition"], priority: 2, weight: 0.88, confidence: "high", commercialScore: 87, futureMetadata: fm },
  { id: "relationship:generic:gift-giver-and-recipient", kind: "relationship", description: "A gift giver and their recipient — the relationship expressed through the act of choosing something for another person, the knowledge of someone else's preferences translated into a specific object", sceneRoles: ["gift giver", "recipient"], tags: ["gift", "giver", "recipient", "empathy"], priority: 2, weight: 0.91, confidence: "high", commercialScore: 90, futureMetadata: fm },

  // ── Universal aspirational relationships (10) ─────────────────────────────────
  { id: "relationship:generic:person-and-aspired-life", kind: "relationship", description: "A person in relationship with the life they are working toward — the gap between current state and desired state that motivates every commercial decision, every self-improvement and every purchase", sceneRoles: ["aspiring person", "desired life"], tags: ["aspiration", "desired", "working-toward", "gap"], priority: 1, weight: 0.94, confidence: "high", commercialScore: 93, futureMetadata: fm },
  { id: "relationship:generic:brand-community-members", kind: "relationship", description: "Members of a brand community — the people who share an affinity for the same brand, the commercial tribe whose shared preference creates social identity and belonging beyond the product itself", sceneRoles: ["brand community members"], tags: ["brand-community", "tribe", "shared-affinity", "belonging"], priority: 2, weight: 0.89, confidence: "high", commercialScore: 88, futureMetadata: fm },
  { id: "relationship:generic:person-and-their-future-self", kind: "relationship", description: "A person in relationship with their future self — the person who is making decisions today based on who they want to be tomorrow, the fundamental structure of aspiration and investment", sceneRoles: ["present self", "imagined future self"], tags: ["future-self", "aspiration", "investment", "becoming"], priority: 2, weight: 0.90, confidence: "high", commercialScore: 89, futureMetadata: fm },
];
